"""Closed native desktop profile and subprocess primitives."""
import json
import os
from pathlib import Path
import re
import subprocess
import sys


def relative_path(value):
    if not isinstance(value, str) or not value or '\\' in value:
        raise ValueError('invalid desktop path')
    relative = Path(value)
    if relative.is_absolute() or any(p in ('', '.', '..') for p in value.split('/')):
        raise ValueError('desktop path must be normalized and relative')
    if any(ord(character) < 32 or ord(character) == 127 for character in value):
        raise ValueError('desktop path contains control characters')
    return relative


def safe_path(root, value):
    relative = relative_path(value)
    root = Path(root).resolve(strict=True)
    candidate = root / relative
    for parent in [candidate, *candidate.parents]:
        if parent == root:
            break
        if parent.is_symlink():
            raise ValueError(f'desktop path contains symlink: {parent}')
    if not candidate.resolve().is_relative_to(root):
        raise ValueError('desktop path escapes source root')
    return candidate


def path(profile, field):
    value = profile
    for part in field.split('.'):
        value = value[part]
    if field == 'native_root' and value == '.':
        return profile['_root']
    base = path(profile, 'native_root') if field in ('apple.project_spec', 'apple.project_path') else profile['_root']
    return safe_path(base, value)


def scalar(value, label, pattern=r'[A-Za-z0-9_][A-Za-z0-9_.-]{0,254}'):
    if not isinstance(value, str) or re.fullmatch(pattern, value) is None:
        raise ValueError(f'invalid desktop {label}')


def keys(value, expected):
    if not isinstance(value, dict) or set(value) != set(expected):
        raise ValueError('unknown or missing desktop profile fields')


def load_profile_source(source, source_root='.'):
    checkout = Path.cwd().resolve(strict=True)
    root = checkout if source_root == '.' else safe_path(checkout, source_root)
    if not root.is_dir():
        raise ValueError('approved source root missing')
    if not isinstance(source, str):
        raise ValueError('native profile source must be text')
    first, separator, rest = source.partition('\n')
    if first.startswith('#'):
        marker = r'# Generated by Velnor Actions [A-Za-z0-9._+-]+; edit \.velnor/config\.toml and regenerate\.'
        if re.fullmatch(marker, first) is None or not separator:
            raise ValueError('invalid generated native profile marker')
        source = rest
    profile = json.loads(source)
    profile.setdefault('apple', None)
    profile.setdefault('checks', None)
    profile.setdefault('target', 'apple-arm64')
    keys(profile, ['ffi', 'native_root', 'apple', 'checks', 'target', 'deployment_target'])
    profile['_root'] = root
    if profile['target'] != 'apple-arm64':
        raise ValueError('native desktop supports apple-arm64 only')
    scalar(profile['deployment_target'], 'deployment target', r'[0-9]+\.[0-9]+')
    path(profile, 'native_root')
    validate_bindings(profile)
    if profile['checks'] is not None:
        validate_checks(profile)
    if profile['apple'] is not None:
        validate_apple(profile)
    return profile


def validate_bindings(profile):
    ffi = profile['ffi']
    if not isinstance(ffi, dict):
        raise ValueError('missing foreign artifact consumer identity')
    keys(ffi, ['bindings_path', 'xcframework_path', 'framework_name', 'module_name',
               'static_library'])
    for name in ['bindings_path', 'xcframework_path']:
        path(profile, 'ffi.' + name)
    for name in ['framework_name', 'module_name', 'static_library']:
        scalar(ffi[name], name)
    if Path(ffi['xcframework_path']).name != ffi['framework_name'] + '.xcframework':
        raise ValueError('XCFramework path must match framework identity')


def validate_apple(profile):
    apple = profile['apple']
    for field in ['test_target', 'ui_test_target']:
        apple.setdefault(field, None)
    for field in ['test_sources', 'ui_test_sources']:
        apple.setdefault(field, [])
    keys(apple, ['test_target', 'ui_test_target', 'test_sources', 'ui_test_sources', 'project_spec', 'project_path', 'scheme', 'app_name', 'bundle_identifier',
                'bundle_name', 'app_path', 'derived_data_path', 'archive_name_prefix',
                'required_resources', 'bundle_lsui_element'])
    for field in ['test_target', 'ui_test_target']:
        if apple[field] is not None:
            scalar(apple[field], field)
    for field, target in [('test_sources', 'test_target'), ('ui_test_sources', 'ui_test_target')]:
        validate_sources(profile, apple[field], field)
        if bool(apple[field]) != (apple[target] is not None):
            raise ValueError('native test target and source directories must be paired')
    for name in ['project_spec', 'project_path', 'app_path', 'derived_data_path']:
        path(profile, 'apple.' + name)
    for name in ['scheme', 'app_name', 'bundle_identifier', 'archive_name_prefix']:
        scalar(apple[name], name)
    scalar(apple['bundle_name'], 'bundle name', r'[^\x00-\x1f\x7f]{1,255}')
    if type(apple['bundle_lsui_element']) is not bool:
        raise ValueError('LSUIElement must be boolean')
    if Path(apple['app_path']).name != apple['app_name'] + '.app':
        raise ValueError('app path must match executable name')
    if (not isinstance(apple['required_resources'], list) or
            any(not isinstance(item, str) for item in apple['required_resources']) or
            apple['required_resources'] != sorted(set(apple['required_resources']))):
        raise ValueError('required resources must be a list')
    for resource in apple['required_resources']:
        relative_path(resource)


def subprocess_environment(env=None, trusted=False):
    original = os.environ if env is None else env
    sensitive = re.compile(r'(TOKEN|SECRET|PASSWORD|PRIVATE_KEY|API_KEY|CREDENTIAL|CERT|ISSUER|DEVELOPER_ID|TEAM_ID)')
    prefixes = ('GITHUB_', 'ACTIONS_', 'RUNNER_', 'GH_', 'APP_STORE_', 'GIT_')
    clean = {}
    for name, value in original.items():
        if trusted and name in ('GH_TOKEN', 'GITHUB_TOKEN'):
            clean[name] = value
        elif not name.startswith(prefixes) and not sensitive.search(name.upper()):
            clean[name] = value
    return clean


def run(argv, cwd=None, env=None, trusted=False, stream=False):
    if stream:
        return run_stream(argv, cwd, env, trusted)
    result = subprocess.run([str(arg) for arg in argv], cwd=cwd,
                            env=subprocess_environment(env, trusted),
                            check=True, text=True, stdout=subprocess.PIPE,
                            stderr=subprocess.STDOUT)
    return result.stdout


def version_build(version=None, build=None):
    version = version or os.environ.get('DESKTOP_APP_VERSION')
    build = build or os.environ.get('DESKTOP_APP_BUILD')
    scalar(version, 'version', r'[0-9]+\.[0-9]+\.[0-9]+')
    scalar(build, 'build number', r'[0-9]+')
    return version, build


def validate_source_sha(profile, expected):
    scalar(expected, 'approved source SHA', r'[0-9a-f]{40}')
    actual = run(['/usr/bin/git', '-C', profile['_root'], 'rev-parse', '--verify', 'HEAD']).strip()
    if actual != expected:
        raise ValueError('native source HEAD differs from admitted SHA')


def validate_sources(profile, sources, field):
    if (not isinstance(sources, list) or any(not isinstance(item, str) for item in sources) or
            sources != sorted(set(sources))):
        raise ValueError('invalid native source directories: ' + field)
    for source in sources:
        safe_path(path(profile, 'native_root'), source)


def validate_checks(profile):
    checks = profile['checks']
    checks.setdefault('format_config', None)
    checks.setdefault('lint_config', None)
    checks.setdefault('swift_test_frameworks', [])
    checks.setdefault('swift_harness_products', [])
    keys(checks, ['source_dirs', 'format_config', 'lint_config', 'swift_test_frameworks',
                  'swift_harness_products'])
    if not checks['source_dirs']:
        raise ValueError('native checks require source directories')
    for field in ['swift_harness_products']:
        values = checks[field]
        if (not isinstance(values, list) or any(not isinstance(item, str) for item in values) or
                values != sorted(set(values))):
            raise ValueError('invalid native test products')
        for value in values:
            scalar(value, field)
    validate_sources(profile, checks['source_dirs'], 'source_dirs')
    for field in ['format_config', 'lint_config']:
        if checks[field] is not None:
            safe_path(path(profile, 'native_root'), checks[field])
    frameworks = checks['swift_test_frameworks']
    if (not isinstance(frameworks, list) or any(item not in ('xctest', 'swift-testing') for item in frameworks) or
            len(set(frameworks)) != len(frameworks)):
        raise ValueError('invalid Swift test framework expectations')


def run_stream(argv, cwd=None, env=None, trusted=False):
    argv = [str(arg) for arg in argv]
    with subprocess.Popen(argv, cwd=cwd, env=subprocess_environment(env, trusted),
                          text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT) as process:
        captured = []
        for line in process.stdout:
            sys.stderr.write(line)
            sys.stderr.flush()
            captured.append(line)
        status = process.wait()
    output = ''.join(captured)
    if status != 0:
        raise subprocess.CalledProcessError(status, argv, output=output)
    return output
