use super::ledger::{AdmissionEntry, AdmissionKind, TerminalOutcome};
use super::observation::{ExecutableObservation, executable};
use eyre::{Result, bail};
use mbx_cache_core::{AdapterKind, CacheDigest, UnitIdentity, canonical_json};
use serde::Serialize;
use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};

pub(crate) struct ProvisionAttempt {
    entry: AdmissionEntry,
    original: ExecutableObservation,
    moved_path: PathBuf,
    unit: Option<UnitIdentity>,
    binary_action: CacheDigest,
    action_sidecar: PathBuf,
}

#[derive(Serialize)]
struct Transformation {
    schema_version: u8,
    kind: &'static str,
    unit: Option<UnitIdentity>,
    original_output: ExecutableObservation,
    preserved_binary: ExecutableObservation,
    final_launcher: ExecutableObservation,
    pinned_executable: ExecutableObservation,
    binary_action: CacheDigest,
    action_sidecar: PathBuf,
    action_sidecar_sha256: String,
}

impl ProvisionAttempt {
    pub(crate) fn begin(
        output: &Path,
        moved: &Path,
        binary_action: &CacheDigest,
        action_sidecar: &Path,
        unit: Option<UnitIdentity>,
    ) -> Result<Option<Self>> {
        let Some(entry) = AdmissionEntry::from_environment(
            AdapterKind::BuildScript,
            AdmissionKind::BuildScriptProvision,
        )?
        else {
            return Ok(None);
        };
        let original = executable(output)?;
        Ok(Some(Self {
            entry,
            original,
            moved_path: moved.into(),
            unit,
            binary_action: binary_action.clone(),
            action_sidecar: action_sidecar.into(),
        }))
    }

    /// Call only after outer installation and final Cargo mtime restoration succeed.
    pub(crate) fn installed(
        self,
        installed: &crate::build_script::InstalledLauncher,
    ) -> Result<()> {
        let preserved_binary = executable(&self.moved_path)?;
        let final_launcher = executable(installed.launcher_path())?;
        let pinned_executable = executable(installed.pinned_executable())?;
        if preserved_binary.sha256 != self.original.sha256 {
            bail!("build script preservation changed original compiler output");
        }
        let expected = hex::encode(Sha256::digest(installed.launcher_bytes()));
        if expected != final_launcher.sha256 {
            bail!("build script final launcher differs from actual generated bytes");
        }
        let owner = executable(&std::env::current_exe()?)?;
        if pinned_executable.sha256 != owner.sha256 {
            bail!("build script pinned executable differs from installing owner");
        }
        self.binary_action.validate()?;
        let action = super::observation::plain_bytes(&self.action_sidecar, 65536)?;
        if action != canonical_json(&self.binary_action)? {
            bail!("build script action sidecar differs from actual installing action");
        }
        self.entry.evidence(&Transformation {
            schema_version: 1,
            kind: "build_script_output_transformation",
            unit: self.unit,
            original_output: self.original,
            preserved_binary,
            final_launcher,
            pinned_executable,
            binary_action: self.binary_action,
            action_sidecar: self.action_sidecar,
            action_sidecar_sha256: hex::encode(Sha256::digest(action)),
        })
    }

    pub(crate) fn failed(self, reason: &str) -> Result<()> {
        self.entry.finish(TerminalOutcome::Failed {
            reason: reason.into(),
        })
    }
}
