[package]
name = "velnor-runner-github"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
zeroize = { workspace = true }
velnor-runner-core = { version = "=0.1.0", path = "../velnor-runner-core" }
