//! Freshness emission: the Velnor policy gains the scheduled upstream
//! probe while consumers omit it (they carry no Velnor-owned inventory).

use std::fs;

use tempfile::TempDir;
use velnor_actions_orchestrator::{GenerateOptions, generate, prepare, render_staged_tree};

use crate::support::{
    TestResult, config_with_branch, make_repo, plan_for, without_ambient_identity,
};

/// Generated freshness workflow path (contract constant mirror).
const FRESHNESS_PATH: &str = ".github/workflows/freshness.yml";

/// Velnor-policy config selecting the fixture crate.
const VELNOR_CONFIG: &str = "schema = 1\n[workflow]\nname = \"CI\"\ndefault_branch = \"testmain\"\npolicy = \"velnor-repository-v1\"\n";

/// Fixture accepted by the Velnor-repository identity check (local origin).
fn make_velnor_repo(config: &str) -> Result<TempDir, Box<dyn std::error::Error>> {
    let repo = make_repo(config)?;
    let git_config = repo.path().join(".git/config");
    let mut text = fs::read_to_string(&git_config)?;
    text.push_str("[remote \"origin\"]\n\turl = https://github.com/tailrocks/velnor-new.git\n");
    fs::write(&git_config, text)?;
    Ok(repo)
}

/// Schedule, pin, probe, timeout, and read-only shape of the workflow.
fn assert_freshness_shape(yaml: &str) {
    assert!(yaml.contains("cron: 0 6 * * 1"), "weekly trigger:\n{yaml}");
    assert!(
        yaml.contains("workflow_dispatch:"),
        "manual re-run:\n{yaml}"
    );
    assert!(
        !yaml.contains("pull_request") && !yaml.contains("push:"),
        "schedule-only:\n{yaml}"
    );
    assert!(
        yaml.contains("uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1"),
        "exact pin:\n{yaml}"
    );
    assert!(
        yaml.contains("scripts/check-freshness.sh --check-upstream"),
        "bounded probe:\n{yaml}"
    );
    assert!(
        yaml.contains("timeout-minutes: 10"),
        "explicit timeout:\n{yaml}"
    );
    assert!(!yaml.contains("write"), "read-only:\n{yaml}");
    assert!(!yaml.contains("secrets."), "no secrets:\n{yaml}");
}

#[test]
fn freshness_velnor_policy_emits_scheduled_probe() -> TestResult {
    without_ambient_identity("freshness_velnor_policy_emits_scheduled_probe", || {
        let repo = make_velnor_repo(VELNOR_CONFIG)?;
        let prep = prepare(repo.path())?;
        let first = render_staged_tree(&prep)?;
        let second = render_staged_tree(&prepare(repo.path())?)?;
        assert_eq!(first, second, "identical inputs render identical trees");
        let yaml = first
            .get(FRESHNESS_PATH)
            .ok_or_else(|| std::io::Error::other("missing freshness workflow"))?;
        assert_freshness_shape(yaml);
        let plan = plan_for(&prep)?;
        assert!(plan.contains(FRESHNESS_PATH), "plan names it:\n{plan}");
        Ok(())
    })
}

#[test]
fn freshness_consumer_omits_probe() -> TestResult {
    let repo = make_repo(config_with_branch())?;
    let prep = prepare(repo.path())?;
    let tree = render_staged_tree(&prep)?;
    assert!(
        tree.get(FRESHNESS_PATH).is_none(),
        "consumers carry no Velnor-owned inventory"
    );
    let plan = plan_for(&prep)?;
    assert!(
        !plan.contains("freshness.yml"),
        "no freshness inventory without the file:\n{plan}"
    );
    Ok(())
}

#[test]
fn freshness_preview_validates_and_writes() -> TestResult {
    without_ambient_identity("freshness_preview_validates_and_writes", || {
        let repo = make_velnor_repo(VELNOR_CONFIG)?;
        let prep = prepare(repo.path())?;
        let parent = TempDir::new()?;
        let preview = parent.path().join("preview");
        let report = generate(
            &prep,
            &GenerateOptions {
                output_dir: Some(preview.clone()),
            },
        )?;
        assert!(
            report.files_written.contains(&FRESHNESS_PATH.to_owned()),
            "written: {:?}",
            report.files_written
        );
        let yaml = fs::read_to_string(preview.join(FRESHNESS_PATH))?;
        assert_freshness_shape(&yaml);
        assert!(yaml.starts_with("# Generated by Velnor Actions "), "marker");
        assert!(
            report.validated_by.len() >= 3,
            "staged validators accepted it: {:?}",
            report.validated_by
        );
        Ok(())
    })
}
