//! P09 concurrency case: parallel `generate` never writes partially.
//!
//! Split from the preview suite; indexed in `cases.rs` with one `mod` line.

use std::fs;

use velnor_actions_orchestrator::{GenerateOptions, generate, prepare};
use velnor_actions_orchestrator_core::OrchestratorError;

use crate::support::{TestResult, config_with_branch, make_repo};

#[test]
fn concurrent_generate_never_writes_partially() -> TestResult {
    use std::sync::Barrier;
    let repo = make_repo(config_with_branch())?;
    let root = repo.path();
    let prep = prepare(root)?;
    let gate = Barrier::new(8);
    let mut outcomes = Vec::new();
    std::thread::scope(|scope| {
        let mut handles = Vec::new();
        for _ in 0..8 {
            handles.push(scope.spawn(|| {
                gate.wait();
                generate(&prep, &GenerateOptions { output_dir: None })
            }));
        }
        for handle in handles {
            outcomes.push(handle.join().expect("thread joined"));
        }
    });
    let mut won = 0;
    for outcome in outcomes {
        match outcome {
            Ok(_) => won += 1,
            Err(OrchestratorError::Contract { problem })
                if problem.contains("concurrent_generate") => {}
            Err(other) => return Err(format!("unexpected outcome: {other}").into()),
        }
    }
    assert!(won >= 1, "someone committed");
    let text = fs::read_to_string(root.join(".github/workflows/ci.yml"))?;
    assert!(
        text.starts_with("# Generated by Velnor Actions "),
        "complete tree"
    );
    assert!(!root.join(".github.velnor-generate.lock").exists());
    Ok(())
}
