//! Marker prefix unification cases.
//!
//! NOTE: wire into `velnor_contract.rs` with
//! `#[path = "impl_contract_marker.rs"] mod impl_contract_marker;`
//! (owned by another agent; same assertions already run as unit tests in
//! `src/marker.rs` until then).
use velnor_actions_contract::MARKER_PREFIX;

#[test]
fn prefix_matches_rendered_first_line_sample() {
    let sample = "# Generated by velnor-actions 0.1.0 - DO NOT EDIT";
    assert!(sample.starts_with(MARKER_PREFIX));
    assert_eq!(MARKER_PREFIX, "# Generated by velnor-actions ");
}
