//! Release workflow rendering and generated-tree determinism cases.
use super::impl_renderer_release_gates::{LABEL, gated_spec};
use velnor_actions_workflow_renderer::RenderError;
use velnor_actions_workflow_renderer::release_jobs::ReleaseWorkflowSpec;
use velnor_actions_workflow_renderer::release_tree::{
    RELEASE_TREE_PATHS, RELEASE_WORKFLOW_PATH, ReleaseRenderContext, release_stale_paths,
    render_release_files, render_release_workflow,
};

const VERSION: &str = "0.1.0";

pub(crate) fn ctx() -> ReleaseRenderContext {
    ReleaseRenderContext {
        generator_version: VERSION.to_owned(),
        runs_on: LABEL.to_owned(),
    }
}

pub(crate) fn spec() -> Result<ReleaseWorkflowSpec, RenderError> {
    gated_spec()
}

#[test]
fn release_jobs_carry_timeout_minutes_by_construction() -> Result<(), RenderError> {
    let workflow = spec()?;
    let text = render_release_workflow(&workflow, &ctx())?;
    assert_eq!(
        text.matches("timeout-minutes: 10").count(),
        workflow.jobs.len()
    );
    Ok(())
}

#[test]
fn render_emits_marked_triggers_and_exact_release_jobs() -> Result<(), RenderError> {
    let text = render_release_workflow(&spec()?, &ctx())?;
    assert_eq!(
        text.lines().next(),
        Some("# Generated by Velnor Actions 0.1.0; edit .velnor/config.toml and regenerate.")
    );
    for needle in [
        "name: Velnor Release",
        "runs-on: ubuntu-26.04",
        "workflow_dispatch",
        "plan-1",
        "release-package:",
        "release-preflight:",
        "release-registry-publish:",
        "release-forge-publish:",
        "release-reconcile:",
        "release-preparation-source:",
        "release-preparation:",
        "always()",
        "upload-artifact",
        "release-package-artifact",
    ] {
        assert!(text.contains(needle), "missing {needle}");
    }
    for forbidden in [
        "pull_request",
        "workflow_run",
        "pull_request_target",
        "CARGO_REGISTRY_TOKEN",
    ] {
        assert!(!text.contains(forbidden), "leaked {forbidden}");
    }
    Ok(())
}

#[test]
fn bootstrap_render_binds_version_and_bootstrap_environment() -> Result<(), RenderError> {
    let workflow = super::impl_renderer_release_gates::bootstrap_spec()?;
    let text = render_release_workflow(&workflow, &ctx())?;
    assert!(text.contains("inputs.version == '1.2.3'"));
    assert!(text.contains("version:"));
    assert!(text.contains("environment: crates-io-bootstrap"));
    assert!(text.contains("CARGO_REGISTRY_TOKEN"));
    Ok(())
}

#[test]
fn render_rejects_label_mismatch_and_bad_context() -> Result<(), RenderError> {
    let mut skewed = spec()?;
    skewed
        .jobs
        .get_mut("release-preflight")
        .expect("preflight")
        .runs_on = "ubuntu-22.04".to_owned();
    assert!(matches!(
        render_release_workflow(&skewed, &ctx()),
        Err(RenderError::InvalidWorkflow(text)) if text == "label_mismatch:release-preflight"
    ));
    let bad_version = ReleaseRenderContext {
        generator_version: "bad version!".to_owned(),
        runs_on: LABEL.to_owned(),
    };
    assert!(matches!(
        render_release_workflow(&spec()?, &bad_version),
        Err(RenderError::BadVersion(_))
    ));
    let bad_label = ReleaseRenderContext {
        generator_version: VERSION.to_owned(),
        runs_on: "ubuntu-latest".to_owned(),
    };
    assert!(render_release_workflow(&spec()?, &bad_label).is_err());
    Ok(())
}

#[test]
fn files_use_the_fixed_release_tree_inventory() -> Result<(), RenderError> {
    let files = render_release_files(&spec()?, &ctx())?;
    assert_eq!(files.workflow.path, RELEASE_WORKFLOW_PATH);
    let paths = files
        .as_sorted_vec()
        .into_iter()
        .map(|file| file.path)
        .collect::<Vec<_>>();
    assert_eq!(
        paths,
        RELEASE_TREE_PATHS
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
    );
    Ok(())
}

#[test]
fn stale_paths_are_sorted_and_match_the_emitted_tree() {
    let mut sorted = release_stale_paths().to_vec();
    sorted.sort_unstable();
    assert_eq!(release_stale_paths(), sorted.as_slice());
    assert_eq!(RELEASE_TREE_PATHS, release_stale_paths());
}

#[test]
fn rendering_is_deterministic_across_runs() -> Result<(), RenderError> {
    let first = render_release_files(&spec()?, &ctx())?;
    let second = render_release_files(&spec()?, &ctx())?;
    assert_eq!(first, second);
    assert_eq!(
        render_release_workflow(&spec()?, &ctx())?,
        render_release_workflow(&spec()?, &ctx())?
    );
    Ok(())
}
