//! Workflow/tree rendering and policy gating cases.
use std::collections::BTreeMap;
use std::error::Error;
use std::fs;
use std::path::PathBuf;
use velnor_actions_contract::{
    Concurrency, GeneratorValidation, Job, JobTimeout, Permissions, Trigger, ValidatorKind,
    VelnorSupportWorkflow, WorkflowIr, WorkflowPolicy,
};
use velnor_actions_workflow_renderer::{
    ACTIONLINT_PATH, AGENTS_MD_PATH, ALINT_USES, CANDIDATE_JOB_ID, CONCURRENCY_CANCEL,
    CONCURRENCY_GROUP, FORBIDDEN_TOKENS, INTERNAL_OP_ENV, REQUEST_FILE_ENV, RenderContext,
    RenderError, ValidatorCommand, WORKFLOW_PATH, checkout_step, plan_step, render_tree,
    render_workflow_ir, with_marker,
};

const VERSION: &str = "0.1.0";
const LABEL: &str = "ubuntu-26.04";

fn checkout_pin() -> String {
    format!("actions/checkout@{:040x}", 0)
}

pub(crate) fn fixture_ctx() -> RenderContext {
    RenderContext {
        generator_version: VERSION.to_owned(),
        runs_on: LABEL.to_owned(),
        staged_binary: format!("$RUNNER_TEMP/velnor/bin/velnor-actions-{VERSION}"),
        request_dir: "${{ runner.temp }}/velnor/r1-a1".to_owned(),
        checkout_uses: checkout_pin(),
        validator_commands: Vec::new(),
        candidate: None,
        preseed: false,
        workflow_tasks: Vec::new(),
        pull_request_cache_policy: velnor_actions_contract::PullRequestCachePolicy::ReadOnly,
        plan_consumer_env: std::collections::BTreeMap::new(),
    }
}

fn exact_triggers() -> Trigger {
    Trigger {
        pull_request_types: ["opened", "synchronize", "reopened", "ready_for_review"]
            .iter()
            .map(ToString::to_string)
            .collect(),
        push_branches: vec!["main".to_owned()],
        merge_group: true,
        workflow_dispatch: None,
        schedule: None,
    }
}

fn exact_concurrency() -> Concurrency {
    Concurrency {
        group: CONCURRENCY_GROUP.to_owned(),
        cancel_in_progress: CONCURRENCY_CANCEL.to_owned(),
    }
}

fn plan_job() -> Result<Job, RenderError> {
    Ok(Job {
        display_name: "Plan".to_owned(),
        runs_on: LABEL.to_owned(),
        check_runner: None,
        timeout_minutes: JobTimeout::PLAN,
        needs: Vec::new(),
        condition: None,
        permissions: None,
        environment: None,
        steps: vec![checkout_step(&checkout_pin())?, plan_step()],
    })
}

pub(crate) fn fixture_ir() -> Result<WorkflowIr, RenderError> {
    let mut jobs = BTreeMap::new();
    jobs.insert("plan".to_owned(), plan_job()?);
    Ok(WorkflowIr {
        name: "CI".to_owned(),
        triggers: exact_triggers(),
        permissions: Permissions::default(),
        concurrency: exact_concurrency(),
        jobs,
    })
}

fn actionlint_bytes() -> Result<String, RenderError> {
    with_marker(VERSION, "config-variables: []\n")
}

#[test]
fn marker_is_exact_first_line_without_dates() -> Result<(), RenderError> {
    let text = render_workflow_ir(
        &fixture_ir()?,
        WorkflowPolicy::ConsumerV1,
        None,
        &fixture_ctx(),
    )?;
    let first = text.lines().next();
    assert!(first.is_some());
    if let Some(line) = first {
        assert_eq!(
            line,
            "# Generated by Velnor Actions 0.1.0; edit .velnor/config.toml and regenerate."
        );
        assert!(!line.contains("2026"));
    }
    assert!(with_marker("bad version", "x").is_err());
    Ok(())
}

#[test]
fn workflow_render_is_byte_stable() -> Result<(), RenderError> {
    let ir = fixture_ir()?;
    let ctx = fixture_ctx();
    let first = render_workflow_ir(&ir, WorkflowPolicy::ConsumerV1, None, &ctx)?;
    let second = render_workflow_ir(&ir, WorkflowPolicy::ConsumerV1, None, &ctx)?;
    assert_eq!(first, second);
    Ok(())
}

#[test]
fn consumer_tree_has_exactly_three_sorted_paths() -> Result<(), RenderError> {
    let workflow = render_workflow_ir(
        &fixture_ir()?,
        WorkflowPolicy::ConsumerV1,
        None,
        &fixture_ctx(),
    )?;
    let tree = render_tree(&workflow, &actionlint_bytes()?, VERSION)?;
    assert_eq!(tree.files.len(), 3);
    assert!(tree.symlinks.is_empty());
    assert_eq!(tree.files[0].path, AGENTS_MD_PATH);
    assert_eq!(tree.files[1].path, ACTIONLINT_PATH);
    assert_eq!(tree.files[2].path, WORKFLOW_PATH);
    assert_eq!(tree.get(WORKFLOW_PATH), Some(workflow.as_str()));
    assert!(tree.get(".github/other.yml").is_none());
    assert!(tree.get(".github/CLAUDE.md").is_none());
    Ok(())
}

#[test]
fn consumer_tree_has_no_codeowners_merges_verify_and_rejects_candidate() -> Result<(), RenderError>
{
    let ir = fixture_ir()?;
    let ctx = fixture_ctx();
    // Config-selected verification jobs merge on the consumer policy.
    let with_verify = VelnorSupportWorkflow {
        validators: vec![ValidatorKind::Alint],
        candidate_validation: false,
    };
    let text = render_workflow_ir(&ir, WorkflowPolicy::ConsumerV1, Some(&with_verify), &ctx)?;
    assert!(text.contains("alint:"));
    // Velnor-only validators still fail closed on the consumer policy.
    let with_denied = VelnorSupportWorkflow {
        validators: vec![ValidatorKind::CargoDeny],
        candidate_validation: false,
    };
    assert!(render_workflow_ir(&ir, WorkflowPolicy::ConsumerV1, Some(&with_denied), &ctx).is_err());
    let with_candidate = VelnorSupportWorkflow {
        validators: Vec::new(),
        candidate_validation: true,
    };
    assert!(
        render_workflow_ir(&ir, WorkflowPolicy::ConsumerV1, Some(&with_candidate), &ctx).is_err()
    );
    let empty = VelnorSupportWorkflow {
        validators: Vec::new(),
        candidate_validation: false,
    };
    let text = render_workflow_ir(&ir, WorkflowPolicy::ConsumerV1, Some(&empty), &ctx)?;
    assert!(!text.contains("CODEOWNERS"));
    let tree = render_tree(&text, &actionlint_bytes()?, VERSION)?;
    assert_eq!(tree.files.len(), 3);
    assert!(tree.symlinks.is_empty());
    Ok(())
}

#[test]
fn consumer_rejects_support_job_ids_in_ir() -> Result<(), RenderError> {
    let mut ir = fixture_ir()?;
    let ctx = fixture_ctx();
    for forbidden in [
        "alint",
        "cargo-deny",
        "cargo-machete",
        "zizmor",
        "candidate",
    ] {
        let mut with_job = ir.clone();
        with_job.jobs.insert(forbidden.to_owned(), plan_job()?);
        assert!(
            render_workflow_ir(&with_job, WorkflowPolicy::ConsumerV1, None, &ctx).is_err(),
            "consumer accepted {forbidden}"
        );
    }
    assert!(render_workflow_ir(&ir, WorkflowPolicy::ConsumerV1, None, &ctx).is_ok());
    ir.jobs.remove("plan");
    assert!(render_workflow_ir(&ir, WorkflowPolicy::ConsumerV1, None, &ctx).is_err());
    Ok(())
}

fn validator_commands() -> Vec<ValidatorCommand> {
    // Production names: the scrub gate allowlists these exactly.
    [
        (ValidatorKind::CargoDeny, "Run cargo-deny"),
        (ValidatorKind::CargoMachete, "Run cargo-machete"),
        (ValidatorKind::Zizmor, "Run zizmor"),
    ]
    .iter()
    .map(|(validator, name)| ValidatorCommand {
        validator: *validator,
        name: (*name).to_owned(),
        argv: vec!["deny".to_owned()],
        prepare_argv: Vec::new(),
    })
    .collect()
}

#[test]
fn velnor_policy_renders_validators_only() -> Result<(), RenderError> {
    let ir = fixture_ir()?;
    let mut ctx = fixture_ctx();
    ctx.validator_commands = validator_commands();
    let support =
        WorkflowPolicy::VelnorRepositoryV1.support_workflow(GeneratorValidation::Bootstrap);
    let text = render_workflow_ir(
        &ir,
        WorkflowPolicy::VelnorRepositoryV1,
        Some(&support),
        &ctx,
    )?;
    for id in ["alint:", "cargo-deny:", "cargo-machete:", "zizmor:"] {
        assert!(text.contains(id), "missing {id}:\n{text}");
    }
    assert!(text.contains(ALINT_USES));
    assert!(text.contains("fail-on-warning"));
    assert!(!text.contains("workflow_dispatch:"));
    assert!(!text.contains("toolchain"));
    assert!(!text.contains(CANDIDATE_JOB_ID));
    let mut dup_ctx = fixture_ctx();
    dup_ctx.validator_commands = validator_commands();
    let dup = VelnorSupportWorkflow {
        validators: vec![ValidatorKind::Alint, ValidatorKind::Alint],
        candidate_validation: false,
    };
    assert!(
        render_workflow_ir(
            &ir,
            WorkflowPolicy::VelnorRepositoryV1,
            Some(&dup),
            &dup_ctx
        )
        .is_err()
    );
    Ok(())
}

#[test]
fn rendered_yaml_contains_no_private_subcommands() -> Result<(), Box<dyn Error>> {
    let ir = fixture_ir()?;
    let mut ctx = fixture_ctx();
    ctx.validator_commands = validator_commands();
    let support =
        WorkflowPolicy::VelnorRepositoryV1.support_workflow(GeneratorValidation::Bootstrap);
    let text = render_workflow_ir(
        &ir,
        WorkflowPolicy::VelnorRepositoryV1,
        Some(&support),
        &ctx,
    )?;
    for token in FORBIDDEN_TOKENS {
        assert!(!text.contains(token), "leaked token: {token}");
    }
    assert!(text.contains(&format!("{INTERNAL_OP_ENV}: plan-v1")));
    assert!(text.contains(&format!(
        "{REQUEST_FILE_ENV}: ${{{{ runner.temp }}}}/velnor/r1-a1/plan-v1-request.json"
    )));
    let rendered_run = rendered_plan_run(&text)
        .ok_or_else(|| std::io::Error::other("rendered plan step has no single-line run scalar"))?;
    let root = scratch_path("rendered-plan-argv")?;
    // A matching path makes an accidental unquoted glob expand during argv execution.
    let glob_match = root.join("Runner Space/literal-match/velnor/bin");
    fs::create_dir_all(&glob_match)?;
    fs::write(
        glob_match.join(format!("velnor-actions-{VERSION}")),
        b"staged",
    )?;
    let runner_temp = root
        .join("Runner Space/[l]iteral*")
        .to_string_lossy()
        .into_owned();
    let expected = ctx.staged_binary.replace("$RUNNER_TEMP", &runner_temp);
    assert_eq!(
        crate::impl_renderer_steps_quote::shell_argv(
            &rendered_run,
            Some(&runner_temp),
            "/tmp/Home Space",
        )?,
        vec![expected]
    );
    fs::remove_dir_all(root)?;
    Ok(())
}

fn rendered_plan_run(yaml: &str) -> Option<String> {
    // Decode the emitted scalar, then test shell argv semantics instead of YAML bytes.
    let mut in_plan_step = false;
    let mut run = None;
    for line in yaml.lines() {
        let trimmed = line.trim_start();
        if trimmed.starts_with("- name: ") {
            in_plan_step = trimmed == "- name: Plan";
            continue;
        }
        if in_plan_step && let Some(scalar) = trimmed.strip_prefix("run: ") {
            if run.is_some() {
                return None;
            }
            run = decode_yaml_scalar(scalar);
        }
    }
    run
}

fn decode_yaml_scalar(scalar: &str) -> Option<String> {
    if scalar.starts_with('\'') {
        let body = scalar.strip_prefix('\'')?.strip_suffix('\'')?;
        let mut decoded = String::with_capacity(body.len());
        let mut chars = body.chars().peekable();
        while let Some(ch) = chars.next() {
            if ch == '\'' {
                chars.next_if_eq(&'\'')?;
            }
            decoded.push(ch);
        }
        return Some(decoded);
    }
    if scalar.starts_with('"') {
        let body = scalar.strip_prefix('"')?.strip_suffix('"')?;
        let mut decoded = String::with_capacity(body.len());
        let mut chars = body.chars();
        while let Some(ch) = chars.next() {
            if ch == '\\' {
                decoded.push(match chars.next()? {
                    '"' => '"',
                    '\\' => '\\',
                    'n' => '\n',
                    'r' => '\r',
                    't' => '\t',
                    _ => return None,
                });
            } else {
                decoded.push(ch);
            }
        }
        return Some(decoded);
    }
    Some(scalar.to_owned())
}

fn scratch_path(name: &str) -> Result<PathBuf, std::io::Error> {
    let temp_root = fs::canonicalize(std::env::temp_dir())?;
    let root = temp_root.join(format!("velnor-{name}-{}", std::process::id()));
    if root.exists() {
        fs::remove_dir_all(&root)?;
    }
    Ok(root)
}

#[test]
fn internal_gate_requires_staged_binary_and_request_dir() -> Result<(), RenderError> {
    let ir = fixture_ir()?;
    let mut ctx = fixture_ctx();
    ctx.staged_binary = "/tmp/velnor-actions-0.1.0".to_owned();
    assert!(render_workflow_ir(&ir, WorkflowPolicy::ConsumerV1, None, &ctx).is_err());
    let mut ctx = fixture_ctx();
    ctx.staged_binary = "$RUNNER_TEMP/velnor/bin/velnor-actions-9.9.9".to_owned();
    assert!(render_workflow_ir(&ir, WorkflowPolicy::ConsumerV1, None, &ctx).is_err());
    let mut ctx = fixture_ctx();
    ctx.request_dir = "/tmp/velnor".to_owned();
    assert!(render_workflow_ir(&ir, WorkflowPolicy::ConsumerV1, None, &ctx).is_err());
    Ok(())
}
