//! Workflow/tree rendering and policy gating cases.
use std::collections::BTreeMap;
use std::error::Error;
use std::fs;
use std::path::PathBuf;
use velnor_actions_contract::{
    Concurrency, GeneratorValidation, Job, JobTimeout, Permissions, Trigger, ValidatorKind,
    VelnorSupportWorkflow, WorkflowIr, WorkflowPolicy,
};
use velnor_actions_workflow_renderer::{
    ACTIONLINT_PATH, AGENTS_MD_PATH, ALINT_USES, CANDIDATE_JOB_ID, CLAUDE_MD_PATH,
    CONCURRENCY_CANCEL, CONCURRENCY_GROUP, FORBIDDEN_TOKENS, INTERNAL_OP_ENV, REQUEST_FILE_ENV,
    RenderContext, RenderError, ValidatorCommand, WORKFLOW_PATH, checkout_step, plan_step,
    render_tree, render_workflow_ir, with_marker,
};

const VERSION: &str = "0.1.0";
const LABEL: &str = "ubuntu-26.04";

fn checkout_pin() -> String {
    format!("actions/checkout@{:040x}", 0)
}

pub(crate) fn fixture_ctx() -> RenderContext {
    RenderContext {
        generator_version: VERSION.to_owned(),
        report_helper_version: VERSION.to_owned(),
        runs_on: LABEL.to_owned(),
        scale_set_selector: None,
        staged_binary: format!("$RUNNER_TEMP/velnor/bin/velnor-actions-{VERSION}"),
        request_dir: "${{ runner.temp }}/velnor/r1-a1".to_owned(),
        checkout_uses: checkout_pin(),
        validator_commands: Vec::new(),
        candidate: None,
        preseed: false,
        workflow_tasks: Vec::new(),
        pull_request_cache_policy: velnor_actions_contract::PullRequestCachePolicy::ReadOnly,
        plan_consumer_env: std::collections::BTreeMap::new(),
    }
}

fn exact_triggers() -> Trigger {
    Trigger {
        pull_request_types: ["opened", "synchronize", "reopened", "ready_for_review"]
            .iter()
            .map(ToString::to_string)
            .collect(),
        push_branches: vec!["main".to_owned()],
        merge_group: true,
        workflow_dispatch: None,
        schedule: None,
    }
}

fn exact_concurrency() -> Concurrency {
    Concurrency {
        group: CONCURRENCY_GROUP.to_owned(),
        cancel_in_progress: CONCURRENCY_CANCEL.to_owned(),
    }
}

fn plan_job() -> Result<Job, RenderError> {
    Ok(Job {
        display_name: "Plan".to_owned(),
        runs_on: LABEL.to_owned(),
        check_runner: None,
        timeout_minutes: JobTimeout::PLAN,
        needs: Vec::new(),
        condition: None,
        permissions: None,
        environment: None,
        steps: vec![checkout_step(&checkout_pin())?, plan_step()],
    })
}

pub(crate) fn fixture_ir() -> Result<WorkflowIr, RenderError> {
    let mut jobs = BTreeMap::new();
    jobs.insert("plan".to_owned(), plan_job()?);
    Ok(WorkflowIr {
        name: "CI".to_owned(),
        triggers: exact_triggers(),
        permissions: Permissions::default(),
        concurrency: exact_concurrency(),
        jobs,
    })
}

fn actionlint_bytes() -> Result<String, RenderError> {
    with_marker(VERSION, "config-variables: []\n")
}

#[test]
fn marker_is_exact_first_line_without_dates() -> Result<(), RenderError> {
    let text = render_workflow_ir(
        &fixture_ir()?,
        WorkflowPolicy::ConsumerV1,
        None,
        &fixture_ctx(),
    )?;
    let first = text.lines().next();
    assert!(first.is_some());
    if let Some(line) = first {
        assert_eq!(
            line,
            "# Generated by Velnor Actions 0.1.0; edit .velnor/config.toml and regenerate."
        );
        assert!(!line.contains("2026"));
    }
    assert!(with_marker("bad version", "x").is_err());
    Ok(())
}

#[test]
fn generator_marker_and_report_helper_versions_are_independent() -> Result<(), RenderError> {
    let ir = fixture_ir()?;
    let mut ctx = fixture_ctx();
    ctx.generator_version = "0.1.7".to_owned();
    ctx.report_helper_version = "0.1.4".to_owned();
    ctx.staged_binary = "$RUNNER_TEMP/velnor/bin/velnor-actions-0.1.4".to_owned();

    let workflow = render_workflow_ir(&ir, WorkflowPolicy::ConsumerV1, None, &ctx)?;
    assert_eq!(
        workflow.lines().next(),
        Some("# Generated by Velnor Actions 0.1.7; edit .velnor/config.toml and regenerate.")
    );

    ctx.staged_binary = "$RUNNER_TEMP/velnor/bin/velnor-actions-0.1.7".to_owned();
    assert!(
        render_workflow_ir(&ir, WorkflowPolicy::ConsumerV1, None, &ctx).is_err(),
        "the staged helper must match the consumer helper release, not the generator marker"
    );

    assert!(
        render_tree(&workflow, &actionlint_bytes()?, VERSION).is_err(),
        "tree assembly rejects a workflow whose generator marker differs from the tree version"
    );
    Ok(())
}

#[test]
fn workflow_render_is_byte_stable() -> Result<(), RenderError> {
    let ir = fixture_ir()?;
    let ctx = fixture_ctx();
    let first = render_workflow_ir(&ir, WorkflowPolicy::ConsumerV1, None, &ctx)?;
    let second = render_workflow_ir(&ir, WorkflowPolicy::ConsumerV1, None, &ctx)?;
    assert_eq!(first, second);
    Ok(())
}

#[test]
fn consumer_tree_has_exactly_four_sorted_paths() -> Result<(), RenderError> {
    let workflow = render_workflow_ir(
        &fixture_ir()?,
        WorkflowPolicy::ConsumerV1,
        None,
        &fixture_ctx(),
    )?;
    let tree = render_tree(&workflow, &actionlint_bytes()?, VERSION)?;
    assert_eq!(tree.files.len(), 4);
    assert_eq!(
        tree.symlinks,
        [] as [velnor_actions_workflow_renderer::RenderedSymlink; 0]
    );
    assert_eq!(tree.files[0].path, AGENTS_MD_PATH);
    assert_eq!(tree.files[1].path, CLAUDE_MD_PATH);
    assert_eq!(tree.files[2].path, ACTIONLINT_PATH);
    assert_eq!(tree.files[3].path, WORKFLOW_PATH);
    assert_eq!(tree.files[1].bytes, "@AGENTS.md\n");
    assert_eq!(tree.get(WORKFLOW_PATH), Some(workflow.as_str()));
    assert!(tree.get(".github/other.yml").is_none());
    Ok(())
}

#[test]
fn consumer_tree_has_no_codeowners_merges_verify_and_rejects_candidate() -> Result<(), RenderError>
{
    let ir = fixture_ir()?;
    let ctx = fixture_ctx();
    // Config-selected verification jobs merge on the consumer policy.
    let with_verify = VelnorSupportWorkflow {
        validators: vec![ValidatorKind::Alint],
        candidate_validation: false,
    };
    let text = render_workflow_ir(&ir, WorkflowPolicy::ConsumerV1, Some(&with_verify), &ctx)?;
    assert!(text.contains("alint:"));
    // Velnor-only validators still fail closed on the consumer policy.
    let with_denied = VelnorSupportWorkflow {
        validators: vec![ValidatorKind::CargoDeny],
        candidate_validation: false,
    };
    assert!(render_workflow_ir(&ir, WorkflowPolicy::ConsumerV1, Some(&with_denied), &ctx).is_err());
    let with_candidate = VelnorSupportWorkflow {
        validators: Vec::new(),
        candidate_validation: true,
    };
    assert!(
        render_workflow_ir(&ir, WorkflowPolicy::ConsumerV1, Some(&with_candidate), &ctx).is_err()
    );
    let empty = VelnorSupportWorkflow {
        validators: Vec::new(),
        candidate_validation: false,
    };
    let text = render_workflow_ir(&ir, WorkflowPolicy::ConsumerV1, Some(&empty), &ctx)?;
    assert!(!text.contains("CODEOWNERS"));
    let tree = render_tree(&text, &actionlint_bytes()?, VERSION)?;
    assert_eq!(tree.files.len(), 4);
    assert_eq!(
        tree.symlinks,
        [] as [velnor_actions_workflow_renderer::RenderedSymlink; 0]
    );
    Ok(())
}

#[test]
fn consumer_rejects_support_job_ids_in_ir() -> Result<(), RenderError> {
    let mut ir = fixture_ir()?;
    let ctx = fixture_ctx();
    for forbidden in [
        "alint",
        "cargo-deny",
        "cargo-machete",
        "zizmor",
        "candidate",
    ] {
        let mut with_job = ir.clone();
        with_job.jobs.insert(forbidden.to_owned(), plan_job()?);
        assert!(
            render_workflow_ir(&with_job, WorkflowPolicy::ConsumerV1, None, &ctx).is_err(),
            "consumer accepted {forbidden}"
        );
    }
    assert!(render_workflow_ir(&ir, WorkflowPolicy::ConsumerV1, None, &ctx).is_ok());
    ir.jobs.remove("plan");
    assert!(render_workflow_ir(&ir, WorkflowPolicy::ConsumerV1, None, &ctx).is_err());
    Ok(())
}

fn validator_commands() -> Vec<ValidatorCommand> {
    // Production names: the scrub gate allowlists these exactly.
    [
        (ValidatorKind::CargoDeny, "Run cargo-deny"),
        (ValidatorKind::CargoMachete, "Run cargo-machete"),
        (ValidatorKind::Zizmor, "Run zizmor"),
    ]
    .iter()
    .map(|(validator, name)| ValidatorCommand {
        validator: *validator,
        name: (*name).to_owned(),
        argv: vec!["deny".to_owned()],
        prepare_argv: Vec::new(),
    })
    .collect()
}

#[test]
fn velnor_policy_renders_validators_only() -> Result<(), RenderError> {
    let ir = fixture_ir()?;
    let mut ctx = fixture_ctx();
    ctx.validator_commands = validator_commands();
    let support =
        WorkflowPolicy::VelnorRepositoryV1.support_workflow(GeneratorValidation::Bootstrap);
    let text = render_workflow_ir(
        &ir,
        WorkflowPolicy::VelnorRepositoryV1,
        Some(&support),
        &ctx,
    )?;
    for id in ["alint:", "cargo-deny:", "cargo-machete:", "zizmor:"] {
        assert!(text.contains(id), "missing {id}:\n{text}");
    }
    assert!(text.contains(ALINT_USES));
    assert!(text.contains("fail-on-warning"));
    assert!(!text.contains("workflow_dispatch:"));
    assert!(!text.contains("toolchain"));
    assert!(!text.contains(CANDIDATE_JOB_ID));
    let mut dup_ctx = fixture_ctx();
    dup_ctx.validator_commands = validator_commands();
    let dup = VelnorSupportWorkflow {
        validators: vec![ValidatorKind::Alint, ValidatorKind::Alint],
        candidate_validation: false,
    };
    assert!(
        render_workflow_ir(
            &ir,
            WorkflowPolicy::VelnorRepositoryV1,
            Some(&dup),
            &dup_ctx
        )
        .is_err()
    );
    Ok(())
}

#[path = "impl_renderer_tree_policy_tests.rs"]
mod policy_tests;
