//! Effective release-plz config validation and rendering cases.
use velnor_actions_workflow_renderer::RenderError;
use velnor_actions_workflow_renderer::release_config::{
    BootstrapReleasePlzConfig, ReleasePlzConfig, ReleasePlzPackage,
    render_bootstrap_release_plz_config, render_release_plz_config, validate_feature_name,
    validate_tag_pattern,
};

const VERSION: &str = "0.1.0";
const TAG: &str = "{{ package }}-v{{ version }}";

/// Extract the `InvalidWorkflow` payload; `None` unless the exact rejection fired.
fn invalid(result: Result<(), RenderError>) -> Option<String> {
    match result {
        Err(RenderError::InvalidWorkflow(text)) => Some(text),
        Err(_) | Ok(()) => None,
    }
}

fn package(name: &str) -> ReleasePlzPackage {
    ReleasePlzPackage {
        name: name.to_owned(),
        publish_features: Vec::new(),
    }
}

fn config() -> ReleasePlzConfig {
    ReleasePlzConfig {
        tag_pattern: TAG.to_owned(),
        semver_check: true,
        packages: vec![package("alpha"), package("beta")],
    }
}

#[test]
fn feature_names_accept_cargo_charset_only() {
    for feature in ["pty", "a+b.c/d-e_f0", "X9"] {
        assert!(validate_feature_name(feature).is_ok(), "for {feature}");
    }
    for feature in [
        "",
        "has space",
        "bad!",
        "x${{y}}",
        "semi;colon",
        "back\\slash",
    ] {
        assert_eq!(
            invalid(validate_feature_name(feature)).expect("reject"),
            format!("bad_feature:{feature}"),
            "for {feature:?}"
        );
    }
}

#[test]
fn tag_pattern_requires_both_placeholders() {
    assert!(validate_tag_pattern(TAG).is_ok());
    assert!(validate_tag_pattern("{{package}}-{{ version }}-x").is_ok());
    for pattern in [
        "",
        "v{{ version }}",
        "{{ package }}-v1.0",
        "{{ package }}-v{{ version }",
        "{{ package }}-v{{ version }} }}",
        "{{ package }}-{{ other }}",
        "{{ package }}-\"v{{ version }}\"",
        "{{ package }}-v{{ version }}\\",
    ] {
        assert_eq!(
            invalid(validate_tag_pattern(pattern)).expect("reject"),
            format!("bad_tag_pattern:{pattern}"),
            "for {pattern:?}"
        );
    }
}

#[test]
fn config_rejects_empty_duplicate_and_oversize_sets() {
    assert!(config().validate().is_ok());
    let empty = ReleasePlzConfig {
        packages: Vec::new(),
        ..config()
    };
    assert_eq!(
        invalid(empty.validate()).expect("reject"),
        "no_release_packages"
    );
    let duplicate = ReleasePlzConfig {
        packages: vec![package("alpha"), package("alpha")],
        ..config()
    };
    assert_eq!(
        invalid(duplicate.validate()).expect("reject"),
        "duplicate_package:alpha"
    );
    let bad_feature = ReleasePlzConfig {
        packages: vec![ReleasePlzPackage {
            name: "alpha".to_owned(),
            publish_features: vec!["bad feature".to_owned()],
        }],
        ..config()
    };
    assert!(
        invalid(bad_feature.validate())
            .expect("reject")
            .starts_with("bad_feature:")
    );
    let oversize = ReleasePlzConfig {
        packages: (0..65).map(|n| package(&format!("p{n:02}"))).collect(),
        ..config()
    };
    assert_eq!(
        invalid(oversize.validate()).expect("reject"),
        "no_release_packages"
    );
}

#[test]
fn normal_render_matches_golden_snapshot() -> Result<(), RenderError> {
    let first = render_release_plz_config(&config(), VERSION)?;
    let second = render_release_plz_config(&config(), VERSION)?;
    assert_eq!(first, second, "byte-identical across runs");
    let expected = "# Generated by Velnor Actions 0.1.0; edit .velnor/config.toml and regenerate.\n\
        [workspace]\nrelease = false\nrelease_always = false\nsemver_check = true\n\
        publish_no_verify = false\npublish_allow_dirty = false\n\
        git_tag_name = \"{{ package }}-v{{ version }}\"\n\
        \n[[package]]\nname = \"alpha\"\nrelease = true\npublish = true\ngit_only = false\n\
        \n[[package]]\nname = \"beta\"\nrelease = true\npublish = true\ngit_only = false\n";
    assert_eq!(first, expected, "golden snapshot");
    Ok(())
}

#[test]
fn bootstrap_differs_only_in_release_always() -> Result<(), RenderError> {
    let normal = render_release_plz_config(&config(), VERSION)?;
    let wrapped = BootstrapReleasePlzConfig::new(config())?;
    let bootstrap = render_bootstrap_release_plz_config(&wrapped, VERSION)?;
    assert!(bootstrap.contains("release_always = true"));
    assert!(!normal.contains("release_always = true"));
    assert_eq!(
        bootstrap.replace("release_always = true", "release_always = false"),
        normal,
        "single-flag variant"
    );
    assert!(
        BootstrapReleasePlzConfig::new(ReleasePlzConfig {
            packages: Vec::new(),
            ..config()
        })
        .is_err()
    );
    Ok(())
}

#[test]
fn semver_and_features_pass_through_verbatim() -> Result<(), RenderError> {
    let strict = ReleasePlzConfig {
        semver_check: false,
        packages: vec![ReleasePlzPackage {
            name: "alpha".to_owned(),
            publish_features: vec!["pty".to_owned(), "serde/std".to_owned()],
        }],
        ..config()
    };
    let text = render_release_plz_config(&strict, VERSION)?;
    assert!(text.contains("semver_check = false"));
    assert!(text.contains("publish_features = [\"pty\", \"serde/std\"]"));
    assert!(!render_release_plz_config(&config(), VERSION)?.contains("publish_features"));
    Ok(())
}
