//! First-line generator-version marker prefix shared by every crate.
//!
//! Single source of truth: the renderer re-exports [`MARKER_PREFIX`] so
//! generated output and generated-output detectors agree byte-for-byte.

/// Marker text before the generator version.
pub const MARKER_PREFIX: &str = "# Generated by Velnor Actions ";

/// Historical marker prefix (`# Generated by velnor-actions <v> - DO NOT
/// EDIT`). Old generated files were never handwritten; recognition MUST
/// accept both spellings so regeneration never misreads them as evidence.
pub const OLD_MARKER_PREFIX: &str = "# Generated by velnor-actions ";

/// Whether a first line marks generated output (current or historical).
#[must_use]
pub fn is_generated_marker_line(first: &str) -> bool {
    first.starts_with(MARKER_PREFIX) || first.starts_with(OLD_MARKER_PREFIX)
}

#[cfg(test)]
mod tests;
