//! Effect-free compiled OCI helper source ownership.

use crate::{OwnedSupportFile, SupportBundle};
use velnor_actions_contract::ContractError;

/// Fixed Python entry source; the executable Bash closure is composed separately.
pub const ENTRY_PATH: &str = ".github/velnor/oci_delivery.py";

/// Complete fixed OCI semantic source inventory; generic admission is composed separately.
pub const SUPPORT_PATHS: &[&str] = &[
    ENTRY_PATH,
    ".github/velnor/oci_digest.py",
    ".github/velnor/oci_digest_parts.py",
    ".github/velnor/oci_index_receipt.py",
    ".github/velnor/oci_archive.py",
    ".github/velnor/oci_registry.py",
    ".github/velnor/oci_platform_publish.py",
];

/// Return the entire fixed OCI source closure with deterministic version markers.
/// # Errors
/// Rejects invalid generated source markers or fixed source records.
pub fn support_sources(version: &str) -> Result<SupportBundle, ContractError> {
    let sources = [
        (SUPPORT_PATHS[0], include_str!("oci_delivery.py")),
        (SUPPORT_PATHS[1], include_str!("oci_digest.py")),
        (SUPPORT_PATHS[2], include_str!("oci_digest_parts.py")),
        (SUPPORT_PATHS[3], include_str!("oci_index_receipt.py")),
        (SUPPORT_PATHS[4], include_str!("oci_archive.py")),
        (SUPPORT_PATHS[5], include_str!("oci_registry.py")),
        (SUPPORT_PATHS[6], include_str!("oci_platform_publish.py")),
    ];
    let files = sources
        .into_iter()
        .map(|(path, body)| OwnedSupportFile::compiled(path, body, version))
        .collect::<Result<Vec<_>, _>>()?;
    SupportBundle::compiled(files)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fixed_source_bundle_is_complete_and_deterministic() {
        let bundle = support_sources("0.1.0").expect("valid compiled sources");
        let paths = bundle
            .files()
            .iter()
            .map(OwnedSupportFile::path)
            .collect::<Vec<_>>();
        let mut expected = SUPPORT_PATHS.to_vec();
        expected.sort_unstable();
        assert_eq!(paths, expected);
        assert_eq!(
            bundle,
            support_sources("0.1.0").expect("deterministic sources")
        );
        assert!(bundle.files().iter().all(|file| {
            file.source()
                .starts_with("# Generated by Velnor Actions 0.1.0;")
        }));
    }

    #[test]
    fn malformed_generator_version_cannot_emit_sources() {
        assert!(support_sources("0.1.0\ninjected").is_err());
    }
}
