"""Fixed entrypoint for generated native OCI publication gates."""
import sys
import types

MODULES = frozenset({
    "oci_digest", "oci_digest_parts", "oci_index_receipt", "release_admission",
    "oci_archive", "oci_registry", "oci_platform_publish",
})


def load_fixed(name):
    if name not in MODULES:
        raise SystemExit("oci_module_identity")
    sources = globals().get("OCI_COMPILED_SOURCES")
    if not isinstance(sources, dict) or set(sources) != MODULES:
        raise SystemExit("oci_compiled_source_closure")
    source = sources[name]
    if not isinstance(source, str) or len(source) > 262144 or not source.splitlines():
        raise SystemExit("oci_module_source")
    if not source.splitlines()[0].startswith("# Generated by Velnor Actions "):
        raise SystemExit("oci_module_marker")
    module = types.ModuleType(name)
    sys.modules[name] = module
    exec(compile(source, "<compiled-oci-" + name + ">", "exec"), module.__dict__)
    return module


def main():
    if len(sys.argv) != 5:
        raise SystemExit("oci_argument_count")
    mode, repository, workflow, branch = sys.argv[1:]
    if mode not in {"verify", "source", "admission", "record", "artifact", "assembly", "publish-admission", "index-receipt", "platform-publish"}:
        raise SystemExit("oci_unknown_mode")
    repository = "" if repository == "-" else repository
    workflow = "" if workflow == "-" else workflow
    branch = "" if branch == "-" else branch
    oci_digest = load_fixed("oci_digest")
    release_admission = load_fixed("release_admission")
    oci_digest_parts = load_fixed("oci_digest_parts")
    if mode == "index-receipt":
        return load_fixed("oci_index_receipt").main()

    oci_digest.shared_main = release_admission.main
    if mode == "platform-publish":
        load_fixed("oci_archive")
        load_fixed("oci_registry")
        return load_fixed("oci_platform_publish").main({
            "repository": repository, "ci_workflow": workflow, "default_branch": branch,
        })
    if mode == "publish-admission":
        return oci_digest.publish_admission_main({
            "repository": repository, "ci_workflow": workflow, "default_branch": branch,
        })
    oci_digest_parts.oci_dispatch(mode, {
        "repository": repository,
        "ci_workflow": workflow,
        "default_branch": branch,
    })


if __name__ == "__main__":
    main()
