"""Offline checks for the actual generated OCI launcher and namespace."""
import importlib.util
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest
from unittest.mock import patch


SOURCE = Path(__file__).resolve().parent
ADMISSION_SOURCE = SOURCE.parents[2] / "velnor-actions-orchestrator" / "src" / "release_admission.py"
NAMES = (
    "oci_delivery.py", "oci_digest.py", "oci_digest_parts.py", "oci_index_receipt.py",
    "release_admission.py", "oci_archive.py", "oci_registry.py", "oci_platform_publish.py",
)
MARKER = "# Generated by Velnor Actions 0.1.0; edit .velnor/config.toml and regenerate.\n"


class LauncherTests(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.workspace = Path(self.temporary.name).resolve()
        self.directory = self.workspace / ".github" / "velnor"
        self.directory.mkdir(parents=True)
        for name in NAMES:
            source = ADMISSION_SOURCE if name == "release_admission.py" else SOURCE / name
            (self.directory / name).write_text(MARKER + source.read_text())
        sources = {name.removesuffix(".py"): (self.directory / name).read_text()
                   for name in NAMES[1:]}
        entry = self.directory / NAMES[0]
        entry.write_text(MARKER + "OCI_COMPILED_SOURCES = " + json.dumps(sources) + "\n" +
                         (SOURCE / NAMES[0]).read_text())
        spec = importlib.util.spec_from_file_location("oci_entry_test", self.directory / NAMES[0])
        self.entry = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(self.entry)

    def test_actual_python_isolated_record_ignores_shadow_modules(self):
        trap = self.workspace / "import-hijack"
        for directory in (self.workspace, self.directory):
            (directory / "json.py").write_text("from pathlib import Path\nPath(" + repr(str(trap)) + ").touch()\n")
        env = dict(os.environ, GITHUB_WORKSPACE=str(self.workspace), GITHUB_RUN_ID="42",
                   GITHUB_RUN_ATTEMPT="2", IMAGE="chainargos/base", IMAGE_ID="base", ARCH="amd64",
                   VERSION="1.2.3", SOURCE_SHA="a" * 40, DIGEST="sha256:" + "b" * 64,
                   PYTHONPATH=str(self.workspace))
        result = subprocess.run([sys.executable, "-I", str(self.directory / NAMES[0]), "record", "-", "-", "-"],
                                cwd=self.workspace, env=env, capture_output=True, text=True, check=False)
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertFalse(trap.exists())
        record = json.loads((self.workspace / "digests" / "base-amd64.json").read_text())
        self.assertEqual(record["run_attempt"], "2")
        self.assertEqual(record["digest"], "sha256:" + "b" * 64)

    def test_all_modes_load_fixed_modules_and_preserve_context(self):
        original = self.entry.load_fixed
        for mode in ("verify", "source", "admission", "record", "artifact", "assembly", "publish-admission", "index-receipt", "platform-publish"):
            with self.subTest(mode=mode):
                calls = []

                def load(name):
                    module = original(name)
                    if name == "oci_digest_parts":
                        module.oci_dispatch = lambda selected, config: calls.append((selected, config))
                    elif name == "oci_digest":
                        module.publish_admission_main = lambda config: calls.append((mode, config))
                    elif name == "oci_index_receipt":
                        module.main = lambda: calls.append((mode, {
                            "repository": "owner/repo", "ci_workflow": "ci.yml", "default_branch": "main"}))
                    elif name == "oci_platform_publish":
                        module.main = lambda config: calls.append((mode, config))
                    return module

                with patch.dict(os.environ, {"GITHUB_WORKSPACE": str(self.workspace)}), \
                     patch.object(self.entry, "load_fixed", load), \
                     patch.object(sys, "argv", [str(self.directory / NAMES[0]), mode, "owner/repo", "ci.yml", "main"]):
                    self.entry.main()
                self.assertEqual(calls, [(mode, {"repository": "owner/repo", "ci_workflow": "ci.yml", "default_branch": "main"})])

    def test_companion_files_have_no_execution_authority(self):
        (self.directory / "oci_digest.py").write_text("raise RuntimeError('checkout authority')")
        module = self.entry.load_fixed("oci_digest")
        self.assertTrue(callable(module.record_main))

    def test_fixed_bash_wrapper_executes_complete_isolated_closure(self):
        wrapper = self.directory / "oci_delivery.sh"
        wrapper.write_text(MARKER + 'set -euo pipefail\npython3 -I -S - "$@" <<\'VELNOR_OCI_COMPILED_BODY\'\n' +
                           (self.directory / NAMES[0]).read_text() + "\nVELNOR_OCI_COMPILED_BODY\n")
        env = dict(os.environ, GITHUB_RUN_ID="42", GITHUB_RUN_ATTEMPT="2", IMAGE="chainargos/base",
                   IMAGE_ID="base", ARCH="amd64", VERSION="1.2.3", SOURCE_SHA="a" * 40,
                   DIGEST="sha256:" + "b" * 64)
        result = subprocess.run(["bash", "-p", str(wrapper), "record", "-", "-", "-"],
                                cwd=self.workspace, env=env, capture_output=True, text=True, check=False)
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertTrue((self.workspace / "digests" / "base-amd64.json").is_file())

    def test_incomplete_embedded_source_closure_rejected(self):
        with patch.object(self.entry, "OCI_COMPILED_SOURCES", {}), \
             self.assertRaisesRegex(SystemExit, "oci_compiled_source_closure"):
            self.entry.load_fixed("oci_digest")

    def test_unknown_mode_rejected_before_loading(self):
        with patch.object(sys, "argv", ["entry", "publish-anything", "-", "-", "-"]), \
             self.assertRaisesRegex(SystemExit, "oci_unknown_mode"):
            self.entry.main()


if __name__ == "__main__":
    unittest.main()
