"""Exercise generated isolated entrypoint before any network or signing tools."""
import json
import hashlib
import os
from pathlib import Path
import py_compile
import subprocess
import tempfile
import unittest


MARKER = "# Generated by Velnor Actions 0.1.0; edit .velnor/config.toml and regenerate.\n"
SOURCE = Path(__file__).resolve().parent
CONFIG = {"source_repository": "owner/source", "consumer_repository": "owner/feed",
          "package": "example", "binary": "example", "identity_directory": "example",
          "manifest_schema": "example.package-release.v1", "keyring": "example.gpg",
          "signer_fingerprint": "A" * 40, "origin": "Example", "description": "Example feed",
          "feed_url": "https://example.test", "branch": "main", "schedule": "0 0 * * *",
          "signer_workflow": ".github/workflows/signer.yml",
          "oci_image_repository": "ghcr.io/owner/source",
          "oci_signer_workflow": ".github/workflows/oci.yml"}


MODULES = ("delivery_apt_core", "delivery_apt_verify", "delivery_apt_stage_feed",
           "delivery_apt_stage_publish", "delivery_apt_stage", "delivery_apt_entry")


def policy_bytes(config, marker):
    return (marker + json.dumps(config, sort_keys=True, separators=(",", ":")) + "\n").encode("utf-8")


def compiled_source(stub=False, source_overrides=None, pinned_policy=None):
    sources = {name: (SOURCE / (name + ".py")).read_text(encoding="utf-8") for name in MODULES}
    if stub:
        sources["delivery_apt_verify"] = "def verify(config): print('compiled verify')\n"
        sources["delivery_apt_stage_feed"] = '"""Compiled empty feed test module."""\n'
        sources["delivery_apt_stage_publish"] = '"""Compiled empty publication test module."""\n'
        sources["delivery_apt_stage"] = ("def stage(config): print('compiled stage')\n"
                                         "def guard(config): print('compiled guard')\n")
    sources.update(source_overrides or {})
    template = (SOURCE / "delivery_apt_loader.py").read_text(encoding="utf-8")
    source = template.replace("__APT_COMPILED_MARKER__", json.dumps(MARKER.rstrip("\n"))).replace(
        "__APT_COMPILED_SOURCES__", json.dumps(sources))
    if pinned_policy is not None:
        digest = hashlib.sha256(pinned_policy).hexdigest()
        if source.count("_APT_POLICY_SHA256 = None") != 1:
            raise ValueError("exact neutral policy binding point required")
        source = source.replace("_APT_POLICY_SHA256 = None", "_APT_POLICY_SHA256 = " + json.dumps(digest))
    return source


class EntryTests(unittest.TestCase):
    def execute(self, action="stage", config=None, marker=MARKER, environment=None,
                hostile=False, stub=False, source_overrides=None, pinned_policy=None, neutral=False):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            generated = root / ".github/velnor"
            generated.mkdir(parents=True)
            pinned = None if neutral else policy_bytes(CONFIG, MARKER) if pinned_policy is None else pinned_policy
            source = compiled_source(stub, source_overrides, pinned)
            (generated / "apt_delivery.py").write_text(MARKER + source, encoding="utf-8")
            (generated / "apt-delivery.jsonc").write_bytes(
                policy_bytes(CONFIG if config is None else config, marker))
            if hostile:
                for name in (*MODULES, "json", "subprocess", "hashlib", "types"):
                    for parent in (generated, root):
                        path = parent / (name + ".py")
                        path.write_text("raise RuntimeError('checkout companion executed')\n")
                        py_compile.compile(str(path), cfile=str(path.with_suffix(".pyc")), doraise=True)
            env = dict(os.environ, GITHUB_REPOSITORY="owner/feed", GITHUB_EVENT_NAME="workflow_dispatch",
                       GITHUB_REF="refs/heads/main", DELIVERY_MODE="validate")
            env.update(environment or {})
            return subprocess.run(["python3", "-B", "-I", "-S", ".github/velnor/apt_delivery.py",
                                   action, ".github/velnor/apt-delivery.jsonc"],
                                  cwd=root, env=env, text=True, capture_output=True, check=False)

    def test_default_dispatch_cannot_sign_or_deploy(self):
        for action in ("stage", "guard"):
            result = self.execute(action)
            self.assertNotEqual(result.returncode, 0)
            self.assertIn("validation dispatch cannot publish", result.stderr)

    def test_unknown_policy_field_is_rejected(self):
        invalid = dict(CONFIG, shell="arbitrary")
        result = self.execute(config=invalid, pinned_policy=policy_bytes(invalid, MARKER))
        self.assertIn("closed generated policy shape", result.stderr)

    def test_policy_marker_must_match_helper_version(self):
        marker = MARKER.replace("0.1.0", "0.2.0")
        result = self.execute(marker=marker, pinned_policy=policy_bytes(CONFIG, marker))
        self.assertIn("generated policy marker required", result.stderr)

    def test_foreign_repository_and_pr_event_rejected(self):
        for env, message in (({"GITHUB_REPOSITORY": "fork/feed"}, "repository identity"),
                             ({"GITHUB_EVENT_NAME": "pull_request"}, "unsupported feed event")):
            result = self.execute("verify", environment=env)
            self.assertIn(message, result.stderr)

    def test_off_branch_explicit_publish_rejected(self):
        result = self.execute(environment={"GITHUB_REF": "refs/heads/feature", "DELIVERY_MODE": "publish"})
        self.assertIn("protected branch", result.stderr)

    def test_isolated_loader_ignores_repository_stdlib_shadow(self):
        result = self.execute(hostile=True, environment={"PYTHONPATH": ".github/velnor"})
        self.assertIn("validation dispatch cannot publish", result.stderr)
        self.assertNotIn("checkout companion executed", result.stderr)


    def test_tampered_checkout_companions_and_bytecode_are_ignored(self):
        for action in ("verify", "stage", "guard"):
            result = self.execute(action, hostile=True, stub=True,
                                  environment={"DELIVERY_MODE": "publish", "PYTHONPATH": ".github/velnor"})
            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertEqual(result.stdout.strip(), "compiled " + action)
            self.assertNotIn("checkout companion executed", result.stderr)

    def test_real_compiled_modules_load_without_checkout_companions(self):
        result = self.execute()
        self.assertIn("validation dispatch cannot publish", result.stderr)
        self.assertNotIn("ModuleNotFoundError", result.stderr)
        self.assertNotIn("__file__", result.stderr)

    def test_incomplete_compiled_closure_is_rejected(self):
        result = self.execute(source_overrides={"unexpected_module": "print('untrusted')"})
        self.assertIn("complete compiled APT source closure required", result.stderr)
        self.assertNotIn("untrusted", result.stdout)

    def test_compiled_module_registration_preserves_dependency_order(self):
        overrides = {
            "delivery_apt_verify": ("from delivery_apt_core import loads\n"
                                    "def verify(config): print(loads('\"compiled ordered verify\"'))\n"),
            "delivery_apt_stage_feed": "from delivery_apt_verify import verify\n",
            "delivery_apt_stage_publish": "from delivery_apt_stage_feed import verify\n",
            "delivery_apt_stage": ("from delivery_apt_stage_publish import verify\n"
                                   "stage = verify\nguard = verify\n"),
        }
        result = self.execute("verify", stub=True, source_overrides=overrides)
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(result.stdout.strip(), "compiled ordered verify")

    def test_bound_launcher_rejects_coherent_policy_rewrite(self):
        rewritten = dict(CONFIG, package="attacker-package", keyring="attacker.gpg")
        result = self.execute("verify", stub=True, config=rewritten)
        self.assertIn("compiled policy digest differs", result.stderr)
        self.assertNotIn("compiled verify", result.stdout)

    def test_neutral_support_has_one_binding_point_and_bound_source_has_none(self):
        neutral = compiled_source(stub=True)
        bound = compiled_source(stub=True, pinned_policy=policy_bytes(CONFIG, MARKER))
        self.assertEqual(neutral.count("_APT_POLICY_SHA256 = None"), 1)
        self.assertNotIn("_APT_POLICY_SHA256 = None", bound)
        result = self.execute("verify", stub=True, neutral=True)
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(result.stdout.strip(), "compiled verify")

    def test_digest_precedes_decode(self):
        core = (SOURCE / "delivery_apt_core.py").read_text(encoding="utf-8")
        core += "\ndef read_bytes(path): return bytes([255])\n"
        result = self.execute("verify", stub=True, source_overrides={"delivery_apt_core": core})
        self.assertIn("compiled policy digest differs", result.stderr)
        self.assertNotIn("UnicodeDecodeError", result.stderr)

    def test_hash_and_parse_share_one_read_buffer(self):
        core = (SOURCE / "delivery_apt_core.py").read_text(encoding="utf-8")
        core += ("\n_original_read_bytes = read_bytes\n"
                 "def read_bytes(path):\n"
                 "    value = _original_read_bytes(path)\n"
                 "    Path(path).write_bytes(b'changed after read')\n"
                 "    return value\n")
        result = self.execute("verify", stub=True, source_overrides={"delivery_apt_core": core})
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(result.stdout.strip(), "compiled verify")


if __name__ == "__main__":
    unittest.main()
