"""Fixed APT adapter entrypoint; generated policy contains data only."""
import os
import sys
import hashlib
from delivery_apt_core import loads, read_bytes
from delivery_apt_verify import verify
from delivery_apt_stage import stage, guard


def main():
    if len(sys.argv) != 3 or sys.argv[1] not in ("verify", "stage", "guard"):
        raise ValueError("fixed action and policy arguments required")
    if sys.argv[2] != ".github/velnor/apt-delivery.jsonc":
        raise ValueError("policy path differs from generated adapter")
    policy = read_bytes(sys.argv[2])
    if _APT_POLICY_SHA256 is not None and hashlib.sha256(policy).hexdigest() != _APT_POLICY_SHA256:
        raise ValueError("compiled policy digest differs")
    marker, separator, body = policy.decode("utf-8").partition("\n")
    if not separator or marker != GENERATED_MARKER or not marker.startswith("# Generated by Velnor Actions "):
        raise ValueError("generated policy marker required")
    config = loads(body)
    keys = {"source_repository", "consumer_repository", "package", "binary",
            "identity_directory", "manifest_schema", "keyring", "signer_fingerprint",
            "origin", "description", "feed_url", "branch", "schedule", "signer_workflow",
            "oci_image_repository", "oci_signer_workflow"}
    if not isinstance(config, dict) or set(config) != keys:
        raise ValueError("closed generated policy shape required")
    if any(not isinstance(value, str) or not value for value in config.values()):
        raise ValueError("generated policy values must be nonempty strings")
    if os.environ.get("GITHUB_REPOSITORY") != config["consumer_repository"]:
        raise ValueError("consumer repository identity differs")
    event = os.environ.get("GITHUB_EVENT_NAME")
    if event not in ("schedule", "workflow_dispatch"):
        raise ValueError("unsupported feed event")
    if sys.argv[1] != "verify":
        if os.environ.get("GITHUB_REF") != "refs/heads/" + config["branch"]:
            raise ValueError("signing and deployment require protected branch")
        if event == "workflow_dispatch" and os.environ.get("DELIVERY_MODE") != "publish":
            raise ValueError("validation dispatch cannot publish")
    {"verify": verify, "stage": stage, "guard": guard}[sys.argv[1]](config)


if __name__ == "__main__":
    main()
