"""Execute the complete compiled APT source closure without companion imports."""
import sys
import types


COMPILED_SOURCES = __APT_COMPILED_SOURCES__
GENERATED_MARKER = __APT_COMPILED_MARKER__
_APT_POLICY_SHA256 = None
MODULES = ("delivery_apt_core", "delivery_apt_verify", "delivery_apt_stage_feed",
           "delivery_apt_stage_publish", "delivery_apt_stage")
ENTRY = "delivery_apt_entry"

if not isinstance(COMPILED_SOURCES, dict) or set(COMPILED_SOURCES) != set(MODULES) | {ENTRY}:
    raise ValueError("complete compiled APT source closure required")
if any(not isinstance(source, str) or not source for source in COMPILED_SOURCES.values()):
    raise ValueError("compiled APT source strings required")
if not isinstance(GENERATED_MARKER, str) or not GENERATED_MARKER.startswith("# Generated by Velnor Actions "):
    raise ValueError("compiled generation marker required")
if "\n" in GENERATED_MARKER or "\r" in GENERATED_MARKER:
    raise ValueError("compiled generation marker must be one line")
if _APT_POLICY_SHA256 is not None and (not isinstance(_APT_POLICY_SHA256, str)
        or len(_APT_POLICY_SHA256) != 64
        or any(character not in "0123456789abcdef" for character in _APT_POLICY_SHA256)):
    raise ValueError("compiled policy digest invalid")

for name in MODULES:
    sys.modules[name] = types.ModuleType(name)
for name in MODULES:
    exec(compile(COMPILED_SOURCES[name], "<compiled:" + name + ">", "exec",
                 dont_inherit=True), sys.modules[name].__dict__)

exec(compile(COMPILED_SOURCES[ENTRY], "<compiled:" + ENTRY + ">", "exec",
             dont_inherit=True), {"__name__": "__main__", "GENERATED_MARKER": GENERATED_MARKER,
                                 "_APT_POLICY_SHA256": _APT_POLICY_SHA256})
