[package]
name = "velnor-actions-rust-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
autotests = false

[lints]
workspace = true

[dependencies]
velnor-actions-contract = { version = "=0.1.7", path = "../../core/velnor-actions-contract" }
velnor-actions-contract-planning = { version = "=0.1.7", path = "../../core/velnor-actions-contract-planning" }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }

[[test]]
name = "velnor_rust_core"
path = "tests/main.rs"
