//! Executable-intent evidence scanning with durability tags.
//!
//! Scanning only; selection lives in [`crate::profile`]. Evidence rooted in
//! the generated `.github` tree is [`EvidenceStrength::Transient`]; evidence
//! elsewhere (Mise settings, rustc wrappers, executable tasks and scripts
//! outside `.github`) is [`EvidenceStrength::Durable`]. Generated workflows
//! (current or historical marker) are never evidence. Line-local text
//! scans live in `crate::evidence_text` (private); this module owns the sighting
//! types plus structurally resolved inputs (Mise wrappers, Nextest config).

use velnor_actions_contract::is_generated_marker_line;

use crate::evidence_text::{scan_cargo_config, scan_command_text, scan_tool_config};

/// Recommendation code for the default-runner notice.
pub const NEXTEST_RECOMMENDATION: &str = "nextest_recommendation";

/// Recommendation code for persisting a durable signal.
pub const PERSIST_EVIDENCE: &str = "persist_evidence";

/// Recommendation code when a farther Nextest config is shadowed.
pub const SHADOWED_NEXTEST_CONFIG: &str = "shadowed_nextest_config";

/// Evidence durability; only durable evidence selects profiles silently.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum EvidenceStrength {
    /// Survives regeneration (config, wrapper, task/script outside `.github`).
    Durable,
    /// Vanishes when Velnor replaces `.github`; needs an explicit declaration.
    Transient,
}

impl EvidenceStrength {
    /// Stable durability name.
    #[must_use]
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Durable => "durable",
            Self::Transient => "transient",
        }
    }
}

/// One recorded evidence sighting.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct Evidence {
    /// Repository-relative evidence path.
    pub path: String,
    /// One-based line number.
    pub line: u32,
    /// Matched setting or command text.
    pub command_or_setting: String,
    /// Evidence durability.
    pub strength: EvidenceStrength,
}

/// One named content blob offered as evidence.
#[derive(Debug, Clone, Copy)]
pub struct EvidenceFile<'a> {
    /// Repository-relative path the content was read from.
    pub path: &'a str,
    /// File content.
    pub content: &'a str,
}

/// Structurally resolved Mise Cargo wrapper offered as evidence.
///
/// The Mise adapter resolves the Cargo wrapper setting plus the
/// `MBX_CARGO_SHIM_MODE` env value from TOML structure; only the exact
/// command `mbx` selects MBX, every other command is an explicit
/// non-MBX wrapper.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MiseWrapperInput {
    /// Repository-relative file that supplied the wrapper.
    pub path: String,
    /// One-based line of the Cargo wrapper assignment.
    pub line: u32,
    /// Exact structural command value.
    pub command: String,
    /// `MBX_CARGO_SHIM_MODE` value when structurally present.
    pub shim_mode: Option<String>,
}

/// Structurally resolved Nextest config offered as evidence.
///
/// File presence is durable Nextest evidence; CI selects `[profile.ci]`
/// when present and Nextest's documented `default` profile otherwise.
/// Inputs arrive nearest-first when several configs exist.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NextestConfigInput {
    /// Repository-relative config path.
    pub path: String,
    /// Sorted profile names declared under `[profile.*]`.
    pub profiles: Vec<String>,
    /// One-based `[profile.ci]` line when present.
    pub ci_line: Option<u32>,
}

/// Whether content is generated output (never evidence).
///
/// Accepts the current spec marker and the historical
/// `# Generated by velnor-actions ` prefix: old files were never handwritten.
#[must_use]
pub fn is_generated_output(content: &str) -> bool {
    content.lines().next().is_some_and(is_generated_marker_line)
}

/// Whether `path` must be skipped by evidence collection (output, docs, locks, caches).
#[must_use]
pub fn evidence_scan_excluded(path: &str) -> bool {
    if is_github_path(path) {
        return true;
    }
    if is_lock_path(path) {
        return true;
    }
    if is_doc_path(path) {
        return true;
    }
    if path == "target" || path.starts_with("target/") || path.contains("/target/") {
        return true;
    }
    path == ".git" || path.starts_with(".git/")
}

/// Whether `path` is rooted in the generated `.github` tree.
fn is_github_path(path: &str) -> bool {
    path == ".github" || path.starts_with(".github/")
}

/// Whether `path` is documentation (never evidence).
fn is_doc_path(path: &str) -> bool {
    if path == "docs" || path.starts_with("docs/") {
        return true;
    }
    path.rsplit('/').next().is_some_and(|file| {
        file.starts_with("README")
            || ["md", "mdx", "markdown", "rst", "adoc"]
                .iter()
                .any(|extension| has_extension(file, extension))
    })
}

/// Whether `file` carries `extension` (ASCII case-insensitive).
fn has_extension(file: &str, extension: &str) -> bool {
    std::path::Path::new(file)
        .extension()
        .is_some_and(|found| found.eq_ignore_ascii_case(extension))
}

/// Whether `path` is a lockfile (never evidence).
fn is_lock_path(path: &str) -> bool {
    path.rsplit('/').next().is_some_and(|file| {
        file == "Cargo.lock" || file == "mise.lock" || has_extension(file, "lock")
    })
}

/// Durability for one file: `.github`-rooted sightings are always transient.
pub(crate) fn strength_for(file: &EvidenceFile<'_>, base: EvidenceStrength) -> EvidenceStrength {
    if is_github_path(file.path) {
        EvidenceStrength::Transient
    } else {
        base
    }
}

/// Build MBX and non-MBX sightings from resolved wrappers.
///
/// Only the exact command `mbx` counts as MBX evidence; every other
/// command is an explicit durable non-MBX signal (used for conflict
/// and ambiguity checks, never silently dropped).
pub(crate) fn wrapper_sightings(wrappers: &[MiseWrapperInput]) -> (Vec<Evidence>, Vec<Evidence>) {
    let mut mbx = Vec::new();
    let mut other = Vec::new();
    for input in wrappers {
        let file = EvidenceFile {
            path: &input.path,
            content: "",
        };
        let strength = strength_for(&file, EvidenceStrength::Durable);
        let sighting = Evidence {
            path: input.path.clone(),
            line: input.line,
            command_or_setting: wrapper_text(input),
            strength,
        };
        if input.command == "mbx" {
            mbx.push(sighting);
        } else {
            other.push(sighting);
        }
    }
    (mbx, other)
}

/// Sighting text for one resolved wrapper, naming the consumed setting.
fn wrapper_text(input: &MiseWrapperInput) -> String {
    match &input.shim_mode {
        Some(mode) => format!(
            "cargo wrapper = {:?} (MBX_CARGO_SHIM_MODE = {mode:?})",
            input.command
        ),
        None => format!("cargo wrapper = {:?}", input.command),
    }
}

/// Build durable Nextest sightings from resolved configs.
///
/// Each config is one sighting: `[profile.ci]` when the section is
/// present, else the documented default-profile selection.
pub(crate) fn nextest_config_sightings(configs: &[NextestConfigInput]) -> Vec<Evidence> {
    configs
        .iter()
        .map(|input| {
            let file = EvidenceFile {
                path: &input.path,
                content: "",
            };
            Evidence {
                path: input.path.clone(),
                line: input.ci_line.unwrap_or(1),
                command_or_setting: if input.ci_line.is_some() {
                    "[profile.ci]".to_owned()
                } else {
                    "nextest default profile (no [profile.ci])".to_owned()
                },
                strength: strength_for(&file, EvidenceStrength::Durable),
            }
        })
        .collect()
}

/// Evidence grouped by durability for selection.
#[derive(Debug, Default)]
pub(crate) struct Seen {
    /// Durable MBX sightings.
    pub(crate) mbx_durable: Vec<Evidence>,
    /// Transient MBX sightings.
    pub(crate) mbx_transient: Vec<Evidence>,
    /// Durable Nextest sightings.
    pub(crate) nextest_durable: Vec<Evidence>,
    /// Transient Nextest sightings.
    pub(crate) nextest_transient: Vec<Evidence>,
    /// Durable `cargo test` sightings.
    pub(crate) cargo_durable: Vec<Evidence>,
    /// Transient `cargo test` sightings.
    pub(crate) cargo_transient: Vec<Evidence>,
    /// Explicit non-MBX wrapper sightings (Cargo-side signals).
    pub(crate) wrapper_other: Vec<Evidence>,
}

impl Seen {
    /// Whether any durable sighting exists.
    pub(crate) fn has_durable(&self) -> bool {
        !self.mbx_durable.is_empty()
            || !self.nextest_durable.is_empty()
            || !self.cargo_durable.is_empty()
            || !self.wrapper_other.is_empty()
    }

    /// Whether no sighting of any kind exists.
    pub(crate) fn is_empty(&self) -> bool {
        self.mbx_durable.is_empty()
            && self.mbx_transient.is_empty()
            && self.nextest_durable.is_empty()
            && self.nextest_transient.is_empty()
            && self.cargo_durable.is_empty()
            && self.cargo_transient.is_empty()
            && self.wrapper_other.is_empty()
    }

    /// Every sighting, sorted.
    pub(crate) fn all_sorted(mut self) -> Vec<Evidence> {
        let mut out = self.mbx_durable;
        out.append(&mut self.mbx_transient);
        out.append(&mut self.nextest_durable);
        out.append(&mut self.nextest_transient);
        out.append(&mut self.cargo_durable);
        out.append(&mut self.cargo_transient);
        out.append(&mut self.wrapper_other);
        out.sort();
        out
    }
}

/// Collect durability-tagged evidence from every input category.
pub(crate) fn collect_evidence(
    tool_config: Option<&EvidenceFile<'_>>,
    cargo_configs: &[EvidenceFile<'_>],
    executables: &[EvidenceFile<'_>],
    handwritten: &[EvidenceFile<'_>],
    mise_wrappers: &[MiseWrapperInput],
    nextest_configs: &[NextestConfigInput],
) -> Seen {
    let mut seen = Seen::default();
    if let Some(config) = tool_config {
        push_mbx(&mut seen, scan_tool_config(config));
    }
    for config in cargo_configs {
        push_mbx(&mut seen, scan_cargo_config(config));
    }
    for file in executables {
        let (mbx, nextest, cargo) = scan_command_text(file, EvidenceStrength::Durable);
        push_mbx(&mut seen, mbx);
        push_runner(&mut seen, nextest, cargo);
    }
    for file in handwritten {
        let (mbx, nextest, cargo) = scan_command_text(file, EvidenceStrength::Transient);
        push_mbx(&mut seen, mbx);
        push_runner(&mut seen, nextest, cargo);
    }
    let (mbx, other) = wrapper_sightings(mise_wrappers);
    push_mbx(&mut seen, mbx);
    push_other(&mut seen, other);
    push_nextest_configs(&mut seen, nextest_config_sightings(nextest_configs));
    seen
}

/// Sort non-MBX wrapper sightings into the explicit-Cargo bucket.
fn push_other(seen: &mut Seen, sightings: Vec<Evidence>) {
    seen.wrapper_other.extend(sightings);
}

/// Sort Nextest-config sightings into the durable Nextest bucket.
fn push_nextest_configs(seen: &mut Seen, sightings: Vec<Evidence>) {
    for sighting in sightings {
        match sighting.strength {
            EvidenceStrength::Durable => seen.nextest_durable.push(sighting),
            EvidenceStrength::Transient => seen.nextest_transient.push(sighting),
        }
    }
}

/// Sort MBX sightings into the durable/transient buckets.
fn push_mbx(seen: &mut Seen, sightings: Vec<Evidence>) {
    for sighting in sightings {
        match sighting.strength {
            EvidenceStrength::Durable => seen.mbx_durable.push(sighting),
            EvidenceStrength::Transient => seen.mbx_transient.push(sighting),
        }
    }
}

/// Sort runner sightings into the durable/transient buckets.
fn push_runner(seen: &mut Seen, nextest: Vec<Evidence>, cargo: Vec<Evidence>) {
    for sighting in nextest {
        match sighting.strength {
            EvidenceStrength::Durable => seen.nextest_durable.push(sighting),
            EvidenceStrength::Transient => seen.nextest_transient.push(sighting),
        }
    }
    for sighting in cargo {
        match sighting.strength {
            EvidenceStrength::Durable => seen.cargo_durable.push(sighting),
            EvidenceStrength::Transient => seen.cargo_transient.push(sighting),
        }
    }
}
