//! Executable-intent evidence scanning with durability tags.
//!
//! Scanning only; selection lives in [`crate::profile`]. Evidence rooted in
//! the generated `.github` tree is [`EvidenceStrength::Transient`]; evidence
//! elsewhere (Mise settings, rustc wrappers, executable tasks and scripts
//! outside `.github`) is [`EvidenceStrength::Durable`]. Generated workflows
//! (current or historical marker) are never evidence.

use velnor_actions_contract::is_generated_marker_line;

use crate::scan::{
    has_adjacent, has_command, has_setting, line_no, snippet, starts_with_word, strip_comment,
};

/// Recommendation code for the default-runner notice.
pub const NEXTEST_RECOMMENDATION: &str = "nextest_recommendation";

/// Recommendation code for persisting a durable signal.
pub const PERSIST_EVIDENCE: &str = "persist_evidence";

/// Evidence durability; only durable evidence selects profiles silently.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum EvidenceStrength {
    /// Survives regeneration (config, wrapper, task/script outside `.github`).
    Durable,
    /// Vanishes when Velnor replaces `.github`; needs an explicit declaration.
    Transient,
}

impl EvidenceStrength {
    /// Stable durability name.
    #[must_use]
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Durable => "durable",
            Self::Transient => "transient",
        }
    }
}

/// One recorded evidence sighting.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct Evidence {
    /// Repository-relative evidence path.
    pub path: String,
    /// One-based line number.
    pub line: u32,
    /// Matched setting or command text.
    pub command_or_setting: String,
    /// Evidence durability.
    pub strength: EvidenceStrength,
}

/// One named content blob offered as evidence.
#[derive(Debug, Clone, Copy)]
pub struct EvidenceFile<'a> {
    /// Repository-relative path the content was read from.
    pub path: &'a str,
    /// File content.
    pub content: &'a str,
}

/// Whether content is generated output (never evidence).
///
/// Accepts the current spec marker and the historical
/// `# Generated by velnor-actions ` prefix: old files were never handwritten.
#[must_use]
pub fn is_generated_output(content: &str) -> bool {
    content.lines().next().is_some_and(is_generated_marker_line)
}

/// Whether `path` must be skipped by evidence collection (output, docs, locks, caches).
#[must_use]
pub fn evidence_scan_excluded(path: &str) -> bool {
    if is_github_path(path) {
        return true;
    }
    if is_lock_path(path) {
        return true;
    }
    if is_doc_path(path) {
        return true;
    }
    if path == "target" || path.starts_with("target/") || path.contains("/target/") {
        return true;
    }
    path == ".git" || path.starts_with(".git/")
}

/// Whether `path` is rooted in the generated `.github` tree.
fn is_github_path(path: &str) -> bool {
    path == ".github" || path.starts_with(".github/")
}

/// Whether `path` is documentation (never evidence).
fn is_doc_path(path: &str) -> bool {
    if path == "docs" || path.starts_with("docs/") {
        return true;
    }
    path.rsplit('/').next().is_some_and(|file| {
        file.starts_with("README")
            || ["md", "mdx", "markdown", "rst", "adoc"]
                .iter()
                .any(|extension| has_extension(file, extension))
    })
}

/// Whether `file` carries `extension` (ASCII case-insensitive).
fn has_extension(file: &str, extension: &str) -> bool {
    std::path::Path::new(file)
        .extension()
        .is_some_and(|found| found.eq_ignore_ascii_case(extension))
}

/// Whether `path` is a lockfile (never evidence).
fn is_lock_path(path: &str) -> bool {
    path.rsplit('/').next().is_some_and(|file| {
        file == "Cargo.lock" || file == "mise.lock" || has_extension(file, "lock")
    })
}

/// Durability for one file: `.github`-rooted sightings are always transient.
fn strength_for(file: &EvidenceFile<'_>, base: EvidenceStrength) -> EvidenceStrength {
    if is_github_path(file.path) {
        EvidenceStrength::Transient
    } else {
        base
    }
}

/// Scan tool-config content for the Rust `mr_boxington` setting.
pub(crate) fn scan_tool_config(file: &EvidenceFile<'_>) -> Vec<Evidence> {
    if is_generated_output(file.content) {
        return Vec::new();
    }
    let strength = strength_for(file, EvidenceStrength::Durable);
    let mut out = Vec::new();
    for (index, line) in file.content.lines().enumerate() {
        let code = strip_comment(line);
        if has_setting(code, "mr_boxington", "true") {
            out.push(sighting(file, index, code, strength));
        }
    }
    out
}

/// Scan Cargo config content for `rustc-wrapper` naming MBX.
pub(crate) fn scan_cargo_config(file: &EvidenceFile<'_>) -> Vec<Evidence> {
    if is_generated_output(file.content) {
        return Vec::new();
    }
    let strength = strength_for(file, EvidenceStrength::Durable);
    let mut out = Vec::new();
    for (index, line) in file.content.lines().enumerate() {
        let code = strip_comment(line);
        if mentions_wrapper(code) && mentions_mbx(code) {
            out.push(sighting(file, index, code, strength));
        }
    }
    out
}

fn mentions_wrapper(code: &str) -> bool {
    code.contains("rustc-wrapper")
        || code.contains("rustc_wrapper")
        || code.contains("RUSTC_WRAPPER")
}

fn mentions_mbx(code: &str) -> bool {
    has_command(code, "mbx") || code.contains("boxington")
}

/// Scan task, script, or workflow text for driver and runner invocations.
///
/// Callers pass [`EvidenceStrength::Durable`] for executable tasks and
/// scripts, [`EvidenceStrength::Transient`] for hand-written workflows;
/// `.github`-rooted files are transient either way.
pub(crate) fn scan_command_text(
    file: &EvidenceFile<'_>,
    base: EvidenceStrength,
) -> (Vec<Evidence>, Vec<Evidence>, Vec<Evidence>) {
    if is_generated_output(file.content) {
        return (Vec::new(), Vec::new(), Vec::new());
    }
    let strength = strength_for(file, base);
    let mut mbx = Vec::new();
    let mut nextest = Vec::new();
    let mut cargo_test = Vec::new();
    for (index, line) in file.content.lines().enumerate() {
        let code = strip_comment(line);
        if code.trim().is_empty() {
            continue;
        }
        if invokes_mbx(code) {
            mbx.push(sighting(file, index, code, strength));
        }
        if invokes_nextest(code) {
            nextest.push(sighting(file, index, code, strength));
        }
        if invokes_cargo_test(code) {
            cargo_test.push(sighting(file, index, code, strength));
        }
    }
    (mbx, nextest, cargo_test)
}

fn invokes_mbx(code: &str) -> bool {
    has_command(code, "mbx")
        || has_command(code, "mr-boxington")
        || has_command(code, "mr_boxington")
}

fn invokes_nextest(code: &str) -> bool {
    if has_adjacent(code, "cargo", "nextest") || has_command(code, "cargo-nextest") {
        return true;
    }
    let mut search = code;
    while let Some(pos) = crate::scan::find_word(search, "nextest") {
        let rest = search[pos + "nextest".len()..].trim_start();
        if starts_with_word(rest, "run")
            || starts_with_word(rest, "archive")
            || starts_with_word(rest, "list")
        {
            return true;
        }
        search = &search[pos + "nextest".len()..];
    }
    false
}

fn invokes_cargo_test(code: &str) -> bool {
    has_adjacent(code, "cargo", "test") || has_adjacent(code, "mbx", "test")
}

fn sighting(
    file: &EvidenceFile<'_>,
    index: usize,
    code: &str,
    strength: EvidenceStrength,
) -> Evidence {
    Evidence {
        path: file.path.to_owned(),
        line: line_no(index),
        command_or_setting: snippet(code),
        strength,
    }
}

/// Evidence grouped by durability for selection.
#[derive(Debug, Default)]
pub(crate) struct Seen {
    /// Durable MBX sightings.
    pub(crate) mbx_durable: Vec<Evidence>,
    /// Transient MBX sightings.
    pub(crate) mbx_transient: Vec<Evidence>,
    /// Durable Nextest sightings.
    pub(crate) nextest_durable: Vec<Evidence>,
    /// Transient Nextest sightings.
    pub(crate) nextest_transient: Vec<Evidence>,
    /// Durable `cargo test` sightings.
    pub(crate) cargo_durable: Vec<Evidence>,
    /// Transient `cargo test` sightings.
    pub(crate) cargo_transient: Vec<Evidence>,
}

impl Seen {
    /// Whether any durable sighting exists.
    pub(crate) fn has_durable(&self) -> bool {
        !self.mbx_durable.is_empty()
            || !self.nextest_durable.is_empty()
            || !self.cargo_durable.is_empty()
    }

    /// Whether no sighting of any kind exists.
    pub(crate) fn is_empty(&self) -> bool {
        self.mbx_durable.is_empty()
            && self.mbx_transient.is_empty()
            && self.nextest_durable.is_empty()
            && self.nextest_transient.is_empty()
            && self.cargo_durable.is_empty()
            && self.cargo_transient.is_empty()
    }

    /// Whether any runner sighting (durable or transient) exists.
    pub(crate) fn has_runner(&self) -> bool {
        !self.nextest_durable.is_empty()
            || !self.nextest_transient.is_empty()
            || !self.cargo_durable.is_empty()
            || !self.cargo_transient.is_empty()
    }

    /// Every sighting, sorted.
    pub(crate) fn all_sorted(mut self) -> Vec<Evidence> {
        let mut out = self.mbx_durable;
        out.append(&mut self.mbx_transient);
        out.append(&mut self.nextest_durable);
        out.append(&mut self.nextest_transient);
        out.append(&mut self.cargo_durable);
        out.append(&mut self.cargo_transient);
        out.sort();
        out
    }
}

/// Collect durability-tagged evidence from every input category.
pub(crate) fn collect_evidence(
    tool_config: Option<&EvidenceFile<'_>>,
    cargo_configs: &[EvidenceFile<'_>],
    executables: &[EvidenceFile<'_>],
    handwritten: &[EvidenceFile<'_>],
) -> Seen {
    let mut seen = Seen::default();
    if let Some(config) = tool_config {
        push_mbx(&mut seen, scan_tool_config(config));
    }
    for config in cargo_configs {
        push_mbx(&mut seen, scan_cargo_config(config));
    }
    for file in executables {
        let (mbx, nextest, cargo) = scan_command_text(file, EvidenceStrength::Durable);
        push_mbx(&mut seen, mbx);
        push_runner(&mut seen, nextest, cargo);
    }
    for file in handwritten {
        let (mbx, nextest, cargo) = scan_command_text(file, EvidenceStrength::Transient);
        push_mbx(&mut seen, mbx);
        push_runner(&mut seen, nextest, cargo);
    }
    seen
}

/// Sort MBX sightings into the durable/transient buckets.
fn push_mbx(seen: &mut Seen, sightings: Vec<Evidence>) {
    for sighting in sightings {
        match sighting.strength {
            EvidenceStrength::Durable => seen.mbx_durable.push(sighting),
            EvidenceStrength::Transient => seen.mbx_transient.push(sighting),
        }
    }
}

/// Sort runner sightings into the durable/transient buckets.
fn push_runner(seen: &mut Seen, nextest: Vec<Evidence>, cargo: Vec<Evidence>) {
    for sighting in nextest {
        match sighting.strength {
            EvidenceStrength::Durable => seen.nextest_durable.push(sighting),
            EvidenceStrength::Transient => seen.nextest_transient.push(sighting),
        }
    }
    for sighting in cargo {
        match sighting.strength {
            EvidenceStrength::Durable => seen.cargo_durable.push(sighting),
            EvidenceStrength::Transient => seen.cargo_transient.push(sighting),
        }
    }
}
