use super::*;

type Outcome = Result<(), Box<dyn std::error::Error>>;
const SHA: &str = "0123456789abcdef0123456789abcdef01234567";

fn profile() -> RustFfiProfile {
    RustFfiProfile {
        manifest_path: "components/orbit-bridge/Cargo.toml".to_owned(),
        package: "orbit-bridge".to_owned(),
        profile: "native-release".to_owned(),
        features: vec!["native".to_owned()],
        framework_name: "OrbitCore".to_owned(),
        module_name: "OrbitCoreFFI".to_owned(),
        static_library: "liborbit_bridge.a".to_owned(),
        bindings_path: "clients/orbit/generated/orbit-bindings".to_owned(),
        xcframework_path: "build/OrbitCore.xcframework".to_owned(),
    }
}

#[test]
fn recipe_embeds_fixed_owner_program_and_typed_native_inputs() -> Outcome {
    let ffi = profile();
    let proposal = native_ffi_proposal(
        &ffi,
        "25.3",
        "apps/orbit",
        SHA,
        CompileDriver::Mbx,
        NativeFfiKind::Library,
        "1.2.3",
    )?;
    let program = proposal.program();
    assert!(
        program
            .source()
            .starts_with("# Generated by Velnor Actions 1.2.3;")
    );
    assert!(program.source().ends_with("produce(REQUEST, build=True)\n"));
    assert_eq!(
        program.argv(),
        ["python3", "-I", program.path()].map(str::to_owned)
    );
    assert!(program.path().starts_with(".github/velnor/rust/native/"));
    assert_eq!(
        program.tool_requirements().compile_driver(),
        CompileDriver::Mbx
    );
    assert!(program.tool_requirements().boltffi());
    assert!(!program.tool_requirements().nextest());
    assert_eq!(
        program.tool_requirements().target(),
        Some("aarch64-apple-darwin")
    );
    assert!(program.source().contains("mbx"));
    assert!(!program.source().contains("DESKTOP_COMPILE_DRIVER"));
    assert!(!program.source().contains("--no-default-features"));
    let artifacts = proposal.artifacts();
    assert_eq!(
        artifacts.output_root(),
        "build/.velnor-rust-ffi/orbit-bridge"
    );
    assert_eq!(
        artifacts.record_path(),
        "build/.velnor-rust-ffi/orbit-bridge/artifacts.json"
    );
    assert_eq!(
        artifacts.bindings_path(),
        "build/.velnor-rust-ffi/orbit-bridge/bindings"
    );
    assert_eq!(
        artifacts.library_path(),
        Some("build/.velnor-rust-ffi/orbit-bridge/library/liborbit_bridge.a")
    );
    assert!(artifacts.profile_digest().starts_with("b3-"));
    Ok(())
}

#[test]
fn producer_identity_binds_configuration_but_artifacts_bind_source_root() -> Outcome {
    let ffi = profile();
    let proposal = native_ffi_proposal(
        &ffi,
        "25.3",
        ".",
        SHA,
        CompileDriver::Cargo,
        NativeFfiKind::Library,
        "1.2.3",
    )?;
    let nested = native_ffi_proposal(
        &ffi,
        "25.3",
        "apps/orbit",
        SHA,
        CompileDriver::Mbx,
        NativeFfiKind::Bindings,
        "1.2.3",
    )?;
    assert_eq!(
        proposal.artifacts().profile_digest(),
        nested.artifacts().profile_digest()
    );
    assert_eq!(
        proposal.artifacts().record_path(),
        nested.artifacts().record_path()
    );
    assert_ne!(proposal.program().path(), nested.program().path());
    assert_eq!(nested.artifacts().library_path(), None);
    assert!(
        nested
            .program()
            .source()
            .ends_with("produce(REQUEST, build=False)\n")
    );
    let changed = native_ffi_proposal(
        &ffi,
        "26.0",
        ".",
        SHA,
        CompileDriver::Cargo,
        NativeFfiKind::Library,
        "1.2.3",
    )?;
    assert_ne!(
        proposal.artifacts().profile_digest(),
        changed.artifacts().profile_digest()
    );
    Ok(())
}

#[test]
fn native_recipes_reject_unsafe_source_and_configuration() {
    for (root, sha, deployment) in [
        ("../other", SHA, "25.3"),
        (".", "bad", "25.3"),
        (".", SHA, "25.3; cargo test"),
        (".", SHA, "25"),
    ] {
        assert!(
            native_ffi_proposal(
                &profile(),
                deployment,
                root,
                sha,
                CompileDriver::Cargo,
                NativeFfiKind::Library,
                "1.2.3"
            )
            .is_err()
        );
    }
    let mut invalid = profile();
    invalid.features = vec!["--all-features".to_owned()];
    assert!(
        native_ffi_proposal(
            &invalid,
            "25.3",
            ".",
            SHA,
            CompileDriver::Cargo,
            NativeFfiKind::Library,
            "1.2.3"
        )
        .is_err()
    );
}

#[test]
fn native_library_tests_have_closed_package_selection() -> Outcome {
    let program = native_library_tests(
        &["orbit-bridge".to_owned()],
        ".",
        SHA,
        CompileDriver::Mbx,
        "1.2.3",
    )?;
    assert!(program.source().ends_with("library_tests(REQUEST)\n"));
    assert_eq!(
        program.tool_requirements().compile_driver(),
        CompileDriver::Mbx
    );
    assert!(!program.tool_requirements().boltffi());
    assert!(program.tool_requirements().nextest());
    assert_eq!(program.tool_requirements().target(), None);
    for packages in [
        vec![],
        vec!["z".to_owned(), "a".to_owned()],
        vec!["--workspace".to_owned()],
        vec!["a".to_owned(), "a".to_owned()],
    ] {
        assert!(native_library_tests(&packages, ".", SHA, CompileDriver::Cargo, "1.2.3").is_err());
    }
    Ok(())
}

#[test]
fn rust_owns_exact_native_producer_evidence_paths() -> Outcome {
    assert_eq!(
        native_ffi_required_inputs(&profile(), "apps/orbit")?,
        [
            "apps/orbit/Cargo.lock",
            "apps/orbit/components/orbit-bridge/Cargo.toml",
            "apps/orbit/components/orbit-bridge/boltffi.toml",
        ]
        .map(str::to_owned)
    );
    let mut root = profile();
    root.manifest_path = "Cargo.toml".to_owned();
    assert_eq!(
        native_ffi_required_inputs(&root, ".")?,
        ["Cargo.lock", "Cargo.toml", "boltffi.toml"].map(str::to_owned)
    );
    assert!(native_ffi_required_inputs(&root, "../escape").is_err());
    Ok(())
}
