//! Effective release-plz configuration emission.
//!
//! Normal emission pins the safe routine policy: workspace `release = false`
//! with an explicit `[[package]]` allowlist, verification on, registry
//! publication. A separate bootstrap-only constructor flips `release_always`
//! for first-publication dispatch; routine config must never carry it.
//! Version groups use the native `version_group` key: changed members take
//! the highest next version while unchanged members stay (no lockstep).

use std::collections::{BTreeMap, BTreeSet};

use crate::release_error::ReleaseError;
use crate::release_facts::validate_registry_name;
use crate::release_select::ReleaseSelection;
use crate::release_semver::parse_version;

/// Default package-qualified tag pattern.
pub const DEFAULT_TAG_PATTERN: &str = "{{ package }}-v{{ version }}";

/// Emission inputs.
#[derive(Debug, Clone)]
pub struct EmitOptions<'a> {
    /// Explicit tag pattern (must hold both placeholders).
    pub tag_pattern: &'a str,
    /// Native version groups applied to member entries.
    pub groups: &'a [VersionGroup],
}

/// One native release-plz version group.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VersionGroup {
    /// Group name.
    pub name: String,
    /// Member package names.
    pub members: Vec<String>,
}

/// One pre-existing tag record.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ExistingTag {
    /// Tag name.
    pub tag: String,
    /// Peeled commit SHA the tag points at.
    pub sha: String,
}

/// Tag-collision classification inputs.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TagState {
    /// Tag the release would create.
    pub expected_tag: String,
    /// Tags already present.
    pub existing: Vec<ExistingTag>,
    /// Independently verified release-source SHA.
    pub source_sha: String,
    /// Whether the registry already holds the version.
    pub registry_has_version: bool,
}

/// Distinct typed tag outcomes (never conflate collision with success).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TagOutcome {
    /// Expected tag absent and registry lacks the version.
    ReadyToPublish,
    /// Expected tag points at the verified source and registry agrees.
    AlreadyReleased {
        /// Tag name.
        tag: String,
        /// Tag target SHA.
        sha: String,
    },
    /// Registry holds the version but the expected tag is missing.
    MetadataRepairNeeded {
        /// Missing tag name.
        tag: String,
    },
    /// Expected tag conflicts (wrong source, or present while absent).
    TagCollision {
        /// Expected tag name.
        expected: String,
        /// SHA the conflicting tag points at.
        found: String,
        /// Verified release-source SHA.
        source: String,
    },
}

/// Emit the normal effective release-plz configuration.
///
/// # Errors
///
/// Returns [`ReleaseError`] on an empty set, bad tag pattern, or bad groups.
pub fn emit_release_plz_config(
    selection: &ReleaseSelection,
    options: &EmitOptions<'_>,
) -> Result<String, ReleaseError> {
    render_config(selection, options, false)
}

/// Emit the bootstrap-only configuration (`release_always = true`).
///
/// First-publication dispatch only; routine emission must use
/// [`emit_release_plz_config`].
///
/// # Errors
///
/// Returns [`ReleaseError`] on an empty set, bad tag pattern, or bad groups.
pub fn emit_bootstrap_config(
    selection: &ReleaseSelection,
    options: &EmitOptions<'_>,
) -> Result<String, ReleaseError> {
    render_config(selection, options, true)
}

/// Render either flavor of the effective configuration.
fn render_config(
    selection: &ReleaseSelection,
    options: &EmitOptions<'_>,
    bootstrap: bool,
) -> Result<String, ReleaseError> {
    if selection.is_empty() {
        return Err(ReleaseError::NothingSelected);
    }
    check_tag_pattern(options.tag_pattern)?;
    let known: BTreeSet<&str> = selection
        .packages
        .iter()
        .map(|package| package.name.as_str())
        .collect();
    let grouped = check_groups(options.groups, &known)?;
    let mut out =
        String::from("# Generated by Velnor Actions; do not edit.\n[workspace]\nrelease = false\n");
    out.push_str("release_always = ");
    out.push_str(render_bool(bootstrap));
    out.push_str("\nsemver_check = true\npublish_no_verify = false\npublish_allow_dirty = false\ngit_tag_name = ");
    toml_string(options.tag_pattern, &mut out);
    out.push('\n');
    for package in &selection.packages {
        out.push_str("\n[[package]]\nname = ");
        toml_string(&package.name, &mut out);
        out.push_str("\nrelease = true\npublish = true\ngit_only = false\n");
        if let Some(group) = grouped.get(package.name.as_str()) {
            out.push_str("version_group = ");
            toml_string(group, &mut out);
            out.push('\n');
        }
    }
    Ok(out)
}

/// Render a TOML boolean.
fn render_bool(value: bool) -> &'static str {
    if value { "true" } else { "false" }
}

/// Check the tag pattern holds both placeholders and no control bytes.
fn check_tag_pattern(pattern: &str) -> Result<(), ReleaseError> {
    let ok = pattern.contains("{{ package }}")
        && pattern.contains("{{ version }}")
        && !pattern.bytes().any(|byte| byte.is_ascii_control());
    if ok {
        Ok(())
    } else {
        Err(ReleaseError::InvalidTagPattern {
            pattern: pattern.to_owned(),
        })
    }
}

/// Check groups against `known` names, returning the member-to-group map.
fn check_groups<'a>(
    groups: &'a [VersionGroup],
    known: &BTreeSet<&str>,
) -> Result<BTreeMap<&'a str, &'a str>, ReleaseError> {
    let mut grouped = BTreeMap::new();
    for group in groups {
        if !validate_registry_name(&group.name) {
            return Err(ReleaseError::InvalidGroupName {
                group: group.name.clone(),
            });
        }
        if group.members.is_empty() {
            return Err(ReleaseError::EmptyGroup {
                group: group.name.clone(),
            });
        }
        for member in &group.members {
            if !known.contains(member.as_str()) {
                return Err(ReleaseError::UnknownGroupMember {
                    group: group.name.clone(),
                    member: member.clone(),
                });
            }
            if grouped
                .insert(member.as_str(), group.name.as_str())
                .is_some()
            {
                return Err(ReleaseError::OverlappingGroups {
                    member: member.clone(),
                });
            }
        }
    }
    Ok(grouped)
}

/// Resolve grouped versions: changed members take the highest planned next
/// version, unchanged members keep their current version (no lockstep).
///
/// `current` holds member versions, `planned` holds release-plz next
/// versions, and `changed` names members with changes. Returns resolved
/// versions for grouped members only.
///
/// # Errors
///
/// Returns [`ReleaseError`] on bad groups or unparsable input versions.
pub fn resolve_version_groups(
    groups: &[VersionGroup],
    current: &BTreeMap<String, String>,
    planned: &BTreeMap<String, String>,
    changed: &BTreeSet<String>,
) -> Result<BTreeMap<String, String>, ReleaseError> {
    let known: BTreeSet<&str> = current.keys().map(String::as_str).collect();
    check_groups(groups, &known)?;
    let mut resolved = BTreeMap::new();
    for group in groups {
        resolve_group(group, current, planned, changed, &mut resolved)?;
    }
    Ok(resolved)
}

/// Resolve one group into `resolved`.
fn resolve_group(
    group: &VersionGroup,
    current: &BTreeMap<String, String>,
    planned: &BTreeMap<String, String>,
    changed: &BTreeSet<String>,
    resolved: &mut BTreeMap<String, String>,
) -> Result<(), ReleaseError> {
    let changed_members: Vec<&str> = group
        .members
        .iter()
        .map(String::as_str)
        .filter(|member| changed.contains(*member))
        .collect();
    let mut next: Option<String> = None;
    for member in &changed_members {
        let text = planned
            .get(*member)
            .ok_or_else(|| ReleaseError::InvalidGroupVersion {
                group: group.name.clone(),
                member: (*member).to_owned(),
                version: String::new(),
            })?;
        let parsed = parse_version(text).ok_or_else(|| ReleaseError::InvalidGroupVersion {
            group: group.name.clone(),
            member: (*member).to_owned(),
            version: text.clone(),
        })?;
        let keep = next.as_ref().is_none_or(|held: &String| {
            parse_version(held).is_none_or(|current_max| parsed > current_max)
        });
        if keep {
            next = Some(text.clone());
        }
    }
    for member in &group.members {
        if changed.contains(member) {
            if let Some(winner) = next.as_deref() {
                resolved.insert(member.clone(), winner.to_owned());
            }
        } else {
            let held = current
                .get(member)
                .ok_or_else(|| ReleaseError::InvalidGroupVersion {
                    group: group.name.clone(),
                    member: member.clone(),
                    version: String::new(),
                })?;
            if parse_version(held).is_none() {
                return Err(ReleaseError::InvalidGroupVersion {
                    group: group.name.clone(),
                    member: member.clone(),
                    version: held.clone(),
                });
            }
            resolved.insert(member.clone(), held.clone());
        }
    }
    Ok(())
}

/// Classify expected-tag versus existing-tag and registry state.
#[must_use]
pub fn classify_tag(state: &TagState) -> TagOutcome {
    let found = state
        .existing
        .iter()
        .find(|tag| tag.tag == state.expected_tag);
    match found {
        None => {
            if state.registry_has_version {
                TagOutcome::MetadataRepairNeeded {
                    tag: state.expected_tag.clone(),
                }
            } else {
                TagOutcome::ReadyToPublish
            }
        }
        Some(tag) => {
            if state.registry_has_version && tag.sha == state.source_sha {
                TagOutcome::AlreadyReleased {
                    tag: tag.tag.clone(),
                    sha: tag.sha.clone(),
                }
            } else {
                TagOutcome::TagCollision {
                    expected: state.expected_tag.clone(),
                    found: tag.sha.clone(),
                    source: state.source_sha.clone(),
                }
            }
        }
    }
}

/// Append a formatted escape without an intermediate allocation.
///
/// `String` writes are infallible; the default maps the unrepresentable error.
fn append_escape(out: &mut String, args: std::fmt::Arguments<'_>) {
    use std::fmt::Write as _;
    write!(out, "{args}").unwrap_or_default();
}

/// Append `text` as a TOML basic string.
fn toml_string(text: &str, out: &mut String) {
    out.push('"');
    for char in text.chars() {
        match char {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            other if other.is_control() => {
                let code = u32::from(other);
                append_escape(out, format_args!("\\u{code:04X}"));
            }
            other => out.push(other),
        }
    }
    out.push('"');
}
