//! Comparison-only reads of committed generated bytes (gaps C).
//!
//! Generated output is never evidence. These helpers read the committed
//! generated header's recorded profile for stability comparison only: when
//! durable evidence vanished purely because Velnor replaced a hand-written
//! workflow, the orchestrator warns (GAP-C.2 fallback) instead of silently
//! flipping Cargo↔MBX or test↔Nextest. Nothing here produces
//! [`Evidence`](crate::evidence::Evidence).

use crate::evidence::is_generated_output;
use crate::profile::{CompileDriver, TestRunner};
use crate::scan::{has_adjacent, has_command, strip_comment};

/// Driver/runner pair recorded by committed generated bytes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CommittedProfile {
    /// Recorded compile driver.
    pub compile_driver: CompileDriver,
    /// Recorded test runner.
    pub test_runner: TestRunner,
}

/// Read the recorded profile from committed generated bytes, if any.
///
/// Returns `None` for non-generated content (comparison applies only to the
/// committed generated header) and for generated bytes carrying no driver or
/// runner signal. The result MUST feed stability comparison only, never
/// [`detect_profile`](crate::profile::detect_profile).
#[must_use]
pub fn read_committed_profile_for_comparison(content: &str) -> Option<CommittedProfile> {
    if !is_generated_output(content) {
        return None;
    }
    let mut mbx = false;
    let mut nextest = false;
    let mut cargo_test = false;
    for line in content.lines().skip(1) {
        let code = strip_comment(line);
        if code.trim().is_empty() {
            continue;
        }
        mbx |= invokes_mbx(code);
        nextest |= invokes_nextest(code);
        cargo_test |= invokes_cargo_test(code);
    }
    if !(mbx || nextest || cargo_test) {
        return None;
    }
    Some(CommittedProfile {
        compile_driver: if mbx {
            CompileDriver::Mbx
        } else {
            CompileDriver::Cargo
        },
        test_runner: if nextest {
            TestRunner::CargoNextest
        } else {
            TestRunner::CargoTest
        },
    })
}

/// Whether the detected profile drifted from the committed recording.
///
/// A `None` recording means nothing to compare against, never a drift. Drift
/// maps to a `persist_evidence`-style warning naming the vanished and durable
/// signals (GAP-C.2); it MUST NOT fail regeneration.
#[must_use]
pub fn committed_profile_differs(
    committed: Option<&CommittedProfile>,
    driver: CompileDriver,
    runner: TestRunner,
) -> bool {
    committed
        .is_some_and(|previous| previous.compile_driver != driver || previous.test_runner != runner)
}

/// Whether `code` invokes MBX outside comments and pins.
fn invokes_mbx(code: &str) -> bool {
    has_command(code, "mbx")
        || has_command(code, "mr-boxington")
        || has_command(code, "mr_boxington")
}

/// Whether `code` invokes Nextest outside comments and pins.
fn invokes_nextest(code: &str) -> bool {
    has_command(code, "nextest") || has_command(code, "cargo-nextest")
}

/// Whether `code` invokes plain `cargo test` (or `mbx test`).
fn invokes_cargo_test(code: &str) -> bool {
    has_adjacent(code, "cargo", "test") || has_adjacent(code, "mbx", "test")
}
