//! Workflow/tree rendering and policy gating cases.
use std::collections::BTreeMap;
use velnor_actions_contract_config::{
    GeneratorValidation, ValidatorKind, VelnorSupportWorkflow, WorkflowPolicy,
};
use velnor_actions_contract_workflow::{
    Concurrency, Job, JobTimeout, Permissions, Trigger, WorkflowIr,
};
use velnor_actions_workflow_renderer::{
    ACTIONLINT_PATH, AGENTS_MD_PATH, ALINT_USES, CANDIDATE_JOB_ID, CLAUDE_MD_PATH,
    CLAUDE_MD_TARGET, CONCURRENCY_CANCEL, CONCURRENCY_GROUP, FORBIDDEN_TOKENS, INTERNAL_OP_ENV,
    REQUEST_FILE_ENV, RenderContext, RenderError, ValidatorCommand, WORKFLOW_PATH, checkout_step,
    plan_step, render_tree, render_workflow_ir, with_marker,
};

const VERSION: &str = "0.1.0";
const LABEL: &str = "ubuntu-26.04";

fn checkout_pin() -> String {
    format!("actions/checkout@{:040x}", 0)
}

pub(crate) fn fixture_ctx() -> RenderContext {
    RenderContext {
        generator_version: VERSION.to_owned(),
        runs_on: LABEL.to_owned(),
        staged_binary: format!("$RUNNER_TEMP/velnor/bin/velnor-actions-{VERSION}"),
        request_dir: "${{ runner.temp }}/velnor/r1-a1".to_owned(),
        checkout_uses: checkout_pin(),
        validator_commands: Vec::new(),
        candidate: None,
        preseed: false,
        verification_tasks: Vec::new(),
        plan_consumer_env: std::collections::BTreeMap::new(),
    }
}

fn exact_triggers() -> Trigger {
    Trigger {
        pull_request_types: ["opened", "synchronize", "reopened", "ready_for_review"]
            .iter()
            .map(ToString::to_string)
            .collect(),
        push_branches: vec!["main".to_owned()],
        merge_group: true,
        workflow_dispatch: None,
        schedule: None,
    }
}

fn exact_concurrency() -> Concurrency {
    Concurrency {
        group: CONCURRENCY_GROUP.to_owned(),
        cancel_in_progress: CONCURRENCY_CANCEL.to_owned(),
    }
}

fn plan_job() -> Result<Job, RenderError> {
    Ok(Job {
        display_name: "Plan".to_owned(),
        runs_on: LABEL.to_owned(),
        check_runner: None,
        timeout_minutes: JobTimeout::PLAN,
        needs: Vec::new(),
        condition: None,
        permissions: None,
        environment: None,
        steps: vec![checkout_step(&checkout_pin())?, plan_step()],
    })
}

pub(crate) fn fixture_ir() -> Result<WorkflowIr, RenderError> {
    let mut jobs = BTreeMap::new();
    jobs.insert("plan".to_owned(), plan_job()?);
    Ok(WorkflowIr {
        name: "CI".to_owned(),
        triggers: exact_triggers(),
        permissions: Permissions::default(),
        concurrency: exact_concurrency(),
        jobs,
    })
}

fn actionlint_bytes() -> Result<String, RenderError> {
    with_marker(VERSION, "config-variables: []\n")
}

#[test]
fn marker_is_exact_first_line_without_dates() -> Result<(), RenderError> {
    let text = render_workflow_ir(
        &fixture_ir()?,
        WorkflowPolicy::ConsumerV1,
        None,
        &fixture_ctx(),
    )?;
    let first = text.lines().next();
    assert!(first.is_some());
    if let Some(line) = first {
        assert_eq!(
            line,
            "# Generated by Velnor Actions 0.1.0; edit .velnor/config.toml and regenerate."
        );
        assert!(!line.contains("2026"));
    }
    assert!(with_marker("bad version", "x").is_err());
    Ok(())
}

#[test]
fn workflow_render_is_byte_stable() -> Result<(), RenderError> {
    let ir = fixture_ir()?;
    let ctx = fixture_ctx();
    let first = render_workflow_ir(&ir, WorkflowPolicy::ConsumerV1, None, &ctx)?;
    let second = render_workflow_ir(&ir, WorkflowPolicy::ConsumerV1, None, &ctx)?;
    assert_eq!(first, second);
    Ok(())
}

#[test]
fn consumer_tree_has_exactly_two_sorted_paths() -> Result<(), RenderError> {
    let workflow = render_workflow_ir(
        &fixture_ir()?,
        WorkflowPolicy::ConsumerV1,
        None,
        &fixture_ctx(),
    )?;
    let tree = render_tree(&workflow, &actionlint_bytes()?, VERSION)?;
    assert_eq!(tree.files.len(), 3);
    assert_eq!(tree.symlinks.len(), 1);
    assert_eq!(tree.files[0].path, AGENTS_MD_PATH);
    assert_eq!(tree.files[1].path, ACTIONLINT_PATH);
    assert_eq!(tree.files[2].path, WORKFLOW_PATH);
    assert_eq!(tree.symlinks[0].path, CLAUDE_MD_PATH);
    assert_eq!(tree.symlinks[0].target, CLAUDE_MD_TARGET);
    assert_eq!(tree.get(WORKFLOW_PATH), Some(workflow.as_str()));
    assert!(tree.get(".github/other.yml").is_none());
    Ok(())
}

#[test]
fn consumer_tree_has_no_codeowners_and_rejects_support_jobs() -> Result<(), RenderError> {
    let ir = fixture_ir()?;
    let ctx = fixture_ctx();
    let with_support = VelnorSupportWorkflow {
        validators: vec![ValidatorKind::Alint],
        candidate_validation: false,
    };
    assert!(
        render_workflow_ir(&ir, WorkflowPolicy::ConsumerV1, Some(&with_support), &ctx).is_err()
    );
    let with_candidate = VelnorSupportWorkflow {
        validators: Vec::new(),
        candidate_validation: true,
    };
    assert!(
        render_workflow_ir(&ir, WorkflowPolicy::ConsumerV1, Some(&with_candidate), &ctx).is_err()
    );
    let empty = VelnorSupportWorkflow {
        validators: Vec::new(),
        candidate_validation: false,
    };
    let text = render_workflow_ir(&ir, WorkflowPolicy::ConsumerV1, Some(&empty), &ctx)?;
    assert!(!text.contains("CODEOWNERS"));
    let tree = render_tree(&text, &actionlint_bytes()?, VERSION)?;
    assert_eq!(tree.files.len(), 3);
    assert_eq!(tree.symlinks.len(), 1);
    Ok(())
}

#[test]
fn consumer_rejects_support_job_ids_in_ir() -> Result<(), RenderError> {
    let mut ir = fixture_ir()?;
    let ctx = fixture_ctx();
    for forbidden in [
        "alint",
        "cargo-deny",
        "cargo-machete",
        "zizmor",
        "candidate",
    ] {
        let mut with_job = ir.clone();
        with_job.jobs.insert(forbidden.to_owned(), plan_job()?);
        assert!(
            render_workflow_ir(&with_job, WorkflowPolicy::ConsumerV1, None, &ctx).is_err(),
            "consumer accepted {forbidden}"
        );
    }
    assert!(render_workflow_ir(&ir, WorkflowPolicy::ConsumerV1, None, &ctx).is_ok());
    ir.jobs.remove("plan");
    assert!(render_workflow_ir(&ir, WorkflowPolicy::ConsumerV1, None, &ctx).is_err());
    Ok(())
}

fn validator_commands() -> Vec<ValidatorCommand> {
    // Production names: the scrub gate allowlists these exactly.
    [
        (ValidatorKind::CargoDeny, "Run cargo-deny"),
        (ValidatorKind::CargoMachete, "Run cargo-machete"),
        (ValidatorKind::Zizmor, "Run zizmor"),
    ]
    .iter()
    .map(|(validator, name)| ValidatorCommand {
        validator: *validator,
        name: (*name).to_owned(),
        argv: vec!["deny".to_owned()],
    })
    .collect()
}

#[test]
fn velnor_policy_renders_validators_only() -> Result<(), RenderError> {
    let ir = fixture_ir()?;
    let mut ctx = fixture_ctx();
    ctx.validator_commands = validator_commands();
    let support =
        WorkflowPolicy::VelnorRepositoryV1.support_workflow(GeneratorValidation::Bootstrap);
    let text = render_workflow_ir(
        &ir,
        WorkflowPolicy::VelnorRepositoryV1,
        Some(&support),
        &ctx,
    )?;
    for id in ["alint:", "cargo-deny:", "cargo-machete:", "zizmor:"] {
        assert!(text.contains(id), "missing {id}:\n{text}");
    }
    assert!(text.contains(ALINT_USES));
    assert!(text.contains("fail-on-warning"));
    assert!(!text.contains("qualification"));
    assert!(!text.contains("toolchain"));
    assert!(!text.contains(CANDIDATE_JOB_ID));
    let mut dup_ctx = fixture_ctx();
    dup_ctx.validator_commands = validator_commands();
    let dup = VelnorSupportWorkflow {
        validators: vec![ValidatorKind::Alint, ValidatorKind::Alint],
        candidate_validation: false,
    };
    assert!(
        render_workflow_ir(
            &ir,
            WorkflowPolicy::VelnorRepositoryV1,
            Some(&dup),
            &dup_ctx
        )
        .is_err()
    );
    Ok(())
}

#[test]
fn velnor_alint_job_materializes_policy_before_running() -> Result<(), RenderError> {
    let ir = fixture_ir()?;
    let mut ctx = fixture_ctx();
    ctx.validator_commands = validator_commands();
    let support =
        WorkflowPolicy::VelnorRepositoryV1.support_workflow(GeneratorValidation::Bootstrap);
    let text = render_workflow_ir(
        &ir,
        WorkflowPolicy::VelnorRepositoryV1,
        Some(&support),
        &ctx,
    )?;
    let alint_at = text.find("  alint:").expect("alint job");
    let lane = &text[alint_at..];
    for pin in [
        "Materialize Rust policy",
        "rust-repository-policy-0.1.2.tar.gz",
        "cf688c1eeb84f74c3b673dcc57e2cafab0156313d25f64b17acf7eda6209d9b1",
        ".cache/rust-policy",
        "sha256sum -c",
        "GITHUB_PATH",
    ] {
        assert!(lane.contains(pin), "policy lane misses {pin}");
    }
    let materialize_at = lane.find("Materialize Rust policy").expect("lane step");
    let run_at = lane.find("Run Alint").expect("run step");
    let checkout_at = lane.find("Checkout").expect("checkout step");
    assert!(
        checkout_at < materialize_at && materialize_at < run_at,
        "policy lane out of order"
    );
    Ok(())
}

#[test]
fn rendered_yaml_contains_no_private_subcommands() -> Result<(), RenderError> {
    let ir = fixture_ir()?;
    let mut ctx = fixture_ctx();
    ctx.validator_commands = validator_commands();
    let support =
        WorkflowPolicy::VelnorRepositoryV1.support_workflow(GeneratorValidation::Bootstrap);
    let text = render_workflow_ir(
        &ir,
        WorkflowPolicy::VelnorRepositoryV1,
        Some(&support),
        &ctx,
    )?;
    for token in FORBIDDEN_TOKENS {
        assert!(!text.contains(token), "leaked token: {token}");
    }
    assert!(text.contains(&format!("{INTERNAL_OP_ENV}: plan-v1")));
    assert!(text.contains(&format!(
        "{REQUEST_FILE_ENV}: ${{{{ runner.temp }}}}/velnor/r1-a1/plan-v1-request.json"
    )));
    assert!(text.contains("run: \"\\\"$RUNNER_TEMP/velnor/bin/velnor-actions-0.1.0\\\"\""));
    assert!(!text.contains("run: $RUNNER_TEMP/velnor/bin/velnor-actions plan"));
    Ok(())
}

#[test]
fn internal_gate_requires_staged_binary_and_request_dir() -> Result<(), RenderError> {
    let ir = fixture_ir()?;
    let mut ctx = fixture_ctx();
    ctx.staged_binary = "/tmp/velnor-actions-0.1.0".to_owned();
    assert!(render_workflow_ir(&ir, WorkflowPolicy::ConsumerV1, None, &ctx).is_err());
    let mut ctx = fixture_ctx();
    ctx.staged_binary = "$RUNNER_TEMP/velnor/bin/velnor-actions-9.9.9".to_owned();
    assert!(render_workflow_ir(&ir, WorkflowPolicy::ConsumerV1, None, &ctx).is_err());
    let mut ctx = fixture_ctx();
    ctx.request_dir = "/tmp/velnor".to_owned();
    assert!(render_workflow_ir(&ir, WorkflowPolicy::ConsumerV1, None, &ctx).is_err());
    Ok(())
}
