//! Golden release-workflow snapshot (byte-exact rendered YAML).
use crate::impl_renderer_release_tree::{ctx, spec};
use velnor_actions_workflow_renderer::release_tree::render_release_workflow;
use velnor_actions_workflow_steps::RenderError;

#[test]
fn golden_workflow_snapshot() -> Result<(), RenderError> {
    assert_eq!(
        render_release_workflow(&spec()?, &ctx())?,
        EXPECTED_YAML,
        "golden snapshot"
    );
    Ok(())
}

const EXPECTED_YAML: &str = concat!(
    r#"# Generated by Velnor Actions 0.1.0; edit .velnor/config.toml and regenerate.
name: Velnor Release
"on":
  push:
    branches:
      - main
  schedule:
    - cron: 0 6 * * 1
  workflow_dispatch:
    inputs:
      plan:
        description: approved plan
        required: true
        default: plan-1
      source_sha:
        description: approved source
        required: true
        default: 0123456789abcdef0123456789abcdef01234567
permissions:
  contents: read
concurrency:
  group: release-acme/widgets
  cancel-in-progress: false
jobs:
  release-preflight:
    name: Release preflight
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: none
      id-token: none
    needs:
      - release-preparation
    steps:
      - name: Checkout
        uses: actions/checkout@0000000000000000000000000000000000000000
        with:
          fetch-depth: "0"
          persist-credentials: "false"
      - name: Checkout exact source
        uses: actions/checkout@0000000000000000000000000000000000000000
        with:
          fetch-depth: "0"
          path: release-source
          persist-credentials: "false"
          ref: 0123456789abcdef0123456789abcdef01234567
      - name: Run
        run: echo ok
  release-preparation:
    name: Release preparation
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
      id-token: none
    steps:
      - name: Run
        run: echo ok
  release-publish:
    name: Release publish-oidc
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    environment: crates-io
    permissions:
      contents: write
      pull-requests: read
      id-token: write
    needs:
      - release-preflight
    if: github.repository == 'acme/widgets' && github.event.inputs.plan == 'plan-1' && github.event.inputs.source_sha == '0123456789abcdef0123456789abcdef01234567'
    steps:
      - name: Checkout
        uses: actions/checkout@0000000000000000000000000000000000000000
        with:
          fetch-depth: "0"
          persist-credentials: "false"
      - name: Checkout exact source
        uses: actions/checkout@0000000000000000000000000000000000000000
        with:
          fetch-depth: "0"
          path: release-source
          persist-credentials: "true"
          ref: 0123456789abcdef0123456789abcdef01234567
      - name: Publish
        env:
          GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: release-plz release --config .github/release-plz.toml
  release-reconcile:
    name: Release reconcile
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: read
      id-token: none
    needs:
      - release-publish
    if: always()
    steps:
      - name: Run
        run: echo ok"#,
    "\n"
);
