//! Repository-owned template handling in the generated tree.

use velnor_actions_contract_release::formats::{
    MAX_PRESERVED_GITHUB_INPUT_BYTES, PULL_REQUEST_TEMPLATE_PATH,
};
use velnor_actions_workflow_renderer::{
    render_tree, render_tree_with_extra, render_tree_with_extra_and_preserved_template,
    render_workflow_ir,
};
use velnor_actions_workflow_steps::RenderError;
use velnor_actions_workflow_tree::rendered::RenderedFile;

use crate::impl_renderer_tree_policy::{actionlint_bytes, fixture_ctx, fixture_ir};

const VERSION: &str = "0.1.0";

fn workflow_bytes() -> Result<String, RenderError> {
    render_workflow_ir(
        &fixture_ir()?,
        velnor_actions_contract_config::WorkflowPolicy::ConsumerV1,
        None,
        &fixture_ctx(),
    )
}

#[test]
fn absent_template_preserves_the_existing_tree_bytes() -> Result<(), RenderError> {
    let workflow = workflow_bytes()?;
    let actionlint = actionlint_bytes()?;
    let before = render_tree(&workflow, &actionlint, VERSION)?;
    let after =
        render_tree_with_extra_and_preserved_template(&workflow, &actionlint, &[], None, VERSION)?;
    assert_eq!(before, after);
    assert_eq!(after.get(PULL_REQUEST_TEMPLATE_PATH), None);
    Ok(())
}

#[test]
fn preserved_markdown_keeps_exact_bytes_without_generated_scans() -> Result<(), RenderError> {
    let workflow = workflow_bytes()?;
    let actionlint = actionlint_bytes()?;
    let template = "# Generated by another tool\n- run: __internal_private\n";
    let tree = render_tree_with_extra_and_preserved_template(
        &workflow,
        &actionlint,
        &[],
        Some(template),
        VERSION,
    )?;
    assert_eq!(tree.get(PULL_REQUEST_TEMPLATE_PATH), Some(template));
    assert!(
        tree.files
            .iter()
            .any(|file| file.path == PULL_REQUEST_TEMPLATE_PATH)
    );
    Ok(())
}

#[test]
fn preserved_template_is_bounded_and_reserved_from_extras() -> Result<(), Box<dyn std::error::Error>>
{
    let workflow = workflow_bytes()?;
    let actionlint = actionlint_bytes()?;
    let exact = "x".repeat(usize::try_from(MAX_PRESERVED_GITHUB_INPUT_BYTES)?);
    assert!(
        render_tree_with_extra_and_preserved_template(
            &workflow,
            &actionlint,
            &[],
            Some(&exact),
            VERSION,
        )
        .is_ok()
    );
    let over = "x".repeat(usize::try_from(MAX_PRESERVED_GITHUB_INPUT_BYTES + 1)?);
    assert!(
        render_tree_with_extra_and_preserved_template(
            &workflow,
            &actionlint,
            &[],
            Some(&over),
            VERSION,
        )
        .is_err()
    );

    let extra = RenderedFile {
        path: PULL_REQUEST_TEMPLATE_PATH.to_owned(),
        bytes: "ordinary markdown".to_owned(),
    };
    assert!(render_tree_with_extra(&workflow, &actionlint, &[extra], VERSION).is_err());
    Ok(())
}
