#!/bin/sh
set -e
PATH=/usr/sbin:/usr/bin:/sbin:/bin
export PATH
# cargo-deb inserts generated systemd cleanup fragments here. The package
# does not delete operator configuration, credentials, or state.
#DEBHELPER#

case "${1:-}" in
    remove|purge)
        if [ -d /run/systemd/system ]; then
            systemctl daemon-reload
        fi
        ;;
esac
