//! Configuration initialization and config-file integration cases.

use super::*;

#[test]
fn init_creates_sample_and_refuses_overwrite() -> TestResult {
    let repo = make_repo(config_with_branch())?;
    let root = repo.path();
    fs::remove_file(root.join(".velnor/config.toml"))?;
    let report = init_config(root)?;
    assert_eq!(report.created, vec![".velnor/config.toml"]);
    let text = fs::read_to_string(root.join(".velnor/config.toml"))?;
    assert!(
        text.starts_with("# Generated by Velnor Actions "),
        "marker:\n{text}"
    );
    assert!(text.contains("\nschema = 1\n"), "schema:\n{text}");
    assert!(text.contains("CODEOWNERS"), "codeowners note:\n{text}");
    let err = err_of(init_config(root), "overwrite refused")?;
    assert!(
        matches!(err, OrchestratorError::OverwriteRefused { .. }),
        "got {err}"
    );
    let flat = TempDir::new()?;
    fs::write(flat.path().join(".velnor"), "file")?;
    let err = err_of(init_config(flat.path()), "file .velnor refused")?;
    assert!(
        matches!(err, OrchestratorError::UnsafePath { .. }),
        "got {err}"
    );
    Ok(())
}

#[test]
fn config_errors_name_file_and_key_path() -> TestResult {
    let repo = make_repo("schema = 3\n")?;
    let err = err_of(prepare(repo.path()), "bad schema")?;
    assert!(err.to_string().contains(".velnor/config.toml"), "got {err}");
    assert!(err.to_string().contains("schema"), "got {err}");

    let repo = make_repo("schema = 1\n[workflow]\nnope = true\n")?;
    let err = err_of(prepare(repo.path()), "unknown key")?;
    assert!(err.to_string().contains(".velnor/config.toml"), "got {err}");

    let repo = make_repo("schema = 1\n[workflow]\nmax_parallel_jobs = 0\n")?;
    let err = err_of(prepare(repo.path()), "bad value")?;
    assert!(
        err.to_string().contains("workflow.max_parallel_jobs"),
        "got {err}"
    );

    let repo = make_repo("schema = 1\n[workflow]\ngenerator_validation = \"candidate\"\n")?;
    let err = err_of(prepare(repo.path()), "consumer candidate rejected")?;
    assert!(
        err.to_string().contains("workflow.generator_validation"),
        "got {err}"
    );

    let missing = TempDir::new()?;
    let err = err_of(prepare(missing.path()), "missing config")?;
    assert!(
        matches!(err, OrchestratorError::ConfigMissing { .. }),
        "got {err}"
    );
    Ok(())
}

#[test]
fn default_branch_prefers_config_then_origin_head() -> TestResult {
    let origin = TempDir::new()?;
    git(&["init", "-b", "upstream-main"], origin.path())?;
    git(&["config", "user.email", "test@example.com"], origin.path())?;
    git(&["config", "user.name", "Test"], origin.path())?;
    git(&["config", "commit.gpgsign", "false"], origin.path())?;
    fs::write(origin.path().join("seed.txt"), "seed")?;
    git(&["add", "."], origin.path())?;
    git(&["commit", "-m", "seed"], origin.path())?;
    let parent = TempDir::new()?;
    let clone_path = parent.path().join("clone");
    git(
        &[
            "clone",
            &origin.path().display().to_string(),
            &clone_path.display().to_string(),
        ],
        parent.path(),
    )?;
    fs::create_dir_all(clone_path.join(".velnor"))?;
    fs::write(clone_path.join(".velnor/config.toml"), "schema = 1\n")?;
    fs::write(
        clone_path.join(".velnor/release-manifest.json"),
        fixture_manifest_json(),
    )?;
    fs::write(
        clone_path.join("Cargo.toml"),
        "[package]\nname = \"demo\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    )?;
    fs::create_dir_all(clone_path.join("src"))?;
    fs::write(clone_path.join("src/lib.rs"), "pub fn f() {}\n")?;
    let prep = prepare(&clone_path)?;
    assert_eq!(prep.default_branch, "upstream-main");

    fs::write(
        clone_path.join(".velnor/config.toml"),
        "schema = 1\n[workflow]\ndefault_branch = \"pinned\"\n",
    )?;
    let prep = prepare(&clone_path)?;
    assert_eq!(prep.default_branch, "pinned");
    Ok(())
}

#[test]
fn resolve_root_from_nested_subdir() -> TestResult {
    let repo = make_repo(config_with_branch())?;
    let nested = repo.path().join("a/b");
    fs::create_dir_all(&nested)?;
    let root = resolve_root(&nested)?;
    assert_eq!(root, repo.path().canonicalize()?);
    Ok(())
}

#[test]
fn velnor_policy_rejected_without_identity() -> TestResult {
    without_ambient_identity("velnor_policy_rejected_without_identity", || {
        let repo = make_repo(
            "schema = 1\n[workflow]\npolicy = \"velnor-repository-v1\"\ndefault_branch = \"testmain\"\n",
        )?;
        let err = err_of(prepare(repo.path()), "identity rejected")?;
        assert!(
            matches!(err, OrchestratorError::IdentityRejected { .. }),
            "got {err}"
        );
        Ok(())
    })
}

#[test]
fn uncommented_init_sample_parses_with_overrides() -> TestResult {
    let repo = make_repo(config_with_branch())?;
    let root = repo.path();
    fs::remove_file(root.join(".velnor/config.toml"))?;
    init_config(root)?;
    let sample = fs::read_to_string(root.join(".velnor/config.toml"))?;
    assert!(sample.contains("# checks = []"));
    assert!(!sample.contains("custom_tasks"));
    let mut live = String::new();
    for line in sample.lines() {
        let uncommented = uncomment_sample_line(line);
        live.push_str(uncommented);
        live.push('\n');
    }
    assert!(
        live.contains("[actions.overrides]"),
        "sample must document overrides"
    );
    fs::write(root.join(".velnor/config.toml"), &live)?;
    let prep = prepare(root)?;
    assert!(prep.config.checks.is_empty());
    assert_eq!(prep.config.actions.overrides.len(), 8);
    assert_eq!(
        prep.config.actions.overrides["actions/checkout"].version,
        "v7.0.1"
    );
    assert_eq!(prep.runner_label, "ubuntu-24.04");
    assert_eq!(prep.runner_selection, RunnerSelection::ConfigOverride);
    Ok(())
}

#[test]
fn unknown_override_key_rejected_with_key_path() -> TestResult {
    let repo = make_repo(
        "schema = 1\n[workflow]\ndefault_branch = \"testmain\"\n[actions.overrides]\n\"bogus/action\" = { version = \"v1.2.3\", sha = \"3d3c42e5aac5ba805825da76410c181273ba90b1\" }\n",
    )?;
    let err = err_of(prepare(repo.path()), "unknown override rejected")?;
    assert!(
        err.to_string().contains("actions.overrides.bogus/action"),
        "got {err}"
    );
    // Policy-owned alint overrides reject like unknown keys (§2, GitHub Action defaults).
    let repo = make_repo(
        "schema = 1\n[workflow]\ndefault_branch = \"testmain\"\n[actions.overrides]\n\"asamarts/alint\" = { version = \"v0.16.1\", sha = \"9f9d34ba0eae3888299b9e570f43338b0e7f2cdb\" }\n",
    )?;
    let m = err_of(prepare(repo.path()), "alint override rejected")?.to_string();
    assert!(m.contains("actions.overrides.asamarts/alint"));
    Ok(())
}
