//! Version-group, emission, and tag-classification cases.
use std::collections::{BTreeMap, BTreeSet};

use serde_json::Value;

use crate::release_support::{doc, pkg, root_of, select_of};
use crate::support::{Outcome, TempDir};
use velnor_actions_rust_core::{
    DEFAULT_TAG_PATTERN, EmitOptions, ExistingTag, ReleaseError, ReleaseScope, TagOutcome,
    TagState, VersionGroup, classify_tag, emit_bootstrap_config, emit_release_plz_config,
    resolve_version_groups,
};

#[test]
fn version_groups_take_max_while_unchanged_stay() -> Outcome {
    let groups = vec![VersionGroup {
        name: "core".to_owned(),
        members: vec!["alpha".to_owned(), "beta".to_owned()],
    }];
    let current = BTreeMap::from([
        ("alpha".to_owned(), "1.0.0".to_owned()),
        ("beta".to_owned(), "1.1.0".to_owned()),
    ]);
    let planned = BTreeMap::from([
        ("alpha".to_owned(), "1.1.0".to_owned()),
        ("beta".to_owned(), "1.2.0".to_owned()),
    ]);
    let changed = BTreeSet::from(["alpha".to_owned(), "beta".to_owned()]);
    let resolved = resolve_version_groups(&groups, &current, &planned, &changed)?;
    assert_eq!(resolved.get("alpha").map(String::as_str), Some("1.2.0"));
    assert_eq!(resolved.get("beta").map(String::as_str), Some("1.2.0"));
    let changed = BTreeSet::from(["alpha".to_owned()]);
    let resolved = resolve_version_groups(&groups, &current, &planned, &changed)?;
    assert_eq!(resolved.get("alpha").map(String::as_str), Some("1.1.0"));
    assert_eq!(resolved.get("beta").map(String::as_str), Some("1.1.0"));
    let overlapping = vec![
        VersionGroup {
            name: "one".to_owned(),
            members: vec!["alpha".to_owned()],
        },
        VersionGroup {
            name: "two".to_owned(),
            members: vec!["alpha".to_owned()],
        },
    ];
    assert!(matches!(
        resolve_version_groups(&overlapping, &current, &planned, &changed),
        Err(ReleaseError::OverlappingGroups { .. })
    ));
    Ok(())
}

#[test]
fn emission_is_deterministic_with_bootstrap_variant() -> Outcome {
    let dir = TempDir::create("release-emit")?;
    let root = root_of(&dir)?;
    let json = doc(
        &root,
        vec!["a-id", "b-id"],
        vec![
            pkg(
                &root,
                "a-id",
                "alpha",
                "1.0.0",
                "crates/a/Cargo.toml",
                Value::Null,
                vec![],
            ),
            pkg(
                &root,
                "b-id",
                "beta",
                "1.0.0",
                "crates/b/Cargo.toml",
                Value::Null,
                vec![],
            ),
        ],
    );
    let scope = ReleaseScope::Packages(vec!["beta".to_owned(), "alpha".to_owned()]);
    let selection = select_of(&json, &root, &scope, &BTreeSet::new(), &[])?;
    let groups = vec![VersionGroup {
        name: "core".to_owned(),
        members: vec!["alpha".to_owned(), "beta".to_owned()],
    }];
    let options = EmitOptions {
        tag_pattern: DEFAULT_TAG_PATTERN,
        groups: &groups,
    };
    let first = emit_release_plz_config(&selection, &options)?;
    let second = emit_release_plz_config(&selection, &options)?;
    assert_eq!(first, second);
    let expected = "# Generated by Velnor Actions; do not edit.\n\
        [workspace]\nrelease = false\nrelease_always = false\nsemver_check = true\n\
        publish_no_verify = false\npublish_allow_dirty = false\n\
        git_tag_name = \"{{ package }}-v{{ version }}\"\n\
        \n[[package]]\nname = \"alpha\"\nrelease = true\npublish = true\ngit_only = false\n\
        version_group = \"core\"\n\
        \n[[package]]\nname = \"beta\"\nrelease = true\npublish = true\ngit_only = false\n\
        version_group = \"core\"\n";
    assert_eq!(first, expected);
    let bootstrap = emit_bootstrap_config(&selection, &options)?;
    assert!(bootstrap.contains("release_always = true"));
    assert_eq!(
        bootstrap.replace("release_always = true", "release_always = false"),
        first
    );
    Ok(())
}

#[test]
fn tag_collision_registry_absence_and_repair_stay_distinct() {
    let found = ExistingTag {
        tag: "alpha-v1.0.0".to_owned(),
        sha: "b".repeat(40),
    };
    let source = "a".repeat(40);
    let ready = classify_tag(&TagState {
        expected_tag: "alpha-v1.0.0".to_owned(),
        existing: vec![],
        source_sha: source.clone(),
        registry_has_version: false,
    });
    assert_eq!(ready, TagOutcome::ReadyToPublish);
    let collision = classify_tag(&TagState {
        expected_tag: "alpha-v1.0.0".to_owned(),
        existing: vec![found.clone()],
        source_sha: source.clone(),
        registry_has_version: false,
    });
    assert!(matches!(collision, TagOutcome::TagCollision { .. }));
    let repair = classify_tag(&TagState {
        expected_tag: "alpha-v1.0.0".to_owned(),
        existing: vec![],
        source_sha: source.clone(),
        registry_has_version: true,
    });
    assert!(matches!(repair, TagOutcome::MetadataRepairNeeded { .. }));
    let released = classify_tag(&TagState {
        expected_tag: "alpha-v1.0.0".to_owned(),
        existing: vec![ExistingTag {
            tag: "alpha-v1.0.0".to_owned(),
            sha: source.clone(),
        }],
        source_sha: source,
        registry_has_version: true,
    });
    assert!(matches!(released, TagOutcome::AlreadyReleased { .. }));
}

#[test]
fn tag_pattern_requires_placeholders_and_escapes_toml() -> Outcome {
    let dir = TempDir::create("release-tag")?;
    let root = root_of(&dir)?;
    let json = doc(
        &root,
        vec!["a-id"],
        vec![pkg(
            &root,
            "a-id",
            "alpha",
            "1.0.0",
            "Cargo.toml",
            Value::Null,
            vec![],
        )],
    );
    let scope = ReleaseScope::Packages(vec!["alpha".to_owned()]);
    let selection = select_of(&json, &root, &scope, &BTreeSet::new(), &[])?;
    let bad = EmitOptions {
        tag_pattern: "v{{ version }}",
        groups: &[],
    };
    assert!(matches!(
        emit_release_plz_config(&selection, &bad),
        Err(ReleaseError::InvalidTagPattern { .. })
    ));
    let quoted = EmitOptions {
        tag_pattern: "{{ package }}-\"v{{ version }}\"",
        groups: &[],
    };
    let rendered = emit_release_plz_config(&selection, &quoted)?;
    assert!(rendered.contains("git_tag_name = \"{{ package }}-\\\"v{{ version }}\\\"\""));
    Ok(())
}
