//! F2F orchestrator-family edges, split from the edge table (size gate).

/// Orchestrator-family edges by member directory.
#[path = "impl_orch_f2f_family_b.rs"]
mod family_b;

const ORCHESTRATOR_FAMILY: &[(&str, &[&str])] = &[
    (
        "crates/services/velnor-actions-orchestrator-check-acquisition",
        &[
            "velnor-actions-contract",
            "velnor-actions-contract-config",
            "velnor-actions-mise",
            "velnor-actions-orchestrator-core",
        ],
    ),
    (
        "crates/services/velnor-actions-orchestrator-check-evidence",
        &[
            "velnor-actions-contract",
            "velnor-actions-contract-config",
            "velnor-actions-contract-workflow",
            "velnor-actions-mise",
            "velnor-actions-orchestrator-check-acquisition",
            "velnor-actions-orchestrator-check-preparation",
            "velnor-actions-orchestrator-core",
        ],
    ),
    (
        "crates/services/velnor-actions-orchestrator-check-preparation",
        &[
            "velnor-actions-contract",
            "velnor-actions-contract-config",
            "velnor-actions-mise",
            "velnor-actions-orchestrator-check-acquisition",
            "velnor-actions-orchestrator-core",
            "velnor-actions-workflow-steps",
        ],
    ),
    (
        "crates/services/velnor-actions-orchestrator-core",
        &[
            "velnor-actions-actionlint",
            "velnor-actions-contract",
            "velnor-actions-contract-config",
            "velnor-actions-contract-planning",
            "velnor-actions-contract-release",
            "velnor-actions-contract-workflow",
            "velnor-actions-mise",
            "velnor-actions-rust",
            "velnor-actions-rust-core",
            "velnor-actions-tofu-core",
            "velnor-actions-workflow-steps",
            "velnor-actions-workflow-tree",
        ],
    ),
    (
        "crates/services/velnor-actions-orchestrator-cover",
        &[
            "velnor-actions-contract",
            "velnor-actions-contract-workflow",
            "velnor-actions-mise",
            "velnor-actions-orchestrator-core",
            "velnor-actions-orchestrator-cover-baseline",
            "velnor-actions-orchestrator-cover-compat",
            "velnor-actions-orchestrator-external-data",
            "velnor-actions-orchestrator-graph",
            "velnor-actions-orchestrator-merge-ports",
            "velnor-actions-orchestrator-run-select",
            "velnor-actions-rust-core",
        ],
    ),
    (
        "crates/services/velnor-actions-orchestrator-cover-baseline",
        &[
            "velnor-actions-contract",
            "velnor-actions-contract-planning",
            "velnor-actions-contract-release",
            "velnor-actions-contract-workflow",
            "velnor-actions-mise",
            "velnor-actions-orchestrator-core",
            "velnor-actions-orchestrator-cover-compat",
            "velnor-actions-orchestrator-discovery",
            "velnor-actions-orchestrator-external-data",
            "velnor-actions-orchestrator-graph",
            "velnor-actions-orchestrator-merge",
            "velnor-actions-orchestrator-merge-ports",
            "velnor-actions-rust",
            "velnor-actions-tofu-core",
        ],
    ),
    (
        "crates/services/velnor-actions-orchestrator-cover-compat",
        &[
            "velnor-actions-contract",
            "velnor-actions-contract-workflow",
        ],
    ),
    (
        "crates/services/velnor-actions-orchestrator-covered-tasks",
        &[
            "velnor-actions-contract-workflow",
            "velnor-actions-workflow-renderer",
        ],
    ),
    (
        "crates/services/velnor-actions-orchestrator-discovery",
        &[
            "velnor-actions-contract",
            "velnor-actions-contract-config",
            "velnor-actions-contract-planning",
            "velnor-actions-contract-release",
            "velnor-actions-mise",
            "velnor-actions-orchestrator-core",
            "velnor-actions-rust",
            "velnor-actions-rust-core",
            "velnor-actions-tofu",
            "velnor-actions-tofu-core",
            "velnor-actions-workflow-renderer",
        ],
    ),
    (
        "crates/services/velnor-actions-orchestrator-external-data",
        &[
            "velnor-actions-contract",
            "velnor-actions-orchestrator-core",
        ],
    ),
    (
        "crates/services/velnor-actions-orchestrator-generation",
        &[
            "velnor-actions-actionlint",
            "velnor-actions-contract",
            "velnor-actions-contract-config",
            "velnor-actions-contract-release",
            "velnor-actions-contract-workflow",
            "velnor-actions-mise",
            "velnor-actions-orchestrator-core",
            "velnor-actions-orchestrator-discovery",
            "velnor-actions-orchestrator-pins",
            "velnor-actions-orchestrator-provisioning",
            "velnor-actions-orchestrator-staged-validation",
            "velnor-actions-orchestrator-workflow-ir",
            "velnor-actions-rust-core",
            "velnor-actions-tofu-core",
            "velnor-actions-workflow-cache",
            "velnor-actions-workflow-generator",
            "velnor-actions-workflow-jobs",
            "velnor-actions-workflow-release",
            "velnor-actions-workflow-render-strict",
            "velnor-actions-workflow-renderer",
            "velnor-actions-workflow-schema2",
            "velnor-actions-workflow-steps",
            "velnor-actions-workflow-tree",
        ],
    ),
    (
        "crates/services/velnor-actions-orchestrator-graph",
        &[
            "velnor-actions-contract",
            "velnor-actions-contract-config",
            "velnor-actions-contract-planning",
            "velnor-actions-contract-release",
            "velnor-actions-contract-workflow",
            "velnor-actions-mise",
            "velnor-actions-orchestrator-core",
            "velnor-actions-orchestrator-discovery",
            "velnor-actions-rust",
            "velnor-actions-rust-core",
            "velnor-actions-tofu",
            "velnor-actions-tofu-core",
            "velnor-actions-workflow-document",
            "velnor-actions-workflow-steps",
        ],
    ),
    (
        "crates/services/velnor-actions-orchestrator-merge",
        &[
            "velnor-actions-contract",
            "velnor-actions-contract-workflow",
            "velnor-actions-orchestrator-check-evidence",
            "velnor-actions-orchestrator-core",
            "velnor-actions-orchestrator-merge-ports",
            "velnor-actions-workflow-jobs",
        ],
    ),
    (
        "crates/services/velnor-actions-orchestrator-merge-ports",
        &[
            "velnor-actions-contract",
            "velnor-actions-contract-planning",
            "velnor-actions-contract-workflow",
            "velnor-actions-mise",
            "velnor-actions-orchestrator-core",
            "velnor-actions-orchestrator-external-data",
            "velnor-actions-orchestrator-selection",
        ],
    ),
    (
        "crates/services/velnor-actions-orchestrator-merge-request",
        &[
            "velnor-actions-contract",
            "velnor-actions-contract-workflow",
            "velnor-actions-orchestrator-check-evidence",
            "velnor-actions-orchestrator-core",
            "velnor-actions-orchestrator-merge-request-ports",
            "velnor-actions-orchestrator-request-event",
            "velnor-actions-workflow-jobs",
        ],
    ),
    (
        "crates/services/velnor-actions-orchestrator-merge-request-ports",
        &["velnor-actions-orchestrator-core"],
    ),
];

pub(crate) fn expected_orchestrator_family(dir: &str) -> Option<Vec<&str>> {
    ORCHESTRATOR_FAMILY
        .iter()
        .chain(family_b::ORCHESTRATOR_FAMILY.iter())
        .find(|(name, _)| *name == dir)
        .map(|(_, edges)| edges.to_vec())
}
