[package]
name = "velnor-actions-orchestrator-covered-tasks"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
autotests = false

[dependencies]
velnor-actions-contract-workflow = { version = "=0.1.1", path = "../../core/velnor-actions-contract-workflow" }
velnor-actions-workflow-renderer = { version = "=0.1.1", path = "../velnor-actions-workflow-renderer" }

[dev-dependencies]
velnor-actions-contract = { version = "=0.1.1", path = "../../core/velnor-actions-contract" }
velnor-actions-contract-config = { version = "=0.1.1", path = "../../core/velnor-actions-contract-config" }

[lints]
workspace = true

[[test]]
name = "velnor_orchestrator_covered_tasks"
path = "tests/main.rs"
