use super::*;
use velnor_actions_contract::FRESHNESS_CRON_WEEKLY;

const CHECKOUT: &str = "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1";

fn spec() -> FreshnessSpec {
    FreshnessSpec {
        schedule: ScheduleTrigger {
            cron: vec![FRESHNESS_CRON_WEEKLY.to_owned()],
        },
        runs_on: "ubuntu-26.04".to_owned(),
        checkout_uses: CHECKOUT.to_owned(),
        mise_setup: MiseSetup {
            uses: "jdx/mise-action@9149ea85001c7435d5a66bb127d6a1b6227cb0a5".to_owned(),
            version: "2026.9.18".to_owned(),
            sha256: "d24fe0bf7e613824ad99f7b8dac3f2b381a37b9f75f84dd250855217095a8de4".to_owned(),
        },
        rust_version: "1.98.1".to_owned(),
        generator_version: "0.1.0".to_owned(),
    }
}

#[test]
fn renders_schedule_only_read_only_probe() {
    let file = render_freshness_workflow(&spec()).expect("render");
    assert_eq!(file.path, ".github/workflows/freshness.yml");
    let yaml = &file.bytes;
    assert!(
        yaml.starts_with("# Generated by Velnor Actions 0.1.0"),
        "marker:\n{yaml}"
    );
    assert!(yaml.contains("cron: 0 6 * * 1"), "weekly trigger:\n{yaml}");
    assert!(
        yaml.contains("workflow_dispatch:"),
        "manual re-run:\n{yaml}"
    );
    assert!(
        !yaml.contains("pull_request") && !yaml.contains("push:"),
        "schedule-only:\n{yaml}"
    );
    assert!(
        yaml.matches("contents: read").count() >= 2,
        "top-level plus job perms:\n{yaml}"
    );
    assert!(!yaml.contains("write"), "read-only:\n{yaml}");
    assert!(!yaml.contains("secrets."), "no secrets:\n{yaml}");
    assert!(
        yaml.contains("uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1"),
        "exact pin:\n{yaml}"
    );
    assert!(
        yaml.contains("persist-credentials: \"false\""),
        "no credentials:\n{yaml}"
    );
    assert!(
        yaml.contains("scripts/check-freshness.sh --check-upstream"),
        "bounded probe:\n{yaml}"
    );
    assert!(
        yaml.contains("uses: jdx/mise-action@9149ea85001c7435d5a66bb127d6a1b6227cb0a5"),
        "pinned Mise setup:\n{yaml}"
    );
    assert!(
        yaml.contains("version: 2026.9.18"),
        "current Mise release pin:\n{yaml}"
    );
    assert!(
        yaml.contains("sha256: d24fe0bf7e613824ad99f7b8dac3f2b381a37b9f75f84dd250855217095a8de4"),
        "current Mise binary digest:\n{yaml}"
    );
    assert!(
        yaml.contains("mise --no-config --no-env --no-hooks install rust@1.98.1"),
        "exact Rust install:\n{yaml}"
    );
    assert!(
        yaml.contains("mise --no-config --no-env --no-hooks exec rust@1.98.1 -- bash scripts/check-freshness.sh --check-upstream"),
        "freshness runs with the installed Rust:\n{yaml}"
    );
    let positions = [
        yaml.find("name: Checkout"),
        yaml.find("name: Setup Mise"),
        yaml.find("name: Install Rust toolchain"),
        yaml.find("name: Check upstream freshness"),
    ];
    assert!(
        positions.iter().all(Option::is_some) && positions.windows(2).all(|pair| pair[0] < pair[1]),
        "checkout, Mise setup, Rust install, and probe are ordered:\n{yaml}"
    );
    assert!(
        yaml.contains("timeout-minutes: 10"),
        "explicit timeout:\n{yaml}"
    );
    assert!(
        yaml.contains("group: freshness") && yaml.contains("cancel-in-progress: false"),
        "serialize scheduled runs:\n{yaml}"
    );
}

#[test]
fn rejects_bad_spec_scalars() {
    let bad_cron = FreshnessSpec {
        schedule: ScheduleTrigger {
            cron: vec!["not-a-cron".to_owned()],
        },
        ..spec()
    };
    assert!(render_freshness_workflow(&bad_cron).is_err(), "bad cron");
    let empty_cron = FreshnessSpec {
        schedule: ScheduleTrigger { cron: Vec::new() },
        ..spec()
    };
    assert!(
        render_freshness_workflow(&empty_cron).is_err(),
        "empty cron"
    );
    for runs_on in ["ubuntu-latest", "ubuntu-26.04 ${{ x }}", ""] {
        let bad = FreshnessSpec {
            runs_on: runs_on.to_owned(),
            ..spec()
        };
        assert!(
            render_freshness_workflow(&bad).is_err(),
            "bad label {runs_on}"
        );
    }
    for rust_version in ["", "latest", "1.98", "1.98.1; id", "1.98.1.2"] {
        let bad = FreshnessSpec {
            rust_version: rust_version.to_owned(),
            ..spec()
        };
        assert!(
            render_freshness_workflow(&bad).is_err(),
            "bad Rust version {rust_version}"
        );
    }
    for uses in [
        "actions/checkout@v7.0.1",
        "actions/checkout@short",
        "other/x@3d3c42e5aac5ba805825da76410c181273ba90b1",
    ] {
        let bad = FreshnessSpec {
            checkout_uses: uses.to_owned(),
            ..spec()
        };
        assert!(
            render_freshness_workflow(&bad).is_err(),
            "bad checkout {uses}"
        );
    }
}

#[test]
fn rejects_internal_steps_fail_closed() {
    let internal = Step {
        name: "Plan".to_owned(),
        id: None,
        role: None,
        condition: None,
        kind: velnor_actions_contract::StepKind::Internal {
            operation: "plan-v1".to_owned(),
            env: std::collections::BTreeMap::new(),
        },
    };
    let err = crate::steps_plain::plain_step_to_yaml(&internal).expect_err("rejected");
    assert!(err.to_string().contains("internal_op_rejected"), "{err}");
}
