//! Qualification outputs promoted from the validated plan step.

use velnor_actions_contract::workflow::{
    QUALIFICATION_CACHE_DIRECTIVES_OUTPUT, QUALIFICATION_CACHE_ENABLED_OUTPUT,
    QUALIFICATION_CACHE_WRITE_OUTPUT, QUALIFICATION_CAMPAIGN_OUTPUT, QUALIFICATION_PHASE_OUTPUT,
};

pub(super) const QUALIFICATION_OUTPUTS: [&str; 5] = [
    QUALIFICATION_CAMPAIGN_OUTPUT,
    QUALIFICATION_PHASE_OUTPUT,
    QUALIFICATION_CACHE_ENABLED_OUTPUT,
    QUALIFICATION_CACHE_WRITE_OUTPUT,
    QUALIFICATION_CACHE_DIRECTIVES_OUTPUT,
];
