use super::{ConsumerBinaryReleaseSpec, render_consumer_binary_release};
use crate::setup::MiseSetup;

fn install_argv(tools: &[&str]) -> Vec<String> {
    let mut command = vec![
        "mise".to_owned(),
        "--no-config".to_owned(),
        "--no-env".to_owned(),
        "--no-hooks".to_owned(),
        "install".to_owned(),
    ];
    command.extend(tools.iter().map(|tool| (*tool).to_owned()));
    command
}

fn exec_argv(tool: &str, program: &str, args: &[&str]) -> Vec<String> {
    let mut command = vec![
        "mise".to_owned(),
        "--no-config".to_owned(),
        "--no-env".to_owned(),
        "--no-hooks".to_owned(),
        "exec".to_owned(),
        tool.to_owned(),
        "--".to_owned(),
        program.to_owned(),
    ];
    command.extend(args.iter().map(|arg| (*arg).to_owned()));
    command
}

fn spec() -> ConsumerBinaryReleaseSpec {
    let linux_setup = MiseSetup {
        uses: "jdx/mise-action@2d8d4cafcbd33be2ea37d2b6f5ad595363d1f1ca".to_owned(),
        version: "2026.10.5".to_owned(),
        sha256: "8a223b5f8ca71100220a3e5bef259614c348e7b1d80e6b15c2a9c9aa3affe5e4".to_owned(),
    };
    ConsumerBinaryReleaseSpec {
        generator_version: "0.1.4".to_owned(),
        repository: "example/repo-scan".to_owned(),
        default_branch: "stable".to_owned(),
        manifest_path: "Cargo.toml".to_owned(),
        package: "repo-scan".to_owned(),
        bin: "repo-scan".to_owned(),
        linux_setup,
        macos_setup: MiseSetup {
            uses: "jdx/mise-action@2d8d4cafcbd33be2ea37d2b6f5ad595363d1f1ca".to_owned(),
            version: "2026.10.5".to_owned(),
            sha256: "41c4028257d30f5f5742c99247c461f417143d6c7301f167a0c185247c8f206e".to_owned(),
        },
        install_tools_argv: install_argv(&["rust@1.98.1", "gh@2.102.0"]),
        install_rust_argv: install_argv(&["rust@1.98.1"]),
        metadata_argv: exec_argv(
            "rust@1.98.1",
            "cargo",
            &[
                "metadata",
                "--format-version",
                "1",
                "--locked",
                "--no-deps",
                "--manifest-path",
                "Cargo.toml",
            ],
        ),
        add_target_argv: exec_argv(
            "rust@1.98.1",
            "rustup",
            &[
                "target",
                "add",
                "--toolchain",
                "1.98.1-aarch64-apple-darwin",
                "aarch64-apple-darwin",
            ],
        ),
        build_argv: exec_argv(
            "rust@1.98.1",
            "cargo",
            &[
                "build",
                "--release",
                "--locked",
                "--manifest-path",
                "Cargo.toml",
                "--package",
                "repo-scan",
                "--bin",
                "repo-scan",
                "--target",
                "aarch64-apple-darwin",
            ],
        ),
        gh_argv: exec_argv("gh@2.102.0", "gh", &[]),
    }
}

#[test]
fn renders_four_isolated_jobs_bound_to_exact_package_and_source() {
    let rendered = render_consumer_binary_release(&spec()).expect("workflow renders");
    let yaml = rendered.bytes;
    assert_eq!(rendered.path, ".github/workflows/binary-release.yml");
    assert!(yaml.starts_with("# Generated by Velnor Actions 0.1.4;"));
    assert!(yaml.contains("workflow_dispatch: {}"));
    assert!(!yaml.contains("inputs:"));
    assert!(yaml.contains("consumer-binary-release-${{ github.repository }}"));
    assert!(yaml.contains("ref:"));
    assert!(yaml.contains("needs.release-eligibility.outputs.source_sha"));
    assert!(yaml.contains("cargo metadata --format-version 1 --locked --no-deps"));
    assert!(yaml.contains("--package repo-scan --bin repo-scan --target aarch64-apple-darwin"));
    assert!(yaml.contains("PACKAGE_NAME-v$version"));
    assert!(
        yaml.contains("actions/attest-build-provenance@4d101475d8b20a2381f78447822ac1eab6504dd8")
    );
    assert!(yaml.contains("contents: write"));
    assert!(yaml.contains("attestations: write"));
    assert!(!yaml.contains("actions: write"));
    let build_start = yaml.find("  build-binary:").expect("build job");
    let attest_start = yaml.find("  attest-binary:").expect("attest job");
    let publish_start = yaml.find("  publish-binary:").expect("publish job");
    let eligibility_start = yaml
        .find("  release-eligibility:")
        .expect("eligibility job");
    let eligibility_job = &yaml[eligibility_start..build_start];
    let build_job = &yaml[build_start..attest_start];
    let attest_job = &yaml[attest_start..publish_start];
    let publish_job = &yaml[publish_start..];
    assert!(eligibility_job.contains("timeout-minutes: 75"));
    assert!(!build_job.contains("actions: write"));
    assert!(build_job.contains("contents: read"));
    assert!(!build_job.contains("contents: write"));
    assert!(!build_job.contains("id-token: write"));
    assert!(attest_job.contains("id-token: write"));
    assert!(attest_job.contains("attestations: write"));
    assert!(!attest_job.contains("contents: write"));
    assert!(publish_job.contains("contents: write"));
    assert!(publish_job.contains("timeout-minutes: 75"));
    assert!(publish_job.contains("actions: read"));
    assert!(publish_job.contains("attestations: read"));
    assert!(!publish_job.contains("id-token: write"));
    assert!(publish_job.contains("environment:"));
    assert!(publish_job.contains("name: consumer-binary-release"));
    assert!(publish_job.contains("IMMUTABILITY_READ_TOKEN"));
    assert!(yaml.contains("default_branch='stable'"));
    assert!(yaml.contains("refs/heads/$default_branch"));
    assert!(yaml.contains("repository='example/repo-scan'"));
    assert!(yaml.contains("binary-release.yml@refs/heads/$default_branch"));
    assert!(!yaml.contains("tailrocks/velnor-new"));
    assert!(!yaml.contains("--clobber"));
    assert!(yaml.contains("require_absent"));
    assert!(yaml.contains("assert_protected_environment"));
    assert!(yaml.contains("IMMUTABILITY_READ_TOKEN"));
    assert!(yaml.contains("consumer-binary-release"));
    assert!(yaml.contains("2026.10.5"));
    assert!(yaml.contains("aarch64-apple-darwin"));
    assert!(yaml.contains("CARGO_TARGET_DIR"));
    assert!(yaml.contains("required-features"));
    assert!(yaml.contains("isImmutable == true"));
    assert!(yaml.contains("gh release create"));
    assert!(yaml.contains("--verify-tag --draft --latest=false"));
}

#[test]
fn rejects_unsafe_consumer_identity_and_shell_values() {
    let mut unsafe_repo = spec();
    unsafe_repo.repository = "example/repo-scan;touch".to_owned();
    assert!(render_consumer_binary_release(&unsafe_repo).is_err());

    let mut unsafe_branch = spec();
    unsafe_branch.default_branch = "stable;touch /tmp/pwned".to_owned();
    assert!(render_consumer_binary_release(&unsafe_branch).is_err());

    let mut unsafe_target = spec();
    unsafe_target.bin = "repo-scan;touch".to_owned();
    assert!(render_consumer_binary_release(&unsafe_target).is_err());
}
