use super::{MARKER_PREFIX, OLD_MARKER_PREFIX, is_generated_marker_line};

#[test]
fn prefix_matches_rendered_first_line() {
    let first = "# Generated by Velnor Actions 0.1.0; edit .velnor/config.toml and regenerate.";
    assert!(first.starts_with(MARKER_PREFIX));
    assert_eq!(MARKER_PREFIX, "# Generated by Velnor Actions ");
}

#[test]
fn both_markers_recognized() {
    assert!(is_generated_marker_line(
        "# Generated by Velnor Actions 0.1.0; edit .velnor/config.toml and regenerate."
    ));
    assert!(is_generated_marker_line(
        "# Generated by velnor-actions 0.1.0 - DO NOT EDIT"
    ));
    assert_eq!(OLD_MARKER_PREFIX, "# Generated by velnor-actions ");
    assert!(!is_generated_marker_line("jobs:"));
    assert!(!is_generated_marker_line("# hand-written workflow"));
}
