[package]
name = "velnor-actions-orchestrator-merge-request-ports"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
autotests = false

[dependencies]
velnor-actions-orchestrator-core = { version = "=0.1.1", path = "../velnor-actions-orchestrator-core" }

[lints]
workspace = true

[[test]]
name = "velnor_orchestrator_merge_request_ports"
path = "tests/main.rs"
