[package]
name = "velnor-actions-orchestrator-plan"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
autotests = false

[dependencies]
velnor-actions-actionlint = { version = "=0.1.7", path = "../../adapters/velnor-actions-actionlint" }
velnor-actions-contract = { version = "=0.1.7", path = "../../core/velnor-actions-contract" }
velnor-actions-contract-config = { version = "=0.1.7", path = "../../core/velnor-actions-contract-config" }
velnor-actions-contract-planning = { version = "=0.1.7", path = "../../core/velnor-actions-contract-planning" }
velnor-actions-contract-workflow = { version = "=0.1.7", path = "../../core/velnor-actions-contract-workflow" }
velnor-actions-orchestrator-core = { version = "=0.1.7", path = "../velnor-actions-orchestrator-core" }
velnor-actions-orchestrator-discovery = { version = "=0.1.7", path = "../velnor-actions-orchestrator-discovery" }
velnor-actions-orchestrator-generation = { version = "=0.1.7", path = "../velnor-actions-orchestrator-generation" }
velnor-actions-orchestrator-provisioning = { version = "=0.1.7", path = "../velnor-actions-orchestrator-provisioning" }
velnor-actions-orchestrator-workflow-ir = { version = "=0.1.7", path = "../velnor-actions-orchestrator-workflow-ir" }
velnor-actions-rust = { version = "=0.1.7", path = "../../adapters/velnor-actions-rust" }
velnor-actions-rust-core = { version = "=0.1.7", path = "../../adapters/velnor-actions-rust-core" }
velnor-actions-tofu-core = { version = "=0.1.7", path = "../../adapters/velnor-actions-tofu-core" }
velnor-actions-workflow-jobs = { version = "=0.1.7", path = "../velnor-actions-workflow-jobs" }
velnor-actions-workflow-release = { version = "=0.1.7", path = "../velnor-actions-workflow-release" }
velnor-actions-workflow-renderer = { version = "=0.1.7", path = "../velnor-actions-workflow-renderer" }
velnor-actions-workflow-tree = { version = "=0.1.7", path = "../velnor-actions-workflow-tree" }

[dev-dependencies]
tempfile = { workspace = true }
velnor-actions-mise = { version = "=0.1.7", path = "../../adapters/velnor-actions-mise" }
velnor-actions-workflow-cache = { version = "=0.1.7", path = "../velnor-actions-workflow-cache" }

[lints]
workspace = true

[[test]]
name = "velnor_orchestrator_plan"
path = "tests/main.rs"
