//! Prepare/plan/generate integration cases over tempdir-built fixtures.

use std::fs;
use std::path::Path;

use tempfile::TempDir;
use velnor_actions_contract::StepKind;
use velnor_actions_orchestrator::decisions::{MetadataFailure, classify_metadata_failure};
use velnor_actions_orchestrator::{
    GenerateOptions, OrchestratorError, generate, prepare, render_staged_tree,
};

use crate::impl_common::{
    ReadonlyGuard, TestResult, config_with_branch, err_of, make_repo, plan_for, snapshot,
};

#[test]
fn prepare_plan_text_is_deterministic_and_write_free() -> TestResult {
    let repo = make_repo(config_with_branch())?;
    let root = repo.path();
    let before = snapshot(root)?;
    let prep = prepare(root)?;
    let first = plan_for(&prep)?;
    let second = plan_for(&prepare(root)?)?;
    assert_eq!(first, second, "plan text must be deterministic");
    assert_eq!(before, snapshot(root)?, "prepare plus plan must not write");
    assert!(first.contains("Velnor Actions plan"), "header:\n{first}");
    assert!(first.contains("Rust: selected"), "stack:\n{first}");
    assert!(first.contains("demo (Cargo.toml)"), "crate:\n{first}");
    assert!(
        first.contains(".github/workflows/ci.yml"),
        "paths:\n{first}"
    );
    assert!(first.contains("Runner: ubuntu-26.04"), "runner:\n{first}");
    let clean = !first.contains('{') && !first.contains('}');
    assert!(clean, "no JSON:\n{first}");
    Ok(())
}

#[test]
fn generate_preview_matches_in_place_and_preserves_repo() -> TestResult {
    let repo = make_repo(config_with_branch())?;
    let root = repo.path();
    let prep = prepare(root)?;
    let before = snapshot(root)?;
    let preview_parent = TempDir::new()?;
    let preview_root = preview_parent.path().join("preview");
    let preview_report = generate(
        &prep,
        &GenerateOptions {
            output_dir: Some(preview_root.clone()),
        },
    )?;
    assert_eq!(before, snapshot(root)?, "preview must not touch the repo");
    let inplace_report = generate(&prep, &GenerateOptions { output_dir: None })?;
    assert_eq!(preview_report.files_written, inplace_report.files_written);
    let expected_files = [
        ".github/AGENTS.md",
        ".github/actionlint.yaml",
        ".github/actions/u26/action.yml",
        ".github/actions/velnor-tool-seed/action.yml",
        ".github/actions/velnor-tools-cache-restore/action.yml",
        ".github/actions/velnor-tools-prelude-u26/action.yml",
        ".github/scripts/velnor-tools-cache-identity.sh",
        ".github/workflows/ci.yml",
    ];
    assert_eq!(preview_report.files_written, expected_files);
    for rel in &inplace_report.files_written {
        let preview_bytes = fs::read(preview_root.join(rel))?;
        let inplace_bytes = fs::read(root.join(rel))?;
        assert_eq!(preview_bytes, inplace_bytes, "parity for {rel}");
        let text = String::from_utf8(preview_bytes)?;
        let marked = text.starts_with("# Generated by Velnor Actions ");
        assert!(marked, "marker for {rel}");
    }
    let text = plan_for(&prep)?;
    for recommendation in &inplace_report.recommendations {
        assert!(
            text.contains(recommendation),
            "plan/generate parity for {recommendation}"
        );
    }
    Ok(())
}

#[test]
fn preview_refuses_unsafe_destinations() -> TestResult {
    let repo = make_repo(config_with_branch())?;
    let root = repo.path();
    let prep = prepare(root)?;
    let generate_preview = |dir: &Path| {
        generate(
            &prep,
            &GenerateOptions {
                output_dir: Some(dir.to_path_buf()),
            },
        )
    };
    let nonempty = TempDir::new()?;
    fs::write(nonempty.path().join("x.txt"), "x")?;
    let err = err_of(generate_preview(nonempty.path()), "non-empty refused")?;
    assert!(
        matches!(err, OrchestratorError::PreviewRefused { .. }),
        "got {err}"
    );
    for bad in [root.to_path_buf(), root.join("sub"), root.join(".github")] {
        let err = err_of(generate_preview(&bad), "inside refused")?;
        assert!(
            matches!(err, OrchestratorError::PreviewRefused { .. }),
            "got {err}"
        );
    }
    let parent = root
        .parent()
        .ok_or_else(|| std::io::Error::other("no parent"))?
        .to_path_buf();
    let err = err_of(generate_preview(&parent), "ancestor refused")?;
    assert!(
        matches!(err, OrchestratorError::PreviewRefused { .. }),
        "got {err}"
    );
    #[cfg(unix)]
    {
        let link_parent = TempDir::new()?;
        let link = link_parent.path().join("link");
        std::os::unix::fs::symlink(TempDir::new()?.path(), &link)?;
        let err = err_of(generate_preview(&link), "symlink refused")?;
        assert!(
            matches!(err, OrchestratorError::PreviewRefused { .. }),
            "got {err}"
        );
    }
    let before = snapshot(root)?;
    assert_eq!(before, snapshot(root)?, "refusals must not write");
    Ok(())
}

#[test]
fn atomic_replace_failure_preserves_old_tree() -> TestResult {
    let repo = make_repo(config_with_branch())?;
    let root = repo.path();
    let github = root.join(".github");
    fs::create_dir_all(github.join("workflows"))?;
    fs::write(github.join("workflows/old.yml"), "old: true\n")?;
    // A colliding backup path is skipped, not fatal: generation succeeds.
    let pid = std::process::id();
    fs::write(root.join(format!(".github.velnor-backup.{pid}")), "block")?;
    let prep = prepare(root)?;
    generate(&prep, &GenerateOptions { output_dir: None })?;
    assert!(
        !github.join("workflows/old.yml").exists(),
        "old tree replaced"
    );
    assert!(github.join("actionlint.yaml").exists(), "new tree present");

    // A read-only root blocks staging: the previous tree stays byte-identical.
    let repo = make_repo(config_with_branch())?;
    let root = repo.path();
    let github = root.join(".github");
    fs::create_dir_all(github.join("workflows"))?;
    fs::write(github.join("workflows/old.yml"), "old: true\n")?;
    let prep = prepare(root)?;
    let guard = ReadonlyGuard::lock(root)?;
    if fs::write(root.join(".probe"), "x").is_ok() {
        fs::remove_file(root.join(".probe"))?;
        drop(guard);
        return Ok(()); // Privileged runner: read-only bits do not bind.
    }
    let err = err_of(
        generate(&prep, &GenerateOptions { output_dir: None }),
        "must fail",
    )?;
    assert!(matches!(err, OrchestratorError::Io { .. }), "got {err}");
    drop(guard);
    assert_eq!(fs::read(github.join("workflows/old.yml"))?, b"old: true\n");
    assert!(!github.join("actionlint.yaml").exists(), "no partial write");
    Ok(())
}

#[test]
fn generated_workflow_has_always_on_lint_job() -> TestResult {
    for config in [
        config_with_branch(),
        "schema = 1\n[workflow]\ndefault_branch = \"testmain\"\n[stacks]\nignore = [\"rust\"]\n",
    ] {
        let repo = make_repo(config)?;
        let root = repo.path();
        let prep = prepare(root)?;
        let parent = TempDir::new()?;
        let preview_root = parent.path().join("preview");
        generate(
            &prep,
            &GenerateOptions {
                output_dir: Some(preview_root.clone()),
            },
        )?;
        let text = fs::read_to_string(preview_root.join(".github/workflows/ci.yml"))?;
        assert!(text.contains("actionlint:"), "lint job:\n{text}");
        assert!(text.contains("Actionlint"), "display name:\n{text}");
        assert!(
            text.contains(
                "mise --no-config --no-env --no-hooks exec actionlint@1.7.12 shellcheck@0.11.0 -- actionlint -color"
            ),
            "pinned actionlint run:\n{text}"
        );
        let (_, tail) = text
            .split_once("required:")
            .ok_or_else(|| std::io::Error::other("missing final job"))?;
        assert!(tail.contains("- actionlint"), "final needs lint:\n{text}");
        // Lint sorts first; its block ends at the plan job without `needs:`.
        let start = text
            .find("  actionlint:")
            .ok_or_else(|| std::io::Error::other("missing lint job"))?;
        let end = text[start..]
            .find("  plan:")
            .map_or(text.len(), |at| start + at);
        let lint = &text[start..end];
        assert!(!lint.contains("needs:"), "lint is independent:\n{text}");
    }
    Ok(())
}

/// Hand-written lock for a no-deps fixture package: hermetic, no network.
fn demo_lock(name: &str) -> String {
    format!("version = 4\n\n[[package]]\nname = \"{name}\"\nversion = \"0.1.0\"\n")
}

#[test]
fn plan_job_fetches_lockful_sources_before_generate_consumers() -> TestResult {
    let repo = make_repo(config_with_branch())?;
    let root = repo.path();
    fs::write(root.join("Cargo.lock"), demo_lock("demo"))?;
    let prep = prepare(root)?;
    let plan = prep
        .workflow
        .ir
        .jobs
        .get("plan")
        .ok_or_else(|| std::io::Error::other("missing plan job"))?;
    let names: Vec<&str> = plan.steps.iter().map(|step| step.name.as_str()).collect();
    let at = |name: &str| names.iter().position(|seen| *seen == name);
    // Cargo-only fixture uses the explicit shared sources restore/save pair.
    let (Some(prepare_at), Some(cache_at), Some(fetch_at), Some(write_at)) = (
        at("Prepare pinned tools"),
        at("Restore Cargo sources"),
        at("Fetch Cargo sources"),
        at("Write request"),
    ) else {
        return Err(format!("plan steps miss fetch ordering: {names:?}").into());
    };
    assert!(
        prepare_at < cache_at && cache_at < fetch_at && fetch_at < write_at,
        "cache<fetch<request: {names:?}"
    );
    let StepKind::Shell { run, env } = &plan.steps[fetch_at].kind else {
        return Err("fetch step must be a shell step".into());
    };
    assert_eq!(&run[..2], ["sh", "-c"]);
    for need in [
        "metadata --locked --offline",
        "cargo fetch --locked",
        "sources miss (source_missing)",
    ] {
        assert!(run[2].contains(need), "fetch script misses {need}");
    }
    assert!(
        env.get("MISE_CARGO_HOME").is_some_and(|v| !v.is_empty()),
        "writer fetches to owned homes"
    );
    let tree = render_staged_tree(&prep)?;
    let yaml = tree
        .get(".github/workflows/ci.yml")
        .ok_or_else(|| std::io::Error::other("missing workflow"))?;
    let fetch_pos = yaml
        .find("Fetch Cargo sources")
        .ok_or_else(|| std::io::Error::other("rendered fetch missing"))?;
    let check_pos = yaml
        .find("Check generated files")
        .ok_or_else(|| std::io::Error::other("rendered freshness missing"))?;
    let ordered = fetch_pos < check_pos;
    assert!(ordered, "fetch must precede Check generated files");
    Ok(())
}

#[test]
fn plan_job_omits_fetch_without_lockfile() -> TestResult {
    let repo = make_repo(config_with_branch())?;
    let prep = prepare(repo.path())?;
    let plan = prep
        .workflow
        .ir
        .jobs
        .get("plan")
        .ok_or_else(|| std::io::Error::other("missing plan job"))?;
    assert!(
        plan.steps
            .iter()
            .all(|step| !step.name.starts_with("Fetch Cargo sources")),
        "lockless workspaces have nothing to fetch"
    );
    Ok(())
}

#[test]
fn nested_lockful_workspace_gets_named_fetch() -> TestResult {
    let repo = make_repo(config_with_branch())?;
    let root = repo.path();
    fs::write(root.join("Cargo.lock"), demo_lock("demo"))?;
    fs::create_dir_all(root.join("nested/src"))?;
    fs::write(
        root.join("nested/Cargo.toml"),
        "[package]\nname = \"nested\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    )?;
    fs::write(root.join("nested/src/lib.rs"), "pub fn g() {}\n")?;
    fs::write(root.join("nested/Cargo.lock"), demo_lock("nested"))?;
    let prep = prepare(root)?;
    let plan = prep
        .workflow
        .ir
        .jobs
        .get("plan")
        .ok_or_else(|| std::io::Error::other("missing plan job"))?;
    let mut nested = plan.steps.iter().filter(|step| {
        matches!(&step.kind, StepKind::Shell { .. })
            && step.name == "Fetch Cargo sources (nested/Cargo.toml)"
    });
    let step = nested
        .next()
        .ok_or_else(|| std::io::Error::other("missing nested fetch"))?;
    assert!(nested.next().is_none(), "exactly one nested fetch");
    let StepKind::Shell { run, .. } = &step.kind else {
        return Err("fetch step must be a shell step".into());
    };
    assert!(
        run[2].contains("--manifest-path \"$GITHUB_WORKSPACE/nested/Cargo.toml\""),
        "nested fetch names its absolute manifest: {run:?}"
    );
    assert!(
        plan.steps
            .iter()
            .any(|step| step.name == "Fetch Cargo sources"),
        "root fetch still present"
    );
    Ok(())
}

#[test]
fn cold_registry_stderr_classifies_incomplete() {
    assert_eq!(
        classify_metadata_failure("error: failed to download anstyle-wincon v3.0.11"),
        MetadataFailure::Incomplete
    );
}

#[test]
fn prepare_lockless_with_deps_writes_nothing() -> TestResult {
    let repo = make_repo(config_with_branch())?;
    let root = repo.path();
    fs::write(
        root.join("Cargo.toml"),
        "[package]\nname = \"demo\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[dependencies]\nserde = \"1\"\nvelnor-poison-probe-nonexistent = \"1\"\n",
    )?;
    let before = snapshot(root)?;
    let prep = prepare(root)?;
    assert_eq!(before, snapshot(root)?, "prepare must not write");
    assert!(!root.join("Cargo.lock").exists(), "no lockfile synthesized");
    assert!(!prep.discovery.workspaces.is_empty(), "demo detected");
    let argv = velnor_actions_mise::MetadataDiscovery::new(root.join("Cargo.toml"))?.cargo_argv();
    let skips = argv.iter().any(|arg| arg == "--no-deps");
    assert!(skips, "discovery skips resolution");
    let probe = std::process::Command::new("cargo")
        .args([
            "metadata",
            "--format-version",
            "1",
            "--no-deps",
            "--manifest-path",
        ])
        .arg(root.join("Cargo.toml"))
        .env("CARGO_HTTP_PROXY", "http://127.0.0.1:9/")
        .env("CARGO_HTTPS_PROXY", "http://127.0.0.1:9/")
        .output()?;
    assert!(probe.status.success(), "no-deps never fetches");
    assert!(probe.stderr.is_empty(), "no index chatter");
    Ok(())
}
