//! Preview and in-place preservation parity.

use crate::impl_common::{TestResult, config_with_branch, make_repo, snapshot};
use std::fs;
use tempfile::TempDir;
use velnor_actions_orchestrator::{GenerateOptions, generate, prepare};

#[test]
fn generate_preview_matches_in_place_and_preserves_repo() -> TestResult {
    let repo = make_repo(config_with_branch())?;
    let root = repo.path();
    fs::create_dir_all(root.join(".github"))?;
    fs::write(root.join(".github/CODEOWNERS"), "* @owners\n")?;
    let prep = prepare(root)?;
    let before = snapshot(root)?;
    let preview_parent = TempDir::new()?;
    let preview_root = preview_parent.path().join("preview");
    let preview_report = generate(
        &prep,
        &GenerateOptions {
            output_dir: Some(preview_root.clone()),
        },
    )?;
    assert_eq!(before, snapshot(root)?, "preview must not touch the repo");
    let inplace_report = generate(&prep, &GenerateOptions { output_dir: None })?;
    assert_eq!(
        fs::read(preview_root.join(".github/CODEOWNERS"))?,
        fs::read(root.join(".github/CODEOWNERS"))?
    );
    assert_eq!(preview_report.files_written, inplace_report.files_written);
    let expected_files = [
        ".github/AGENTS.md",
        ".github/CLAUDE.md",
        ".github/actionlint.yaml",
        ".github/workflows/ci.yml",
    ];
    assert_eq!(preview_report.files_written, expected_files);
    for rel in &inplace_report.files_written {
        let preview_bytes = fs::read(preview_root.join(rel))?;
        let inplace_bytes = fs::read(root.join(rel))?;
        assert_eq!(preview_bytes, inplace_bytes, "parity for {rel}");
        let text = String::from_utf8(preview_bytes)?;
        let marked = text.starts_with("# Generated by Velnor Actions ");
        assert!(marked, "marker for {rel}");
    }
    assert_eq!(
        preview_report.recommendations,
        inplace_report.recommendations
    );
    Ok(())
}
