//! Init/config plus internal plan/merge integration cases.

use std::fs;

use tempfile::TempDir;
use velnor_actions_contract::FinalReport;
use velnor_actions_orchestrator::{
    OrchestratorError, init_config, merge_internal, plan_internal, prepare, resolve_root,
};

use crate::impl_common::{
    TestResult, config_with_branch, err_of, git, make_repo, passing_reports, plan_for_source_change,
};

#[test]
fn init_creates_sample_and_refuses_overwrite() -> TestResult {
    let repo = make_repo(config_with_branch())?;
    let root = repo.path();
    fs::remove_file(root.join(".velnor/config.toml"))?;
    let report = init_config(root)?;
    assert_eq!(report.created, vec![".velnor/config.toml"]);
    let text = fs::read_to_string(root.join(".velnor/config.toml"))?;
    assert!(
        text.starts_with("# Generated by velnor-actions "),
        "marker:\n{text}"
    );
    assert!(text.contains("\nschema = 1\n"), "schema:\n{text}");
    assert!(text.contains("CODEOWNERS"), "codeowners note:\n{text}");
    let err = err_of(init_config(root), "overwrite refused")?;
    assert!(
        matches!(err, OrchestratorError::OverwriteRefused { .. }),
        "got {err}"
    );
    let flat = TempDir::new()?;
    fs::write(flat.path().join(".velnor"), "file")?;
    let err = err_of(init_config(flat.path()), "file .velnor refused")?;
    assert!(
        matches!(err, OrchestratorError::UnsafePath { .. }),
        "got {err}"
    );
    Ok(())
}

#[test]
fn config_errors_name_file_and_key_path() -> TestResult {
    let repo = make_repo("schema = 2\n")?;
    let err = err_of(prepare(repo.path()), "bad schema")?;
    assert!(err.to_string().contains(".velnor/config.toml"), "got {err}");
    assert!(err.to_string().contains("schema"), "got {err}");

    let repo = make_repo("schema = 1\n[workflow]\nnope = true\n")?;
    let err = err_of(prepare(repo.path()), "unknown key")?;
    assert!(err.to_string().contains(".velnor/config.toml"), "got {err}");

    let repo = make_repo("schema = 1\n[workflow]\nmax_parallel_jobs = 0\n")?;
    let err = err_of(prepare(repo.path()), "bad value")?;
    assert!(
        err.to_string().contains("workflow.max_parallel_jobs"),
        "got {err}"
    );

    let repo = make_repo("schema = 1\n[workflow]\ngenerator_validation = \"candidate\"\n")?;
    let err = err_of(prepare(repo.path()), "consumer candidate rejected")?;
    assert!(
        err.to_string().contains("workflow.generator_validation"),
        "got {err}"
    );

    let missing = TempDir::new()?;
    let err = err_of(prepare(missing.path()), "missing config")?;
    assert!(
        matches!(err, OrchestratorError::ConfigMissing { .. }),
        "got {err}"
    );
    Ok(())
}

#[test]
fn default_branch_prefers_config_then_origin_head() -> TestResult {
    let origin = TempDir::new()?;
    git(&["init", "-b", "upstream-main"], origin.path())?;
    git(&["config", "user.email", "test@example.com"], origin.path())?;
    git(&["config", "user.name", "Test"], origin.path())?;
    git(&["config", "commit.gpgsign", "false"], origin.path())?;
    fs::write(origin.path().join("seed.txt"), "seed")?;
    git(&["add", "."], origin.path())?;
    git(&["commit", "-m", "seed"], origin.path())?;
    let parent = TempDir::new()?;
    let clone_path = parent.path().join("clone");
    git(
        &[
            "clone",
            &origin.path().display().to_string(),
            &clone_path.display().to_string(),
        ],
        parent.path(),
    )?;
    fs::create_dir_all(clone_path.join(".velnor"))?;
    fs::write(clone_path.join(".velnor/config.toml"), "schema = 1\n")?;
    fs::write(
        clone_path.join("Cargo.toml"),
        "[package]\nname = \"demo\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    )?;
    fs::create_dir_all(clone_path.join("src"))?;
    fs::write(clone_path.join("src/lib.rs"), "pub fn f() {}\n")?;
    let prep = prepare(&clone_path)?;
    assert_eq!(prep.default_branch, "upstream-main");

    fs::write(
        clone_path.join(".velnor/config.toml"),
        "schema = 1\n[workflow]\ndefault_branch = \"pinned\"\n",
    )?;
    let prep = prepare(&clone_path)?;
    assert_eq!(prep.default_branch, "pinned");
    Ok(())
}

#[test]
fn resolve_root_from_nested_subdir() -> TestResult {
    let repo = make_repo(config_with_branch())?;
    let nested = repo.path().join("a/b");
    fs::create_dir_all(&nested)?;
    let root = resolve_root(&nested)?;
    assert_eq!(root, repo.path().canonicalize()?);
    Ok(())
}

#[test]
fn velnor_policy_rejected_without_identity() -> TestResult {
    if std::env::var("GITHUB_REPOSITORY").is_ok() {
        return Ok(()); // Precondition: no ambient repository identity.
    }
    let repo = make_repo(
        "schema = 1\n[workflow]\npolicy = \"velnor-repository-v1\"\ndefault_branch = \"testmain\"\n",
    )?;
    let err = err_of(prepare(repo.path()), "identity rejected")?;
    assert!(
        matches!(err, OrchestratorError::IdentityRejected { .. }),
        "got {err}"
    );
    Ok(())
}

#[test]
fn internal_plan_selects_affected_and_validates() -> TestResult {
    let (_repo, plan) = plan_for_source_change()?;
    assert!(!plan.task_ids.is_empty(), "affected obligations selected");
    Ok(())
}

#[test]
fn internal_merge_aggregates_reports() -> TestResult {
    let (_repo, plan) = plan_for_source_change()?;
    let merge_request = serde_json::json!({
        "schema": 1,
        "run_key": "local",
        "plan": plan,
        "matrix": plan.matrix,
        "matrix_reports": [],
        "required_jobs": [{"job_id": "velnor-plan", "conclusion": "success"}],
    });
    let merged = merge_internal(&merge_request.to_string())?;
    let final_report: FinalReport = serde_json::from_str(&merged)?;
    final_report.validate()?;
    assert_eq!(
        final_report.status,
        velnor_actions_contract::FinalStatus::NotRun
    );

    let reports = passing_reports(&plan)?;
    let merge_request = serde_json::json!({
        "schema": 1,
        "run_key": "local",
        "plan": plan,
        "matrix": plan.matrix,
        "matrix_reports": reports,
        "required_jobs": [{"job_id": "velnor-plan", "conclusion": "success"}],
    });
    let merged = merge_internal(&merge_request.to_string())?;
    let final_report: FinalReport = serde_json::from_str(&merged)?;
    assert_eq!(
        final_report.status,
        velnor_actions_contract::FinalStatus::Passed
    );
    Ok(())
}

#[test]
fn internal_entrypoints_reject_bad_schema() -> TestResult {
    let err = err_of(plan_internal(r#"{"schema":2}"#), "plan schema rejected")?;
    assert!(
        matches!(err, OrchestratorError::Internal { .. }),
        "got {err}"
    );
    let err = err_of(merge_internal(r#"{"schema":2}"#), "merge schema rejected")?;
    assert!(
        matches!(err, OrchestratorError::Internal { .. }),
        "got {err}"
    );
    let err = err_of(plan_internal("not json"), "malformed rejected")?;
    assert!(
        matches!(err, OrchestratorError::Internal { .. }),
        "got {err}"
    );
    Ok(())
}
