//! Consumer binary release generation from repository inputs.

use std::fs;
use velnor_actions_orchestrator::{GenerateOptions, generate, prepare, render_staged_tree};

use crate::impl_common::{TestResult, anchor_repo, git, make_repo};

const CONSUMER: &str =
    "schema = 1\n[workflow]\npolicy = \"consumer-v1\"\ndefault_branch = \"testmain\"\n";
const ENABLED: &str = "schema = 1\n[workflow]\npolicy = \"consumer-v1\"\ndefault_branch = \"testmain\"\n[stacks.rust.binary_release]\nenabled = true\npackage = \"demo\"\nbin = \"demo\"\n";

fn binary_repo(config: &str) -> Result<tempfile::TempDir, Box<dyn std::error::Error>> {
    let repo = make_repo(config)?;
    fs::write(repo.path().join("src/main.rs"), "fn main() {}\n")?;
    fs::write(
        repo.path().join("Cargo.lock"),
        "version = 4\n\n[[package]]\nname = \"demo\"\nversion = \"0.1.0\"\n",
    )?;
    git(&["add", "Cargo.lock"], repo.path())?;
    anchor_repo(repo.path())?;
    Ok(repo)
}

#[test]
fn binary_release_is_default_off_and_generated_through_render_tree() -> TestResult {
    let disabled = binary_repo(CONSUMER)?;
    let disabled_tree = render_staged_tree(&prepare(disabled.path())?)?;
    assert!(
        disabled_tree
            .get(".github/workflows/binary-release.yml")
            .is_none()
    );

    let enabled = binary_repo(ENABLED)?;
    let prep = prepare(enabled.path())?;
    let tree = render_staged_tree(&prep)?;
    let workflow = tree
        .get(".github/workflows/binary-release.yml")
        .ok_or("enabled binary workflow missing from generated tree")?;
    assert!(workflow.starts_with("# Generated by Velnor Actions "));
    assert!(workflow.contains("name: Rust binary release"));
    assert!(workflow.contains("--package demo --bin demo --target aarch64-apple-darwin"));
    assert!(workflow.contains("contents: write"));
    assert!(workflow.contains("attestations: write"));
    assert!(workflow.contains("PACKAGE_NAME-v$version"));

    let preview = tempfile::TempDir::new()?;
    let report = generate(
        &prep,
        &GenerateOptions {
            output_dir: Some(preview.path().to_path_buf()),
        },
    )?;
    assert!(
        report
            .files_written
            .contains(&".github/workflows/binary-release.yml".to_owned())
    );
    assert_eq!(
        fs::read_to_string(preview.path().join(".github/workflows/binary-release.yml"))?,
        workflow
    );
    Ok(())
}

#[test]
fn binary_release_rejects_missing_binary_and_required_features() -> TestResult {
    let missing = binary_repo(&ENABLED.replace("bin = \"demo\"", "bin = \"missing\""))?;
    let err = render_staged_tree(&prepare(missing.path())?)
        .err()
        .ok_or("missing bin must be rejected")?;
    assert!(
        err.to_string()
            .contains("binary_release_target_not_discovered")
    );

    let required = binary_repo(ENABLED)?;
    fs::write(
        required.path().join("Cargo.toml"),
        "[package]\nname = \"demo\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[features]\noptional-bin = []\n\n[[bin]]\nname = \"demo\"\npath = \"src/main.rs\"\nrequired-features = [\"optional-bin\"]\n",
    )?;
    let err = render_staged_tree(&prepare(required.path())?)
        .err()
        .ok_or("required features are unsupported")?;
    assert!(err.to_string().contains("binary_required_features"));
    Ok(())
}

#[test]
fn binary_release_requires_a_present_tracked_lockfile() -> TestResult {
    let missing = binary_repo(ENABLED)?;
    fs::remove_file(missing.path().join("Cargo.lock"))?;
    let err = render_staged_tree(&prepare(missing.path())?)
        .err()
        .ok_or("missing lockfile must be rejected")?;
    assert!(err.to_string().contains("binary_release_lockfile_missing"));

    let untracked = binary_repo(ENABLED)?;
    git(&["rm", "--cached", "--", "Cargo.lock"], untracked.path())?;
    let err = render_staged_tree(&prepare(untracked.path())?)
        .err()
        .ok_or("untracked lockfile must be rejected")?;
    assert!(
        err.to_string()
            .contains("binary_release_lockfile_untracked")
    );
    Ok(())
}

#[test]
fn binary_release_rejects_dash_leading_workspace_path() -> TestResult {
    let config = ENABLED.replace(
        "[stacks.rust.binary_release]\nenabled = true\n",
        "[stacks.rust.binary_release]\nenabled = true\nmanifest_path = \"-workspace/Cargo.toml\"\n",
    );
    let repo = binary_repo(&config)?;
    let workspace = repo.path().join("-workspace");
    fs::create_dir_all(workspace.join("demo/src"))?;
    fs::write(
        workspace.join("Cargo.toml"),
        "[workspace]\nmembers = [\"demo\"]\nresolver = \"2\"\n",
    )?;
    fs::write(
        workspace.join("demo/Cargo.toml"),
        "[package]\nname = \"demo\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    )?;
    fs::write(workspace.join("demo/src/main.rs"), "fn main() {}\n")?;
    fs::write(
        workspace.join("Cargo.lock"),
        "version = 4\n\n[[package]]\nname = \"demo\"\nversion = \"0.1.0\"\n",
    )?;
    git(&["add", "--", "-workspace"], repo.path())?;

    let err = match prepare(repo.path()) {
        Ok(prep) => render_staged_tree(&prep)
            .err()
            .ok_or("dash-leading workspace path must be rejected")?,
        Err(err) => err,
    };
    assert!(err.to_string().contains("leading_dash_manifest"));
    Ok(())
}
