//! Repository-owned `.github` preservation through generate output paths.

use std::fs;

use tempfile::TempDir;
use velnor_actions_orchestrator::{
    ExecutionMode, GenerateOptions, generate, generate_dispatched, prepare,
};

use crate::impl_common::{TestResult, config_with_branch, git, make_repo};

#[test]
fn generate_preserves_unmanaged_github_content_and_retires_owned_files() -> TestResult {
    let repo = make_repo(config_with_branch())?;
    let root = repo.path();
    let github = root.join(".github");
    fs::create_dir_all(github.join("ISSUE_TEMPLATE/empty"))?;
    fs::create_dir_all(github.join("workflows"))?;
    fs::write(github.join("CODEOWNERS"), b"* @owners\0\xff")?;
    fs::write(github.join("ISSUE_TEMPLATE/bug.yml"), b"custom template\n")?;
    fs::write(github.join(".local-config"), b"private config\n")?;
    fs::write(github.join("actionlint.yaml"), b"stale generated output\n")?;
    fs::write(github.join("workflows/obsolete.yml"), b"stale workflow\n")?;
    fs::write(
        github.join("workflows/foundation-qualification.yml"),
        b"# Generated by Velnor Actions 0.1.0\nuses: tailrocks/velnor-new/foundation-qualification@8758d976a1b25eb387f48aa04ea86f57739b84cf\n",
    )?;
    fs::write(github.join("release-plz.toml"), b"stale release config\n")?;
    #[cfg(unix)]
    std::os::unix::fs::symlink("../missing", github.join("local-link"))?;

    let prep = prepare(root)?;
    let preview_parent = TempDir::new()?;
    let preview = preview_parent.path().join("preview");
    generate(
        &prep,
        &GenerateOptions {
            output_dir: Some(preview.clone()),
        },
    )?;
    generate(&prep, &GenerateOptions::default())?;

    for output in [&preview, root] {
        let output_github = output.join(".github");
        assert_eq!(
            fs::read(output_github.join("CODEOWNERS"))?,
            b"* @owners\0\xff"
        );
        assert_eq!(
            fs::read(output_github.join("ISSUE_TEMPLATE/bug.yml"))?,
            b"custom template\n"
        );
        assert_eq!(
            fs::read(output_github.join(".local-config"))?,
            b"private config\n"
        );
        assert!(output_github.join("ISSUE_TEMPLATE/empty").is_dir());
        assert!(output_github.join("actionlint.yaml").is_file());
        assert!(!output_github.join("workflows/obsolete.yml").exists());
        assert!(
            !output_github
                .join("workflows/foundation-qualification.yml")
                .exists(),
            "generation must retire a stale Foundation workflow"
        );
        assert!(!output_github.join("release-plz.toml").exists());
        #[cfg(unix)]
        {
            assert!(fs::symlink_metadata(output_github.join("local-link"))?.is_symlink());
            assert_eq!(
                fs::read_link(output_github.join("local-link"))?,
                std::path::Path::new("../missing")
            );
        }
    }
    assert!(
        fs::read_to_string(preview.join(".github/actionlint.yaml"))?
            .starts_with("# Generated by Velnor Actions ")
    );

    generate(&prep, &GenerateOptions::default())?;
    assert_eq!(fs::read(github.join("CODEOWNERS"))?, b"* @owners\0\xff");
    assert_eq!(fs::read(github.join(".local-config"))?, b"private config\n");
    assert!(!github.join("workflows/obsolete.yml").exists());
    assert!(
        !github
            .join("workflows/foundation-qualification.yml")
            .exists()
    );
    Ok(())
}

#[test]
fn dispatch_switch_preserves_custom_actions_and_removes_shared_outputs() -> TestResult {
    let config = "schema = 2\n[workflow]\nname = \"CI\"\ndefault_branch = \"testmain\"\n[execution]\ndefault_profile = \"hosted\"\nhosted_profile = \"hosted\"\nscale_set_profile = \"local\"\nmode = \"both\"\n[execution.profiles.hosted]\nkind = \"github-hosted\"\nlabel = \"ubuntu-26.04\"\nplatform = \"linux/amd64\"\n[execution.profiles.local]\nkind = \"github-scale-set\"\nname = \"ubuntu-26.04-scale-set\"\nlabels = [\"ubuntu-26.04-scale-set\", \"velnor\"]\nplatform = \"linux/amd64\"\n";
    let repo = make_repo(config)?;
    let root = repo.path();
    let github = root.join(".github");
    fs::create_dir_all(github.join("actions/custom"))?;
    fs::create_dir_all(github.join("actions/retired"))?;
    fs::write(
        github.join("actions/custom/action.yml"),
        b"name: Custom\ndescription: Local action\nruns:\n  using: composite\n  steps:\n    - shell: bash\n      run: echo custom\n",
    )?;
    fs::write(
        github.join("actions/custom/README.md"),
        b"hand-maintained action docs",
    )?;
    fs::write(
        github.join("actions/retired/action.yml"),
        b"# Generated by Velnor Actions 0.0.9; edit .velnor/config.toml and regenerate.\nold\n",
    )?;
    git(&["add", "."], root)?;
    git(&["commit", "-m", "fixture"], root)?;

    let prep = prepare(root)?;
    let both = generate_dispatched(
        &prep,
        &GenerateOptions::default(),
        Some(ExecutionMode::Both),
    )?;
    assert!(
        both.files_written
            .iter()
            .any(|path| path == ".github/actions/rust-demo/action.yml"),
        "both-mode shared action is generated: {:?}",
        both.files_written
    );
    assert_eq!(
        fs::read(github.join("actions/custom/action.yml"))?,
        b"name: Custom\ndescription: Local action\nruns:\n  using: composite\n  steps:\n    - shell: bash\n      run: echo custom\n"
    );
    assert!(!github.join("actions/retired").exists());

    let hosted = generate_dispatched(
        &prep,
        &GenerateOptions::default(),
        Some(ExecutionMode::Hosted),
    )?;
    // V2 tools-cache actions are always emitted with cache lanes (PR38);
    // only demo/lane-shared actions must stay out of hosted output.
    assert!(
        hosted.files_written.iter().all(|path| {
            [
                ".github/actions/velnor-tool-seed/action.yml",
                ".github/actions/u26/action.yml",
                ".github/actions/velnor-tools-cache-restore/action.yml",
                ".github/actions/velnor-tools-prelude-u26/action.yml",
            ]
            .contains(&path.as_str())
                || !path.starts_with(".github/actions/")
        }),
        "hosted output has no lane-shared action: {:?}",
        hosted.files_written
    );
    assert!(!github.join("actions/rust-demo/action.yml").exists());
    assert!(!github.join("actions/retired").exists());
    assert_eq!(
        fs::read(github.join("actions/custom/action.yml"))?,
        b"name: Custom\ndescription: Local action\nruns:\n  using: composite\n  steps:\n    - shell: bash\n      run: echo custom\n"
    );
    assert_eq!(
        fs::read(github.join("actions/custom/README.md"))?,
        b"hand-maintained action docs"
    );
    Ok(())
}

#[cfg(unix)]
#[test]
fn preview_preservation_failure_cleans_reservation_and_allows_retry() -> TestResult {
    use std::os::unix::net::UnixListener;

    let repo = make_repo(config_with_branch())?;
    let root = repo.path();
    let github = root.join(".github");
    fs::create_dir_all(&github)?;
    let socket_path = github.join("unsupported-socket");
    let socket = UnixListener::bind(&socket_path)?;
    let prep = prepare(root)?;
    let preview_parent = TempDir::new()?;
    let preview = preview_parent.path().join("preview");
    let options = GenerateOptions {
        output_dir: Some(preview.clone()),
    };

    let error = generate(&prep, &options).expect_err("unsupported entry must refuse preview");
    assert!(
        error.to_string().contains("unsupported_repository_entry"),
        "got {error}"
    );
    assert!(preview.is_dir());
    assert!(
        !preview.join(".github").exists(),
        "failed preview must remove its reserved output"
    );
    drop(socket);
    fs::remove_file(socket_path)?;

    generate(&prep, &options)?;
    assert!(preview.join(".github/workflows/ci.yml").is_file());
    Ok(())
}

#[cfg(target_os = "macos")]
#[test]
fn generate_preserves_dangling_symlink_permissions() -> TestResult {
    use std::os::unix::fs::{PermissionsExt, symlink};

    let repo = make_repo(config_with_branch())?;
    let root = repo.path();
    let github = root.join(".github");
    fs::create_dir_all(&github)?;

    let link = github.join("dangling-link");
    symlink("../missing-target", &link)?;
    rustix::fs::chmodat(
        rustix::fs::CWD,
        &link,
        rustix::fs::Mode::from_raw_mode(0o750),
        rustix::fs::AtFlags::SYMLINK_NOFOLLOW,
    )?;
    let expected_mode = fs::symlink_metadata(&link)?.permissions().mode() & 0o7777;
    assert_eq!(expected_mode, 0o750);

    let prep = prepare(root)?;
    let preview_parent = TempDir::new()?;
    let preview = preview_parent.path().join("preview");
    generate(
        &prep,
        &GenerateOptions {
            output_dir: Some(preview.clone()),
        },
    )?;
    generate(&prep, &GenerateOptions::default())?;

    for output in [&preview, root] {
        let copied = fs::symlink_metadata(output.join(".github/dangling-link"))?;
        assert!(copied.file_type().is_symlink());
        assert_eq!(copied.permissions().mode() & 0o7777, expected_mode);
    }
    Ok(())
}
