//! Init/config plus internal plan/merge integration cases.

use std::fs;

use tempfile::TempDir;
use velnor_actions_contract::{FinalReport, RunnerSelection};
use velnor_actions_orchestrator::{
    OrchestratorError, finalized_jobs, init_config, merge_internal, plan_internal, plan_text,
    prepare, resolve_root,
};

use crate::impl_common::{
    TestResult, config_with_branch, err_of, fixture_manifest_json, git, make_repo, passing_reports,
    plan_for_source_change, without_ambient_identity,
};
use crate::impl_merge::task_reports_for;

#[test]
fn init_creates_sample_and_refuses_overwrite() -> TestResult {
    let repo = make_repo(config_with_branch())?;
    let root = repo.path();
    fs::remove_file(root.join(".velnor/config.toml"))?;
    let report = init_config(root)?;
    assert_eq!(report.created, vec![".velnor/config.toml"]);
    let text = fs::read_to_string(root.join(".velnor/config.toml"))?;
    assert!(
        text.starts_with("# Generated by Velnor Actions "),
        "marker:\n{text}"
    );
    assert!(text.contains("\nschema = 1\n"), "schema:\n{text}");
    assert!(text.contains("CODEOWNERS"), "codeowners note:\n{text}");
    let err = err_of(init_config(root), "overwrite refused")?;
    assert!(
        matches!(err, OrchestratorError::OverwriteRefused { .. }),
        "got {err}"
    );
    let flat = TempDir::new()?;
    fs::write(flat.path().join(".velnor"), "file")?;
    let err = err_of(init_config(flat.path()), "file .velnor refused")?;
    assert!(
        matches!(err, OrchestratorError::UnsafePath { .. }),
        "got {err}"
    );
    Ok(())
}

#[test]
fn config_errors_name_file_and_key_path() -> TestResult {
    let repo = make_repo("schema = 99\n")?;
    let err = err_of(prepare(repo.path()), "bad schema")?;
    assert!(err.to_string().contains(".velnor/config.toml"), "got {err}");
    assert!(err.to_string().contains("schema"), "got {err}");

    let repo = make_repo("schema = 1\n[workflow]\nnope = true\n")?;
    let err = err_of(prepare(repo.path()), "unknown key")?;
    assert!(err.to_string().contains(".velnor/config.toml"), "got {err}");

    let repo = make_repo("schema = 1\n[workflow]\nmax_parallel_jobs = 0\n")?;
    let err = err_of(prepare(repo.path()), "bad value")?;
    assert!(
        err.to_string().contains("workflow.max_parallel_jobs"),
        "got {err}"
    );

    let repo = make_repo("schema = 1\n[workflow]\ngenerator_validation = \"candidate\"\n")?;
    let err = err_of(prepare(repo.path()), "consumer candidate rejected")?;
    assert!(
        err.to_string().contains("workflow.generator_validation"),
        "got {err}"
    );

    let missing = TempDir::new()?;
    let err = err_of(prepare(missing.path()), "missing config")?;
    assert!(
        matches!(err, OrchestratorError::ConfigMissing { .. }),
        "got {err}"
    );
    Ok(())
}

#[test]
fn default_branch_prefers_config_then_origin_head() -> TestResult {
    let origin = TempDir::new()?;
    git(&["init", "-b", "upstream-main"], origin.path())?;
    git(&["config", "user.email", "test@example.com"], origin.path())?;
    git(&["config", "user.name", "Test"], origin.path())?;
    git(&["config", "commit.gpgsign", "false"], origin.path())?;
    fs::write(origin.path().join("seed.txt"), "seed")?;
    git(&["add", "."], origin.path())?;
    git(&["commit", "-m", "seed"], origin.path())?;
    let parent = TempDir::new()?;
    let clone_path = parent.path().join("clone");
    git(
        &[
            "clone",
            &origin.path().display().to_string(),
            &clone_path.display().to_string(),
        ],
        parent.path(),
    )?;
    fs::create_dir_all(clone_path.join(".velnor"))?;
    fs::write(clone_path.join(".velnor/config.toml"), "schema = 1\n")?;
    fs::write(
        clone_path.join(".velnor/release-manifest.json"),
        fixture_manifest_json(),
    )?;
    fs::write(
        clone_path.join("Cargo.toml"),
        "[package]\nname = \"demo\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    )?;
    fs::create_dir_all(clone_path.join("src"))?;
    fs::write(clone_path.join("src/lib.rs"), "pub fn f() {}\n")?;
    let prep = prepare(&clone_path)?;
    assert_eq!(prep.default_branch, "upstream-main");

    fs::write(
        clone_path.join(".velnor/config.toml"),
        "schema = 1\n[workflow]\ndefault_branch = \"pinned\"\n",
    )?;
    let prep = prepare(&clone_path)?;
    assert_eq!(prep.default_branch, "pinned");
    Ok(())
}

#[test]
fn resolve_root_from_nested_subdir() -> TestResult {
    let repo = make_repo(config_with_branch())?;
    let nested = repo.path().join("a/b");
    fs::create_dir_all(&nested)?;
    let root = resolve_root(&nested)?;
    assert_eq!(root, repo.path().canonicalize()?);
    Ok(())
}

#[test]
fn velnor_policy_rejected_without_identity() -> TestResult {
    without_ambient_identity("velnor_policy_rejected_without_identity", || {
        let repo = make_repo(
            "schema = 1\n[workflow]\npolicy = \"velnor-repository-v1\"\ndefault_branch = \"testmain\"\n",
        )?;
        let err = err_of(prepare(repo.path()), "identity rejected")?;
        assert!(
            matches!(err, OrchestratorError::IdentityRejected { .. }),
            "got {err}"
        );
        Ok(())
    })
}

#[test]
fn internal_plan_selects_affected_and_validates() -> TestResult {
    let (_repo, plan) = plan_for_source_change()?;
    assert!(!plan.task_ids.is_empty(), "affected obligations selected");
    Ok(())
}

#[test]
fn internal_merge_aggregates_reports() -> TestResult {
    let (_repo, plan) = plan_for_source_change()?;
    let merge_request = serde_json::json!({
        "schema": 1,
        "run_key": "local",
        "actual_event": "pull_request",
        "plan": plan,
        "matrix": plan.matrix,
        "matrix_reports": [],
        "required_job_ids": ["plan"],
        "required_jobs": [{"job_id": "plan", "conclusion": "success"}],
    });
    let merged = merge_internal(&merge_request.to_string())?;
    let final_report: FinalReport = serde_json::from_str(&merged)?;
    final_report.validate()?;
    assert_eq!(
        final_report.status,
        velnor_actions_contract::FinalStatus::NotRun
    );

    let reports = passing_reports(&plan)?;
    let plan_value = serde_json::to_value(&plan)?;
    let task_files = task_reports_for(&plan_value, &serde_json::to_value(&reports)?);
    let merge_request = serde_json::json!({
        "schema": 1,
        "run_key": "local",
        "actual_event": "pull_request",
        "plan": plan,
        "matrix": plan.matrix,
        "matrix_reports": reports,
        "task_reports": task_files,
        "required_job_ids": ["plan"],
        "required_jobs": [{"job_id": "plan", "conclusion": "success"}],
    });
    let merged = merge_internal(&merge_request.to_string())?;
    let final_report: FinalReport = serde_json::from_str(&merged)?;
    assert_eq!(
        final_report.status,
        velnor_actions_contract::FinalStatus::Passed
    );
    Ok(())
}

#[test]
fn internal_entrypoints_reject_bad_schema() -> TestResult {
    let err = err_of(plan_internal(r#"{"schema":2}"#), "plan schema rejected")?;
    assert!(
        matches!(err, OrchestratorError::Internal { .. }),
        "got {err}"
    );
    let err = err_of(merge_internal(r#"{"schema":2}"#), "merge schema rejected")?;
    assert!(
        matches!(err, OrchestratorError::Internal { .. }),
        "got {err}"
    );
    let err = err_of(plan_internal("not json"), "malformed rejected")?;
    assert!(
        matches!(err, OrchestratorError::Internal { .. }),
        "got {err}"
    );
    Ok(())
}

#[test]
fn uncommented_init_sample_parses_with_overrides() -> TestResult {
    let repo = make_repo(config_with_branch())?;
    let root = repo.path();
    fs::remove_file(root.join(".velnor/config.toml"))?;
    init_config(root)?;
    let sample = fs::read_to_string(root.join(".velnor/config.toml"))?;
    let mut live = String::new();
    for line in sample.lines() {
        let uncommented = uncomment_sample_line(line);
        live.push_str(uncommented);
        live.push('\n');
    }
    assert!(
        live.contains("[actions.overrides]"),
        "sample must document overrides"
    );
    fs::write(root.join(".velnor/config.toml"), &live)?;
    let prep = prepare(root)?;
    assert_eq!(prep.config.actions.overrides.len(), 8);
    assert_eq!(
        prep.config.actions.overrides["actions/checkout"].version,
        "v7.0.1"
    );
    assert_eq!(prep.runner_label, "ubuntu-24.04");
    assert_eq!(prep.runner_selection, RunnerSelection::ConfigOverride);
    Ok(())
}

/// Uncomment a sample line when it carries TOML after the `#`.
fn uncomment_sample_line(line: &str) -> &str {
    let Some(rest) = line.strip_prefix('#') else {
        return line;
    };
    let code = rest.trim_start();
    if code.starts_with('[') || code.starts_with('"') || is_assignment(code) {
        code
    } else {
        line
    }
}

/// True for `key = value` sample lines (prose has no assignment).
fn is_assignment(code: &str) -> bool {
    let Some((key, _)) = code.split_once('=') else {
        return false;
    };
    !key.trim().is_empty()
        && key.trim().bytes().all(|b| {
            b.is_ascii_alphanumeric() || matches!(b, b'_' | b'.' | b'-' | b'"' | b'/' | b' ')
        })
        && !key.contains("  ")
}

#[test]
fn unknown_override_key_rejected_with_key_path() -> TestResult {
    let repo = make_repo(
        "schema = 1\n[workflow]\ndefault_branch = \"testmain\"\n[actions.overrides]\n\"bogus/action\" = { version = \"v1.2.3\", sha = \"3d3c42e5aac5ba805825da76410c181273ba90b1\" }\n",
    )?;
    let err = err_of(prepare(repo.path()), "unknown override rejected")?;
    assert!(
        err.to_string().contains("actions.overrides.bogus/action"),
        "got {err}"
    );
    // Policy-owned alint overrides reject like unknown keys (§2, GitHub Action defaults).
    let repo = make_repo(
        "schema = 1\n[workflow]\ndefault_branch = \"testmain\"\n[actions.overrides]\n\"asamarts/alint\" = { version = \"v0.16.1\", sha = \"9f9d34ba0eae3888299b9e570f43338b0e7f2cdb\" }\n",
    )?;
    let m = err_of(prepare(repo.path()), "alint override rejected")?.to_string();
    assert!(m.contains("actions.overrides.asamarts/alint"));
    Ok(())
}

#[test]
fn runner_label_exact_match_at_prepare() -> TestResult {
    for label in ["ubuntu-latest", "ubuntu-24.04-latest", "ubuntu-99.04"] {
        let repo = make_repo(&format!(
            "schema = 1\n[workflow]\ndefault_branch = \"testmain\"\nrunner_label = \"{label}\"\n"
        ))?;
        let err = err_of(prepare(repo.path()), "label rejected")?;
        assert!(
            err.to_string().contains("workflow.runner_label"),
            "{label}: got {err}"
        );
    }
    let repo = make_repo(
        "schema = 1\n[workflow]\ndefault_branch = \"testmain\"\nrunner_label = \"ubuntu-22.04\"\n",
    )?;
    let prep = prepare(repo.path())?;
    assert_eq!(prep.runner_label, "ubuntu-22.04");
    assert_eq!(prep.runner_selection, RunnerSelection::ConfigOverride);
    // Gate 8: `-arm` labels have no supported release target, so consumer
    // generation fails rather than embedding a wrong-architecture asset.
    for label in ["ubuntu-24.04-arm", "ubuntu-26.04-arm"] {
        let repo = make_repo(&format!(
            "schema = 1\n[workflow]\ndefault_branch = \"testmain\"\nrunner_label = \"{label}\"\n"
        ))?;
        let err = err_of(prepare(repo.path()), "arm label rejected")?;
        assert!(
            err.to_string().contains("unsupported_target_for_runner"),
            "{label}: got {err}"
        );
    }
    let repo = make_repo(config_with_branch())?;
    let prep = prepare(repo.path())?;
    assert_eq!(prep.runner_label, "ubuntu-26.04");
    assert_eq!(prep.runner_selection, RunnerSelection::LatestDefault);
    Ok(())
}

#[test]
fn uppercase_rust_name_rejected_with_key_path() -> TestResult {
    let repo = make_repo(
        "schema = 1\n[workflow]\ndefault_branch = \"testmain\"\n[stacks.rust]\nconfigurations = [{ name = \"Default\", features = [], target = \"host\" }]\n",
    )?;
    let err = err_of(prepare(repo.path()), "uppercase rejected")?;
    assert!(
        err.to_string().contains("stacks.rust.configurations.name"),
        "got {err}"
    );
    Ok(())
}

#[test]
fn branch_failure_hints_default_branch_setting() -> TestResult {
    let repo = make_repo("schema = 1\n")?;
    let err = err_of(prepare(repo.path()), "branch unresolvable")?;
    assert!(
        matches!(err, OrchestratorError::DefaultBranch { .. }),
        "got {err}"
    );
    assert!(
        err.to_string().contains("set workflow.default_branch"),
        "got {err}"
    );
    Ok(())
}

#[test]
fn plan_job_lines_come_from_finalized_jobs() -> TestResult {
    let repo = make_repo(config_with_branch())?;
    let prep = prepare(repo.path())?;
    let jobs = finalized_jobs(&prep)?;
    let text = plan_text(&prep, &jobs);
    assert!(!jobs.is_empty(), "finalized jobs exist");
    for (id, job) in &jobs {
        let line = format!("- {id} ({} steps)", job.steps.len());
        assert!(text.contains(&line), "missing {line}:\n{text}");
    }
    assert!(text.contains("1 Rust crate job"), "crate detail:\n{text}");
    Ok(())
}

#[test]
fn identity_ignores_decoy_lines_and_remotes() -> TestResult {
    without_ambient_identity("identity_ignores_decoy_lines_and_remotes", || {
        let config = "schema = 1\n[workflow]\npolicy = \"velnor-repository-v1\"\ndefault_branch = \"testmain\"\n";
        // Decoy: identity in another remote, in a non-url key, and in comments.
        let repo = make_repo(config)?;
        let git_config = repo.path().join(".git/config");
        let mut text = fs::read_to_string(&git_config)?;
        text.push_str(
        "[remote \"upstream\"]\n\turl = https://github.com/tailrocks/velnor-new.git\n[remote \"origin\"]\n\turl = https://example.com/other/repo.git\n\tpushurl = https://github.com/tailrocks/velnor-new.git\n# tailrocks/velnor-new\n",
    );
        fs::write(&git_config, text)?;
        let err = err_of(prepare(repo.path()), "decoys rejected")?;
        assert!(
            matches!(err, OrchestratorError::IdentityRejected { .. }),
            "got {err}"
        );
        // Positive control: origin url grants the identity.
        let repo = make_repo(config)?;
        let git_config = repo.path().join(".git/config");
        let mut text = fs::read_to_string(&git_config)?;
        text.push_str("[remote \"origin\"]\n\turl = https://github.com/tailrocks/velnor-new.git\n");
        fs::write(&git_config, text)?;
        prepare(repo.path())?;
        Ok(())
    })
}
