//! Oversized workflow generation fails before replacing in-place output.

use std::fs;
use std::path::{Path, PathBuf};

use velnor_actions_orchestrator::{GenerateOptions, generate, prepare};
use velnor_actions_workflow_renderer::MAX_WORKFLOW_BYTES;

use crate::impl_common::{TestResult, make_repo};

type Snapshot = Vec<(PathBuf, Vec<u8>)>;

#[test]
fn workflow_size_failure_preserves_existing_github_tree() -> TestResult {
    let name = "x".repeat(MAX_WORKFLOW_BYTES + 1);
    let config =
        format!("schema = 1\n[workflow]\nname = \"{name}\"\ndefault_branch = \"testmain\"\n");
    let repo = make_repo(&config)?;
    let root = repo.path();
    let old_workflow = root.join(".github/workflows/ci.yml");
    fs::create_dir_all(old_workflow.parent().expect("workflow parent"))?;
    fs::write(
        &old_workflow,
        b"# Generated by Velnor Actions 0.1.4; edit .velnor/config.toml and regenerate.\nold ci\n",
    )?;
    let old_policy = root.join(".github/policy.txt");
    fs::write(&old_policy, b"old policy\n")?;
    let before = snapshot_tree(&root.join(".github"))?;

    let prep = prepare(root)?;
    let error = generate(&prep, &GenerateOptions::default())
        .expect_err("oversized render must fail before replacement");
    assert!(error.to_string().contains("workflow_too_large"), "{error}");
    assert_eq!(snapshot_tree(&root.join(".github"))?, before);
    Ok(())
}

fn snapshot_tree(root: &Path) -> Result<Snapshot, Box<dyn std::error::Error>> {
    fn visit(root: &Path, current: &Path, files: &mut Snapshot) -> TestResult {
        for entry in fs::read_dir(current)? {
            let entry = entry?;
            let path = entry.path();
            if entry.file_type()?.is_dir() {
                visit(root, &path, files)?;
            } else {
                files.push((path.strip_prefix(root)?.to_path_buf(), fs::read(path)?));
            }
        }
        Ok(())
    }

    let mut files = Vec::new();
    visit(root, root, &mut files)?;
    files.sort_by(|left, right| left.0.cmp(&right.0));
    Ok(files)
}
