"""Offline real parser intent proofs; the source capability boundary is mocked."""
import copy
from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1] / "src"
SOURCE_ROOT = "/owned/source"
CONFIG = ('# Generated by Velnor Actions; do not edit.\n[workspace]\nrelease = false\n'
          'release_always = false\nsemver_check = true\npublish_no_verify = false\n'
          'publish_allow_dirty = false\ngit_tag_name = "custom/{{ package }}/{{ version }}"\n')


def config_package(name, enabled=True):
    return (f'\n[[package]]\nname = "{name}"\nrelease = {str(enabled).lower()}\n'
            'publish = true\ngit_only = false\n')


def require(condition, reason):
    if not condition:
        raise ValueError(reason)


def package(name, version="1.2.3", publish=None):
    return {"id": "path+file:///owned/source/" + name + "#" + version,
            "name": name, "version": version, "publish": publish,
            "manifest_path": SOURCE_ROOT + "/" + name + "/Cargo.toml"}


class SourceIntentDescriptorTest(unittest.TestCase):
    def setUp(self):
        self.ns = {"require": require, "ReconcileError": ValueError,
                   "__name__": "source_intent_test"}
        for name in ("release_prepare_notes.py", "release_source_intent_descriptor.py"):
            path = ROOT / name
            exec(compile(path.read_bytes(), str(path), "exec"), self.ns)
        self.cap = object()
        self.calls = []
        self.files = {"demo/CHANGELOG.md": b"## 1.2.3\n\nLatest.\n## 1.2.2\nOld."}
        self.ns["authenticated_source_file"] = self.read_source
        self.metadata = {"workspace_root": SOURCE_ROOT, "packages": [package("demo")],
                         "workspace_members": [package("demo")["id"]]}
        self.policy = {"approved": {"packages": {"demo": "1.2.3"},
                                    "tags": {"demo": "custom/demo/1.2.3"}},
                       "release_config": CONFIG + config_package("demo")}

    def read_source(self, cap, path, limit):
        require(cap is self.cap, "source_capability")
        self.assertEqual(limit, 1024 * 1024)
        self.calls.append(path)
        return self.files[path]

    def derive(self, cap=None, root=SOURCE_ROOT):
        return self.ns["forge_release_intent"](
            self.metadata, self.cap if cap is None else cap, self.policy, root)

    def add_member(self, name, enabled, publish=False):
        entry = package(name, publish=publish)
        self.metadata["packages"].append(entry)
        self.metadata["workspace_members"].append(entry["id"])
        self.policy["release_config"] += config_package(name, enabled)

    def test_single_defaults_exact_tag_body_and_closed_fields(self):
        self.assertEqual(self.derive(), {"demo": {
            "tag_name": "custom/demo/1.2.3", "body": "Latest.", "name": "v1.2.3",
            "draft": False, "prerelease": False}})
        self.assertEqual(self.calls, ["demo/CHANGELOG.md"])

    def test_full_enabled_workspace_cardinality_ignores_publishability(self):
        self.add_member("private", True, publish=False)
        self.assertEqual(self.derive()["demo"]["name"], "demo-v1.2.3")
        self.assertEqual(self.calls, ["demo/CHANGELOG.md"])

    def test_disabled_member_and_nonmember_never_change_cardinality(self):
        self.add_member("disabled", False, publish=True)
        self.metadata["packages"].append(package("dependency"))
        self.assertEqual(self.derive()["demo"]["name"], "v1.2.3")

    def test_implicit_workspace_disabled_member_never_changes_cardinality(self):
        member = package("implicit", publish=True)
        self.metadata["packages"].append(member)
        self.metadata["workspace_members"].append(member["id"])
        self.assertEqual(self.derive()["demo"]["name"], "v1.2.3")

    def test_all_selected_use_same_workspace_cardinality(self):
        self.add_member("other", True)
        self.policy["approved"]["packages"]["other"] = "1.2.3"
        self.policy["approved"]["tags"]["other"] = "custom/other/1.2.3"
        self.files["other/CHANGELOG.md"] = b"## 1.2.3\nOther."
        result = self.derive()
        self.assertEqual(result["demo"]["name"], "demo-v1.2.3")
        self.assertEqual(result["other"]["name"], "other-v1.2.3")

    def test_prerelease_and_build_metadata(self):
        for version, prerelease in (("1.2.3-rc.1+build", True), ("1.2.3+has-dash", False)):
            self.metadata["packages"][0]["version"] = version
            self.policy["approved"]["packages"]["demo"] = version
            self.policy["approved"]["tags"]["demo"] = "custom/demo/" + version
            self.files["demo/CHANGELOG.md"] = f"## {version}\nNotes.".encode()
            self.assertIs(self.derive()["demo"]["prerelease"], prerelease)

    def test_real_parser_latest_notes_preserve_fences_links_crlf(self):
        body = "### Added\r\n```markdown\r\n## 9.0.0\r\n```\r\n[ref]: url"
        self.files["demo/CHANGELOG.md"] = (
            "## Unreleased\r\n\r\n## [1.2.3](url)\r\n\r\n" + body +
            "\r\n\r\n## 1.2.2\r\nOld.").encode()
        self.assertEqual(self.derive()["demo"]["body"], body)

    def test_real_parser_setext_empty_and_wrong_latest(self):
        for raw, expected in ((b"Version [1.2.3]\n---\n\nNotes.", "Notes."),
                              (b"## 1.2.3", "")):
            self.files["demo/CHANGELOG.md"] = raw
            self.assertEqual(self.derive()["demo"]["body"], expected)
        for raw in (b"## 1.2.4\nWrong.", b"## 1.2.3\nNul\0",
                    b"## 1.2.3\nOne\n## 1.2.3\nDuplicate"):
            self.files["demo/CHANGELOG.md"] = raw
            with self.assertRaises(ValueError):
                self.derive()

    def test_capability_required_and_archive_source_claims_ignored(self):
        self.metadata["packages"][0].update(
            forge_release={"body": "Forged"}, source_sha="claimed", vcs="claimed")
        self.assertEqual(self.derive()["demo"]["body"], "Latest.")
        with self.assertRaisesRegex(ValueError, "source_capability"):
            self.derive(cap={"source_sha": "claimed", "blobs": self.files})

    def test_paths_reject_outside_aliases_and_git_without_reads(self):
        for path in ("/outside/Cargo.toml", "/owned/source/demo/../Cargo.toml",
                     "/owned/source//demo/Cargo.toml", "/owned/source/./Cargo.toml",
                     "/owned/source/.GIT/Cargo.toml", "demo/Cargo.toml",
                     "/owned/source/demo\\Cargo.toml", "/owned/source/x\0/Cargo.toml"):
            self.metadata["packages"][0]["manifest_path"] = path
            with self.subTest(path=path), self.assertRaises(ValueError):
                self.derive()
        self.assertEqual(self.calls, [])

    def test_root_data_rejects_alias_and_wrong_binding(self):
        for root in ("/", "/owned/./source", "/owned/source/", "/another/source"):
            with self.subTest(root=root), self.assertRaises(ValueError):
                self.derive(root=root)
        self.assertEqual(self.calls, [])

    def test_workspace_and_config_fail_closed_before_reads(self):
        original_metadata, original_policy = copy.deepcopy(self.metadata), copy.deepcopy(self.policy)
        mutations = [lambda: self.metadata.update(workspace_members=[]),
                     lambda: self.metadata.update(workspace_members=["missing"]),
                     lambda: self.metadata["workspace_members"].append(
                         self.metadata["workspace_members"][0]),
                     lambda: self.metadata["packages"].append(self.metadata["packages"][0]),
                     lambda: self.metadata["packages"][0].update(version="9.0.0"),
                     lambda: self.policy.update(release_config="[workspace]\nrelease=true"),
                     lambda: self.policy.update(release_config="[workspace]\nrelease=false"),
                     lambda: self.policy.update(release_config=self.policy["release_config"] +
                                               '[[package]]\nname="missing"\nrelease=true'),
                     lambda: self.policy["approved"]["tags"].clear(),
                     lambda: self.policy.update(extra="candidate")]
        for mutate in mutations:
            self.metadata, self.policy = copy.deepcopy(original_metadata), copy.deepcopy(original_policy)
            mutate()
            with self.assertRaises(ValueError):
                self.derive()
        self.assertEqual(self.calls, [])

    def test_source_bytes_and_descriptor_size_bounds(self):
        for raw in ("## 1.2.3", b"x" * (1024 * 1024 + 1), b"## 1.2.3\n" + b"x" * 65537):
            self.files["demo/CHANGELOG.md"] = raw
            with self.assertRaises(ValueError):
                self.derive()

    def test_closed_compiled_config_rejects_fields_types_and_unsafe_switches(self):
        original = self.policy["release_config"]
        malformed = [original + 'unknown = true\n',
                     original.replace('[workspace]', 'unknown = true\n[workspace]'),
                     original.replace('git_tag_name =', 'git_release_name = "forged"\ngit_tag_name ='),
                     original.replace('release_always = false', 'release_always = true'),
                     original.replace('semver_check = true', 'semver_check = false'),
                     original.replace('publish_no_verify = false', 'publish_no_verify = true'),
                     original.replace('publish_allow_dirty = false', 'publish_allow_dirty = true'),
                     original.replace('release = true', 'release = 1'),
                     original.replace('publish = true', 'publish = 1'),
                     original.replace('git_only = false', 'git_only = true'),
                     original + 'version_group = false\n',
                     original + 'version_group = "-invalid"\n',
                     original.replace('git_tag_name = "custom/{{ package }}/{{ version }}"',
                                      'git_tag_name = false'),
                     original.replace('{{ version }}', '{{ version }}{{ unknown }}'),
                     original.replace('{{ version }}', '{% command %}{{ version }}'),
                     original.replace('{{ package }}', 'demo')]
        for config in malformed:
            self.policy["release_config"] = config
            with self.subTest(config=config), self.assertRaises(ValueError):
                self.derive()
        self.assertEqual(self.calls, [])

    def test_compiled_tag_binding_and_optional_version_group(self):
        self.policy["release_config"] += 'version_group = "Group.1"\n'
        self.assertEqual(self.derive()["demo"]["tag_name"], "custom/demo/1.2.3")
        self.calls.clear()
        self.policy["approved"]["tags"]["demo"] = "forged-tag"
        with self.assertRaisesRegex(ValueError, "source_intent_selected_identity"):
            self.derive()
        self.assertEqual(self.calls, [])

    def test_semver_rejects_leading_zero_and_overflow_before_reads(self):
        for version in ("01.2.3", "1.2.3-01", "1.2.3-", "18446744073709551616.2.3"):
            self.metadata["packages"][0]["version"] = version
            self.policy["approved"]["packages"]["demo"] = version
            with self.assertRaises(ValueError):
                self.derive()
        self.assertEqual(self.calls, [])


if __name__ == "__main__":
    unittest.main()
