//! Dynamic profiles require both compiled descriptor authority and a marker.

use std::fs;
use std::path::Path;

use crate::desktop_delivery::desktop_helper_files;
use velnor_actions_contract::config::{
    NativeDesktopProfile, NativeDesktopTarget, RustFfiProfile, SwiftInputs,
};
use velnor_actions_contract::generated_source;
use velnor_actions_workflow_renderer::render::RenderedTree;

use super::{TestResult, copy_repository_content, replacement, swap_directories, write_tree};

const PROFILES: &str = "velnor/desktop/workloads";

fn profile() -> NativeDesktopProfile {
    NativeDesktopProfile {
        ffi: RustFfiProfile {
            manifest_path: "bridge/Cargo.toml".into(),
            package: "example-bridge".into(),
            profile: "release".into(),
            features: Vec::new(),
            framework_name: "ExampleCore".into(),
            module_name: "ExampleFFI".into(),
            static_library: "libexample_bridge.a".into(),
            bindings_path: "generated/bindings".into(),
            xcframework_path: "build/Example.xcframework".into(),
        },
        native_root: "client".into(),
        target: NativeDesktopTarget::AppleArm64,
        deployment_target: "26.0".into(),
        apple: None,
        checks: None,
    }
}

fn emitted_profile(name: &str, version: &str) -> Result<String, Box<dyn std::error::Error>> {
    let path = format!(".github/{PROFILES}/{name}.json");
    let files = desktop_helper_files(&profile(), &path, version)?;
    Ok(files
        .into_iter()
        .find(|file| file.path == path)
        .ok_or("profile not emitted")?
        .bytes)
}

fn generation(root: &Path, name: Option<&str>) -> TestResult {
    let staging = tempfile::tempdir_in(root)?;
    let staged = staging.path().join(".github");
    copy_repository_content(&root.join(".github"), &staged)?;
    let files = match name {
        Some(name) => desktop_helper_files(
            &profile(),
            &format!(".github/{PROFILES}/{name}.json"),
            "0.2.0",
        )?,
        None => Vec::new(),
    };
    write_tree(
        &staged,
        &RenderedTree {
            files,
            symlinks: Vec::new(),
        },
    )?;
    assert!(swap_directories(root, &root.join(".github"), &staged)?.is_empty());
    Ok(())
}

#[test]
fn profile_rename_repeat_and_removal_preserve_unmarked_human_siblings() -> TestResult {
    let root = tempfile::tempdir()?;
    let directory = root.path().join(".github").join(PROFILES);
    fs::create_dir_all(&directory)?;
    fs::write(directory.join("old.json"), emitted_profile("old", "0.0.1")?)?;
    fs::write(directory.join("human.json"), b"human data\0\xff")?;
    let typed_human = serde_json::to_vec(&profile())?;
    fs::write(directory.join("typed-human.json"), &typed_human)?;
    for name in [Some("renamed"), Some("renamed"), None] {
        generation(root.path(), name)?;
        assert!(!directory.join("old.json").exists());
        assert_eq!(directory.join("renamed.json").exists(), name.is_some());
        assert_eq!(fs::read(directory.join("human.json"))?, b"human data\0\xff");
        assert_eq!(fs::read(directory.join("typed-human.json"))?, typed_human);
    }
    Ok(())
}

#[test]
fn current_profile_destination_collision_cannot_overwrite_unmarked_human_file() -> TestResult {
    let root = tempfile::tempdir()?;
    let directory = root.path().join(".github").join(PROFILES);
    fs::create_dir_all(&directory)?;
    let human = directory.join("native.json");
    fs::write(&human, b"human profile bytes")?;
    let error =
        generation(root.path(), Some("native")).expect_err("unmarked destination collision");
    assert!(error.to_string().contains("overwrite"), "{error}");
    assert_eq!(fs::read(human)?, b"human profile bytes");
    assert!(
        !root
            .path()
            .join(".github/velnor/desktop/desktop_native.py")
            .exists()
    );
    Ok(())
}

#[test]
fn malformed_marked_and_unknown_descriptor_profiles_refuse_before_swap() -> TestResult {
    let mut unknown = serde_json::to_value(SwiftInputs::from(&profile()))?;
    unknown["unknown_future_schema"] = serde_json::json!(true);
    let mut invalid = serde_json::to_value(SwiftInputs::from(&profile()))?;
    invalid["ffi"]["bindings_path"] = serde_json::json!("../foreign/Cargo.toml");
    let duplicate = serde_json::to_string(&SwiftInputs::from(&profile()))?.replace(
        "\"native_root\":\"client\"",
        "\"native_root\":\"client\",\"native_root\":\"other\"",
    );
    for content in [
        "# Generated by Velnor Actions 0.0.1\n{}\n".to_owned(),
        generated_source("0.0.1", "{}\n")?,
        generated_source("0.0.1", &serde_json::to_string(&unknown)?)?,
        generated_source("0.0.1", &serde_json::to_string(&invalid)?)?,
        generated_source("0.0.1", &duplicate)?,
        generated_source(
            "0.0.1",
            &"x".repeat(usize::try_from(crate::safe_read::MAX_REPO_FILE_BYTES)? + 1),
        )?,
    ] {
        let root = tempfile::tempdir()?;
        let directory = root.path().join(".github").join(PROFILES);
        fs::create_dir_all(&directory)?;
        let path = directory.join("stale.json");
        fs::write(&path, &content)?;
        let error = replacement(root.path()).expect_err("ambiguous marked ownership refuses");
        assert!(
            error
                .to_string()
                .contains("generated_profile_ownership_refused"),
            "{error}"
        );
        assert_eq!(fs::read_to_string(path)?, content);
        assert!(!root.path().join(".github/workflows").exists());
    }
    Ok(())
}

#[test]
fn projected_schema_and_canonical_serialization_are_required() -> TestResult {
    for (body, diagnostic) in [
        (serde_json::to_string(&profile())?, "invalid_profile"),
        (
            serde_json::to_string(&SwiftInputs::from(&profile()))?,
            "noncanonical_profile",
        ),
    ] {
        let root = tempfile::tempdir()?;
        let directory = root.path().join(".github").join(PROFILES);
        fs::create_dir_all(&directory)?;
        let path = directory.join("stale.json");
        let content = generated_source("0.0.1", &format!("{body}\n"))?;
        fs::write(&path, &content)?;
        let error = replacement(root.path()).expect_err("noncanonical ownership proof");
        assert!(error.to_string().contains(diagnostic), "{error}");
        assert_eq!(fs::read_to_string(path)?, content);
    }
    Ok(())
}

#[test]
fn descriptor_size_bound_includes_the_marker() -> TestResult {
    let bound = usize::try_from(crate::safe_read::MAX_REPO_FILE_BYTES)?;
    let mut content = emitted_profile("boundary", "0.0.1")?;
    content.push_str(
        &" ".repeat(
            bound
                .checked_sub(content.len())
                .ok_or("profile too large")?,
        ),
    );
    for extra in [false, true] {
        let root = tempfile::tempdir()?;
        let directory = root.path().join(".github").join(PROFILES);
        fs::create_dir_all(&directory)?;
        let path = directory.join("boundary.json");
        let bytes = if extra {
            format!("{content} ")
        } else {
            content.clone()
        };
        fs::write(&path, &bytes)?;
        if extra {
            let error = replacement(root.path()).expect_err("whole file exceeds bound");
            assert!(error.to_string().contains("oversize"), "{error}");
            assert_eq!(fs::read_to_string(path)?, bytes);
        } else {
            let error = replacement(root.path()).expect_err("noncanonical profile refuses");
            assert!(
                error.to_string().contains("invalid_profile")
                    || error.to_string().contains("noncanonical_profile"),
                "{error}"
            );
            assert_eq!(fs::read_to_string(path)?, bytes);
        }
    }
    Ok(())
}

#[test]
fn marked_profiles_outside_exact_namespace_remain_repository_owned() -> TestResult {
    let root = tempfile::tempdir()?;
    let github = root.path().join(".github");
    let content = emitted_profile("original", "0.0.1")?;
    for path in [
        "velnor/custom.json",
        "velnor/desktop/workloads/nested/custom.json",
        "velnor/desktop/workloads/human.json/child.json",
        "velnor/desktop/workloads/custom.txt",
    ] {
        let file = github.join(path);
        fs::create_dir_all(file.parent().ok_or("missing parent")?)?;
        fs::write(file, &content)?;
    }
    replacement(root.path())?;
    for path in [
        "velnor/custom.json",
        "velnor/desktop/workloads/nested/custom.json",
        "velnor/desktop/workloads/human.json/child.json",
        "velnor/desktop/workloads/custom.txt",
    ] {
        assert_eq!(fs::read_to_string(github.join(path))?, content);
    }
    Ok(())
}

#[cfg(unix)]
#[test]
fn dynamic_profile_symlink_refuses_without_reading_or_deleting_its_target() -> TestResult {
    let root = tempfile::tempdir()?;
    let outside = tempfile::tempdir()?;
    let content = emitted_profile("external", "0.0.1")?;
    let external = outside.path().join("external.json");
    fs::write(&external, &content)?;
    let directory = root.path().join(".github").join(PROFILES);
    fs::create_dir_all(&directory)?;
    let link = directory.join("linked.json");
    std::os::unix::fs::symlink(&external, &link)?;
    assert!(replacement(root.path()).is_err());
    assert!(fs::symlink_metadata(&link)?.is_symlink());
    assert_eq!(fs::read_link(link)?, external);
    assert_eq!(fs::read_to_string(external)?, content);
    assert!(!root.path().join(".github/workflows").exists());
    Ok(())
}
