//! Reserved shared-script ownership and replacement regressions.

use std::fs;
use std::path::Path;

use super::{TestResult, replace_with_tree};
use crate::OrchestratorError;
use velnor_actions_workflow_renderer::render::{RenderedFile, RenderedTree};

const MARKER: &str =
    "# Generated by Velnor Actions 0.1.0; edit .velnor/config.toml and regenerate.\n";
const SCRIPT_BODY: &str = "#!/bin/sh\nprintf 'managed\\n'\n";
const OLD_SCRIPT_BODY: &str = "#!/bin/sh\nprintf 'old\\n'\n";

fn shared_script_path(body: &str) -> String {
    let digest = velnor_actions_contract::digest_b3(format!("sh\0{body}").as_bytes());
    format!(".github/scripts/velnor-shared/sh-{digest}.sh")
}

fn generated_tree(script_body: Option<&str>) -> RenderedTree {
    let mut files = vec![RenderedFile {
        path: ".github/workflows/ci.yml".to_owned(),
        bytes: "new workflow\n".to_owned(),
    }];
    if let Some(body) = script_body {
        files.push(RenderedFile {
            path: shared_script_path(body),
            bytes: format!("{MARKER}{body}"),
        });
    }
    RenderedTree {
        files,
        symlinks: Vec::new(),
    }
}

fn replace(root: &Path, tree: &RenderedTree) -> TestResult {
    replace_with_tree(root, tree, false)
}

#[test]
fn marked_script_repeats_and_retires_while_unmarked_file_survives() -> TestResult {
    let root = tempfile::tempdir()?;
    let github = root.path().join(".github");
    let script = github.join(
        shared_script_path(SCRIPT_BODY)
            .strip_prefix(".github/")
            .ok_or("shared path")?,
    );
    let stale_script = github.join(
        shared_script_path(OLD_SCRIPT_BODY)
            .strip_prefix(".github/")
            .ok_or("stale shared path")?,
    );
    let unmarked = github.join("scripts/velnor-shared/local-helper.sh");
    fs::create_dir_all(script.parent().ok_or("script parent")?)?;
    fs::write(&stale_script, format!("{MARKER}{OLD_SCRIPT_BODY}"))?;
    fs::write(&unmarked, b"# Maintained by this repository\n")?;

    let tree = generated_tree(Some(SCRIPT_BODY));
    replace(root.path(), &tree)?;
    let expected = format!("{MARKER}{SCRIPT_BODY}");
    assert_eq!(fs::read(&script)?, expected.as_bytes());
    assert!(
        !stale_script.exists(),
        "stale content-addressed script survives"
    );
    let first = fs::read(&script)?;
    replace(root.path(), &tree)?;
    assert_eq!(fs::read(&script)?, first);
    assert_eq!(fs::read(&unmarked)?, b"# Maintained by this repository\n");

    replace(root.path(), &generated_tree(None))?;
    assert!(!script.exists(), "stale marked shared script survives");
    assert!(!stale_script.exists(), "older marked script survives");
    assert_eq!(fs::read(&unmarked)?, b"# Maintained by this repository\n");
    Ok(())
}

#[test]
fn unmarked_active_script_is_preserved_and_collision_refused() -> TestResult {
    let root = tempfile::tempdir()?;
    let github = root.path().join(".github");
    let script = github.join(
        shared_script_path(SCRIPT_BODY)
            .strip_prefix(".github/")
            .ok_or("shared path")?,
    );
    let user_bytes = b"#!/bin/sh\nprintf 'repository-owned\\n'\n";
    fs::create_dir_all(script.parent().ok_or("script parent")?)?;
    fs::write(&script, user_bytes)?;

    let error = replace(root.path(), &generated_tree(Some(SCRIPT_BODY)))
        .expect_err("unmarked active output collision refuses");
    assert!(matches!(
        error.downcast_ref::<OrchestratorError>(),
        Some(OrchestratorError::OverwriteRefused { .. })
    ));
    assert_eq!(fs::read(&script)?, user_bytes);
    assert!(!github.join("workflows/ci.yml").exists());
    Ok(())
}

#[cfg(unix)]
#[test]
fn shared_script_symlink_collision_does_not_follow_target() -> TestResult {
    use std::os::unix::fs::symlink;

    let root = tempfile::tempdir()?;
    let outside = tempfile::tempdir()?;
    let github = root.path().join(".github");
    let script = github.join(
        shared_script_path(SCRIPT_BODY)
            .strip_prefix(".github/")
            .ok_or("shared path")?,
    );
    let outside_script = outside.path().join("shared.sh");
    let outside_bytes = format!("{MARKER}outside\n");
    fs::create_dir_all(script.parent().ok_or("script parent")?)?;
    fs::write(&outside_script, &outside_bytes)?;
    symlink(&outside_script, &script)?;

    let error = replace(root.path(), &generated_tree(Some(SCRIPT_BODY)))
        .expect_err("symlink output collision refuses");
    assert!(matches!(
        error.downcast_ref::<OrchestratorError>(),
        Some(OrchestratorError::UnsafePath { .. })
    ));
    assert!(fs::symlink_metadata(&script)?.file_type().is_symlink());
    assert_eq!(fs::read(&outside_script)?, outside_bytes.as_bytes());
    assert!(!github.join("workflows/ci.yml").exists());
    Ok(())
}

#[cfg(unix)]
#[test]
fn shared_script_symlink_ancestor_is_not_traversed() -> TestResult {
    use std::os::unix::fs::symlink;

    let root = tempfile::tempdir()?;
    let outside = tempfile::tempdir()?;
    let github = root.path().join(".github");
    let scripts = github.join("scripts");
    let shared = scripts.join("velnor-shared");
    let outside_script = outside.path().join(
        shared_script_path(SCRIPT_BODY)
            .strip_prefix(".github/scripts/velnor-shared/")
            .ok_or("shared filename")?,
    );
    let outside_bytes = format!("{MARKER}outside\n");
    fs::create_dir_all(&scripts)?;
    fs::write(&outside_script, &outside_bytes)?;
    symlink(outside.path(), &shared)?;

    let error = replace(root.path(), &generated_tree(Some(SCRIPT_BODY)))
        .expect_err("symlink ancestor refuses");
    assert!(matches!(
        error.downcast_ref::<OrchestratorError>(),
        Some(OrchestratorError::UnsafePath { .. })
    ));
    assert!(fs::symlink_metadata(&shared)?.file_type().is_symlink());
    assert_eq!(fs::read(&outside_script)?, outside_bytes.as_bytes());
    assert!(!github.join("workflows/ci.yml").exists());
    Ok(())
}
