//! Preservation safety and lifecycle checks for staged replacement.

use std::fs;
use std::path::Path;

use tempfile::TempDir;
use velnor_actions_workflow_renderer::render::{RenderedFile, RenderedTree};

use crate::OrchestratorError;

type TestResult = Result<(), Box<dyn std::error::Error>>;

fn tree(path: &str) -> RenderedTree {
    RenderedTree {
        files: vec![RenderedFile {
            path: path.to_owned(),
            bytes: "generated bytes\n".to_owned(),
        }],
        symlinks: Vec::new(),
    }
}

fn generated_tree(paths: &[&str]) -> RenderedTree {
    RenderedTree {
        files: paths
            .iter()
            .map(|path| RenderedFile {
                path: (*path).to_owned(),
                bytes: "# Generated by Velnor Actions 0.1.0; edit .velnor/config.toml and regenerate.\nnew bytes\n".to_owned(),
            })
            .collect(),
        symlinks: Vec::new(),
    }
}

fn replace(root: &Path) -> TestResult {
    let target = root.join(".github");
    let staging = TempDir::new_in(root)?;
    let staged = super::stage_in_place(
        &target,
        staging.path(),
        &generated_tree(&[".github/workflows/ci.yml"]),
    )?;
    crate::generate::swap_directories(root, &target, &staged)?;
    Ok(())
}

#[test]
fn replacement_keeps_unmanaged_entries_and_drops_generated_workflows() -> TestResult {
    let root = TempDir::new()?;
    let github = root.path().join(".github");
    fs::create_dir_all(github.join("ISSUE_TEMPLATE/empty"))?;
    fs::create_dir_all(github.join("workflows/nested"))?;
    fs::write(github.join("ISSUE_TEMPLATE/bug.yml"), b"custom\0bytes\xff")?;
    fs::write(github.join("workflows/old.yml"), b"stale")?;
    replace(root.path())?;
    assert_eq!(
        fs::read(github.join("ISSUE_TEMPLATE/bug.yml"))?,
        b"custom\0bytes\xff"
    );
    assert!(github.join("ISSUE_TEMPLATE/empty").is_dir());
    assert_eq!(
        fs::read(github.join("workflows/ci.yml"))?,
        b"# Generated by Velnor Actions 0.1.0; edit .velnor/config.toml and regenerate.\nnew bytes\n"
    );
    assert!(!github.join("workflows/old.yml").exists());
    assert!(!github.join("workflows/nested").exists());
    Ok(())
}

#[test]
#[cfg(unix)]
fn retired_claude_symlink_is_dropped_by_replacement() -> TestResult {
    let root = TempDir::new()?;
    let github = root.path().join(".github");
    fs::create_dir_all(&github)?;
    fs::write(github.join("AGENTS.md"), b"instructions\n")?;
    std::os::unix::fs::symlink("AGENTS.md", github.join("CLAUDE.md"))?;
    fs::write(github.join("PULL_REQUEST_TEMPLATE.md"), b"custom\n")?;
    replace(root.path())?;
    assert!(
        fs::symlink_metadata(github.join("CLAUDE.md")).is_err(),
        "retired symlink must not survive replacement"
    );
    assert_eq!(
        fs::read(github.join("PULL_REQUEST_TEMPLATE.md"))?,
        b"custom\n"
    );
    assert!(github.join("workflows/ci.yml").is_file());
    Ok(())
}

#[test]
fn retired_claude_file_is_dropped_by_replacement() -> TestResult {
    let root = TempDir::new()?;
    let github = root.path().join(".github");
    fs::create_dir_all(&github)?;
    fs::write(github.join("CLAUDE.md"), b"stale copy\n")?;
    fs::write(github.join("PULL_REQUEST_TEMPLATE.md"), b"custom\n")?;
    replace(root.path())?;
    assert!(
        fs::symlink_metadata(github.join("CLAUDE.md")).is_err(),
        "retired file must not survive replacement"
    );
    assert_eq!(
        fs::read(github.join("PULL_REQUEST_TEMPLATE.md"))?,
        b"custom\n"
    );
    assert!(github.join("workflows/ci.yml").is_file());
    Ok(())
}

#[test]
fn shared_action_markers_preserve_custom_actions_and_retire_stale_ones() -> TestResult {
    let root = TempDir::new()?;
    let github = root.path().join(".github");
    let old_marker =
        b"# Generated by Velnor Actions 0.0.9; edit .velnor/config.toml and regenerate.\nold\n";
    fs::create_dir_all(github.join("actions/rust-demo"))?;
    fs::create_dir_all(github.join("actions/retired"))?;
    fs::create_dir_all(github.join("actions/custom"))?;
    fs::write(github.join("actions/rust-demo/action.yml"), old_marker)?;
    fs::write(github.join("actions/retired/action.yml"), old_marker)?;
    fs::write(
        github.join("actions/custom/action.yml"),
        b"name: local custom action\nruns:\n  using: composite\n  steps: []\n",
    )?;
    fs::write(github.join("actions/custom/README.md"), b"keep me")?;
    let staging = TempDir::new_in(root.path())?;
    let staged = super::stage_in_place(
        &github,
        staging.path(),
        &generated_tree(&[
            ".github/workflows/ci.yml",
            ".github/actions/rust-demo/action.yml",
        ]),
    )?;
    crate::generate::swap_directories(root.path(), &github, &staged)?;
    assert!(
        fs::read_to_string(github.join("actions/rust-demo/action.yml"))?
            .starts_with("# Generated by Velnor Actions 0.1.0")
    );
    assert!(!github.join("actions/retired").exists());
    assert_eq!(
        fs::read(github.join("actions/custom/action.yml"))?,
        b"name: local custom action\nruns:\n  using: composite\n  steps: []\n"
    );
    assert_eq!(
        fs::read(github.join("actions/custom/README.md"))?,
        b"keep me"
    );
    Ok(())
}

#[test]
fn marked_helper_scripts_stay_generator_owned() -> TestResult {
    let root = TempDir::new()?;
    let github = root.path().join(".github");
    let old_marker =
        b"# Generated by Velnor Actions 0.0.9; edit .velnor/config.toml and regenerate.\nold\n";
    fs::create_dir_all(github.join("scripts"))?;
    fs::write(github.join("scripts/generated.sh"), old_marker)?;
    fs::write(github.join("scripts/custom.sh"), b"#!/bin/sh\necho keep\n")?;
    let staging = TempDir::new_in(root.path())?;
    let staged = super::stage_in_place(
        &github,
        staging.path(),
        &generated_tree(&[".github/workflows/ci.yml", ".github/scripts/generated.sh"]),
    )?;
    crate::generate::swap_directories(root.path(), &github, &staged)?;
    assert!(
        fs::read_to_string(github.join("scripts/generated.sh"))?
            .starts_with("# Generated by Velnor Actions 0.1.0")
    );
    assert_eq!(
        fs::read(github.join("scripts/custom.sh"))?,
        b"#!/bin/sh\necho keep\n"
    );
    Ok(())
}

#[test]
fn unmanaged_generated_path_collision_refuses_before_commit() -> TestResult {
    let root = TempDir::new()?;
    let github = root.path().join(".github");
    fs::create_dir_all(github.join("custom"))?;
    fs::write(github.join("custom/support.py"), b"repository bytes")?;
    let staging = TempDir::new_in(root.path())?;
    let error = super::stage_in_place(&github, staging.path(), &tree(".github/custom/support.py"))
        .expect_err("unknown generated collision refuses");
    assert!(matches!(error, OrchestratorError::OverwriteRefused { .. }));
    assert_eq!(
        fs::read(github.join("custom/support.py"))?,
        b"repository bytes"
    );
    Ok(())
}

#[cfg(unix)]
#[test]
fn preserved_symlink_ancestor_refuses_generated_write() -> TestResult {
    use std::os::unix::fs::symlink;

    let root = TempDir::new()?;
    let outside = TempDir::new()?;
    let github = root.path().join(".github");
    fs::create_dir_all(github.join("custom"))?;
    fs::write(github.join("CODEOWNERS"), b"owners")?;
    symlink(outside.path(), github.join("custom/link"))?;
    let staging = TempDir::new_in(root.path())?;
    let error = super::stage_in_place(
        &github,
        staging.path(),
        &tree(".github/custom/link/escaped/output.py"),
    )
    .expect_err("symlink ancestor refuses");
    assert!(matches!(error, OrchestratorError::UnsafePath { .. }));
    assert!(!outside.path().join("escaped").exists());
    assert_eq!(fs::read(github.join("CODEOWNERS"))?, b"owners");
    assert!(fs::symlink_metadata(github.join("custom/link"))?.is_symlink());
    Ok(())
}

#[cfg(unix)]
#[test]
fn copy_preserves_modes_and_literal_symlinks() -> TestResult {
    use std::os::unix::fs::{PermissionsExt, symlink};

    let root = TempDir::new()?;
    let github = root.path().join(".github");
    fs::create_dir_all(github.join("scripts"))?;
    fs::write(github.join("scripts/check"), b"#!/bin/sh\nexit 0\n")?;
    fs::set_permissions(
        github.join("scripts/check"),
        fs::Permissions::from_mode(0o751),
    )?;
    fs::set_permissions(github.join("scripts"), fs::Permissions::from_mode(0o750))?;
    let dangling = github.join("dangling");
    symlink("../missing", &dangling)?;
    #[cfg(target_os = "macos")]
    rustix::fs::chmodat(
        rustix::fs::CWD,
        &dangling,
        rustix::fs::Mode::from_raw_mode(0o750),
        rustix::fs::AtFlags::SYMLINK_NOFOLLOW,
    )?;
    replace(root.path())?;
    assert_eq!(
        fs::metadata(github.join("scripts/check"))?
            .permissions()
            .mode()
            & 0o777,
        0o751
    );
    assert_eq!(
        fs::metadata(github.join("scripts"))?.permissions().mode() & 0o777,
        0o750
    );
    assert_eq!(fs::read_link(&dangling)?, Path::new("../missing"));
    let dangling_metadata = fs::symlink_metadata(&dangling)?;
    assert!(dangling_metadata.is_symlink());
    #[cfg(target_os = "macos")]
    assert_eq!(dangling_metadata.permissions().mode() & 0o777, 0o750);
    Ok(())
}

#[cfg(unix)]
#[test]
fn raw_mode_conversion_checks_narrowing_and_keeps_wide_modes() -> TestResult {
    assert_eq!(
        super::checked_raw_mode::<u16>(0o750, Path::new("dangling"))?,
        0o750
    );
    assert!(super::checked_raw_mode::<u16>(u32::MAX, Path::new("dangling")).is_err());
    assert_eq!(
        super::checked_raw_mode::<u32>(u32::MAX, Path::new("dangling"))?,
        u32::MAX
    );
    Ok(())
}

#[cfg(unix)]
#[test]
fn unsupported_entry_refuses_before_replacement() -> TestResult {
    use std::os::unix::net::UnixListener;

    let root = TempDir::new()?;
    let github = root.path().join(".github");
    fs::create_dir_all(&github)?;
    fs::write(github.join("CODEOWNERS"), b"kept")?;
    let _socket = UnixListener::bind(github.join("socket"))?;
    let staging = TempDir::new_in(root.path())?;
    let error = super::stage_in_place(&github, staging.path(), &tree(".github/workflows/ci.yml"))
        .expect_err("socket cannot be preserved safely");
    assert!(error.to_string().contains("unsupported_repository_entry"));
    assert_eq!(fs::read(github.join("CODEOWNERS"))?, b"kept");
    assert!(!github.join("workflows").exists());
    Ok(())
}
