//! Exact retired outputs require marker proof; human siblings survive replacement.

use super::{TestResult, replacement};
use crate::apt_delivery::{APT_DELIVERY_TREE_PATHS, APT_RETIRED_TREE_PATHS};
use std::fs;
use velnor_actions_contract::generated_source;
use velnor_actions_workflow_renderer::release_tree::{
    RELEASE_RETIRED_TREE_PATHS, RELEASE_TREE_PATHS,
};

fn retired_paths() -> impl Iterator<Item = &'static str> {
    APT_RETIRED_TREE_PATHS
        .iter()
        .copied()
        .chain(RELEASE_RETIRED_TREE_PATHS.iter().copied())
}

#[test]
fn marked_retired_outputs_are_removed_and_unknown_marked_siblings_survive() -> TestResult {
    let root = tempfile::tempdir()?;
    let directory = root.path().join(".github/velnor");
    fs::create_dir_all(&directory)?;
    let marked = generated_source("0.0.1", "retired compiled source\n")?;
    for path in retired_paths() {
        fs::write(root.path().join(path), &marked)?;
    }
    fs::write(directory.join("human.py"), &marked)?;
    for _ in 0..2 {
        replacement(root.path())?;
        for path in retired_paths() {
            assert!(
                !root.path().join(path).exists(),
                "retired output survives: {path}"
            );
        }
        assert_eq!(fs::read_to_string(directory.join("human.py"))?, marked);
    }
    Ok(())
}

#[test]
fn unmarked_retired_names_remain_human_owned() -> TestResult {
    let root = tempfile::tempdir()?;
    fs::create_dir_all(root.path().join(".github/velnor"))?;
    for path in retired_paths() {
        fs::write(root.path().join(path), b"human script\0\xff")?;
    }
    replacement(root.path())?;
    for path in retired_paths() {
        assert_eq!(fs::read(root.path().join(path))?, b"human script\0\xff");
    }
    Ok(())
}

#[test]
fn malformed_retired_marker_refuses_before_swap() -> TestResult {
    let root = tempfile::tempdir()?;
    let path = root.path().join(".github/velnor/release_preflight.py");
    fs::create_dir_all(path.parent().ok_or("missing parent")?)?;
    let bytes = "# Generated by Velnor Actions 0.0.1; invalid\nsource\n";
    fs::write(&path, bytes)?;
    let error = replacement(root.path()).expect_err("invalid claimed ownership");
    assert!(
        error.to_string().contains("invalid_retired_marker"),
        "{error}"
    );
    assert_eq!(fs::read_to_string(path)?, bytes);
    assert!(!root.path().join(".github/workflows").exists());
    Ok(())
}

#[cfg(unix)]
#[test]
fn retired_name_symlink_preserves_literal_target() -> TestResult {
    let root = tempfile::tempdir()?;
    let outside = tempfile::tempdir()?;
    let external = outside.path().join("human.py");
    let marked = generated_source("0.0.1", "external source\n")?;
    fs::write(&external, &marked)?;
    let link = root.path().join(".github/velnor/release_preflight.py");
    fs::create_dir_all(link.parent().ok_or("missing parent")?)?;
    std::os::unix::fs::symlink(&external, &link)?;
    replacement(root.path())?;
    assert!(fs::symlink_metadata(&link)?.is_symlink());
    assert_eq!(fs::read_link(link)?, external);
    assert_eq!(fs::read_to_string(external)?, marked);
    Ok(())
}

#[test]
fn retired_outputs_have_no_current_execution_routes() {
    for path in retired_paths() {
        assert!(
            !APT_DELIVERY_TREE_PATHS.contains(&path),
            "retired APT route: {path}"
        );
        assert!(
            !RELEASE_TREE_PATHS.contains(&path),
            "retired Rust route: {path}"
        );
    }
}
