//! Generation coordination: root, config, discovery, IR, and writes.

mod action_report;
mod analysis_inventory;
pub mod apt_delivery;
mod attach;
mod baseline_publish;
pub mod cache_producer_workflow;
pub mod cache_receipt_source;
mod clippy_groups;
mod config;
mod config_stacks;
mod cover;
mod cover_baseline;
mod cover_compat;
mod cover_identity;
mod covered_tasks;
mod crate_job_ids;
mod crate_jobs;
mod critical_path;
mod current_candidate_source;
mod current_semantic_input_proof;
mod current_source_context;
mod current_source_snapshot;
pub mod decisions;
mod delivery_emit;
mod derive_groups;
pub mod desktop_delivery;
mod discover;
mod discover_index;
mod discover_tofu;
mod error;
mod evidence;
mod exclusive_write;
mod exports;
mod extension_schemas;
mod external_data;
mod finalized;
mod freshness_emit;
mod generate;
mod git_paths;
mod helper_obligation_binding;
mod helper_obligation_coverage;
mod helper_obligation_report;
mod helper_obligation_steps;
mod init;
mod internal;
mod internal_plan;
mod internal_request;
mod inventory;
mod inventory_reuse;
mod lock_audit;
mod matrix_step;
mod mbx_admission_source;
mod mbx_export;
mod mbx_partition;
pub mod mbx_producer;
mod merge;
mod merge_request;
mod native_source_graph;
mod noop_report;
mod obligation_steps;
mod origin;
mod owned_tool_preview;
mod owned_tool_publication;
mod pins;
mod plan;
mod plan_stacks;
mod prepare;
mod preseed_manifest;
mod provenance;
mod publish_job;
mod qualify;
mod recommendations;
mod release_emit;
mod request_event;
mod retrieve_baseline;
mod retrieve_reports;
mod retrieve_retry;
mod root;
pub mod run_select;
mod rust_features;
mod rust_report_preexec;
mod rust_report_wrapper;
mod safe_read;
pub mod schedule;
mod select;
mod select_affected;
mod select_edges;
mod select_tofu;
mod source_prep;
mod task_clock;
mod task_report;
mod task_report_aggregate;
#[cfg(test)]
mod test_mise;
mod tofu_cache;
mod tofu_cache_source;
mod tofu_cached_init;
mod tofu_config_step;
mod tofu_ownership_helper;
mod tofu_producer_job;
mod tofu_producer_source;
mod toolcheck;
mod toolfindings;
mod utf8;
mod validate;
mod validate_shell;
mod validate_zizmor;
mod validators;
mod vectors;
mod workflow;
mod workflow_jobs;
mod workflow_mbx_finalize;
mod workflow_tool_producer;
mod workloads;

pub use exports::*;

/// Version marker for the orchestrator shell.
pub const ORCHESTRATOR_VERSION: u32 = 0;
