"""Strict RootLinux candidate recipe parser tests; fixtures grant no authority."""
import copy
import hashlib
import json
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

ORCH_SOURCE = Path(__file__).resolve().parent
MISE_SOURCE = ORCH_SOURCE.parents[1] / 'velnor-actions-mise' / 'src'
sys.path.insert(0, str(MISE_SOURCE))
sys.path.insert(0, str(ORCH_SOURCE))

import source_root_rust_candidate_recipe as recipe
from source_intent_cold_common import ColdSourceIntent
from source_intent_cold_compiler import _manifest_identity
import source_intent_cold_foundation as foundation_owner


def _manifest():
    return {
        'version': '1.98.1', 'target': 'x86_64-unknown-linux-gnu',
        'manifest_url': 'https://static.rust-lang.org/dist/channel-rust-1.98.1.toml',
        'manifest_sha256': 'a7c8774a5fd8441c997d94c029776cbc5eb111e9d72ab5d256fa69866644347e',
        'release_date': '2026-09-03',
        'rust_source_repository': 'https://github.com/rust-lang/rust',
        'rust_source_commit': '48a229ceaefd4985c50990b14116b6d856af0985',
        'rust_source_tree': '22cb8c2037692834918e9320e63a6f87bb8d92ef',
        'cargo_source_repository': 'https://github.com/rust-lang/cargo',
        'cargo_source_commit': '797e8a9bca276c1c9f9f738d2a20f484fa4eea9d',
        'cargo_source_tree': '4007da55f36ad45f760b98668fc17807030ef22f',
        'components': [
            {'component': 'rustc',
             'xz_url': 'https://static.rust-lang.org/dist/2026-09-03/'
                       'rustc-1.98.1-x86_64-unknown-linux-gnu.tar.xz',
             'xz_sha256': 'e974f036b28565f37c0f3bd92ddefa809bee16c04f9dcf07b9ed96e05aaaf7c4',
             'gzip_url': 'https://static.rust-lang.org/dist/2026-09-03/'
                         'rustc-1.98.1-x86_64-unknown-linux-gnu.tar.gz',
             'gzip_sha256': 'a6e35741daaac7978e7f485b564a783d13b6740a1ecf3e80c2e71696ca5cabb2'},
            {'component': 'cargo',
             'xz_url': 'https://static.rust-lang.org/dist/2026-09-03/'
                       'cargo-1.98.1-x86_64-unknown-linux-gnu.tar.xz',
             'xz_sha256': 'ea1de9f9e23107d97ee2b41a72c552f34064a593da503789218387aee59f3ba4',
             'gzip_url': 'https://static.rust-lang.org/dist/2026-09-03/'
                         'cargo-1.98.1-x86_64-unknown-linux-gnu.tar.gz',
             'gzip_sha256': '3f1215b2a3b88c7aaa008b561bd4f39d6c6672fa7821e562ab6ba1a6d6f37f61'},
            {'component': 'rust-std',
             'xz_url': 'https://static.rust-lang.org/dist/2026-09-03/'
                       'rust-std-1.98.1-x86_64-unknown-linux-gnu.tar.xz',
             'xz_sha256': 'fa3ff450172a16c026944030230c5069947af93c728d9179971d44e5e0cfb561',
             'gzip_url': 'https://static.rust-lang.org/dist/2026-09-03/'
                         'rust-std-1.98.1-x86_64-unknown-linux-gnu.tar.gz',
             'gzip_sha256': 'eddab0358cbd12aeb897716aab00d1db7b59696e85b9ac4982e72259a9a976b1'},
            {'component': 'clippy-preview',
             'xz_url': 'https://static.rust-lang.org/dist/2026-09-03/'
                       'clippy-1.98.1-x86_64-unknown-linux-gnu.tar.xz',
             'xz_sha256': 'e167f333be24e1d5eea56ea563c7def0aa0bd613f5ce3445976c93b0288799d1',
             'gzip_url': 'https://static.rust-lang.org/dist/2026-09-03/'
                         'clippy-1.98.1-x86_64-unknown-linux-gnu.tar.gz',
             'gzip_sha256': '81ee497320fc54bab54f27692513808663a120496c27f4c02f60f10645dbc0cc'},
            {'component': 'rustfmt-preview',
             'xz_url': 'https://static.rust-lang.org/dist/2026-09-03/'
                       'rustfmt-1.98.1-x86_64-unknown-linux-gnu.tar.xz',
             'xz_sha256': 'b29a1addcbf2aa8f5785075605700e63cbe131b08c8334b50c09cfca8bbc51dc',
             'gzip_url': 'https://static.rust-lang.org/dist/2026-09-03/'
                         'rustfmt-1.98.1-x86_64-unknown-linux-gnu.tar.gz',
             'gzip_sha256': '16db0d6bb3535cfa84c009cffb161aac32d48f6e0648507a1f3368323cac3ec7'},
        ],
    }


def _native_source():
    payload_path = MISE_SOURCE / 'catalog_root_rust_candidate_payload.json'
    payload = json.loads(payload_path.read_text())
    record = {
        'schema': 1, 'purpose': 'root-linux-candidate-artifact-v1',
        'authority': 'source-inputs-only', 'manifest': _manifest(),
        'manifest_identity_sha256': _manifest_identity(_manifest()), 'payload': payload,
        'payload_sha256': recipe._PAYLOAD_FILE_SHA256, 'manager': dict(recipe._MANAGER),
        'transform_abi': recipe._TRANSFORM_ABI,
        'constraints': copy.deepcopy(recipe._CONSTRAINTS),
    }
    record['qualification_sha256'] = recipe._sha256(recipe._canonical(record))
    return record


def _recipe():
    stages = []
    for name in ('clear', 'acquire', 'install'):
        source = '# Generated by Velnor Actions 0.1.0; edit .velnor/config.toml and regenerate.\n' \
                 'exit 0\n'
        stages.append({'name': name, 'source': source,
                       'source_sha256': hashlib.sha256(source.encode()).hexdigest(),
                       'arguments': [],
                       'executable_roster': list(recipe._EXECUTABLE_ROSTER),
                       'executable_search_paths': list(recipe._EXECUTABLE_SEARCH_PATHS)})
    record = {
        'schema': 1, 'purpose': 'root-linux-compiler-candidate', 'role': 'root-linux',
        'host': recipe._HOST, 'rust_version': recipe._VERSION,
        'toolchain': recipe._TOOLCHAIN, 'namespace': recipe._NAMESPACE,
        'leaves': list(recipe._LEAVES), 'stages': stages,
        'environment': dict(recipe._SOURCE_ENVIRONMENT),
        'manager_sha256': recipe._MANAGER_SHA256, 'manager_version': recipe._MANAGER_VERSION,
        'native_source_authority': _native_source(),
        'installer_source_identity': hashlib.sha256(
            '\0'.join(stage['source'] for stage in stages).encode()).hexdigest(),
    }
    return record


class _SyntheticCandidateOwner:
    compiled_role = 'RootRustCandidate'

    def __init__(self, root, ca_file):
        self.candidate_root = root
        self.ca_file = ca_file

    def require_current(self):
        return None


def _foundation_fixture(root, ca_file='/etc/ssl/cert.pem'):
    owner = _SyntheticCandidateOwner(root, ca_file)
    getter = lambda: owner
    binding = patch.multiple(
        foundation_owner,
        _COMPILED_ROOT_RUST_CANDIDATE_FOUNDATION_TYPE=type(owner),
        _COMPILED_ROOT_RUST_CANDIDATE_FOUNDATION_GETTER=getter,
    )
    return owner, binding


class CandidateRecipeTests(unittest.TestCase):
    def test_compiled_recipe_is_fail_closed_until_source_owner_binds_it(self):
        with self.assertRaisesRegex(ColdSourceIntent, 'root_rust_candidate_recipe_unavailable'):
            recipe._compiled_candidate_recipe()

    def test_valid_recipe_binds_native_source_and_returns_copy(self):
        record = _recipe()
        with patch.object(recipe, '_COMPILED_ROOT_RUST_CANDIDATE_RECIPE', record):
            actual = recipe._compiled_candidate_recipe()
        self.assertEqual(actual, record)
        self.assertIsNot(actual, record)
        self.assertEqual(actual['native_source_authority']['qualification_sha256'],
                         recipe._NATIVE_QUALIFICATION_SHA256)

    def test_recipe_literals_and_each_stage_binding_are_closed(self):
        for field, value in (
                ('purpose', 'foreign'), ('role', 'desktop'), ('host', 'aarch64'),
                ('toolchain', '1.98.1-aarch64'), ('namespace', 'foreign/root'),
                ('manager_sha256', '0' * 64), ('manager_version', '1.29.0')):
            record = _recipe()
            record[field] = value
            with self.subTest(field=field), patch.object(
                    recipe, '_COMPILED_ROOT_RUST_CANDIDATE_RECIPE', record), \
                    self.assertRaises(ColdSourceIntent):
                recipe._compiled_candidate_recipe()
        for index in range(3):
            record = _recipe()
            record['stages'][index]['source'] += 'changed\n'
            with self.subTest(index=index), patch.object(
                    recipe, '_COMPILED_ROOT_RUST_CANDIDATE_RECIPE', record), \
                    self.assertRaises(ColdSourceIntent):
                recipe._compiled_candidate_recipe()
        for index in range(3):
            for field in ('executable_roster', 'executable_search_paths'):
                record = _recipe()
                record['stages'][index][field][0] = '/caller-controlled'
                with self.subTest(index=index, field=field), patch.object(
                        recipe, '_COMPILED_ROOT_RUST_CANDIDATE_RECIPE', record), \
                        self.assertRaises(ColdSourceIntent):
                    recipe._compiled_candidate_recipe()

    def test_forged_native_source_rows_receipts_and_constraints_reject(self):
        for mutate in (
                lambda value: value.__setitem__('authority', 'installed-authority'),
                lambda value: value['manifest'].__setitem__('rust_source_commit', '0' * 40),
                lambda value: value['payload'][0].__setitem__('sha256', '0' * 64),
                lambda value: value.__setitem__('payload_sha256', '0' * 64),
                lambda value: value['manager'].__setitem__('sha256', '0' * 64),
                lambda value: value['constraints'].__setitem__('automatic_install', True),
                lambda value: value.__setitem__('installation_receipt_sha256', '0' * 64),
        ):
            record = _recipe()
            native = record['native_source_authority']
            mutate(native)
            with self.subTest(mutate=mutate), patch.object(
                    recipe, '_COMPILED_ROOT_RUST_CANDIDATE_RECIPE', record), \
                    self.assertRaises(ColdSourceIntent):
                recipe._compiled_candidate_recipe()

    def test_candidate_environment_has_only_fixed_values(self):
        record = _recipe()
        root = '/missing/runner-temp/' + recipe._NAMESPACE
        _owner, binding = _foundation_fixture(root)
        with binding:
            foundation = foundation_owner.require_preparation_foundation(
                'root-linux-compiler-candidate')
            with self.assertRaisesRegex(ColdSourceIntent, 'root_rust_candidate_runner_temp'):
                with patch.object(recipe.platform, 'system', return_value='Linux'), \
                        patch.object(recipe.platform, 'machine', return_value='x86_64'):
                    recipe._candidate_environment(record, foundation)

    def test_candidate_environment_binds_root_and_rejects_foreign_binding(self):
        record = _recipe()
        with tempfile.TemporaryDirectory(prefix='root-rust-candidate-') as directory:
            temp = str(Path(directory).resolve())
            root = temp + '/' + recipe._NAMESPACE
            ca_file = str(Path(temp) / 'ca.pem')
            Path(ca_file).write_bytes(b'fixture-ca\n')
            owner, binding = _foundation_fixture(root, ca_file)
            with binding:
                foundation = foundation_owner.require_preparation_foundation(
                    'root-linux-compiler-candidate')
                with patch.object(recipe.platform, 'system', return_value='Linux'), \
                        patch.object(recipe.platform, 'machine', return_value='x86_64'), \
                        patch.dict(recipe.os.environ, {
                            'RUNNER_TEMP': '/caller-runner-temp',
                            recipe._ROOT_ENV: '/caller-root', 'PATH': 'caller-path',
                            'LANG': 'caller-lang', 'LC_ALL': 'caller-locale',
                            'TZ': 'caller-zone', 'HOME': '/caller',
                            'SSL_CERT_FILE': '/caller-ca', 'CURL_CA_BUNDLE': '/caller-ca',
                        }, clear=False):
                    actual_root, environment = recipe._candidate_environment(record, foundation)
            self.assertEqual(actual_root, root)
            self.assertEqual(set(environment), set(recipe._SOURCE_ENVIRONMENT)
                             | {'PATH', 'LANG', 'LC_ALL', 'SSL_CERT_FILE', 'CURL_CA_BUNDLE'})
            self.assertEqual(environment['PATH'], '/usr/bin:/bin:/usr/sbin:/sbin')
            self.assertEqual(environment['LANG'], 'C')
            self.assertEqual(environment['LC_ALL'], 'C')
            self.assertEqual(environment['SSL_CERT_FILE'], ca_file)
            self.assertEqual(environment['CURL_CA_BUNDLE'], ca_file)
            self.assertNotIn('HOME', environment)
            self.assertNotIn('TZ', environment)
            with binding:
                owner.candidate_root = root + '/foreign'
                with self.assertRaisesRegex(ColdSourceIntent, 'root_rust_candidate_foundation_root'):
                    with patch.object(recipe.platform, 'system', return_value='Linux'), \
                        patch.object(recipe.platform, 'machine', return_value='x86_64'):
                        recipe._candidate_environment(record, foundation)

            owner.candidate_root = root
            owner.ca_file = temp
            with binding, self.assertRaisesRegex(ColdSourceIntent,
                                                  'root_rust_candidate_ca_file'):
                with patch.object(recipe.platform, 'system', return_value='Linux'), \
                        patch.object(recipe.platform, 'machine', return_value='x86_64'):
                    recipe._candidate_environment(record, foundation)

    def test_candidate_environment_requires_exact_foundation_issuer(self):
        with self.assertRaisesRegex(ColdSourceIntent, 'root_rust_candidate_foundation_issuer'):
            recipe._candidate_environment(_recipe(), object())


if __name__ == '__main__':
    unittest.main()
