use super::*;

use velnor_actions_contract::SourceBoundOperation;

const HOST: DistributionHost = DistributionHost::MacosArm64;

const ROOT_TASK: &str = "stack/tofu/dir-/init/default";
const NESTED_TASK: &str = "stack/tofu/dir-737461636b732f767063/init/default";

#[test]
fn owner_binds_root_and_exact_open_tofu_pin() {
    let record = from_task_id(
        ROOT_TASK,
        &ToolCatalog::pinned(),
        HOST,
        env!("CARGO_PKG_VERSION"),
    )
    .expect("root helper");
    assert_eq!(
        record.invocation().args(),
        &[
            ".".to_owned(),
            "1.13.1".to_owned(),
            "dir-".to_owned(),
            "installs/http-opentofu/1.13.1/tofu".to_owned()
        ]
    );
    assert_eq!(
        record.invocation().installed_selectors(),
        ToolCatalog::pinned()
            .native_tool_specs(HOST, &[PinnedTool::Opentofu])
            .expect("qualified selectors")
            .as_slice()
    );
    assert_eq!(
        record.invocation().descriptor().operation(),
        SourceBoundOperation::TofuCachedInit
    );
    assert_eq!(
        record.invocation().descriptor().path(),
        ".github/velnor/tofu_cached_init.sh"
    );
    assert_source_digest(&record);
    assert_exact_environment(&record, "");
}

#[test]
fn owner_binds_nested_root_without_wire_extras() {
    let record = from_task_id(
        NESTED_TASK,
        &ToolCatalog::pinned(),
        HOST,
        env!("CARGO_PKG_VERSION"),
    )
    .expect("nested helper");
    assert_eq!(
        record.invocation().args(),
        &[
            "stacks/vpc".to_owned(),
            "1.13.1".to_owned(),
            "dir-737461636b732f767063".to_owned(),
            "installs/http-opentofu/1.13.1/tofu".to_owned(),
        ]
    );
    assert_source_digest(&record);
    assert_exact_environment(&record, "stacks/vpc");
}

#[test]
fn owner_rejects_non_native_init_shapes() {
    let catalog = ToolCatalog::pinned();
    for task_id in [
        "stack/rust/root/init/default",
        "stack/tofu/dir-/validate/default",
        "stack/tofu/dir-/init/release",
        "stack/tofu/dir-/init/default/shard-1-of-2",
    ] {
        assert!(
            from_task_id(task_id, &catalog, HOST, env!("CARGO_PKG_VERSION")).is_err(),
            "{task_id}"
        );
    }
}

#[test]
fn owner_rejects_catalog_and_generator_version_drift() {
    let catalog = ToolCatalog::new(
        velnor_actions_mise::RUST_VERSION,
        velnor_actions_mise::MR_BOXINGTON_VERSION,
        velnor_actions_mise::GH_VERSION,
        velnor_actions_mise::ACTIONLINT_VERSION,
        velnor_actions_mise::SHELLCHECK_VERSION,
        velnor_actions_mise::ZIZMOR_VERSION,
        velnor_actions_mise::catalog::NEXTEST_VERSION,
        "1.13.0",
    )
    .expect("valid alternate catalog");
    assert!(from_task_id(ROOT_TASK, &catalog, HOST, env!("CARGO_PKG_VERSION")).is_err());
    assert!(from_task_id(ROOT_TASK, &ToolCatalog::pinned(), HOST, "other-version").is_err());
}

#[test]
fn proposal_factory_binds_actual_root_and_all_native_identity_fields() {
    let catalog = ToolCatalog::pinned();
    let version = env!("CARGO_PKG_VERSION");
    for root in ["", "root", "stacks/vpc", "literal'$`/space dir"] {
        let task = velnor_actions_tofu::propose_task(&velnor_actions_tofu::TofuTaskGroup {
            root: root.to_owned(),
            kind: velnor_actions_tofu::TofuTaskKind::InitForValidate,
            configuration: "default".to_owned(),
            no_targets: false,
        })
        .expect("native proposal");
        let record = from_proposal(&task, &catalog, HOST, version).expect("qualified proposal");
        assert_eq!(
            record.invocation().args()[2],
            velnor_actions_tofu::key_for_root(root)
        );
        assert_eq!(
            record,
            from_task_id(&task.task_id, &catalog, HOST, version).expect("same recipe")
        );
        let mut wrong_root = task.clone();
        wrong_root.identity.project_root = "other".to_owned();
        assert!(from_proposal(&wrong_root, &catalog, HOST, version).is_err());
        let mut wrong_component = task;
        wrong_component.component_id.push_str("-other");
        assert!(from_proposal(&wrong_component, &catalog, HOST, version).is_err());
    }
}

fn assert_source_digest(record: &CompiledSourceHelper) {
    assert!(
        record
            .source()
            .starts_with("# Generated by Velnor Actions ")
    );
    assert_eq!(
        velnor_actions_contract::compiled_source_sha256(record.source().as_bytes()),
        record.invocation().descriptor().source_sha256()
    );
}

fn assert_exact_environment(record: &CompiledSourceHelper, root: &str) {
    let mut expected = crate::tofu_config_step::task_env(root).expect("task environment");
    expected.insert(
        velnor_actions_mise::runtime_paths::MISE_DATA_DIR_ENV.to_owned(),
        velnor_actions_mise::runtime_paths::MISE_DATA_DIR.to_owned(),
    );
    assert_eq!(record.environment(), &expected);
    for key in ["TF_VAR_SECRET", "TF_CLI_ARGS_init", "TF_TOKEN_registry"] {
        assert!(
            !record.environment().contains_key(key),
            "reserved key {key}"
        );
    }
    for key in ["GITHUB_OUTPUT", "VELNOR_TASK_DIGEST", "VELNOR_DOWNSTREAM"] {
        assert!(!record.environment().contains_key(key), "wire key {key}");
    }
}
