use super::*;

fn descriptor() -> ProviderExportDescriptor {
    let lock = "provider \"registry.opentofu.org/hashicorp/random\" {
  version = \"3.6.3\"
  hashes = [\"h1:fixture\"]
}
";
    crate::tofu_cache_source::descriptor_from_lock("", lock).expect("valid fixture lock")
}

#[test]
fn compiled_record_binds_exact_pin_and_source() {
    let record = compiled_helper(
        &descriptor(),
        "aarch64-apple-darwin",
        &ToolCatalog::pinned(),
        "${{ runner.temp }}/candidate",
        "${{ runner.temp }}/output",
        env!("CARGO_PKG_VERSION"),
    )
    .expect("compiled producer");
    assert!(
        record
            .source()
            .starts_with("# Generated by Velnor Actions ")
    );
    assert!(record.source().contains("init -backend=false -input=false"));
    assert!(record.source().contains("-lockfile=readonly"));
    assert!(record.source().contains("provider_installation"));
    assert!(record.source().contains("direct {}"));
    assert!(
        record
            .source()
            .contains("\"$tofu_bin\" \"-chdir=$root\" init")
    );
    assert!(
        !record
            .source()
            .contains("opentofu@$tofu_version\" -- \"-chdir")
    );
    assert!(record.source().contains("safe_version \"$tofu_version\""));
    assert!(!record.source().contains("tofu_version\" = 1.13.1"));
    assert!(record.source().contains("platform_for_host"));
    assert!(
        record
            .source()
            .contains("test \"$host_platform\" = \"$platform\"")
    );
    assert_eq!(
        record.invocation().args().first().map(String::as_str),
        Some("aarch64-apple-darwin")
    );
    assert_eq!(
        record.invocation().args().get(3).map(String::as_str),
        Some("1.13.1")
    );
    assert_eq!(
        record.invocation().args().get(4).map(String::as_str),
        Some("dir-")
    );
    assert_eq!(
        record.invocation().args().get(5).map(String::as_str),
        Some("installs/http-opentofu/1.13.1/tofu")
    );
    assert_eq!(
        record.invocation().installed_selectors(),
        ToolCatalog::pinned()
            .native_tool_specs(DistributionHost::MacosArm64, &[PinnedTool::Opentofu])
            .expect("qualified selectors")
            .as_slice()
    );
}

#[test]
fn compiled_record_rejects_independently_changed_lock_selection() {
    let mut changed = descriptor();
    changed.selections[0].1 = "3.6.4".to_owned();
    assert!(
        compiled_helper(
            &changed,
            "aarch64-apple-darwin",
            &ToolCatalog::pinned(),
            "/tmp/candidate",
            "/tmp/output",
            env!("CARGO_PKG_VERSION"),
        )
        .is_err()
    );
}

#[test]
fn producer_bindings_reject_control_paths_and_marker_skew() {
    let result = compiled_helper(
        &descriptor(),
        "aarch64-apple-darwin",
        &ToolCatalog::pinned(),
        "/tmp/candidate\nbad",
        "/tmp/output",
        env!("CARGO_PKG_VERSION"),
    );
    assert!(result.is_err());
    assert!(
        compiled_helper(
            &descriptor(),
            "aarch64-apple-darwin",
            &ToolCatalog::pinned(),
            "/tmp/candidate",
            "/tmp/output",
            "different-version",
        )
        .is_err()
    );
}

#[test]
fn producer_environment_binds_only_owned_paths() {
    let environment = producer_environment(
        Some("${{ runner.temp }}/candidate"),
        "${{ runner.temp }}/output",
    )
    .expect("owned paths");
    assert_eq!(environment.len(), 2);
    assert_eq!(
        environment.get("VELNOR_TOFU_PROVIDER_CANDIDATE"),
        Some(&"${{ runner.temp }}/candidate".to_owned())
    );
    assert!(producer_environment(Some("relative"), "/tmp/output").is_err());
    assert!(producer_environment(Some("/tmp/../candidate"), "/tmp/output").is_err());
    assert!(producer_environment(Some("/tmp/candidate\nbad"), "/tmp/output").is_err());
}

#[path = "tofu_producer_transport_tests.rs"]
mod transport_tests;
