//! Pinned ShellCheck coverage for content-addressed shared scripts.

use std::fs;

use super::{
    SHARED_SCRIPT_PREFIX, run_shellcheck_bodies, shared_script_dialect, workflow::ShellDialect,
};
use crate::OrchestratorError;
use velnor_actions_mise::ToolCatalog;
use velnor_actions_workflow_renderer::render::{RenderedFile, RenderedTree};

const MARKER: &str =
    "# Generated by Velnor Actions 0.1.0; edit .velnor/config.toml and regenerate.\n";
const DIGEST: &str = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef";

fn generated_file(dialect: &str, body: &str) -> RenderedFile {
    let digest = velnor_actions_contract::digest_b3(format!("{dialect}\0{body}").as_bytes());
    let extension = if dialect == "bash" { "bash" } else { "sh" };
    RenderedFile {
        path: format!("{SHARED_SCRIPT_PREFIX}{dialect}-{digest}.{extension}"),
        bytes: format!("{MARKER}{body}"),
    }
}

fn tree(file: RenderedFile) -> RenderedTree {
    RenderedTree {
        files: vec![file],
        symlinks: Vec::new(),
    }
}

fn staged_root() -> Result<(tempfile::TempDir, Vec<String>), String> {
    let staging = tempfile::tempdir().map_err(|err| err.to_string())?;
    let relative = ".github/workflows/t.yml".to_owned();
    let workflow = staging.path().join(&relative);
    fs::create_dir_all(workflow.parent().ok_or("workflow parent")?)
        .map_err(|err| err.to_string())?;
    fs::write(
        workflow,
        "jobs:\n  probe:\n    runs-on: ubuntu-26.04\n    steps:\n      - name: check\n        run: true\n",
    )
    .map_err(|err| err.to_string())?;
    Ok((staging, vec![relative]))
}

#[test]
fn shared_script_selection_requires_exact_lowercase_digest_and_suffix() {
    assert_eq!(
        shared_script_dialect(&format!("{SHARED_SCRIPT_PREFIX}sh-b3-{DIGEST}.sh")),
        Some(ShellDialect::Sh)
    );
    assert_eq!(
        shared_script_dialect(&format!("{SHARED_SCRIPT_PREFIX}bash-b3-{DIGEST}.bash")),
        Some(ShellDialect::Bash)
    );
    for path in [
        format!("{SHARED_SCRIPT_PREFIX}bash-b3-{DIGEST}.sh"),
        format!("{SHARED_SCRIPT_PREFIX}sh-b3-{DIGEST}.bash"),
        format!(
            "{SHARED_SCRIPT_PREFIX}sh-b3-{}.sh",
            DIGEST.to_ascii_uppercase()
        ),
        format!("{SHARED_SCRIPT_PREFIX}nested/sh-b3-{DIGEST}.sh"),
        format!(".github/scripts/other/sh-b3-{DIGEST}.sh"),
        format!("{SHARED_SCRIPT_PREFIX}sh-b3-short.sh"),
    ] {
        assert_eq!(
            shared_script_dialect(&path),
            None,
            "unexpected selection: {path}"
        );
    }
}

#[test]
fn shared_script_artifact_must_keep_its_generated_marker_first() -> Result<(), String> {
    let catalog = ToolCatalog::pinned();
    let (staging, workflows) = staged_root()?;
    let mut file = generated_file("sh", "true\n");
    file.bytes = "not a generated marker\ntrue\n".to_owned();
    let error = run_shellcheck_bodies(&catalog, staging.path(), &workflows, &tree(file))
        .expect_err("missing marker fails before linting");
    assert!(error.to_string().contains("shared_script_marker_missing"));
    Ok(())
}

#[test]
fn malformed_reserved_shared_paths_fail_before_linting() -> Result<(), String> {
    let catalog = ToolCatalog::pinned();
    let malformed_paths = [
        format!("{SHARED_SCRIPT_PREFIX}sh-b3-b3-{DIGEST}.sh"),
        format!("{SHARED_SCRIPT_PREFIX}sh-b3-{DIGEST}.bash"),
        format!("{SHARED_SCRIPT_PREFIX}sh-b3-{}g.sh", &DIGEST[..63]),
    ];
    for path in malformed_paths {
        let (staging, workflows) = staged_root()?;
        let file = RenderedFile {
            path: path.clone(),
            bytes: format!("{MARKER}true\n"),
        };
        let error = run_shellcheck_bodies(&catalog, staging.path(), &workflows, &tree(file))
            .expect_err("malformed generated shared paths fail closed");
        assert!(
            error.to_string().contains("shared_script_path_invalid"),
            "unexpected error for {path}: {error}"
        );
    }
    Ok(())
}

#[test]
fn shared_script_dialect_sets_the_temporary_shebang() -> Result<(), String> {
    let catalog = ToolCatalog::pinned();
    let body = "items=(one); test \"${items[0]}\" = one";
    let (bash, workflows) = staged_root()?;
    let bash_tree = tree(generated_file("bash", body));
    let original = bash_tree.files[0].bytes.clone();
    run_shellcheck_bodies(&catalog, bash.path(), &workflows, &bash_tree)
        .map_err(|err| err.to_string())?;
    assert_eq!(bash_tree.files[0].bytes, original);
    assert_eq!(
        fs::read_to_string(bash.path().join("shellcheck-1.bash")).map_err(|err| err.to_string())?,
        format!("#!/bin/bash\n{body}\n")
    );

    let (sh, workflows) = staged_root()?;
    let error = run_shellcheck_bodies(
        &catalog,
        sh.path(),
        &workflows,
        &tree(generated_file("sh", body)),
    )
    .expect_err("bash-only body fails under sh");
    assert!(matches!(
        error,
        OrchestratorError::Validation { tool, .. } if tool == "shellcheck"
    ));
    assert_eq!(
        fs::read_to_string(sh.path().join("shellcheck-1.sh")).map_err(|err| err.to_string())?,
        format!("#!/bin/sh\n{body}\n")
    );
    Ok(())
}

#[test]
fn shared_script_bodies_reach_warning_and_sc2086_passes() -> Result<(), String> {
    let catalog = ToolCatalog::pinned();
    let (warning, workflows) = staged_root()?;
    let warning_body = "echo $FOO/bar && [ -n $BAZ ]";
    let error = run_shellcheck_bodies(
        &catalog,
        warning.path(),
        &workflows,
        &tree(generated_file("sh", warning_body)),
    )
    .expect_err("warning in shared script fails the warning pass");
    assert!(error.to_string().contains("SC2070"));

    let (info, workflows) = staged_root()?;
    let error = run_shellcheck_bodies(
        &catalog,
        info.path(),
        &workflows,
        &tree(generated_file("bash", "echo $SHARED_VALUE\n")),
    )
    .expect_err("SC2086 in shared script fails the targeted pass");
    assert!(error.to_string().contains("SC2086"));
    Ok(())
}

#[test]
fn unrelated_github_shell_files_are_not_selected() {
    assert_eq!(shared_script_dialect(".github/scripts/check.sh"), None);
    assert_eq!(
        shared_script_dialect(".github/scripts/velnor-shared/local-helper.sh"),
        None
    );
}
