//! Pure anonymous source producer; fixed scripts never execute project code.

use crate::{OrchestratorError, workloads::cache_eligibility::NativeNpmSource};
use velnor_actions_contract::{
    CompiledSourceHelper, HelperInvocation, SourceBoundHelper, SourceBoundOperation, Step, StepId,
};
use velnor_actions_mise::{PinnedTool, ToolCatalog, catalog::qualification::DistributionHost};

const PROOF: &str = include_str!("workloads_cache_npm_proof.py");
const NATIVE: &str = include_str!("workloads_cache_npm_native.py");

/// Native companion expectations come solely from the selected tool catalog.
#[derive(Debug, serde::Serialize)]
pub(crate) struct NativeOwnerExpectation {
    node: String,
    npm: &'static str,
    module_abi: &'static str,
}

/// Exact versions expected from the catalog-selected native installation.
pub(crate) fn owner_expectation(catalog: &ToolCatalog) -> NativeOwnerExpectation {
    NativeOwnerExpectation {
        node: format!("v{}", catalog.version(PinnedTool::Node)),
        npm: velnor_actions_mise::catalog::NODE_NPM_VERSION,
        module_abi: velnor_actions_mise::catalog::NODE_MODULE_ABI_VERSION,
    }
}

/// Fixed engine composition; fixture execution supplies a non-main module name.
pub(crate) fn producer_code() -> String {
    let sanitizer = serde_json::json!(super::npm_sanitize::SANITIZE);
    format!("SANITIZER_CODE = {sanitizer}\n{PROOF}\n{NATIVE}")
}

/// Complete generated bytes and literal invocation own helper authority.
pub(crate) fn source_record(
    sources: &[NativeNpmSource],
    catalog: &ToolCatalog,
    host: DistributionHost,
    node_bin: &str,
    source_key: &str,
    version: &str,
) -> Result<CompiledSourceHelper, OrchestratorError> {
    let mut sources = sources.to_vec();
    sources.sort();
    sources.dedup();
    let owner = serde_json::to_string(&owner_expectation(catalog)).map_err(contract_error)?;
    let mut arguments = vec![node_bin.to_owned(), source_key.to_owned(), owner];
    for source in &sources {
        arguments.push(serde_json::to_string(source).map_err(contract_error)?);
    }
    let body = format!(
        "/usr/bin/env -i RUNNER_TEMP=\"$RUNNER_TEMP\" npm_config_cache=\"$npm_config_cache\" \
         GITHUB_OUTPUT=\"$GITHUB_OUTPUT\" /usr/bin/python3 -I - \"$@\" <<'VELNOR_FIXED_NPM_SOURCE'\n\
         __name__ = 'velnor_npm_source'\n{}\nmain()\nVELNOR_FIXED_NPM_SOURCE\n",
        producer_code()
    );
    let source = velnor_actions_contract::generated_source(version, &body)?;
    let operation = SourceBoundOperation::NpmPublicSourceProducer;
    let digest = velnor_actions_contract::compiled_source_sha256(source.as_bytes());
    arguments.insert(2, digest.clone());
    let helper = SourceBoundHelper::compiled(operation, operation.path(), &digest)?;
    let selectors = catalog.native_tool_specs(host, &[PinnedTool::Node])?;
    let invocation = HelperInvocation::compiled(helper, arguments, selectors)?;
    let mut environment = source_environment();
    environment.insert("VELNOR_SOURCE_IDENTITY".to_owned(), source_key.to_owned());
    Ok(CompiledSourceHelper::compiled(invocation, source)?.with_environment(environment))
}

/// Pure producer owns writes; descriptor arguments cannot be replaced by env.
pub(crate) fn source_step(
    sources: &[NativeNpmSource],
    catalog: &ToolCatalog,
    host: DistributionHost,
    node_bin: &str,
    source_key: &str,
    version: &str,
) -> Result<Step, OrchestratorError> {
    let record = source_record(sources, catalog, host, node_bin, source_key, version)?;
    let mut step = velnor_actions_workflow_renderer::source_helper::source_helper_step(
        "Populate proven npm public source cache",
        &record,
        record.environment().clone(),
    )?;
    step.id = Some(StepId::new("velnor-npm-public-proof").map_err(contract_error)?);
    Ok(step)
}

/// The runner shell and its interpreter ignore earlier task startup selectors.
fn source_environment() -> std::collections::BTreeMap<String, String> {
    let mut env = super::npm::task_env();
    env.insert("PATH".to_owned(), "/usr/bin:/bin".to_owned());
    for name in [
        "BASH_ENV",
        "ENV",
        "LD_PRELOAD",
        "LD_LIBRARY_PATH",
        "LD_AUDIT",
        "DYLD_INSERT_LIBRARIES",
        "DYLD_LIBRARY_PATH",
        "DYLD_FRAMEWORK_PATH",
        "DYLD_FALLBACK_LIBRARY_PATH",
        "DYLD_FALLBACK_FRAMEWORK_PATH",
        "PYTHONPATH",
        "PYTHONHOME",
    ] {
        env.insert(name.to_owned(), String::new());
    }
    for key in velnor_actions_workflow_renderer::source_helper::HELPER_STARTUP_KEYS {
        env.remove(key);
    }
    env
}

fn contract_error(error: impl std::fmt::Display) -> OrchestratorError {
    OrchestratorError::Contract {
        problem: error.to_string(),
    }
}

#[cfg(test)]
#[path = "workloads_cache_npm_native_tests.rs"]
mod native_tests;
#[cfg(test)]
#[path = "workloads_cache_npm_proof_tests.rs"]
mod tests;
