//! First-line generator-version marker prefix shared by every crate.
//!
//! Single source of truth: the renderer re-exports [`MARKER_PREFIX`] so
//! generated output and generated-output detectors agree byte-for-byte.

/// Marker text before the generator version.
pub const MARKER_PREFIX: &str = "# Generated by velnor-actions ";

#[cfg(test)]
mod tests {
    use super::MARKER_PREFIX;

    #[test]
    fn prefix_matches_rendered_first_line() {
        let first = "# Generated by velnor-actions 0.1.0 - DO NOT EDIT";
        assert!(first.starts_with(MARKER_PREFIX));
        assert_eq!(MARKER_PREFIX, "# Generated by velnor-actions ");
    }
}
