//! Deterministic actionlint.yaml generator cases.
use velnor_actions_actionlint::{
    ActionlintCapabilities, ActionlintConfigInput, ActionlintError, IgnoreEntry, IgnorePolicy,
    render_actionlint_yaml,
};

/// Default bytes from the generated-file contract template.
const DEFAULT_YAML: &str = "# Generated by Velnor Actions 0.1.0; edit .velnor/config.toml and regenerate.\n\nconfig-variables: []\n\nself-hosted-runner:\n  labels:\n    - ubuntu-26.04\n";

/// Sample generated workflow path shared by config cases.
const WORKFLOW: &str = ".github/workflows/velnor.yml";

fn narrow_ignore() -> IgnoreEntry {
    IgnoreEntry {
        rule: "shellcheck".to_owned(),
        path: WORKFLOW.to_owned(),
        justification: "approved SC2086 for quoted matrix expansion".to_owned(),
    }
}

#[test]
fn default_bytes_match_spec_template() {
    let input = ActionlintConfigInput::new("0.1.0");
    assert_eq!(
        render_actionlint_yaml(&input).map(|output| output.yaml),
        Ok(DEFAULT_YAML.to_owned())
    );
}

#[test]
fn config_bytes_are_deterministic() {
    let first = ActionlintConfigInput::new("0.1.0")
        .with_config_variable("ZULU")
        .with_config_variable("ALPHA")
        .with_config_variable("ALPHA");
    let second = ActionlintConfigInput::new("0.1.0")
        .with_config_variable("ALPHA")
        .with_config_variable("ZULU");
    let first_yaml = render_actionlint_yaml(&first).map(|output| output.yaml);
    let second_yaml = render_actionlint_yaml(&second).map(|output| output.yaml);
    assert!(first_yaml.is_ok());
    assert_eq!(first_yaml, second_yaml);
}

#[test]
fn config_variables_render_sorted() {
    let input = ActionlintConfigInput::new("0.1.0")
        .with_config_variable("ZULU")
        .with_config_variable("ALPHA");
    let expected = "# Generated by Velnor Actions 0.1.0; edit .velnor/config.toml and regenerate.\n\nconfig-variables:\n  - ALPHA\n  - ZULU\n\nself-hosted-runner:\n  labels:\n    - ubuntu-26.04\n";
    assert_eq!(
        render_actionlint_yaml(&input).map(|output| output.yaml),
        Ok(expected.to_owned())
    );
}

#[test]
fn bridge_removed_when_label_recognized() {
    let caps = ActionlintCapabilities::for_pinned().recognize_hosted_label_26_04();
    let input = ActionlintConfigInput::new("0.1.0").with_capabilities(caps);
    let expected = "# Generated by Velnor Actions 0.1.0; edit .velnor/config.toml and regenerate.\n\nconfig-variables: []\n";
    assert_eq!(
        render_actionlint_yaml(&input).map(|output| output.yaml),
        Ok(expected.to_owned())
    );
}

#[test]
fn ignores_empty_by_default() {
    let input = ActionlintConfigInput::new("0.1.0");
    assert_eq!(
        render_actionlint_yaml(&input).map(|output| output.approved_ignores),
        Ok(Vec::new())
    );
}

#[test]
fn consumer_ignore_rejected() {
    let input = ActionlintConfigInput::new("0.1.0")
        .with_workflow_path(WORKFLOW)
        .with_ignore(narrow_ignore());
    assert!(matches!(
        render_actionlint_yaml(&input),
        Err(ActionlintError::ConsumerIgnoreForbidden { .. })
    ));
}

#[test]
fn broad_ignore_glob_rejected() {
    let entry = IgnoreEntry {
        rule: "shellcheck".to_owned(),
        path: ".github/workflows/**".to_owned(),
        justification: "too broad".to_owned(),
    };
    let input = ActionlintConfigInput::new("0.1.0")
        .with_policy(IgnorePolicy::VelnorProtected)
        .with_workflow_path(WORKFLOW)
        .with_ignore(entry);
    assert!(matches!(
        render_actionlint_yaml(&input),
        Err(ActionlintError::BroadIgnore { .. })
    ));
}

#[test]
fn broad_ignore_outside_workflows_rejected() {
    let entry = IgnoreEntry {
        rule: "shellcheck".to_owned(),
        path: "*.yml".to_owned(),
        justification: "too broad".to_owned(),
    };
    let input = ActionlintConfigInput::new("0.1.0")
        .with_policy(IgnorePolicy::VelnorProtected)
        .with_workflow_path(WORKFLOW)
        .with_ignore(entry);
    assert!(matches!(
        render_actionlint_yaml(&input),
        Err(ActionlintError::BroadIgnore { .. })
    ));
}

#[test]
fn ignore_for_undeclared_workflow_rejected() {
    let input = ActionlintConfigInput::new("0.1.0")
        .with_policy(IgnorePolicy::VelnorProtected)
        .with_ignore(narrow_ignore());
    assert!(matches!(
        render_actionlint_yaml(&input),
        Err(ActionlintError::InvalidIgnore { .. })
    ));
}

#[test]
fn narrow_ignore_approved_with_justification() {
    let input = ActionlintConfigInput::new("0.1.0")
        .with_policy(IgnorePolicy::VelnorProtected)
        .with_workflow_path(WORKFLOW)
        .with_ignore(narrow_ignore());
    assert_eq!(
        render_actionlint_yaml(&input).map(|output| output.approved_ignores),
        Ok(vec![narrow_ignore()])
    );
}

#[test]
fn ignore_missing_justification_rejected() {
    let entry = IgnoreEntry {
        rule: "shellcheck".to_owned(),
        path: WORKFLOW.to_owned(),
        justification: "  ".to_owned(),
    };
    let input = ActionlintConfigInput::new("0.1.0")
        .with_policy(IgnorePolicy::VelnorProtected)
        .with_workflow_path(WORKFLOW)
        .with_ignore(entry);
    assert!(matches!(
        render_actionlint_yaml(&input),
        Err(ActionlintError::InvalidIgnore { .. })
    ));
}

#[test]
fn generator_version_injection_rejected() {
    let newline = ActionlintConfigInput::new("0.1.0\nconfig-variables: [X]");
    assert!(matches!(
        render_actionlint_yaml(&newline),
        Err(ActionlintError::InvalidGeneratorVersion { .. })
    ));
    let empty = ActionlintConfigInput::new("");
    assert!(matches!(
        render_actionlint_yaml(&empty),
        Err(ActionlintError::InvalidGeneratorVersion { .. })
    ));
}

#[test]
fn reserved_and_malformed_variables_rejected() {
    let reserved = ActionlintConfigInput::new("0.1.0").with_config_variable("GITHUB_TOKEN_NAME");
    assert!(matches!(
        render_actionlint_yaml(&reserved),
        Err(ActionlintError::InvalidConfigVariable { .. })
    ));
    let leading_digit = ActionlintConfigInput::new("0.1.0").with_config_variable("9LIVES");
    assert!(matches!(
        render_actionlint_yaml(&leading_digit),
        Err(ActionlintError::InvalidConfigVariable { .. })
    ));
}

#[test]
fn invalid_workflow_paths_rejected() {
    for path in [
        "workflows/velnor.yml",
        "/.github/workflows/velnor.yml",
        ".github/workflows/../evil.yml",
        ".github/workflows/velnor.yaml.bak",
        ".github/workflows/*.yml",
    ] {
        let input = ActionlintConfigInput::new("0.1.0").with_workflow_path(path);
        assert!(
            matches!(
                render_actionlint_yaml(&input),
                Err(ActionlintError::InvalidWorkflowPath { .. })
            ),
            "path must be rejected: {path}"
        );
    }
}
