//! Deterministic actionlint.yaml generator cases.
use velnor_actions_actionlint::{
    ActionlintCapabilities, ActionlintConfigInput, ActionlintError, IgnoreEntry, IgnorePolicy,
    config::{ZizmorConfigInput, ZizmorWorkflowText, render_zizmor_yaml},
    render_actionlint_yaml,
};

/// Default bytes from the generated-file contract template.
const DEFAULT_YAML: &str = "# Generated by Velnor Actions 0.1.0; edit .velnor/config.toml and regenerate.\n\nconfig-variables: []\n\nself-hosted-runner:\n  labels:\n    - ubuntu-26.04\n";

/// Sample generated workflow path shared by config cases.
const WORKFLOW: &str = ".github/workflows/velnor.yml";

fn narrow_ignore() -> IgnoreEntry {
    IgnoreEntry {
        rule: "shellcheck".to_owned(),
        path: WORKFLOW.to_owned(),
        justification: "approved SC2086 for quoted matrix expansion".to_owned(),
    }
}

#[test]
fn default_bytes_match_spec_template() {
    let input = ActionlintConfigInput::new("0.1.0");
    assert_eq!(
        render_actionlint_yaml(&input).map(|output| output.yaml),
        Ok(DEFAULT_YAML.to_owned())
    );
}

#[test]
fn config_bytes_are_deterministic() {
    let first = ActionlintConfigInput::new("0.1.0")
        .with_config_variable("ZULU")
        .with_config_variable("ALPHA")
        .with_config_variable("ALPHA");
    let second = ActionlintConfigInput::new("0.1.0")
        .with_config_variable("ALPHA")
        .with_config_variable("ZULU");
    let first_yaml = render_actionlint_yaml(&first).map(|output| output.yaml);
    let second_yaml = render_actionlint_yaml(&second).map(|output| output.yaml);
    assert!(first_yaml.is_ok());
    assert_eq!(first_yaml, second_yaml);
}

#[test]
fn config_variables_render_sorted() {
    let input = ActionlintConfigInput::new("0.1.0")
        .with_config_variable("ZULU")
        .with_config_variable("ALPHA");
    let expected = "# Generated by Velnor Actions 0.1.0; edit .velnor/config.toml and regenerate.\n\nconfig-variables:\n  - ALPHA\n  - ZULU\n\nself-hosted-runner:\n  labels:\n    - ubuntu-26.04\n";
    assert_eq!(
        render_actionlint_yaml(&input).map(|output| output.yaml),
        Ok(expected.to_owned())
    );
}

#[test]
fn config_variables_emit_exact_declared_set() {
    let input = ActionlintConfigInput::new("0.1.0")
        .with_config_variable("ZULU")
        .with_config_variable("ALPHA")
        .with_config_variable("ZULU");
    let output = render_actionlint_yaml(&input).expect("renders");
    let mut in_variables = false;
    let mut rendered = Vec::new();
    for line in output.yaml.lines() {
        if line == "config-variables:" {
            in_variables = true;
            continue;
        }
        if in_variables {
            if let Some(name) = line.strip_prefix("  - ") {
                rendered.push(name.to_owned());
            } else {
                break;
            }
        }
    }
    assert_eq!(rendered, vec!["ALPHA".to_owned(), "ZULU".to_owned()]);
    let empty = render_actionlint_yaml(&ActionlintConfigInput::new("0.1.0")).expect("renders");
    assert!(empty.yaml.contains("config-variables: []"));
}

/// Filesystem/process/network tokens that must never appear in config sources.
const FORBIDDEN_TOKENS: &[&str] = &[
    "init-config",
    "Command",
    "std::process",
    "reqwest",
    "ureq",
    "fetch(",
    "fetch_",
    "from_url",
    "Url::",
    "download(",
    "TcpStream",
];

#[test]
fn config_render_never_inits_or_fetches() {
    let src = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("src");
    let entries = std::fs::read_dir(&src).expect("src readable");
    let mut checked = 0;
    for entry in entries {
        let path = entry.expect("entry readable").path();
        if path.extension().is_none_or(|ext| ext != "rs") {
            continue;
        }
        let text = std::fs::read_to_string(&path).expect("source readable");
        checked += 1;
        let code: String = text
            .lines()
            .map(|line| line.split("//").next().unwrap_or_default())
            .collect::<Vec<_>>()
            .join("\n");
        for token in FORBIDDEN_TOKENS {
            assert!(
                !code.contains(token),
                "forbidden token {token} in {}",
                path.display()
            );
        }
    }
    assert!(checked > 0, "at least one source file must be scanned");
}

#[test]
fn bridge_removed_when_label_recognized() {
    let caps = ActionlintCapabilities::for_pinned().recognize_hosted_label_26_04();
    let input = ActionlintConfigInput::new("0.1.0").with_capabilities(caps);
    let expected = "# Generated by Velnor Actions 0.1.0; edit .velnor/config.toml and regenerate.\n\nconfig-variables: []\n";
    assert_eq!(
        render_actionlint_yaml(&input).map(|output| output.yaml),
        Ok(expected.to_owned())
    );
}

#[test]
fn ignores_empty_by_default() {
    let input = ActionlintConfigInput::new("0.1.0");
    assert_eq!(
        render_actionlint_yaml(&input).map(|output| output.approved_ignores),
        Ok(Vec::new())
    );
}

#[test]
fn consumer_ignore_rejected() {
    let input = ActionlintConfigInput::new("0.1.0")
        .with_workflow_path(WORKFLOW)
        .with_ignore(narrow_ignore());
    assert!(matches!(
        render_actionlint_yaml(&input),
        Err(ActionlintError::ConsumerIgnoreForbidden { .. })
    ));
}

#[test]
fn broad_ignore_glob_rejected() {
    let entry = IgnoreEntry {
        rule: "shellcheck".to_owned(),
        path: ".github/workflows/**".to_owned(),
        justification: "too broad".to_owned(),
    };
    let input = ActionlintConfigInput::new("0.1.0")
        .with_policy(IgnorePolicy::VelnorProtected)
        .with_workflow_path(WORKFLOW)
        .with_ignore(entry);
    assert!(matches!(
        render_actionlint_yaml(&input),
        Err(ActionlintError::BroadIgnore { .. })
    ));
}

#[test]
fn broad_ignore_outside_workflows_rejected() {
    let entry = IgnoreEntry {
        rule: "shellcheck".to_owned(),
        path: "*.yml".to_owned(),
        justification: "too broad".to_owned(),
    };
    let input = ActionlintConfigInput::new("0.1.0")
        .with_policy(IgnorePolicy::VelnorProtected)
        .with_workflow_path(WORKFLOW)
        .with_ignore(entry);
    assert!(matches!(
        render_actionlint_yaml(&input),
        Err(ActionlintError::BroadIgnore { .. })
    ));
}

#[test]
fn ignore_for_undeclared_workflow_rejected() {
    let input = ActionlintConfigInput::new("0.1.0")
        .with_policy(IgnorePolicy::VelnorProtected)
        .with_ignore(narrow_ignore());
    assert!(matches!(
        render_actionlint_yaml(&input),
        Err(ActionlintError::InvalidIgnore { .. })
    ));
}

#[test]
fn narrow_ignore_approved_with_justification() {
    let input = ActionlintConfigInput::new("0.1.0")
        .with_policy(IgnorePolicy::VelnorProtected)
        .with_workflow_path(WORKFLOW)
        .with_ignore(narrow_ignore());
    assert_eq!(
        render_actionlint_yaml(&input).map(|output| output.approved_ignores),
        Ok(vec![narrow_ignore()])
    );
}

#[test]
fn ignore_missing_justification_rejected() {
    let entry = IgnoreEntry {
        rule: "shellcheck".to_owned(),
        path: WORKFLOW.to_owned(),
        justification: "  ".to_owned(),
    };
    let input = ActionlintConfigInput::new("0.1.0")
        .with_policy(IgnorePolicy::VelnorProtected)
        .with_workflow_path(WORKFLOW)
        .with_ignore(entry);
    assert!(matches!(
        render_actionlint_yaml(&input),
        Err(ActionlintError::InvalidIgnore { .. })
    ));
}

#[test]
fn generator_version_injection_rejected() {
    let newline = ActionlintConfigInput::new("0.1.0\nconfig-variables: [X]");
    assert!(matches!(
        render_actionlint_yaml(&newline),
        Err(ActionlintError::InvalidGeneratorVersion { .. })
    ));
    let empty = ActionlintConfigInput::new("");
    assert!(matches!(
        render_actionlint_yaml(&empty),
        Err(ActionlintError::InvalidGeneratorVersion { .. })
    ));
}

#[test]
fn reserved_and_malformed_variables_rejected() {
    let reserved = ActionlintConfigInput::new("0.1.0").with_config_variable("GITHUB_TOKEN_NAME");
    assert!(matches!(
        render_actionlint_yaml(&reserved),
        Err(ActionlintError::InvalidConfigVariable { .. })
    ));
    let leading_digit = ActionlintConfigInput::new("0.1.0").with_config_variable("9LIVES");
    assert!(matches!(
        render_actionlint_yaml(&leading_digit),
        Err(ActionlintError::InvalidConfigVariable { .. })
    ));
}

#[test]
fn invalid_workflow_paths_rejected() {
    for path in [
        "workflows/velnor.yml",
        "/.github/workflows/velnor.yml",
        ".github/workflows/../evil.yml",
        ".github/workflows/velnor.yaml.bak",
        ".github/workflows/*.yml",
    ] {
        let input = ActionlintConfigInput::new("0.1.0").with_workflow_path(path);
        assert!(
            matches!(
                render_actionlint_yaml(&input),
                Err(ActionlintError::InvalidWorkflowPath { .. })
            ),
            "path must be rejected: {path}"
        );
    }
}

/// Workflow text with the blessed tag on line 3, ref at column 15.
fn blessed_text() -> String {
    "# Generated by Velnor Actions 0.1.0 - DO NOT EDIT\nname: CI\n        uses: asamarts/alint@v0.16.1 # v0.16.1\n"
        .to_owned()
}

fn zizmor_input(text: &str) -> ZizmorConfigInput {
    ZizmorConfigInput {
        generator_version: "0.1.0".to_owned(),
        workflows: vec![ZizmorWorkflowText {
            path: WORKFLOW.to_owned(),
            text: text.to_owned(),
        }],
    }
}

#[test]
fn zizmor_blessed_tag_ignores_exact_location() {
    let output = render_zizmor_yaml(&zizmor_input(&blessed_text()));
    assert_eq!(
        output.map(|output| output.approved_ignores),
        Ok(vec!["velnor.yml:3:15".to_owned()])
    );
}

#[test]
fn zizmor_bytes_match_template_with_policy_citation() {
    let expected = "# Generated by Velnor Actions 0.1.0 for staged zizmor validation; never commit.\n# Version-policy exception (docs/proposed/version-policy.md §2): exactly\n# uses asamarts/alint@v0.16.1 may stay tag-pinned; every\n# other ref still requires a hash (implicit \"*\": hash-pin).\nrules:\n  unpinned-uses:\n    ignore:\n      - velnor.yml:3:15  # expires: alint reviewed-tag exception review (version-policy §2)\n";
    assert_eq!(
        render_zizmor_yaml(&zizmor_input(&blessed_text())).map(|output| output.yaml),
        Ok(expected.to_owned())
    );
}

#[test]
fn zizmor_ignores_carry_expiry_comments() {
    let output = render_zizmor_yaml(&zizmor_input(&blessed_text())).expect("renders");
    assert!(!output.approved_ignores.is_empty());
    let mut entries = 0;
    for line in output.yaml.lines() {
        if !line.starts_with("      - ") {
            continue;
        }
        entries += 1;
        assert!(line.contains("# expires:"), "ignore without expiry: {line}");
    }
    assert_eq!(entries, output.approved_ignores.len());
    for rule in &output.approved_ignores {
        let parts: Vec<&str> = rule.split(':').collect();
        assert_eq!(parts.len(), 3, "narrow file:line:col: {rule}");
        assert!(parts[1].chars().all(|c| c.is_ascii_digit()));
        assert!(parts[2].chars().all(|c| c.is_ascii_digit()));
    }
}

#[test]
fn zizmor_consumer_tree_has_no_ignores() {
    let text = "name: CI\n        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1\n";
    let output = render_zizmor_yaml(&zizmor_input(text)).expect("consumer renders");
    assert!(output.approved_ignores.is_empty());
    assert!(output.yaml.ends_with("    ignore: []\n"));
}

#[test]
fn zizmor_longer_tag_prefix_not_matched() {
    let text = "name: CI\n        uses: asamarts/alint@v0.16.10 # v0.16.10\n";
    let output = render_zizmor_yaml(&zizmor_input(text)).expect("renders");
    assert!(output.approved_ignores.is_empty(), "prefix is not exact");
}

#[test]
fn zizmor_bytes_deterministic_across_workflow_order() {
    let blessed = ZizmorWorkflowText {
        path: WORKFLOW.to_owned(),
        text: blessed_text(),
    };
    let other = ZizmorWorkflowText {
        path: ".github/workflows/other.yml".to_owned(),
        text: "name: Other\n".to_owned(),
    };
    let first = ZizmorConfigInput {
        generator_version: "0.1.0".to_owned(),
        workflows: vec![blessed.clone(), other.clone()],
    };
    let second = ZizmorConfigInput {
        generator_version: "0.1.0".to_owned(),
        workflows: vec![other, blessed],
    };
    let first_yaml = render_zizmor_yaml(&first).map(|output| output.yaml);
    let second_yaml = render_zizmor_yaml(&second).map(|output| output.yaml);
    assert!(first_yaml.is_ok());
    assert_eq!(first_yaml, second_yaml);
}

#[test]
fn zizmor_bad_version_and_path_rejected() {
    let bad_version = ZizmorConfigInput {
        generator_version: String::new(),
        workflows: Vec::new(),
    };
    assert!(matches!(
        render_zizmor_yaml(&bad_version),
        Err(ActionlintError::InvalidGeneratorVersion { .. })
    ));
    let bad_path = ZizmorConfigInput {
        generator_version: "0.1.0".to_owned(),
        workflows: vec![ZizmorWorkflowText {
            path: ".github/workflows/*.yml".to_owned(),
            text: blessed_text(),
        }],
    };
    assert!(matches!(
        render_zizmor_yaml(&bad_path),
        Err(ActionlintError::InvalidWorkflowPath { .. })
    ));
}
