//! Profile evidence cases.
use velnor_actions_rust::{
    CompileDriver, EvidenceFile, NEXTEST_RECOMMENDATION, PERSIST_EVIDENCE, ProfileError,
    ProfileInputs, TestRunner, detect_profile, evidence_scan_excluded, is_generated_output,
};

/// Wrap `content` read from `path` as evidence input.
fn file<'a>(path: &'a str, content: &'a str) -> EvidenceFile<'a> {
    EvidenceFile { path, content }
}

/// Recommendation codes of an outcome, in order.
fn codes(outcome: &velnor_actions_rust::ProfileOutcome) -> Vec<&str> {
    outcome
        .recommendations
        .iter()
        .map(|item| item.code.as_str())
        .collect()
}

#[test]
fn tool_setting_selects_mbx() {
    let inputs = ProfileInputs {
        tool_config: Some(file("mise.toml", "[tools.rust]\nmr_boxington = true\n")),
        ..ProfileInputs::default()
    };
    let outcome = detect_profile(&inputs);
    let Ok(outcome) = outcome else {
        panic!("tool setting must select a profile");
    };
    assert_eq!(outcome.profile.compile_driver, CompileDriver::Mbx);
    assert_eq!(outcome.profile.test_runner, TestRunner::CargoTest);
    assert_eq!(outcome.profile.evidence.len(), 1);
    assert_eq!(outcome.profile.evidence[0].path, "mise.toml");
    assert_eq!(outcome.profile.evidence[0].line, 2);
    assert_eq!(codes(&outcome), vec![NEXTEST_RECOMMENDATION]);
}

#[test]
fn tool_pin_without_setting_is_not_evidence() {
    let inputs = ProfileInputs {
        tool_config: Some(file("mise.toml", "[tools]\nmr-boxington = \"1.2.3\"\n")),
        ..ProfileInputs::default()
    };
    let Ok(outcome) = detect_profile(&inputs) else {
        panic!("tool pin must fall back to defaults");
    };
    assert_eq!(outcome.profile.compile_driver, CompileDriver::Cargo);
    assert_eq!(
        outcome.profile.evidence,
        [] as [velnor_actions_rust::Evidence; 0]
    );
    assert_eq!(
        codes(&outcome),
        vec![NEXTEST_RECOMMENDATION, PERSIST_EVIDENCE]
    );
}

#[test]
fn rustc_wrapper_naming_mbx_selects_mbx() {
    let inputs = ProfileInputs {
        cargo_configs: vec![file(
            ".cargo/config.toml",
            "[build]\nrustc-wrapper = \"mbx\"\n",
        )],
        ..ProfileInputs::default()
    };
    let Ok(outcome) = detect_profile(&inputs) else {
        panic!("rustc wrapper must select MBX");
    };
    assert_eq!(outcome.profile.compile_driver, CompileDriver::Mbx);
    let plain = ProfileInputs {
        cargo_configs: vec![file(
            ".cargo/config.toml",
            "[build]\nrustc-wrapper = \"sccache\"\n",
        )],
        ..ProfileInputs::default()
    };
    let Ok(plain) = detect_profile(&plain) else {
        panic!("plain wrapper must fall back");
    };
    assert_eq!(plain.profile.compile_driver, CompileDriver::Cargo);
}

#[test]
fn executable_invoking_mbx_selects_mbx() {
    let inputs = ProfileInputs {
        executables: vec![file(
            ".mise/tasks/test",
            "#!/usr/bin/env bash\nmbx test --package a\n",
        )],
        ..ProfileInputs::default()
    };
    let Ok(outcome) = detect_profile(&inputs) else {
        panic!("mbx invocation must select a profile");
    };
    assert_eq!(outcome.profile.compile_driver, CompileDriver::Mbx);
    assert_eq!(outcome.profile.test_runner, TestRunner::CargoTest);
    assert_eq!(
        outcome.recommendations,
        [] as [velnor_actions_rust::Recommendation; 0]
    );
}

#[test]
fn handwritten_workflow_invoking_mbx_is_strong_evidence() {
    let inputs = ProfileInputs {
        handwritten_workflows: vec![file(
            ".github/workflows/ci.yml",
            "jobs:\n  build:\n    steps:\n      - run: mbx clippy --package a\n",
        )],
        ..ProfileInputs::default()
    };
    let Ok(outcome) = detect_profile(&inputs) else {
        panic!("hand-written workflow must count as evidence");
    };
    assert_eq!(outcome.profile.compile_driver, CompileDriver::Mbx);
    assert_eq!(
        codes(&outcome),
        vec![NEXTEST_RECOMMENDATION, PERSIST_EVIDENCE]
    );
}

#[test]
fn generated_output_is_never_evidence() {
    let generated = "# Generated by Velnor Actions 1.2.3; edit .velnor/config.toml and regenerate.\nrun: mbx clippy\nrun: cargo nextest run\n";
    assert!(is_generated_output(generated));
    let inputs = ProfileInputs {
        executables: vec![file("preview/.github/workflows/ci.yml", generated)],
        tool_config: Some(file("mise.toml", generated)),
        ..ProfileInputs::default()
    };
    let Ok(outcome) = detect_profile(&inputs) else {
        panic!("generated output must fall back to defaults");
    };
    assert_eq!(outcome.profile.compile_driver, CompileDriver::Cargo);
    assert_eq!(outcome.profile.test_runner, TestRunner::CargoTest);
    assert_eq!(
        outcome.profile.evidence,
        [] as [velnor_actions_rust::Evidence; 0]
    );
}

#[test]
fn scan_excludes_output_docs_locks_and_caches() {
    for path in [
        ".github/workflows/ci.yml",
        "README.md",
        "docs/guide.md",
        "CHANGELOG.rst",
        "Cargo.lock",
        "mise.lock",
        "crates/a/Cargo.lock",
        "target/debug/build",
        "crates/a/target/debug",
        ".git/config",
    ] {
        assert!(evidence_scan_excluded(path), "must be excluded: {path}");
    }
    for path in [
        "src/main.rs",
        ".mise/tasks/test",
        "scripts/check.sh",
        "mise.toml",
        ".cargo/config.toml",
    ] {
        assert!(!evidence_scan_excluded(path), "must be scanned: {path}");
    }
}

#[test]
fn comments_and_pins_are_not_evidence() {
    let inputs = ProfileInputs {
        executables: vec![file(
            "scripts/check.sh",
            "# mbx clippy --package a\nmise use mr-boxington@1.2.3\n",
        )],
        handwritten_workflows: vec![file(
            ".github/workflows/ci.yml",
            "steps:\n  - uses: jdx/mr-boxington-action@v1\n  - uses: taiki-e/install-action@nextest\n",
        )],
        ..ProfileInputs::default()
    };
    let Ok(outcome) = detect_profile(&inputs) else {
        panic!("comments and pins must fall back to defaults");
    };
    assert_eq!(
        outcome.profile.evidence,
        [] as [velnor_actions_rust::Evidence; 0]
    );
    assert_eq!(outcome.profile.compile_driver, CompileDriver::Cargo);
}

#[test]
fn nextest_invocation_selects_nextest() {
    let inputs = ProfileInputs {
        executables: vec![file("scripts/test.sh", "cargo nextest run --package a\n")],
        ..ProfileInputs::default()
    };
    let Ok(outcome) = detect_profile(&inputs) else {
        panic!("nextest invocation must select Nextest");
    };
    assert_eq!(outcome.profile.test_runner, TestRunner::CargoNextest);
    assert_eq!(outcome.profile.compile_driver, CompileDriver::Cargo);
    let via_mbx = ProfileInputs {
        executables: vec![file("scripts/test.sh", "mbx nextest run --package a\n")],
        ..ProfileInputs::default()
    };
    let Ok(via_mbx) = detect_profile(&via_mbx) else {
        panic!("mbx nextest must select both");
    };
    assert_eq!(via_mbx.profile.test_runner, TestRunner::CargoNextest);
    assert_eq!(via_mbx.profile.compile_driver, CompileDriver::Mbx);
}

#[test]
fn cargo_test_invocation_selects_cargo_test() {
    let inputs = ProfileInputs {
        executables: vec![file("scripts/test.sh", "cargo test --package a --locked\n")],
        ..ProfileInputs::default()
    };
    let Ok(outcome) = detect_profile(&inputs) else {
        panic!("cargo test must select a profile");
    };
    assert_eq!(outcome.profile.test_runner, TestRunner::CargoTest);
    assert_eq!(
        outcome.recommendations,
        [] as [velnor_actions_rust::Recommendation; 0]
    );
}

#[test]
fn conflicting_runners_rejected() {
    let inputs = ProfileInputs {
        executables: vec![
            file("scripts/a.sh", "cargo test --package a\n"),
            file("scripts/b.sh", "cargo nextest run --package b\n"),
        ],
        ..ProfileInputs::default()
    };
    let result = detect_profile(&inputs);
    let Err(ProfileError::AmbiguousTestRunner { evidence }) = result else {
        panic!("conflicting runners must fail");
    };
    assert_eq!(evidence.len(), 2);
    assert!(evidence.windows(2).all(|pair| pair[0] <= pair[1]));
}

#[test]
fn no_evidence_defaults_with_both_recommendations() {
    let Ok(outcome) = detect_profile(&ProfileInputs::default()) else {
        panic!("empty inputs must fall back to defaults");
    };
    assert_eq!(outcome.profile.compile_driver, CompileDriver::Cargo);
    assert_eq!(outcome.profile.test_runner, TestRunner::CargoTest);
    assert_eq!(
        codes(&outcome),
        vec![NEXTEST_RECOMMENDATION, PERSIST_EVIDENCE]
    );
}

#[test]
fn nextest_pin_without_invocation_is_not_evidence() {
    let inputs = ProfileInputs {
        executables: vec![file("scripts/setup.sh", "mise use cargo-nextest@0.9.102\n")],
        ..ProfileInputs::default()
    };
    let Ok(outcome) = detect_profile(&inputs) else {
        panic!("nextest pin must fall back to defaults");
    };
    assert_eq!(outcome.profile.test_runner, TestRunner::CargoTest);
    assert_eq!(
        outcome.profile.evidence,
        [] as [velnor_actions_rust::Evidence; 0]
    );
}
