//! F2 closure cases: committed-header comparison, alint content, ownership.
use std::path::PathBuf;

use velnor_actions_rust::tasks::{DigestSlot, parse_rerun_changed};
use velnor_actions_rust::{
    CompileDriver, EvidenceFile, NextestProfile, ProfileInputs, TaskGroup, TaskKind, TestRunner,
    committed_profile_differs, detect_profile, inspect_toolchain_file, is_generated_output,
    read_committed_profile_for_comparison,
};

/// One derived group for producer-identity checks.
fn group() -> TaskGroup {
    TaskGroup {
        task_id: "stack/rust/root/test/default".to_owned(),
        package_id: "demo 0.1.0".to_owned(),
        package_name: "demo".to_owned(),
        manifest_key: "root".to_owned(),
        kind: TaskKind::Test,
        configuration: "default".to_owned(),
        features: vec!["default".to_owned()],
        target: "host".to_owned(),
        gated_by: Vec::new(),
        depends_on: Vec::new(),
        target_flags: Vec::new(),
        no_test_targets: false,
        package_arg: None,
        compile_driver: CompileDriver::Cargo,
        test_runner: TestRunner::CargoTest,
        declared_inputs: Vec::new(),
        undeclared_reads: false,
        uses_network: false,
        uses_clock: false,
        uses_random: false,
        run_ignored: None,
        nextest_profile: NextestProfile::Default,
    }
}

#[test]
fn committed_header_read_is_comparison_only() {
    let generated = "# Generated by Velnor Actions 0.1.0; edit .velnor/config.toml and regenerate.\nrun: cargo nextest run --package a\nrun: mbx build --locked\n";
    assert!(is_generated_output(generated));
    let inputs = ProfileInputs {
        executables: vec![EvidenceFile {
            path: ".github/workflows/ci.yml",
            content: generated,
        }],
        ..ProfileInputs::default()
    };
    let outcome = detect_profile(&inputs).expect("profile");
    assert_eq!(
        outcome.profile.evidence,
        [] as [velnor_actions_rust::Evidence; 0]
    );
    let committed = read_committed_profile_for_comparison(generated).expect("committed");
    assert_eq!(committed.compile_driver, CompileDriver::Mbx);
    assert_eq!(committed.test_runner, TestRunner::CargoNextest);
    assert!(committed_profile_differs(
        Some(&committed),
        CompileDriver::Cargo,
        TestRunner::CargoTest
    ));
    assert!(!committed_profile_differs(
        Some(&committed),
        CompileDriver::Mbx,
        TestRunner::CargoNextest
    ));
    assert!(!committed_profile_differs(
        None,
        CompileDriver::Cargo,
        TestRunner::CargoTest
    ));
    assert!(read_committed_profile_for_comparison("run: cargo nextest run\n").is_none());
    let quiet = "# Generated by Velnor Actions 0.1.0; edit .velnor/config.toml and regenerate.\nrun: echo hi\n";
    assert!(read_committed_profile_for_comparison(quiet).is_none());
}

#[test]
fn declared_inputs_shift_extension_identity() {
    let first = parse_rerun_changed("cargo::rerun-if-changed=proto/a.proto\n");
    let second = parse_rerun_changed("cargo::rerun-if-changed=proto/b.proto\n");
    let one = group().with_rerun_inputs(&first).expect("attach");
    let two = group().with_rerun_inputs(&second).expect("attach");
    let targets = vec!["lib".to_owned()];
    let digests_for = |group: &TaskGroup| {
        group.identity_extension(&velnor_actions_rust::GroupExtensionInputs {
            package_id: "demo 0.1.0",
            workspace_id: "workspace",
            profile: "default",
            manifest: "Cargo.toml",
            graph_digest: "graph",
            targets: &targets,
            config_digest: "config",
            lock_digest: DigestSlot::Unknown("unprobed".to_owned()),
            nextest_digest: DigestSlot::Unknown("unprobed".to_owned()),
            archive_source: None,
            rerun_inputs: Some(&[]),
            has_build_script: false,
        })
    };
    let left = serde_json::to_value(digests_for(&one)).expect("serialize");
    let right = serde_json::to_value(digests_for(&two)).expect("serialize");
    assert_ne!(left, right);
}

#[test]
fn toolchain_inspection_never_fails_never_writes() {
    for content in [
        "",
        "\0\0not toml [[[\n",
        "[toolchain]\nchannel = \"stable\"\n",
    ] {
        let inspection =
            inspect_toolchain_file("rust-toolchain.toml", Some(content)).expect("never fails");
        for finding in &inspection.findings {
            assert_eq!(finding.file, "rust-toolchain.toml");
            assert_ne!(finding.code, "");
            assert_ne!(finding.recommendation, "");
        }
    }
    let missing = inspect_toolchain_file("rust-toolchain.toml", None).expect("never fails");
    assert_eq!(missing.findings.len(), 1);
    assert_ne!(missing.findings[0].recommendation, "");
}

#[test]
fn rust_never_inspects_mise_files() {
    let src = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("src");
    let entries = std::fs::read_dir(&src).expect("src readable");
    for entry in entries {
        let entry = entry.expect("entry");
        let path = entry.path();
        if path.extension().is_none_or(|ext| ext != "rs") {
            continue;
        }
        let text = std::fs::read_to_string(&path).expect("readable");
        let name = path
            .file_name()
            .expect("name")
            .to_string_lossy()
            .into_owned();
        for (index, line) in text.lines().enumerate() {
            let mentions =
                line.contains("mise.toml") || line.contains("mise.lock") || line.contains("MISE_");
            if !mentions {
                continue;
            }
            assert!(
                name == "toolfiles.rs" || name == "evidence.rs",
                "mise mention outside router/classifier: {name}"
            );
            assert!(
                !line.contains("parse") && !line.contains("from_str") && !line.contains("inspect"),
                "rust must route or classify mise files, never parse them ({}:{})",
                name,
                index + 1
            );
        }
    }
}
