//! Gap C cases: marker compatibility, durability, declarations, conflicts.
use velnor_actions_rust::{
    CompileDriver, EvidenceFile, PROFILE_CONFLICT_CODE, ProfileError, ProfileInputs, ProfileSource,
    TRANSIENT_EVIDENCE_CODE, TestRunner, detect_profile, is_generated_output,
};

/// Wrap `content` read from `path` as evidence input.
fn file<'a>(path: &'a str, content: &'a str) -> EvidenceFile<'a> {
    EvidenceFile { path, content }
}

/// Generated body invoking both MBX and Nextest under `marker`.
fn generated(marker: &str) -> String {
    format!("{marker}\nrun: mbx clippy --package a\nrun: cargo nextest run\n")
}

#[test]
fn old_marker_output_is_never_evidence() {
    let content = generated("# Generated by velnor-actions 0.1.0 - DO NOT EDIT");
    assert!(is_generated_output(&content));
    let inputs = ProfileInputs {
        handwritten_workflows: vec![file(".github/workflows/ci.yml", &content)],
        ..ProfileInputs::default()
    };
    let Ok(outcome) = detect_profile(&inputs) else {
        panic!("old-marker output must fall back to defaults");
    };
    assert_eq!(outcome.profile.compile_driver, CompileDriver::Cargo);
    assert_eq!(outcome.profile.test_runner, TestRunner::CargoTest);
    assert_eq!(
        outcome.profile.evidence,
        [] as [velnor_actions_rust::Evidence; 0]
    );
    assert_eq!(
        outcome.findings,
        [] as [velnor_actions_rust::ProfileFinding; 0]
    );
}

#[test]
fn new_marker_output_is_never_evidence() {
    let content =
        generated("# Generated by Velnor Actions 0.1.0; edit .velnor/config.toml and regenerate.");
    assert!(is_generated_output(&content));
    let inputs = ProfileInputs {
        handwritten_workflows: vec![file(".github/workflows/ci.yml", &content)],
        ..ProfileInputs::default()
    };
    let Ok(outcome) = detect_profile(&inputs) else {
        panic!("new-marker output must fall back to defaults");
    };
    assert_eq!(outcome.profile.compile_driver, CompileDriver::Cargo);
    assert_eq!(
        outcome.profile.evidence,
        [] as [velnor_actions_rust::Evidence; 0]
    );
    assert_eq!(
        outcome.findings,
        [] as [velnor_actions_rust::ProfileFinding; 0]
    );
}

#[test]
fn handwritten_workflow_evidence_is_transient() {
    let inputs = ProfileInputs {
        handwritten_workflows: vec![file(
            ".github/workflows/ci.yml",
            "jobs:\n  build:\n    steps:\n      - run: mbx clippy --package a\n",
        )],
        ..ProfileInputs::default()
    };
    let Ok(outcome) = detect_profile(&inputs) else {
        panic!("hand-written workflow must select a profile");
    };
    assert_eq!(outcome.profile.compile_driver, CompileDriver::Mbx);
    assert_eq!(outcome.profile.evidence.len(), 1);
    assert_eq!(outcome.profile.evidence[0].strength.as_str(), "transient");
    assert_eq!(outcome.findings.len(), 1);
    assert_eq!(outcome.findings[0].code, TRANSIENT_EVIDENCE_CODE);
    assert!(
        outcome.findings[0]
            .message
            .contains("[stacks.rust] compile_driver")
    );
    assert!(
        outcome.findings[0]
            .message
            .contains("durable executable task outside .github")
    );
}

#[test]
fn executable_evidence_is_durable() {
    let inputs = ProfileInputs {
        executables: vec![file(
            ".mise/tasks/test",
            "#!/usr/bin/env bash\nmbx test --package a\n",
        )],
        ..ProfileInputs::default()
    };
    let Ok(outcome) = detect_profile(&inputs) else {
        panic!("executable must select a profile");
    };
    assert_eq!(outcome.profile.compile_driver, CompileDriver::Mbx);
    assert!(
        outcome
            .profile
            .evidence
            .iter()
            .all(|sighting| sighting.strength.as_str() == "durable")
    );
    assert_eq!(
        outcome.findings,
        [] as [velnor_actions_rust::ProfileFinding; 0]
    );
}

#[test]
fn declared_profile_is_sticky_without_evidence() {
    let inputs = ProfileInputs {
        declared_driver: Some(CompileDriver::Mbx),
        declared_runner: Some(TestRunner::CargoNextest),
        ..ProfileInputs::default()
    };
    let Ok(outcome) = detect_profile(&inputs) else {
        panic!("declared profile must be selected");
    };
    assert_eq!(outcome.profile.compile_driver, CompileDriver::Mbx);
    assert_eq!(outcome.profile.test_runner, TestRunner::CargoNextest);
    assert_eq!(outcome.profile.driver_source, ProfileSource::Declared);
    assert_eq!(outcome.profile.runner_source, ProfileSource::Declared);
    assert_eq!(
        outcome.findings,
        [] as [velnor_actions_rust::ProfileFinding; 0]
    );
}

#[test]
fn declaration_resolves_transient_evidence() {
    let inputs = ProfileInputs {
        handwritten_workflows: vec![file(
            ".github/workflows/ci.yml",
            "steps:\n  - run: mbx clippy --package a\n",
        )],
        declared_driver: Some(CompileDriver::Mbx),
        ..ProfileInputs::default()
    };
    let Ok(outcome) = detect_profile(&inputs) else {
        panic!("declared profile must win over transient evidence");
    };
    assert_eq!(outcome.profile.compile_driver, CompileDriver::Mbx);
    assert_eq!(outcome.profile.driver_source, ProfileSource::Declared);
    assert_eq!(
        outcome.findings,
        [] as [velnor_actions_rust::ProfileFinding; 0]
    );
}

#[test]
fn conflicting_declaration_fails_closed() {
    let inputs = ProfileInputs {
        executables: vec![file("scripts/test.sh", "mbx test --package a\n")],
        declared_driver: Some(CompileDriver::Cargo),
        ..ProfileInputs::default()
    };
    let Err(ProfileError::ProfileConflict { declared, evidence }) = detect_profile(&inputs) else {
        panic!("durable evidence contradicting a declaration must fail");
    };
    assert!(declared.contains("compile_driver"));
    assert_eq!(evidence.len(), 1);
    assert_eq!(evidence[0].path, "scripts/test.sh");
    let text = ProfileError::ProfileConflict { declared, evidence }.to_string();
    assert!(text.contains(PROFILE_CONFLICT_CODE), "code: {text}");
}

#[test]
fn transient_runner_selection_reports_finding() {
    let inputs = ProfileInputs {
        handwritten_workflows: vec![file(
            ".github/workflows/ci.yml",
            "steps:\n  - run: cargo nextest run --package a\n",
        )],
        ..ProfileInputs::default()
    };
    let Ok(outcome) = detect_profile(&inputs) else {
        panic!("transient runner must select with a finding");
    };
    assert_eq!(outcome.profile.test_runner, TestRunner::CargoNextest);
    assert_eq!(outcome.findings.len(), 1);
    assert_eq!(outcome.findings[0].code, TRANSIENT_EVIDENCE_CODE);
    assert!(
        outcome.findings[0]
            .message
            .contains("[stacks.rust] test_runner")
    );
}
