[package]
name = "velnor-actions-orchestrator-preseed-manifest"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
autotests = false

[dependencies]
velnor-actions-contract = { version = "=0.1.1", path = "../../core/velnor-actions-contract" }
velnor-actions-contract-release = { version = "=0.1.1", path = "../../core/velnor-actions-contract-release" }
velnor-actions-orchestrator-core = { version = "=0.1.1", path = "../velnor-actions-orchestrator-core" }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }

[dev-dependencies]
velnor-actions-workflow-jobs = { version = "=0.1.1", path = "../velnor-actions-workflow-jobs" }
velnor-actions-workflow-steps = { version = "=0.1.1", path = "../velnor-actions-workflow-steps" }

[lints]
workspace = true

[[test]]
name = "velnor_orchestrator_preseed_manifest"
path = "tests/main.rs"
