[package]
name = "velnor-actions-tofu-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
autotests = false

[lints]
workspace = true

[dependencies]
velnor-actions-contract = { version = "=0.1.7", path = "../../core/velnor-actions-contract" }
velnor-actions-contract-config = { version = "=0.1.7", path = "../../core/velnor-actions-contract-config" }
velnor-actions-contract-planning = { version = "=0.1.7", path = "../../core/velnor-actions-contract-planning" }
velnor-actions-contract-release = { version = "=0.1.7", path = "../../core/velnor-actions-contract-release" }
hcl = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[[test]]
name = "velnor_tofu_core"
path = "tests/main.rs"
