[package]
name = "velnor-actions-workflow-renderer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
autotests = false

[features]
test-render-capture = []

[dependencies]
velnor-actions-contract = { version = "=0.1.6", path = "../velnor-actions-contract" }
velnor-actions-mise = { version = "=0.1.6", path = "../velnor-actions-mise" }

[lints]
workspace = true

[[test]]
name = "velnor_workflow_renderer"
path = "tests/velnor_workflow_renderer.rs"
