[package]
name = "velnor-actions-contract"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
autotests = false

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
blake3 = { workspace = true }
thiserror = { workspace = true }

[[test]]
name = "velnor_contract"
path = "tests/main.rs"

[dev-dependencies]
velnor-actions-contract-config = { version = "=0.1.1", path = "../velnor-actions-contract-config" }
velnor-actions-contract-release = { version = "=0.1.1", path = "../velnor-actions-contract-release" }
velnor-actions-contract-workflow = { version = "=0.1.1", path = "../velnor-actions-contract-workflow" }
serde_json = { workspace = true }
