use super::{
    CompiledSourceHelper, HelperInvocation, SourceBoundHelper, SourceBoundOperation,
    compiled_source_sha256,
};

fn valid_record() -> CompiledSourceHelper {
    let operation = SourceBoundOperation::RustPrepareRootLinux;
    let source = crate::generated_source("0.1.0", "exit 0\n").expect("generated source");
    let digest = compiled_source_sha256(source.as_bytes());
    let descriptor = SourceBoundHelper::compiled(operation, operation.path(), &digest)
        .expect("source descriptor");
    let invocation =
        HelperInvocation::compiled(descriptor, Vec::new(), Vec::new()).expect("helper invocation");
    CompiledSourceHelper::compiled(invocation, source).expect("compiled source helper")
}

#[test]
fn compiled_source_sha256_matches_known_vector_and_marked_source() {
    assert_eq!(
        compiled_source_sha256(b"abc"),
        "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
    );
    let record = valid_record();
    assert!(
        record
            .source()
            .starts_with("# Generated by Velnor Actions 0.1.0;")
    );
    assert_eq!(
        compiled_source_sha256(record.source().as_bytes()),
        record.invocation().descriptor().source_sha256()
    );
}

#[test]
fn compiled_source_rejects_forged_descriptor_digest() {
    let operation = SourceBoundOperation::RustPrepareRootLinux;
    let source = crate::generated_source("0.1.0", "exit 0\n").expect("generated source");
    let descriptor = SourceBoundHelper::compiled(operation, operation.path(), &"0".repeat(64))
        .expect("descriptor shape");
    let invocation =
        HelperInvocation::compiled(descriptor, Vec::new(), Vec::new()).expect("invocation");
    assert!(CompiledSourceHelper::compiled(invocation, source).is_err());
}

#[test]
fn validate_binding_rejects_private_source_mutation() {
    let mut record = valid_record();
    record.source.push_str("tampered\n");
    assert!(record.validate_binding().is_err());
}
