[package]
name = "velnor-actions-workflow-generator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
autotests = false

[dependencies]
velnor-actions-contract-config = { version = "=0.1.1", path = "../../core/velnor-actions-contract-config" }
velnor-actions-contract-release = { version = "=0.1.1", path = "../../core/velnor-actions-contract-release" }
velnor-actions-workflow-steps = { version = "=0.1.1", path = "../velnor-actions-workflow-steps" }
velnor-actions-workflow-tree = { version = "=0.1.1", path = "../velnor-actions-workflow-tree" }

[lints]
workspace = true

[[test]]
name = "velnor_workflow_generator"
path = "tests/main.rs"
