[package]
name = "velnor-actions-mise-nextest"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
autotests = false

[lints]
workspace = true

[dependencies]
velnor-actions-contract = { version = "=0.1.1", path = "../../core/velnor-actions-contract" }
velnor-actions-contract-config = { version = "=0.1.1", path = "../../core/velnor-actions-contract-config" }
velnor-actions-contract-release = { version = "=0.1.1", path = "../../core/velnor-actions-contract-release" }
velnor-actions-mise-core = { version = "=0.1.1", path = "../velnor-actions-mise-core" }
velnor-actions-mise-catalog = { version = "=0.1.1", path = "../velnor-actions-mise-catalog" }

[[test]]
name = "velnor_mise_nextest"
path = "tests/main.rs"
