//! Share exact MBX setup scripts while keeping each typed step in its job.
//!
//! Only bodies regenerated by the MBX preflight and cache-key factories are
//! eligible. The checkout, shell process, step environment, and job context
//! stay in the workflow document.

use std::collections::{BTreeMap, BTreeSet};

use velnor_actions_contract::{Job, Step, StepKind, digest_b3};

use crate::lane_share::LaneShare;
use crate::render::RenderContext;
use crate::tree::RenderedFile;
use crate::{RenderError, marker, steps};

#[cfg(test)]
#[path = "document_shared_scripts_tests.rs"]
mod tests;

const SCRIPT_ROOT: &str = ".github/scripts/velnor-shared";

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
enum ShellDialect {
    Sh,
    Bash,
}

impl ShellDialect {
    fn as_str(self) -> &'static str {
        match self {
            Self::Sh => "sh",
            Self::Bash => "bash",
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
struct ScriptKey {
    dialect: ShellDialect,
    body: String,
}

#[derive(Debug, Clone)]
struct Occurrence {
    job_id: String,
    step_index: usize,
}

/// Replace repeated source-factory scripts in place and return their files.
///
/// The exact `Step` remains at its original position. Only its `-c` payload
/// changes; its credential prelude, environment, condition, and identity stay
/// untouched.
///
/// # Errors
///
/// Returns [`RenderError`] when a canonical factory cannot be regenerated or
/// a generated file cannot be marked.
pub(crate) fn share_trusted_scripts(
    shared: &mut LaneShare,
    ctx: &RenderContext,
) -> Result<Vec<RenderedFile>, RenderError> {
    let checkout = steps::checkout_step(&ctx.checkout_uses)?;
    let mut groups = BTreeMap::<ScriptKey, Vec<Occurrence>>::new();
    for (job_id, job) in &shared.jobs {
        if shared.calls.contains_key(job_id) || !has_root_checkout(job, &checkout) {
            continue;
        }
        for (step_index, step) in job.steps.iter().enumerate() {
            if let Some(key) = approved_script(job, step_index, step)? {
                groups.entry(key).or_default().push(Occurrence {
                    job_id: job_id.clone(),
                    step_index,
                });
            }
        }
    }

    let mut files = Vec::new();
    for (key, occurrences) in groups {
        let jobs: BTreeSet<&str> = occurrences
            .iter()
            .map(|occurrence| occurrence.job_id.as_str())
            .collect();
        if jobs.len() < 2 {
            continue;
        }
        let file = script_file(&key, &ctx.generator_version)?;
        for occurrence in occurrences {
            replace_with_source(shared, &occurrence, &file.path)?;
        }
        files.push(file);
    }
    Ok(files)
}

fn has_root_checkout(job: &Job, expected: &Step) -> bool {
    job.steps.first() == Some(expected)
        && !job.steps.iter().skip(1).any(|step| {
            step.name == "Checkout"
                || matches!(
                    &step.kind,
                    StepKind::Action { uses, .. } if uses.starts_with("actions/checkout@")
                )
        })
}

fn approved_script(
    job: &Job,
    step_index: usize,
    step: &Step,
) -> Result<Option<ScriptKey>, RenderError> {
    let canonical = if step.name == crate::steps::MBX_PREFLIGHT_NAME {
        canonical_preflight(job, step_index, step)
    } else if step.name == crate::mbx_bundle::MBX_CACHE_KEY_NAME {
        canonical_cache_key(job, step_index, step)?
    } else {
        false
    };
    if !canonical {
        return Ok(None);
    }
    Ok(trusted_shell(step).map(|(dialect, body)| ScriptKey { dialect, body }))
}

fn canonical_preflight(job: &Job, step_index: usize, step: &Step) -> bool {
    if count_named(job, crate::steps::MBX_PREFLIGHT_NAME) != 1
        || count_named(job, crate::mbx_bundle::MBX_CACHE_KEY_NAME) != 1
    {
        return false;
    }
    let actions: Vec<(usize, &Step)> = job
        .steps
        .iter()
        .enumerate()
        .filter(|(_, candidate)| crate::cache_steps::is_mbx_action(candidate))
        .collect();
    let [(action_index, action)] = actions.as_slice() else {
        return false;
    };
    if *action_index != step_index + 2
        || job
            .steps
            .get(step_index + 1)
            .map(|value| value.name.as_str())
            != Some(crate::mbx_bundle::MBX_CACHE_KEY_NAME)
    {
        return false;
    }
    let (
        StepKind::Shell { env, .. },
        StepKind::Action {
            uses,
            with,
            env: action_env,
        },
    ) = (&step.kind, &action.kind)
    else {
        return false;
    };
    let (Some(version), Some(toolchain)) =
        (action_env.get("VELNOR_MBX_VERSION"), with.get("toolchain"))
    else {
        return false;
    };
    let Ok(Some([expected, _])) = steps::mbx_steps_for_driver(
        uses,
        steps::CompileDriver::Mbx,
        version,
        toolchain,
        factory_input_env(env),
    ) else {
        return false;
    };
    expected == *step
}

fn factory_input_env(env: &BTreeMap<String, String>) -> BTreeMap<String, String> {
    let scrub = crate::toolchain_env::credential_scrub();
    env.iter()
        .filter(|(key, _)| !scrub.contains_key(*key))
        .map(|(key, value)| (key.clone(), value.clone()))
        .collect()
}

fn canonical_cache_key(job: &Job, step_index: usize, step: &Step) -> Result<bool, RenderError> {
    if count_named(job, crate::mbx_bundle::MBX_CACHE_KEY_NAME) != 1 {
        return Ok(false);
    }
    let actions: Vec<&Step> = job
        .steps
        .iter()
        .filter(|candidate| crate::cache_steps::is_mbx_action(candidate))
        .collect();
    if actions.len() != 1 {
        return Ok(false);
    }
    let mut regenerated = job.clone();
    regenerated.steps.remove(step_index);
    let mut candidates = BTreeMap::from([("candidate".to_owned(), regenerated)]);
    crate::mbx_bundle::append_single_bundle_saves(&mut candidates)?;
    let Some(regenerated_job) = candidates.get("candidate") else {
        return Err(RenderError::InvalidWorkflow(
            "shared_script_factory_job_missing".to_owned(),
        ));
    };
    let matches: Vec<&Step> = regenerated_job
        .steps
        .iter()
        .filter(|candidate| candidate.name == crate::mbx_bundle::MBX_CACHE_KEY_NAME)
        .collect();
    Ok(matches.len() == 1 && matches[0] == step)
}

fn count_named(job: &Job, name: &str) -> usize {
    job.steps.iter().filter(|step| step.name == name).count()
}

fn trusted_shell(step: &Step) -> Option<(ShellDialect, String)> {
    if step.condition.is_some() {
        return None;
    }
    let StepKind::Shell { run, .. } = &step.kind else {
        return None;
    };
    let [interpreter, flag, command] = run.as_slice() else {
        return None;
    };
    if flag != "-c" {
        return None;
    }
    let dialect = match interpreter.as_str() {
        "sh" => ShellDialect::Sh,
        "bash" => ShellDialect::Bash,
        _ => return None,
    };
    let prelude = format!("{} ", crate::toolchain_env::credential_unset_prelude());
    let body = command.strip_prefix(&prelude)?;
    if body.is_empty()
        || body.contains("${{")
        || body.contains("$BASH_SOURCE")
        || body.contains("${BASH_SOURCE")
        || body.contains("$0")
        || body.contains("${0}")
        || body.contains("LINENO")
        || has_shell_word(body, "return")
    {
        return None;
    }
    Some((dialect, body.to_owned()))
}

fn has_shell_word(body: &str, word: &str) -> bool {
    body.split(|character: char| !character.is_ascii_alphanumeric() && character != '_')
        .any(|part| part == word)
}

fn script_file(key: &ScriptKey, version: &str) -> Result<RenderedFile, RenderError> {
    let digest_input = format!("{}\0{}", key.dialect.as_str(), key.body);
    let digest = digest_b3(digest_input.as_bytes());
    let extension = match key.dialect {
        ShellDialect::Sh => "sh",
        ShellDialect::Bash => "bash",
    };
    let path = format!(
        "{SCRIPT_ROOT}/{}-{digest}.{extension}",
        key.dialect.as_str()
    );
    let bytes = marker::with_marker(version, &key.body)?;
    Ok(RenderedFile { path, bytes })
}

fn replace_with_source(
    shared: &mut LaneShare,
    occurrence: &Occurrence,
    path: &str,
) -> Result<(), RenderError> {
    let Some(job) = shared.jobs.get_mut(&occurrence.job_id) else {
        return Err(RenderError::InvalidWorkflow(
            "shared_script_job_missing".to_owned(),
        ));
    };
    let Some(step) = job.steps.get_mut(occurrence.step_index) else {
        return Err(RenderError::InvalidWorkflow(
            "shared_script_step_missing".to_owned(),
        ));
    };
    let StepKind::Shell { run, .. } = &mut step.kind else {
        return Err(RenderError::InvalidWorkflow(
            "shared_script_step_not_shell".to_owned(),
        ));
    };
    if run.len() != 3 {
        return Err(RenderError::InvalidWorkflow(
            "shared_script_argv_changed".to_owned(),
        ));
    }
    run[2] = crate::toolchain_env::with_credential_unset_script(&format!(". './{path}'"));
    Ok(())
}
