[package]
name = "velnor-runner-docker-spec"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
velnor-runner-core = { version = "=0.1.7", path = "../velnor-runner-core" }
velnor-runner-journal = { version = "=0.1.7", path = "../velnor-runner-journal" }
