//! Staging-only zizmor config for blessed-tag validation.
//!
//! Scans staged workflow bytes for the exact blessed `uses:` line and
//! renders deterministic `.zizmor.yml` bytes that are never committed.
//! Pure data plus validation: never spawns processes, never reads the
//! filesystem.

use crate::ActionlintError;
use crate::actions::{ALINT_ACTION, ALINT_REVIEWED_TAG};
use crate::config::{check_generator_version, is_valid_workflow_path};
use std::collections::BTreeSet;

/// One staged workflow's bytes for zizmor ignore derivation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ZizmorWorkflowText {
    /// Repository-relative workflow path.
    pub path: String,
    /// Complete rendered workflow bytes.
    pub text: String,
}

/// Typed input for staging-only zizmor config generation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ZizmorConfigInput {
    /// Exact generator version for the header comment.
    pub generator_version: String,
    /// Staged workflow bytes scanned for the blessed tag.
    pub workflows: Vec<ZizmorWorkflowText>,
}

/// Deterministic output: staging config bytes plus ignores.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ZizmorConfigOutput {
    /// Exact staging `.zizmor.yml` bytes (never committed).
    pub yaml: String,
    /// Approved `unpinned-uses` rules, sorted by `(file, line, col)`.
    pub approved_ignores: Vec<String>,
}

/// Render deterministic staging-only zizmor config bytes.
///
/// # Errors
///
/// Returns [`ActionlintError`] for a bad version or path.
pub fn render_zizmor_yaml(
    input: &ZizmorConfigInput,
) -> Result<ZizmorConfigOutput, ActionlintError> {
    check_generator_version(&input.generator_version)?;
    let mut ignores = BTreeSet::new();
    for workflow in &input.workflows {
        if !is_valid_workflow_path(&workflow.path) {
            return Err(ActionlintError::InvalidWorkflowPath {
                path: workflow.path.clone(),
            });
        }
        let base = workflow.path.rsplit('/').next().unwrap_or_default();
        ignores.extend(blessed_locations(base, &workflow.text));
    }
    let approved: Vec<String> = ignores.into_iter().collect();
    let yaml = render_zizmor_bytes(&input.generator_version, &approved);
    Ok(ZizmorConfigOutput {
        yaml,
        approved_ignores: approved,
    })
}

/// `file:line:col` rules for exact blessed-tag `uses:` lines only.
fn blessed_locations(base: &str, text: &str) -> Vec<String> {
    let needle = format!("uses: {ALINT_ACTION}@{ALINT_REVIEWED_TAG}");
    let mut out = Vec::new();
    for (index, line) in text.lines().enumerate() {
        let Some(start) = line.find(needle.as_str()) else {
            continue;
        };
        let after = line.as_bytes().get(start + needle.len());
        if after.is_none_or(u8::is_ascii_whitespace) {
            let col = start + "uses: ".len() + 1;
            out.push(format!("{}:{}:{col}", base, index + 1));
        }
    }
    out
}

/// Expiry note carried by every rendered ignore entry.
const IGNORE_EXPIRY_COMMENT: &str =
    "  # expires: alint reviewed-tag exception review (version-policy §2)";

/// Render fixed staging-only bytes with sorted ignore rules.
fn render_zizmor_bytes(version: &str, ignores: &[String]) -> String {
    let mut yaml = format!(
        "# Generated by Velnor Actions {version} for staged zizmor validation; never commit.\n\
         # Version-policy exception (docs/proposed/version-policy.md §2): exactly\n\
         # uses {ALINT_ACTION}@{ALINT_REVIEWED_TAG} may stay tag-pinned; every\n\
         # other ref still requires a hash (implicit \"*\": hash-pin).\n\
         rules:\n  unpinned-uses:\n"
    );
    if ignores.is_empty() {
        yaml.push_str("    ignore: []\n");
    } else {
        yaml.push_str("    ignore:\n");
        for rule in ignores {
            yaml.push_str("      - ");
            yaml.push_str(rule);
            yaml.push_str(IGNORE_EXPIRY_COMMENT);
            yaml.push('\n');
        }
    }
    yaml
}
