//! Staging-only zizmor config for hash-pinned validation.
//!
//! Renders deterministic `.zizmor.yml` bytes that are never committed.
//! Every emitted ref is hash-pinned, so the config carries zero
//! `unpinned-uses` ignores. Pure data plus validation: never spawns
//! processes, never reads the filesystem.

use crate::ActionlintError;
use crate::config::{check_generator_version, is_valid_workflow_path};

/// One staged workflow's bytes for zizmor validation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ZizmorWorkflowText {
    /// Repository-relative workflow path.
    pub path: String,
    /// Complete rendered workflow bytes.
    pub text: String,
}

/// Typed input for staging-only zizmor config generation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ZizmorConfigInput {
    /// Exact generator version for the header comment.
    pub generator_version: String,
    /// Staged workflow bytes covered by the config.
    pub workflows: Vec<ZizmorWorkflowText>,
}

/// Deterministic output: staging config bytes plus ignores.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ZizmorConfigOutput {
    /// Exact staging `.zizmor.yml` bytes (never committed).
    pub yaml: String,
    /// Approved `unpinned-uses` rules; always empty (every ref is hashed).
    pub approved_ignores: Vec<String>,
}

/// Render deterministic staging-only zizmor config bytes.
///
/// # Errors
///
/// Returns [`ActionlintError`] for a bad version or path.
pub fn render_zizmor_yaml(
    input: &ZizmorConfigInput,
) -> Result<ZizmorConfigOutput, ActionlintError> {
    check_generator_version(&input.generator_version)?;
    for workflow in &input.workflows {
        if !is_valid_workflow_path(&workflow.path) {
            return Err(ActionlintError::InvalidWorkflowPath {
                path: workflow.path.clone(),
            });
        }
    }
    Ok(ZizmorConfigOutput {
        yaml: render_zizmor_bytes(&input.generator_version),
        approved_ignores: Vec::new(),
    })
}

/// Render fixed staging-only bytes with an empty ignore list.
fn render_zizmor_bytes(version: &str) -> String {
    format!(
        "# Generated by Velnor Actions {version} for staged zizmor validation; never commit.\n\
         # Every emitted ref is hash-pinned; no unpinned-uses ignores exist.\n\
         rules:\n  unpinned-uses:\n    ignore: []\n"
    )
}
