use super::*;
use velnor_actions_contract_workflow::FRESHNESS_CRON_WEEKLY;

const CHECKOUT: &str = "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1";

fn spec() -> FreshnessSpec {
    FreshnessSpec {
        schedule: ScheduleTrigger {
            cron: vec![FRESHNESS_CRON_WEEKLY.to_owned()],
        },
        runs_on: "ubuntu-26.04".to_owned(),
        checkout_uses: CHECKOUT.to_owned(),
        generator_version: "0.1.0".to_owned(),
    }
}

#[test]
fn renders_schedule_only_read_only_probe() {
    let file = render_freshness_workflow(&spec()).expect("render");
    assert_eq!(file.path, ".github/workflows/freshness.yml");
    let yaml = &file.bytes;
    assert!(
        yaml.starts_with("# Generated by Velnor Actions 0.1.0"),
        "marker:\n{yaml}"
    );
    assert!(yaml.contains("cron: 0 6 * * 1"), "weekly trigger:\n{yaml}");
    assert!(
        yaml.contains("workflow_dispatch:"),
        "manual re-run:\n{yaml}"
    );
    assert!(
        !yaml.contains("pull_request") && !yaml.contains("push:"),
        "schedule-only:\n{yaml}"
    );
    assert!(
        yaml.matches("contents: read").count() >= 2,
        "top-level plus job perms:\n{yaml}"
    );
    assert!(!yaml.contains("write"), "read-only:\n{yaml}");
    assert!(!yaml.contains("secrets."), "no secrets:\n{yaml}");
    assert!(
        yaml.contains("uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1"),
        "exact pin:\n{yaml}"
    );
    assert!(
        yaml.contains("persist-credentials: \"false\""),
        "no credentials:\n{yaml}"
    );
    assert!(
        yaml.contains("scripts/check-freshness.sh --check-upstream"),
        "bounded probe:\n{yaml}"
    );
    assert!(
        yaml.contains("timeout-minutes: 10"),
        "explicit timeout:\n{yaml}"
    );
    assert!(
        yaml.contains("group: freshness") && yaml.contains("cancel-in-progress: false"),
        "serialize scheduled runs:\n{yaml}"
    );
}

#[test]
fn rejects_bad_spec_scalars() {
    let bad_cron = FreshnessSpec {
        schedule: ScheduleTrigger {
            cron: vec!["not-a-cron".to_owned()],
        },
        ..spec()
    };
    assert!(render_freshness_workflow(&bad_cron).is_err(), "bad cron");
    let empty_cron = FreshnessSpec {
        schedule: ScheduleTrigger { cron: Vec::new() },
        ..spec()
    };
    assert!(
        render_freshness_workflow(&empty_cron).is_err(),
        "empty cron"
    );
    for runs_on in ["ubuntu-latest", "ubuntu-26.04 ${{ x }}", ""] {
        let bad = FreshnessSpec {
            runs_on: runs_on.to_owned(),
            ..spec()
        };
        assert!(
            render_freshness_workflow(&bad).is_err(),
            "bad label {runs_on}"
        );
    }
    for uses in [
        "actions/checkout@v7.0.1",
        "actions/checkout@short",
        "other/x@3d3c42e5aac5ba805825da76410c181273ba90b1",
    ] {
        let bad = FreshnessSpec {
            checkout_uses: uses.to_owned(),
            ..spec()
        };
        assert!(
            render_freshness_workflow(&bad).is_err(),
            "bad checkout {uses}"
        );
    }
}

#[test]
fn rejects_internal_steps_fail_closed() {
    let internal = Step {
        name: "Plan".to_owned(),
        id: None,
        role: None,
        condition: None,
        kind: velnor_actions_contract_workflow::StepKind::Internal {
            operation: "plan-v1".to_owned(),
            env: std::collections::BTreeMap::new(),
        },
    };
    let err = velnor_actions_workflow_tree::steps_plain::plain_step_to_yaml(&internal)
        .expect_err("rejected");
    assert!(err.to_string().contains("internal_op_rejected"), "{err}");
}
