[package]
name = "velnor-actions-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
autotests = false

[[bin]]
name = "velnor-actions"
path = "src/main.rs"

[dependencies]
velnor-actions-orchestrator = { version = "=0.1.1", path = "../services/velnor-actions-orchestrator" }
clap = { workspace = true }

[lints]
workspace = true

[[test]]
name = "velnor_cli"
path = "tests/velnor_cli.rs"

[dev-dependencies]
proc-macro2 = { workspace = true }
serde_json = { workspace = true }
syn = { workspace = true }
