[package]
name = "velnor-actions-contract-workflow"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
autotests = false

[lints]
workspace = true

[dependencies]
velnor-actions-contract = { version = "=0.1.7", path = "../velnor-actions-contract" }
velnor-actions-contract-config = { version = "=0.1.7", path = "../velnor-actions-contract-config" }
velnor-actions-contract-planning = { version = "=0.1.7", path = "../velnor-actions-contract-planning" }
velnor-actions-contract-release = { version = "=0.1.7", path = "../velnor-actions-contract-release" }
serde = { workspace = true }
serde_json = { workspace = true }

[[test]]
name = "velnor_contract_workflow"
path = "tests/main.rs"

[dev-dependencies]
serde_json = { workspace = true }
