//! Init lifecycle: nesting, exclusivity, sample content, error behavior.

use std::error::Error;
use std::path::Path;

use crate::impl_cli_tmp::{
    add_crate_pair, cleanup, code, fresh_tempdir, git_init, ignore_rust, init_repo, spawn,
};

/// Collect repo-relative file paths under `dir`, skipping `.git`.
fn list_files(dir: &Path) -> Result<Vec<String>, Box<dyn Error>> {
    let mut out = Vec::new();
    let mut pending = vec![dir.to_path_buf()];
    while let Some(path) = pending.pop() {
        for entry in std::fs::read_dir(&path)? {
            let entry = entry?;
            let relative = entry
                .path()
                .strip_prefix(dir)?
                .to_string_lossy()
                .into_owned();
            if relative == ".git" || relative.starts_with(".git/") {
                continue;
            }
            if entry.file_type()?.is_dir() {
                pending.push(entry.path());
            } else {
                out.push(relative);
            }
        }
    }
    out.sort();
    Ok(out)
}

#[test]
fn nested_init_writes_only_root_config() -> Result<(), Box<dyn Error>> {
    let tmp = fresh_tempdir("init-nested")?;
    git_init(&tmp)?;
    let nested = tmp.join("nested").join("deep");
    std::fs::create_dir_all(&nested)?;
    let output = spawn(&["init"], &[], &nested)?;
    assert_eq!(code(&output), 0, "stderr: {:?}", output.stderr);
    assert!(tmp.join(".velnor").join("config.toml").is_file());
    assert!(!nested.join(".velnor").exists());
    assert!(!tmp.join("nested").join(".velnor").exists());
    let stdout = String::from_utf8_lossy(&output.stdout).into_owned();
    assert!(stdout.contains(".velnor/config.toml"), "{stdout}");
    cleanup(&tmp);
    Ok(())
}

#[test]
fn init_writes_no_other_file() -> Result<(), Box<dyn Error>> {
    let tmp = fresh_tempdir("init-exclusive")?;
    git_init(&tmp)?;
    let before = list_files(&tmp)?;
    assert_eq!(code(&spawn(&["init"], &[], &tmp)?), 0);
    let after = list_files(&tmp)?;
    let added: Vec<&String> = after.iter().filter(|path| !before.contains(path)).collect();
    assert_eq!(added, [".velnor/config.toml"]);
    cleanup(&tmp);
    Ok(())
}

#[test]
fn velnor_file_blocks_init() -> Result<(), Box<dyn Error>> {
    let tmp = fresh_tempdir("init-file")?;
    git_init(&tmp)?;
    std::fs::write(tmp.join(".velnor"), "decoy")?;
    let output = spawn(&["init"], &[], &tmp)?;
    assert_eq!(code(&output), 1);
    assert_eq!(std::fs::read_to_string(tmp.join(".velnor"))?, "decoy");
    assert!(!tmp.join(".velnor").join("config.toml").exists());
    let stderr = String::from_utf8_lossy(&output.stderr).into_owned();
    assert!(stderr.contains("not_a_directory"), "{stderr}");
    cleanup(&tmp);
    Ok(())
}

#[test]
fn sample_comments_describe_values_defaults_effects() -> Result<(), Box<dyn Error>> {
    let tmp = fresh_tempdir("init-sample")?;
    git_init(&tmp)?;
    assert_eq!(code(&spawn(&["init"], &[], &tmp)?), 0);
    let body = std::fs::read_to_string(tmp.join(".velnor").join("config.toml"))?;
    let comments = body.lines().filter(|line| line.starts_with('#')).count();
    assert!(comments >= 10, "only {comments} comment lines");
    assert!(body.contains("efault"), "no default documented:\n{body}");
    assert!(
        body.contains("omit"),
        "no omission effect documented:\n{body}"
    );
    assert!(body.contains("Example:"), "no valid value shown:\n{body}");
    assert!(body.contains("[workflow]"), "sections missing:\n{body}");
    assert!(body.contains("[stacks]"), "sections missing:\n{body}");
    assert!(body.contains("[discovery]"), "sections missing:\n{body}");
    cleanup(&tmp);
    Ok(())
}

#[test]
fn sample_first_line_is_version_marker() -> Result<(), Box<dyn Error>> {
    let tmp = fresh_tempdir("init-marker")?;
    git_init(&tmp)?;
    assert_eq!(code(&spawn(&["init"], &[], &tmp)?), 0);
    let version = spawn(&["--version"], &[], &tmp)?;
    let reported = String::from_utf8_lossy(&version.stdout).into_owned();
    let number = reported
        .strip_prefix("velnor-actions ")
        .ok_or("version shape")?
        .trim();
    let body = std::fs::read_to_string(tmp.join(".velnor").join("config.toml"))?;
    let first = body.lines().next().ok_or("empty sample")?;
    assert_eq!(
        first,
        &format!(
            "# Generated by Velnor Actions {number}; edit .velnor/config.toml and regenerate."
        )
    );
    cleanup(&tmp);
    Ok(())
}

#[test]
fn init_leaves_tool_files_and_sources_untouched() -> Result<(), Box<dyn Error>> {
    let tmp = fresh_tempdir("init-untouched")?;
    git_init(&tmp)?;
    std::fs::create_dir_all(tmp.join(".mise").join("tasks"))?;
    std::fs::create_dir_all(tmp.join(".github").join("workflows"))?;
    std::fs::create_dir_all(tmp.join("src"))?;
    let witnesses = [
        "mise.toml",
        "rust-toolchain.toml",
        ".mise/tasks/check.toml",
        ".github/workflows/old.yml",
        "src/main.rs",
    ];
    for name in witnesses {
        std::fs::write(tmp.join(name), format!("witness:{name}\n"))?;
    }
    let before = list_files(&tmp)?;
    let mut bytes = Vec::new();
    for name in before.clone() {
        bytes.push(std::fs::read(tmp.join(&name))?);
    }
    assert_eq!(code(&spawn(&["init"], &[], &tmp)?), 0);
    assert_eq!(list_files(&tmp)?, {
        let mut want = before.clone();
        want.push(".velnor/config.toml".to_owned());
        want.sort();
        want
    });
    for (name, body) in before.iter().zip(bytes.iter()) {
        assert_eq!(&std::fs::read(tmp.join(name))?, body, "{name} changed");
    }
    cleanup(&tmp);
    Ok(())
}

#[test]
fn invalid_config_fails_with_key_path_and_no_replace() -> Result<(), Box<dyn Error>> {
    let tmp = fresh_tempdir("init-badcfg")?;
    init_repo(&tmp)?;
    std::fs::create_dir_all(tmp.join(".github").join("workflows"))?;
    std::fs::write(tmp.join(".github/workflows/old.yml"), "old: true\n")?;
    let config = tmp.join(".velnor").join("config.toml");
    let mut body = std::fs::read_to_string(&config)?;
    body.push_str("\n[stacks]\nignore = [\"bogus\"]\n");
    std::fs::write(&config, body)?;
    let plan = spawn(&["plan"], &[], &tmp)?;
    assert_eq!(code(&plan), 1);
    assert_eq!(plan.stdout, [] as [u8; 0]);
    let stderr = String::from_utf8_lossy(&plan.stderr).into_owned();
    assert!(stderr.contains(".velnor/config.toml"), "{stderr}");
    assert!(stderr.contains("stacks.ignore"), "{stderr}");
    let generated = spawn(&["generate"], &[], &tmp)?;
    assert_eq!(code(&generated), 1);
    assert_eq!(
        std::fs::read_to_string(tmp.join(".github/workflows/old.yml"))?,
        "old: true\n"
    );
    assert!(!tmp.join(".github/workflows/ci.yml").exists());
    cleanup(&tmp);
    Ok(())
}

#[test]
fn malformed_manifest_fails_naming_file() -> Result<(), Box<dyn Error>> {
    let tmp = fresh_tempdir("init-malformed")?;
    let mbx = fresh_tempdir("init-malformed-mbx")?;
    init_repo(&tmp)?;
    add_crate_pair(&tmp)?;
    ignore_rust(&tmp)?;
    std::fs::write(tmp.join("apple").join("Cargo.toml"), "[[[\n")?;
    let catalog = crate::impl_repo_policy::read("crates/velnor-actions-mise/src/catalog.rs")?;
    let rust_version = crate::impl_repo_policy::quoted_value(&catalog, "RUST_VERSION")?;
    let mbx_version = crate::impl_repo_policy::quoted_value(&catalog, "MR_BOXINGTON_VERSION")?;
    let log = write_mbx_fixture(&mbx)?;
    let mut search_path = vec![mbx.join("bin")];
    if let Some(parent) = std::env::var_os("PATH") {
        search_path.extend(std::env::split_paths(&parent));
    }
    let path = std::env::join_paths(search_path)?;
    let path = path.to_string_lossy().into_owned();
    let log = log.to_string_lossy().into_owned();
    let root = tmp.to_string_lossy().into_owned();
    let plan = spawn(
        &["plan"],
        &[
            ("PATH", &path),
            ("VELNOR_TEST_RUST_VERSION", &rust_version),
            ("VELNOR_TEST_MBX_VERSION", &mbx_version),
            ("VELNOR_TEST_MBX_LOG", &log),
            ("VELNOR_TEST_MBX_ROOT", &root),
        ],
        &tmp,
    )?;
    assert_eq!(code(&plan), 1);
    let stderr = String::from_utf8_lossy(&plan.stderr).into_owned();
    assert!(stderr.contains("apple/Cargo.toml"), "{stderr}");
    assert!(stderr.contains("malformed_manifest"), "{stderr}");
    let calls = std::fs::read_to_string(&log)?;
    assert!(calls.lines().any(|line| line == "--version"), "{calls}");
    assert!(
        calls.lines().any(|line| {
            line.starts_with(&format!("+{rust_version} metadata "))
                && line.contains("apple/Cargo.toml")
        }),
        "{calls}"
    );
    cleanup(&tmp);
    cleanup(&mbx);
    Ok(())
}

fn write_mbx_fixture(root: &Path) -> Result<std::path::PathBuf, Box<dyn Error>> {
    use std::os::unix::fs::PermissionsExt;

    let bin = root.join("bin");
    std::fs::create_dir_all(&bin)?;
    let script = bin.join("mbx");
    std::fs::write(
        &script,
        r##"#!/bin/sh
set -eu
printf '%s\n' "$*" >> "$VELNOR_TEST_MBX_LOG"
if [ "${1-}" = "--version" ]; then
    printf 'mbx %s\n' "$VELNOR_TEST_MBX_VERSION"
    exit 0
fi
if [ "${1-}" = "+$VELNOR_TEST_RUST_VERSION" ]; then
    shift
fi
if [ "${1-}" != "metadata" ]; then
    echo "unexpected MBX command: $*" >&2
    exit 2
fi
manifest=''
previous=''
for argument do
    if [ "$previous" = "--manifest-path" ]; then
        manifest=$argument
        break
    fi
    previous=$argument
done
if [ -z "$manifest" ]; then
    echo "metadata manifest path missing" >&2
    exit 2
fi
case "$manifest" in
    */apple/Cargo.toml) printf '%s\n' '{ malformed metadata';;
    *) printf '{"version":1,"workspace_root":"%s"}\n' "$VELNOR_TEST_MBX_ROOT";;
esac
"##,
    )?;
    let mut permissions = std::fs::metadata(&script)?.permissions();
    permissions.set_mode(0o755);
    std::fs::set_permissions(&script, permissions)?;
    Ok(root.join("calls.log"))
}
