//! Effect-free owned support source records; no command or domain dispatcher.

use std::collections::BTreeMap;
use velnor_actions_contract::{ContractError, generated_source, normalize_posix_path};

/// Complete generated support source from a compiled domain owner.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OwnedSupportFile {
    path: String,
    source: String,
}

impl OwnedSupportFile {
    /// Bind a fixed domain-owned path and source to the generator version.
    /// # Errors
    /// Rejects unsafe paths or malformed source/version markers.
    pub(crate) fn compiled(path: &str, body: &str, version: &str) -> Result<Self, ContractError> {
        if !path.starts_with(".github/velnor/")
            || normalize_posix_path(path)? != path
            || body.contains('\0')
            || body.len() > 262_144
        {
            return Err(ContractError::identity(
                "native_support",
                "invalid_fixed_source",
            ));
        }
        Ok(Self {
            path: path.to_owned(),
            source: generated_source(version, body)?,
        })
    }

    /// Fixed repository-relative generated output path.
    #[must_use]
    pub fn path(&self) -> &str {
        &self.path
    }

    /// Exact complete generated bytes, including their version marker.
    #[must_use]
    pub fn source(&self) -> &str {
        &self.source
    }
}

/// A complete fixed helper closure; entry verification must cover every member.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SupportBundle {
    files: Vec<OwnedSupportFile>,
}

impl SupportBundle {
    /// Construct a deterministic complete source closure from a compiled owner.
    /// # Errors
    /// Rejects duplicate paths, even if their bytes agree, and empty bundles.
    pub(crate) fn compiled(files: Vec<OwnedSupportFile>) -> Result<Self, ContractError> {
        if files.is_empty() {
            return Err(ContractError::identity(
                "native_support",
                "empty_source_closure",
            ));
        }
        let mut ordered = BTreeMap::new();
        for file in files {
            if ordered.insert(file.path.clone(), file).is_some() {
                return Err(ContractError::identity(
                    "native_support",
                    "duplicate_source_path",
                ));
            }
        }
        Ok(Self {
            files: ordered.into_values().collect(),
        })
    }

    /// Complete companion source closure. No member grants launch authority alone.
    #[must_use]
    pub fn files(&self) -> &[OwnedSupportFile] {
        &self.files
    }
}
