[package]
name = "velnor-actions-actionlint"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
autotests = false

[lints]
workspace = true

[dependencies]
velnor-actions-contract = { version = "=0.1.7", path = "../../core/velnor-actions-contract" }
velnor-actions-contract-config = { version = "=0.1.7", path = "../../core/velnor-actions-contract-config" }
velnor-actions-contract-release = { version = "=0.1.7", path = "../../core/velnor-actions-contract-release" }

[[test]]
name = "velnor_actionlint"
path = "tests/main.rs"
