"""Build-only strict SDK source extraction; research artifact, never registry.

The publisher reviews the retained raw sources and generated bytes. A future
Rust capsule export supersedes this research extraction before product grants.
"""
import hashlib
import json
from pathlib import Path
import re
import sys

_SDK = 'crates/velnor-actions-mise/src/'
_OWNER = 'crates/velnor-actions-orchestrator/src/'
_MODULES = ('cache_receipt_common', 'cache_receipt_api', 'cache_receipt_gh',
            'receipt_fresh_gh_download', 'receipt_fresh_gh_archive', 'receipt_fresh_gh')


def _one(pattern, source):
    matches = re.findall(pattern, source, re.MULTILINE)
    if len(matches) != 1:
        raise ValueError('SDK source extraction match count')
    return matches[0]


def _constant(name, source):
    return _one(r'^const ' + name + r': &str =\s*"([^"\n]+)";', source)


def _identity(fields):
    digest = hashlib.sha256()
    for field in fields:
        data = field.encode('utf-8')
        digest.update(str(len(data)).encode('ascii') + b':' + data)
    return digest.hexdigest()


def _distribution(source, types, host, arch, machine):
    values = _one(r'DistributionHost::' + host + r' => \(\s*"([^"]+)",\s*'
        r'"([a-f0-9]{64})",\s*"([a-f0-9]{64})",\s*"([^"]+)",\s*'
        r'&LINUX_' + arch.upper() + r'_LAUNCH\[\.\.\],\s*'
        r'DistributionAssetFormat::TarGzip,\s*None,\s*None,\s*\)', source)
    url, archive, binary, member = values
    launch = _one(r'static LINUX_' + arch.upper() + r'_LAUNCH: \[QualifiedLaunchEntry; 1\]'
        r' = \[QualifiedLaunchEntry \{\s*archive_member: "([^"]+)",\s*'
        r'installed_relative_path: None,\s*sha256: "([a-f0-9]{64})",\s*'
        r'kind: QualifiedLaunchKind::Executable,\s*\}\];', source)
    if launch != (member, binary):
        raise ValueError('SDK launch tuple mismatch')
    version = _constant('VERSION', source)
    selector = _constant('LINUX_SELECTOR', source)
    repository, commit, tree, owner, abi = [_constant(name, source) for name in
        ('SOURCE_REPOSITORY', 'SOURCE_COMMIT', 'SOURCE_TREE', 'OWNER', 'ABI')]
    target = _one(r'Self::' + host + r' => "([^"\n]+)",', types)
    if (version != '2.102.0' or owner != 'cli/cli' or repository != 'https://github.com/cli/cli' or
            url != f'https://github.com/cli/cli/releases/download/v{version}/gh_{version}_linux_{arch}.tar.gz'
            or member != f'gh_{version}_linux_{arch}/bin/gh'):
        raise ValueError('SDK release shape')
    fields = ['velnor-qualified-distribution-v1', 'gh', target, selector, url, archive,
        binary, 'tar-gzip', member, repository, commit, tree, owner, version, version,
        abi, 'official', 'uninstalled', '', '1', member, 'uninstalled', '', binary,
        'executable', '0', 'installer-unqualified']
    return {'tool': 'gh', 'version': version, 'machine': machine, 'asset_url': url,
        'archive_sha256': archive, 'binary_sha256': binary, 'binary_member': member,
        'source_repository': repository, 'source_commit': commit, 'source_tree': tree,
        'qualification_sha256': _identity(fields)}


def _roots(root, snapshot):
    source = (root / (_OWNER + 'cache_receipt_trust_root.rs')).read_text()
    evidence = root / (_OWNER + 'cache_receipt_public_good')
    constants = {
        'trusted_root.json': _constant('RAW_SHA256', source),
        'trusted_root.jsonl': _constant('VERIFIER_SHA256', source),
        'qualification.json': _constant('QUALIFICATION_SHA256', source),
    }
    additional = re.findall(r'include_bytes!\("cache_receipt_public_good/([^"/]+)"\),'
                             r'\s*"([a-f0-9]{64})",', source)
    if len(additional) != 7 or len(dict(additional)) != 7:
        raise ValueError('Root evidence source match count')
    constants.update(additional)
    if len(constants) != 10:
        raise ValueError('Root evidence topology')
    target = snapshot / 'root'
    target.mkdir()
    for filename, expected in constants.items():
        data = (evidence / filename).read_bytes()
        if hashlib.sha256(data).hexdigest() != expected:
            raise ValueError('Root owner evidence changed')
        (target / filename).write_bytes(data)
    (snapshot / 'cache_receipt_trust_root.rs').write_text(source)


def export(root, destination):
    snapshot = destination / 'fresh-gh-sdk'
    snapshot.mkdir()
    for name in _MODULES:
        (snapshot / (name + '.py')).write_bytes((root / (_OWNER + name + '.py')).read_bytes())
    paths = ('catalog_qualification_gh.rs', 'catalog_qualification_types.rs',
             'catalog_qualification_identity.rs')
    sources = {}
    for name in paths:
        data = (root / (_SDK + name)).read_bytes()
        (snapshot / name).write_bytes(data)
        sources[name] = data.decode('utf-8')
    records = {arch: _distribution(sources[paths[0]], sources[paths[1]], host, arch, machine)
               for host, arch, machine in (('LinuxAmd64', 'amd64', 'x86_64'),
                                           ('LinuxArm64', 'arm64', 'aarch64'))}
    _roots(root, snapshot)
    literal = json.dumps(records, separators=(',', ':'), sort_keys=True)
    (snapshot / 'sdk-gh-distributions.mjs').write_text(
        '// Build-only SDK source-extracted research artifact; not a product registry.\n'
        'export const SDK_GH_DISTRIBUTIONS = Object.freeze(' + literal + ');\n')
    manifest = [{'path': str(path.relative_to(destination)), 'bytes': path.stat().st_size,
                 'sha256': hashlib.sha256(path.read_bytes()).hexdigest()}
                for path in sorted(snapshot.rglob('*')) if path.is_file()]
    (snapshot / 'research-extraction.json').write_text(json.dumps({
        'schema': 1, 'authority': False, 'scope': 'strict-source-extracted-research-artifact',
        'canonical_rust_export_executed': False, 'source_files': manifest,
        'match_counts': {'linux_host_tuples': 2, 'linux_launch_records': 2,
                         'root_evidence': 10,
                         'each_constant': {name: 1 for name in (
                             'VERSION', 'LINUX_SELECTOR', 'SOURCE_REPOSITORY', 'SOURCE_COMMIT',
                             'SOURCE_TREE', 'OWNER', 'ABI', 'RAW_SHA256', 'VERIFIER_SHA256',
                             'QUALIFICATION_SHA256')},
                         'each_host_abi': {'LinuxAmd64': 1, 'LinuxArm64': 1}}}, indent=2) + '\n')


if __name__ == '__main__':
    if len(sys.argv) != 3:
        raise SystemExit('build-only: exporter SOURCE_REPO DESTINATION_OWNED_CACHE')
    export(Path(sys.argv[1]).resolve(strict=True), Path(sys.argv[2]).resolve(strict=True))
